/*  File : sal_vrtx.idl
*   Table: sal_vrtx
*   Description:  Table for vertex position        
*            
*/
        struct sal_vrtx {
       long      id;         /* Identifier for Vertex row */
       long      quality;     /* quality produced by the cluster finder 
				flag 0=poor;100=good poit */ 
       float     cov[6];     /* covariance matrix */
       float     x[3];       /* vertex position in GRF. */
   };
/*  Last mod. for sal_vrtx: $Date: 1997/12/31 14:33:39 $ */

