/*   sce_dspt_st.idl
 *   Module: sce SSD Chain Evalutator
 *   Output of the space point comparison
 *   Table of space points comparison characteristics. (14*4 = 56 bytes)
 */
  struct sce_dspt {

       long      id;            /* Identifier of the reconstructed point */
       long      prob;          /* probability of the reconstructed point */
       long      ghost_true;    /* ghost = 0 and true-point = 1 */
       long      kind_package;  /* kind of reconstruction package */
       long      id_match;      /* key to match simulated point            */
       long      id_wafer;      /* Identifier in svt_geom table of wafer   */
       float     d2e[2];        /* E resolution in Si (+error)   */
       float     dx[3];         /* residual in STAR reference system    */
       float     dxl[3];        /* residual in wafer reference system   */
   };

/* last modified $Date: 2000/07/21 14:57:52 $ */


