/*   sce_ctrl_st.idl
 *   Module: sce
 *   Table of control information for sce
 */

   struct sce_ctrl {
     long      TrueClusterP;/* nbre of true cluster*/
     long      GhostClusterP;/* nbre of ghost cluster*/
     long      LostClusterP;/* nbre of lost cluster*/
     long      TrueClusterN;/* nbre of true cluster*/
     long      GhostClusterN;/* nbre of ghost cluster*/
     long      LostClusterN;/* nbre of lost cluster*/
     long      TrueSpt11;/* nbre of true space point from 1-1 case*/
     long      GhostSpt11;/* nbre of ghost */
     long      LostSpt11;/* nbre of lost   */
     long      TrueSpt12;/* nbre of true space point from 1-2 case*/
     long      GhostSpt12;/* nbre of ghost */
     long      LostSpt12;/* nbre of lost   */
     long      TrueSpt22;/* nbre of true space point from 2-2 case*/
     long      GhostSpt22;/* nbre of ghost */
     long      LostSpt22;/* nbre of lost   */
     long      TrueSpt23;/* nbre of true space point from 2-3 case*/
     long      GhostSpt23;/* nbre of ghost */
     long      LostSpt23;/* nbre of lost   */
     long      TrueSpt33;/* nbre of true space point from 3-3 case*/
     long      GhostSpt33;/* nbre of ghost */
     long      LostSpt33;/* nbre of lost   */
    };
 
 
 
 
 

