/*   scf_ctrl_st.idl
 *   Module: scf
 *   Table of control parameters for scf module 
 */

   struct scf_ctrl {
     float     high_cut; /* high cut for central strip */
     float     testTolerance; /* set to 20% */	
    };
 
 
 
 
 

