/*   scf_cluster.idl
 *   Module: scf SSD Cluster Finder
 *   Output of cluster finder
 *   Table of clusters characteristics. (15*4 = 60 bytes)
 */
  struct scf_cluster {
     long   id;              /* cluster index           */
     long   id_cluster;      /* cluster address         */
     long   first_strip;     /* first strip             */
     long   n_strip;         /* number of strips        */
     long   adc_count;       /* sum of strip adc count  */
     long   first_adc_count; /* adc count of the first strip in the cluster */
     long   last_adc_count;  /* adc count of the last strip in the cluster */
     long   noise_count;     /* sum of noise count      */
     float  strip_mean;      /* middle of the cluster   */
     long   flag;            /* flag (splitted cluster) */
     long   id_mchit[5];     /* EVALUATION: key to monte carlo hit  */
     long   id_mctrack[5]; /* id of montecarlo track                  */
   };

/*  Last modified  $Date: 2005/11/22 04:06:13 $*/

