/* sci_par.idl                                       */
/* SVT Calibration Drift Speed from charge injection */
/* array[4] refers to four injection lines           */

struct sci_par{
  long      method;     /*  method selection, 0=default                           */
  long      peak_min;    /* minimum ADC peak value required to accept a cluster   */
  float     adcs_min[4]; /* minimum ADC sum value required to accept a cluster    */
  float     adcs_max[4]; /* maximum ADC sum value required to accept a cluster    */
  float     t_drift_min[4]; /* minimum drift time value required to accept a cluster */
  float     t_drift_max[4]; /* maximum drift time value required to accept a cluster */
  float     t_rms_min[4];   /* minimum cluster rms time required to accept a cluster */
  float     t_rms_max[4];   /* maximum cluster rms time required to accept a cluster */  
  long      n_min;          /* minimum of events required to update avg drift time value   */
  float     t[4];           /* drift time used with faker                                  */
  float     t2[4];          /* drift time rms used by faker                                */
};

