/* sci_inj.idl                                 */
/* SVT Injection Line Characterization         */

struct sci_inj{
  long   id;       /* identification number                                      */
  long   anode;    /* anode index                                                */
  long   injector; /* injector index 0-3                                         */
  float  sum_w;    /* cluster ADC sum                                            */
  float  time_w;   /* cluster mean time/centroid obtained by weighte average     */
  float  rms_w;    /* cluster rms size obtained by weighted average              */
  float  sum_f;    /* total ADC obtained by fit to a Gaussian profile            */
  float  time_f;   /* cluster time/centroid obtained by fit                      */
  float  rms_f;    /* cluster width/sigma obtained by Gaussian fit               */
  long   n;        /* number of events to get above values                       */
};
