/*   scm_ctrl_st.idl
 *   Module: scm
 *   Input of the cluster matcher: SSD Cluster Matching 
 *   Table of control parameters for scm module 
 */

   struct scm_ctrl {
     long      clusterTreat; /* max number of cluster in a matched */
     float     AdcTolerance; /* set to 20% */	
     float     matchMean;    /* matching mean */
     float     matchSigma;   /* matching sigma */
    };
 
 
 
 
 

