/* scp_par.idl                                     */
/* SVT Calibration Pedestal Calculation Parameters */

struct scp_par{
  long      method;     /* method selection                                      */
  long      n_min;      /* minimum of events required to update pedestal value   */
  float     rms;        /* pedestal rms width used with faker                    */
  long      ped_min;    /* minimum acceptable pedestal value                     */ 
  long      ped_max;    /* maximum acceptable pedestal value                     */ 
  long      dev_max;    /* maximum acceptable deviation for raw data             */

};

