/*   scs_merge_st.idl
 *   Module: scs
 *   Output of the cluster finder and fitter program
 *   Table of merge cluster.
 */
  struct scs_merge {
	long   numpeaks;
	float  h1_x[2];
	float  h1_dx[2];
	float  h1_amp;
	float  h2_x[2];
	float  h2_dx[2];
	float  h2_amp;
	long   id_clus;
	float  x2mom;
	float  y2mom;
	float  clus_x[2];
	long   wafer_id;
   };

/* last modified $Date: 1997/12/31 14:33:39 $ */


