/*   sdm_calib_par_st.idl
 *   Module: sdm
 *   Table of calibration parameters
 */
struct sdm_calib_par {
long  i_seed;//               random initialisation seed
long  barrel_ped;//           offset
long  wafer_sig;//            dispersion around the offset
long  alice_sig;//            dispersion of alice pedestal
long  strip_P_sig;//          dispersion of strip P pedestal
long  strip_N_sig;//          dispersion of strip N pedestal
long  strip_P_noise;//        mean value of strip P noise
long  strip_N_noise;//        mean value of strip N noise
long  strip_P_noise_sig;//    dispersion of strip P noise around mean value
long  strip_N_noise_sig;//    dispersion of strip N noise mean value
float n_strip_P_factor;//     max noise multiplication factor for a noisy P strip
float n_strip_N_factor;//     max noise multiplication factor for a noisy N strip
float n_noisy_strip;//        percentage of noisy strip
};
 