/*   sdm_geom_st.idl
 *   Module: sdm
 *   Table of geometry parameters
 */
struct sdm_geom_par{
long  N_layer;//           SSD layer number
long  N_ladder;//          Nbr ladder per layer
long  N_waf_per_ladder;//  Nbr wafer per ladder
long  N_alice_per_side;//  Nbr A128C per wafer side
long  N_strip_per_side;//  Nbr Strip per wafer side 
float L_strip_pitch;//     strip pitch
float L_stereo_angle;//    half stereo angle
float L_wafer_tot_l;//     half wafer total length
float L_wafer_tot_w;//     half wafer total width
float L_wafer_tot_t;//     half wafer total thickness  
float L_wafer_act_l;//     half wafer active length
float L_wafer_act_w;//     half wafer active width
};
 