/*   sdm_condition_par.idl
 *   Module: sdm
 *   Table of condition parameters
 */
struct sdm_condition_par{
long  i_seed;//              random initialisation seed 
long  N_active_ladder[20];// array of active(1) and dead(0) ladders
float p_bad_wafer;//         percentage of dead wafers
float p_bad_alice;//         percentage of dead A128C
float p_bad_strip;//         percentage of dead strips
};
 
 
 
 