/**   
  sgr_groups.idl
  
  Table: Many to Many Relationship table
  
  This is a generic table used for many to many
  relationships (links) of tracks and space points.
  
  The variable "ident" is used to keep track
  of the code that generated the links. The same
  table instance can be used with many sources of link.
  
  id1 is a key (index) to a track.
  id2 is a key to a point.
  
  Note: the value of ident determines what track and 
  space point tables are refered to.
  
  Provisional Convention for "ident"
  
  1       Monte Carlo Track assignment
  2       STK Package Track assignment
  3+n*10  SGR Package Track assignment, n=1,2, ... is a SGR loop index.
  4       SFT Package Track assignment

  */

struct sgr_groups{
  long       ident;   /* Key to which tracker made groups etc. */
  long       id1;     /* Key to a track table                  */
  long       id2;     /* Key to a point table                  */
};


/*  Last mod. for sgr_groups: Mon Aug 25 10:12:19 EDT 1997 */

