/*   sls_strip_st.idl
 *   Module: sls
 *   Output for reconstruction software 
 *   Table of strips with signal (22*4 = 88 bytes)
 */
//the strip id is coded as fallow:
// id_strip=10000*(10*strip_number+id_side)+id_wafer
//strip number=1-768
//id_side=0 for p side, 1 for n side

   struct sls_strip {
     long      id;       /* Strip Id in the table */
     long      id_strip;    /* Strip identifier  strip(              */
     long      id_cluster; /* link to cluster point came from         */
     long      adc_count;  /* ADC count */
     long      noise_count; /* noise in ADC count*/
     long      id_hit[5];   /* if the strip is included in more than 1 hit  */
     long      N_hits;      /* number of occurence of previous case   */       
     float     de;         /* charge on the strip                       */
     long      id_mchit[5];   /* key to monte carlo hit                  */
     long      id_mctrack[5]; /* id of montecarlo track                  */
    };
 
 
 
 
 

