/*   sls_ctrl_st.idl
 *   Module: sls
 *   Table of control parameters for sls and spa modules 
 */

   struct sls_ctrl {
     long      NElectronInAMip;/* in electron unit*/
     long      ADCDynamic;/*in mip unit*/
     long      A128Dynamic;/*in mip unit*/
     long      NBitEncoding;/*number od adc bit for encoding*/
     long      NStripInACluster;/**/
     double    PairCreationEnergy;/*energy to create a e+e-pair(GeV)*/
     double    ParDiffP;
     double    ParDiffN;
     double    ParIndRightP;
     double    ParIndRightN;
     double    ParIndLeftP;
     double    ParIndLeftN;
     float     DAQCutValue;/*in "sigma unit"*/
    };
 
 
 
 
 

