/*   srs_srspar.idl
*   Table: srs_srspar
*        description: parameter table for svt resol. sim      
*/
	struct srs_srspar {
       long      id_active[10];/* id for active area on each layer */
       long      init_ran;   /* if not 0 init seed with this each event */
       long      merge;      /* merge=1 when merging enabled */
       long      method;     /* how to copy hits to spt table */
       long      nsca;       /* number of sca channels */
       float     bucket;     /* space extent of time bucket */
       float     enc;        /* equivalent noise charge per bucket */
       float     fsca;       /* sca frequency */
       float     pitch;      /* distance between anodes (cm) */
       float     shaper;     /* gaussian responce of electronics (s) */
       float     thickness;  /* SVT wafer thickness */
       float     vd;         /* drift velocity */
   };
/*  Last mod. for srspar: $Date: 1997/12/31 14:33:40 $ */

