/* ssf_adc.idl
 * 
 * Table: ssf_adc
 * ADC values for one half wafer
 * The same generic table is used for different
 * applications
 *  1- raw data (10 bits)
 *  2- raw data compressed (8 bits)
 *  3- zero suppressed data (8 bits)
 *  4- zero suppressed data expanded (10 bits)
 *  In the case of zero suppressed data, it is
 *  assumed that the "geographical" information 
 *  is included in a different table i.e. ssf_seq
 */
struct ssf_adc {
  short adc;  /* pixel value in ADC channel */
};

