/* ssf_zero_par.idl
 * 
 * Table: ssf_zero_par
 * Zero Suppression Parameters
 * 
 */
struct ssf_zero_par {
  short  n_anode;     /* twice th number of active anodes (2 sides)  */
  short  n_time;      /* number of active time bins                  */
  short  n_high;      /* number of bins to be above high threshold   */
  short  n_low;       /* number of bins to be above low threshold    */
  short  thresh_high; /* high threshold                              */
  short  thresh_low;  /* min ADC value for inclusion in line cluster */
};

