/*   stk_kine.idl
*   Table: stk_kine
*        description: kine observables reconstructed with svt 
*/
	 struct stk_kine {
       long       id;         /* sequence id number */
       long       id_vtx;     /* key to svt_vtx vertex table */
       long       pid;        /* particle identification number (geant) */
       float     p[3];       /* 3-momentum */
       float     ph;         /* azimuthal angle (degrees) */
       float     pt;         /* transverse momentum */
       float     ptot;       /* total momentum */
       float     sec;        /* primary or secondary */
       float     th;         /* polar angle (degrees) */
   } ;
/*  Last mod. for stk_kine: $Date: 1997/12/31 14:33:40 $ */

