/*   stk_vtx_direct.idl
*   Table: stk_vtx_direct
*        description: monte carlo vertex smearing with        
*             more..: gaussian                                
*/

	 struct stk_vtx_direct {
       long      init_ran;   /* if not 0 init seed with this each event */
       float     sx[3];      /* sigma for smearing */
   };

/*  Last mod. for stk_vtx_direct: $Date: 1997/12/31 14:33:40 $ */

