/*   stk_track.idl
*   Table: stk_track
*        description: Tracks reconstructed in the SVT         
*/
	 struct stk_track {
       long      flag;       /* status flag */
       long      id;         /* track unique id number */
       long      id_globtrk; /* key to global track table */
       long      id_match;   /* key to match table */
       long      id_mctrack; /* key to mkine table */
       long      sec;        /* sec=0 unknown =1 primary =2 secondary */
       long      nspt;       /* No of space points on track */
       float     chisq[2];   /* chi squares of circle/line fit */
       float     cov[15];    /* covariant matrix */
       float     cres[10];   /* residue in circle fit */
       float     dedx[2];    /* dE/dx information with error */
       float     impact;     /* impact parameter */
       float     invpt;      /* (charge)/momentum at reference point */
       float     lres[10];   /* residue from linear fit (phi-z) */
       float     phi0;       /* aximuthal angle of first point */
       float     pid;        /* Particle ID in SVT alone */
       float     psi;        /* azimuthal angle of momentum at r,phi,z */
       float     r0;         /* reference point in cyl.coord. of 1 point */
       float     tanl;       /* tg of dip angle at r,phi,z */
       float     z0;         /* z coordinate of first point */
   };
/*  Last mod. for stk_track: $Date: 1997/12/31 14:33:40 $ */

