/*   stk_filler.idl
*   Table: stk_filler
*        description: Parameters for svt_tracking_fill routine
*/

	 struct stk_filler {
       float     th12_min;   /* min cone angle 12 */
       float     th12_step;  /* step size cone12 */
       float     th21;       /* cone 1 to 2 */
       float     th23_min;   /* min cone angle 23 (degrees) */
       float     th23_step;  /* step size cone23 */
       float     th31;       /* cone 1 to 3 */
       float     th32;       /* cone 2 to 3 */
       float     th41;       /* cone 1 to 4 */
       float     th42;       /* cone 2 to 4 */
       float     th43;       /* cone 3 to 4 */
       float     th51;       /* cone 1 to 5 */
       float     th52;       /* cone 2 to 5 */
       float     th53;       /* cone 3 to 5 */
       float     th54;       /* cone 4 to 5 */
       float     th61;       /* cone 1 to 6 */
       float     th62;       /* cone 2 to 6 */
       float     th63;       /* cone 3 to 6 */
       float     th64;       /* cone 4 to 6 */
       float     th65;       /* cone 5 to 6 */
       float     th71;       /* cone 1 to 7 */
       float     th72;       /* cone 2 to 7 */
       float     th73;       /* cone 3 to 7 */
       float     th74;       /* cone 4 to 7 */
       float     th75;       /* cone 5 to 7 */
       float     th76;       /* cone 6 to 7 */
       float     th81;       /* cone 1 to 8 */
       float     th82;       /* cone 2 to 8 */
       float     th83;       /* cone 3 to 8 */
       float     th84;       /* cone 4 to 8 */
       float     th85;       /* cone 5 to 8 */
       float     th86;       /* cone 6 to 8 */
       float     th87;       /* cone 7 to 8 */
       float     wth21;      /* wafer cone from 1 to 2 */
       float     wth31;      /* wafer cone from 1 to 3 */
       float     wth32;      /* wafer cone from 2 to 3 */
       float     wth41;      /* wafer cone from 1 to 4 */
       float     wth42;      /* wafer cone from 2 to 4 */
       float     wth43;      /* wafer cone from 3 to 4 */
       float     wth51;      /* wafer cone from 1 to 5 */
       float     wth52;      /* wafer cone from 2 to 5 */
       float     wth53;      /* wafer cone from 3 to 5 */
       float     wth54;      /* wafer cone from 4 to 5 */
       float     wth61;      /* wafer cone from 1 to 6 */
       float     wth62;      /* wafer cone from 2 to 6 */
       float     wth63;      /* wafer cone from 3 to 6 */
       float     wth64;      /* wafer cone from 4 to 6 */
       float     wth65;      /* wafer cone from 5 to 6 */
       float     wth71;      /* wafer cone 1 to 7 */
       float     wth72;      /* wafer cone 2 to 7 */
       float     wth73;      /* wafer cone 3 to 7 */
       float     wth74;      /* wafer cone 4 to 7 */
       float     wth75;      /* wafer cone 5 to 7 */
       float     wth76;      /* wafer cone 6 to 7 */
       float     wth81;      /* wafer cone 1 to 8 */
       float     wth82;      /* wafer cone 2 to 8 */
       float     wth83;      /* wafer cone 3 to 8 */
       float     wth84;      /* wafer cone 4 to 8 */
       float     wth85;      /* wafer cone 5 to 8 */
       float     wth86;      /* wafer cone 6 to 8 */
       float     wth87;      /* wafer cone 7 to 8 */
   };
/*  Last mod. for stk_filler: $Date: 1997/12/31 14:33:40 $ */

