/*	stk_stkpar.idl
*	Table: stk_stkpar
*	description: parameters for svt stand-alone tracking 
*/

	 struct stk_stkpar {
       long       direct;     /* control call to svt_tracking_direct */
       long       fill;       /* control call to svt_tracking_fill3 */
       long       long_tracks;/* 1=get rid of short tracks */
       long       method;     /* fit as prim, secondary, etc. */
       long       mode;       /* track pri, sec, or both, ... */
       long       ngood;      /* number of checked tracks in svt_track */
       long       nitermax;   /* max number iteration in fill3 */
       long       niternull;  /* max number iter without track change */
       long       nlayers;    /* number of super layers */
       long       secondary;  /* open gates for secondaries */
       long       spt_mark;   /* 1 = remove used space points */
       long       vertex;     /* control call to svt_vertex_direct */
       float     c1norm[3];  /* norm factors for chi1 (circle fit) */
       float     c2norm[3];  /* norm factors for chi from phi-z fit */
       float     chi_filter; /* parameter to turn chi filtering on/off */
       float     chibreak;   /* value of zchi2 that triggers sec fitting */
       float     chicut[2];  /* cut on chisqr of tracks to be accepted */
       float     sec_factor; /* factor to loosen cones by for secondary */
       float     th_init;    /* initial th max */
       float     th_max;     /* largest step */
       float     th_step;    /* th step */
   };
/*  Last mod. for stk_stkpar: $Date: 1998/06/10 21:34:45 $ */

