/*   svg_config.idl
*   Table: svg_config
*        description: Table holding SVT configuration information 
*/
      struct svg_config {
       long      cap_nshape; /* number of shape parameters */
       long      cap_shape_id;/* GEANT shape id for end caps */
       long      cap_trackmed;/* tracking medium for end caps */
       long      frame_trackmed;/* tracking medium for frame */
       long      layer_drift[10];/* drift direction indicator 3=Z=beam axis */
       long      n_ladder[10];/* Number of ladders in layer(x)  x-->1-5 */
       long      n_layer;    /* SVT layer number */
       long      n_wafer[10];/* Number of wafers on ladder for layer(x) */
       float     be_support_thick[10];/* berylium support */
       float     be_support_width[10];/* berylium support */
       float     cap_position;/* distance of svt end cap from origin */
       float     cap_shape[20];/* shape parameter values */
       float     frame_al_length[10];/* frame */
       float     frame_al_thick[10];/* frame */
       float     frame_al_width[10];/* frame */
       float     frame_cs_length[10];/* frame */
       float     frame_cs_thick[10];/* fram */
       float     frame_cs_width[10];/* fram */
       float     frame_length[10];/* length of frame */
       float     frame_si_length[10];/* frame */
       float     frame_si_thick[10];/* frame */
       float     frame_si_width[10];/* frame */
       float     frame_thick[10];/* frame thickness */
       float     frame_width[10];/* frame width */
       float     layer_back[10];/* layer back */
       float     layer_lateral[10];/* lateral offset for ladder */
       float     layer_longi[10];/* longitudinal offset for ladder */
       float     layer_phioff[10];/* phi offset for 1st ladder of layer */
       float     layer_radial[10];/* radial offset (wafer staggering) */
       float     layer_radius[10];/* radius of layers */
       float     layer_shape[10];/* shape id for layer */
       float     size[3];    /* TUBE inner,outer radius and half lenght */
       float     water_channel_thick[10];/* water channel */
       float     water_channel_width[10];/* water channel */
       float     x[3];       /* position of the SVT in STAR */
   };
/*  Last mod. for svg_config: $Date: 1997/12/31 14:33:39 $ */

