/*   svg_geom.idl
*   Table: svg_geom
*        description: svt geometry definition                 
*/
      struct svg_geom {
       long      id;         /* wafer id number */
       long      id_shape;   /* wafer shape id index */
       long      ladder;     /* Ladder number wafer is on */
       long      layer;      /* Layer number wafer is on. */
       long      num_chip;   /* Chip number within ladder */
       float     d[3];       /*   drift direction */
       float     n[3];       /* coord of unit vector normal to wafer */
       float     t[3];       /* t=nxd. Trnsverse to drift,normal direct. */
       float     x[3];       /* coordinates of wafer center in STAR syst */
   };
/*  Last mod. for svg_geom: $Date: 1997/12/31 14:33:39 $ */

