/*   svg_shape.idl
*   Table: svg_shape
*        description: Geometry parameters for each SDD type   
*/
      struct svg_shape {
       long      id;         /* Type of SDD shape */
       long      n_shape;    /* number of shape parameters */
       float     active[10]; /* active area of sdd */
       float     shape[10];  /* custom shape parameters of SDD wafer */
   };
/*  Last mod. for svg_shape: $Date: 1997/12/31 14:33:40 $ */

