/*****************************************************************************/

/*   diag_cortr.idl
*
*   Table: diag_cortr
*        description: Contains information about the correctly tracked tracks
*
*/
   /*******************  Row struct *******************/
   struct diag_cortr {    
 	long	id_first;	/* ID of first hit */
	long	id_last;	/* ID of last hit */
	long	nu_hits;	/* # of intermediate hits */
	long	db_flag;	/* Debug-Flag */
	float	x_first[3];	/* Koord. of first hit */
	float	x_last[3];	/* Koord. of last hit */
	float   p[3];		/* GEANT momentum */
	float	del_cord;	/* Difference of the two cord val. */
	float   tl_crit;        /* Applied criterion for del_cord */
	float	tau;		/* Twist angle */
	float	interm_dev;	/* Av. deviation of interm. hits to circ. */
	float	r_in;		/* inner radius limit */
	float	r_out;		/* outer radius limit */
    };
/*  Last mod. for diag_cortr: $Date: 1998/01/19 02:25:10 $ */
