/*****************************************************************************/

/*   fcl_ftpcsqndx.idl
*
*   Table: fcl_ftpcsqndx
*        description: FTPC raw data sequence index
*
*/

   /*******************  Row struct *******************/
   struct fcl_ftpcsqndx {    
       unsigned short      index;      /* raw data sequence index */
    };

/*  Last mod. for fcl_ftpcsqndx: $Date: 1998/06/24 13:30:42 $ */











