/*****************************************************************************/

/*   fcl_ampslope.idl
*
*   Table: fcl_ampslope
*        description: calibration amplitude slope table 
*
*/

   /*******************  Row struct *******************/
   struct fcl_ampslope { 
       float slope;       /* amplitude slope for this channel */   
   };

/*  Last mod. for fcl_ampslope: $Date: 1998/07/15 15:04:08 $ */

