/*****************************************************************************/

/*   fcl_ampoff.idl
*
*   Table: fcl_ampoff
*        description: calibration amplitude offset table 
*
*/

   /*******************  Row struct *******************/
   struct fcl_ampoff { 
       float offset;       /* amplitude offset for this channel */   
   };

/*  Last mod. for fcl_ampoff: $Date: 1998/07/15 15:04:34 $ */

