/*****************************************************************************/

/*   fcl_padtrans.idl
*
*   Table: fcl_padtrans
*        description: Parameters for the pad-bin to x-y transformation 
*
*/

   /*******************  Row struct *******************/
   struct fcl_padtrans {    
       float t0;         /* offset for time direction polynomial */
       float t1;         /* 1st parameter for time direction polynomial */
       float t2;         /* 2nd parameter for time direction polynomial */
       float t3;         /* 3rd parameter for time direction polynomial */
       float t4;         /* 4th parameter for time direction polynomial */
       float p1;         /* 1st parameter for pad direction polynomial */
       float p2;         /* 2nd parameter for pad direction polynomial */
       float p3;         /* 3rd parameter for pad direction polynomial */
       float p4;         /* 4th parameter for pad direction polynomial */
       float p5;         /* 5th parameter for pad direction polynomial */
       float p6;         /* 6th parameter for pad direction polynomial */
   };

/*  Last mod. for fcl_padtrans: $Date: 1998/03/25 10:43:22 $ */

