/*****************************************************************************/

/*   fcl_det.idl
*
*   Table: fcl_det
*        description: ftpc detector pad layout description 
*
*/

   /*******************  Row struct *******************/
   struct fcl_det {
       long firstrow;         /* first padrow with data (1-20) */
       long lastrow;          /* last padrow with data */
       long firstsec;         /* first sector in padrow with data (1-6) */
       long lastsec;          /* last sector with data */
       long n_rows;           /* total number of padrows, def 20 */
       long n_sectors;        /* total number of sectors per padrow, def 6 */
       long n_pads;           /* number of pads per sector, def 160 */
       long n_bins;           /* number of timebins, def 256 */
       long n_pads_raw;       /* number of pads per raw object, def 16 */
       long usegauss;         /* 0=no gaussfit, 1=pad gaussfit, */
                              /* 2=time gaussfit, 3=all gaussfit */
       long threshold;        /* cluster threshold */
       long min_max_adc;      /* cluster minimum peakheight */
       float rad_per_pad;     /* phi angle for each pad, def 0.0062295082*/
       float rad_per_gap;     /* phi angle of sector gap, def 0.05047541 */
   };

/*  Last mod. for fcl_det: $Date: 1998/02/23 14:32:56 $ */

