/*****************************************************************************/

/*   fcl_det.idl
*
*   Table: fcl_det
*        description: ftpc detector pad layout description 
*
*/

   /*******************  Row struct *******************/
   struct fcl_det {
       long firstrow;         /* first padrow with data (1-20) */
       long lastrow;          /* last padrow with data */
       long firstsec;         /* first sector in padrow with data (1-6) */
       long lastsec;          /* last sector with data */
       long n_rows;           /* total number of padrows, def 20 */
       long n_sectors;        /* total number of sectors per padrow, def 6 */
       long n_pads;           /* number of pads per sector, def 160 */
       long n_bins;           /* number of timebins, def 256 */
       long n_pads_raw;       /* number of pads per raw object, def 16 */
       long usegauss;         /* 0=no gaussfit, 1=pad gaussfit, */
                              /* 2=time gaussfit, 3=all gaussfit */
       long threshold;        /* cluster threshold */
       long min_max_adc;      /* cluster minimum peakheight */
       long n_magboltz_bins;  /* # of bins in magboltz database */
       long n_int_steps;      /* # of steps in padtrans integration */
       long magfld;           /* direction of magnetic fiels (+/- 1) */
       float r_in;            /* inner radius of readout volume 7.73cm */
       float r_out;           /* outer radius of readout volume 30.05cm */
       float rad_times_field; /* v(r)/ln(r(a)/r(i)), 7365.1 V */
       float deg_to_rad;      /* 0.017453293 radians per degree */
       float timebin_size;    /* 0.2 usec per timebin */
       float rad_per_pad;     /* phi angle for each pad, def 0.0062295082*/
       float rad_per_gap;     /* phi angle of sector gap, def 0.05047541 */
       float p_standard;      /* standard air pressure (1013.25hPa) */
       float p_normalized;    /* normalized air pressure (in hPa) */
       float padtrans_e_min;  /* lowest e-field in padtrans database */
       float padtrans_e_max;  /* highest e-field in padtrans database */
       char ampslopepath[200];/* path and name of ampslope database */
       char ampoffpath[200];  /* path and name of ampoff database */
       char timeoffpath[200]; /* path and name of timeoff database */
       char padtranspath[200];/* path and name of padtrans database */
   };

/*  Last mod. for fcl_det: $Date: 1998/07/15 15:05:29 $ */





