/*****************************************************************************/

/*   fcl_raw.idl
*
*   Table: fcl_raw
*        description: Raw data input for fcl FTPC cluster finder
*
*/

   /*******************  Row struct *******************/
   struct fcl_raw {    
       long      pixel[1024];      /* raw data for one chip */
                                   /* four timebins per long word */
    };

/*  Last mod. for fcl_raw: $Date: 1998/02/23 14:32:57 $ */











