/*   fcl_fppoint.idl
*   Table type: fcl_fppoint
*        description: Reconstructed FTPC points               
*/

   struct fcl_fppoint {  
       long      id;         /* a unique point id */
       long      cluster;    /* id of a cluster used to reconstruct pt. */
       long      ge_track_p; /* track_p of g2t_ftp_hit */
       long      ge_pid;     /* GEANT particle ID from track-table */
       long      track_type; /* 1=primary, 2=secondary, 3=shower */
       long      n_hits;     /* # of hits in the track this hit belongs to */
       long      row;        /* TPC row number */
       long      merge_tag;  /* 0=hit would not merge, 1=hit would merge */
       float     rapi;       /* rapidity */
       float     eta;        /* pseudorapidity */
       float     p_v[3];     /* Vertex Momentum */
       float     p_tot_g_p;  /* total momentum of assigned GEANT track */
       float     p_t_g_p;    /* transverse momentum of assigned GEANT track */
       float     px_g;       /* local geant x-momentum */ 
       float     py_g;       /* local geant y-momentum */ 
       float     pz_g;       /* local geant z-momentum */ 
       float     de;         /* energy deposition at hit */
       float     x_g;        /* GEANT x-position of hit */
       float     y_g;        /* GEANT y-position of hit */
       float     z_g;        /* GEANT z-position of hit */
       float     theta;      /* dipa angle */
       float     twist;      /* twist angle */
       float     cross_ang;  /* crossing angle (between padrow and track) */
       float     x;          /* x-position of hit after ffs tratment */
       float     y;          /* y-position of hit after ffs tratment */
       float     z;          /* z-position of hit after ffs tratment */
       float     vertex[3];  /* position of the start-vertex */
       float     ge_proc;    /* GEANT process for sec. production */
   };
/*  Last mod. for fcl_fppoint:   $Date: 1997/12/31 14:34:15 $ */
