/*****************************************************************************/

/*   fcl_ftpcndx.idl
*
*   Table: fcl_ftpcndx
*        description: FTPC raw data chamber index
*
*/

   /*******************  Row struct *******************/
   struct fcl_ftpcndx {    
       unsigned short index; /* index to 1st/2nd chamber */
                             /* should be unsigned int */
    };

/*  Last mod. for fcl_ftpcndx: $Date: 1998/06/24 13:30:42 $ */











