/*****************************************************************************/

/*   fcl_ftpcadc.idl
*
*   Table: fcl_ftpcadc
*        description: FTPC raw data adc output
*
*/

   /*******************  Row struct *******************/
   struct fcl_ftpcadc {    
       char      data;               /* 1 pixel of 8bit ADC output */
                                     /* should be unsigned char */
    };

/*  Last mod. for fcl_ftpcadc: $Date: 1998/06/24 13:30:41 $ */











