/*****************************************************************************/

/*   fcl_raw.idl
*
*   Table: fcl_raw
*        description: Raw data input for fcl FTPC cluster finder
*
*/

   /*******************  Row struct *******************/
   struct fcl_raw {    
       unsigned long      pixel[1024];      /* raw data for one chip */
                                            /* four timebins per long word */
    };

/*  Last mod. for fcl_raw: $Date: 1998/03/25 10:43:22 $ */











