/*   ffs_fspar.idl
*   Table type: ffs_fspar
*        description: FFS parameter table                     
*/

   struct ffs_fspar {    
       float     padwid[2];  /* pad width (cm) */
       float     sprf_0[2];  /* prf intrinsic term */
       float     sprf_ta[2]; /* prf tan-alpha term */
   };

/*  Last mod. for ffs_fspar:   $Date: 1998/12/16 08:10:30 $  */

