/*****************************************************************************/

/*   ffs_gepoint.idl
*
*   Table: ffs_gepoint
*        description: Output of ffs FTPC fast simulator
*
*/

   /*******************  Row struct *******************/
   struct ffs_gepoint {    
       long      row;      /* FTPC row number */
       long      sector;   /* FTPC readout sector number */
       long      n_pads;   /* number of pads in cluster */
       long      n_bins;   /* number of consecutive timebins in cluster*/
       long      max_adc;  /* cluster peak height (adc channels) */
       long      charge;   /* cluster charge (adc channels) */
       long      flags;    /* bit0:unfolded, bit1:unfold failed, */
                           /* bit2: saturated, bit3:bad shape, */
                           /* bit4:cut off, bit5:tracked */
       long      ge_track_p; /* track_p of g2t_ftp_hit */ 
       long      ge_pid;     /* GEANT pid */
       long      prim_tag;   /*1=primary,2=secondary,3=shower,+/-=ge_charge*/
       float     x;        /* x-position of hit */
       float     y;        /* y-position of hit */
       float     z;        /* z-position of hit */
       float     s_phi;    /* cluster sigma in pad direction */
       float     s_r;      /* cluster sigma in drift direction */
       float     p_v[3];   /* Geant Vertex Momentum */
       float     p_g[3];   /* Geant Local Momentum */
       float     vertex[3];/* position of the start-vertex */
       float     ge_proc;  /* GEANT process for sec. production */
    };

/*  Last mod. for ffs_gepoint: $Date: 1998/02/23 14:32:58 $ */











