/*****************************************************************************/

/*   ffs_gepoint.idl
*
*   Table: ffs_gepoint
*        description: Output of ffs FTPC fast simulator
*
*/

   /*******************  Row struct *******************/
   struct ffs_gepoint {    
       long      ge_track_p; /* track_p of g2t_ftp_hit */ 
       long      ge_pid;     /* GEANT pid */
       long      prim_tag;   /*1=primary,2=secondary,3=shower,+/-=ge_charge*/
       float     p_v[3];   /* Geant Vertex Momentum */
       float     p_g[3];   /* Geant Local Momentum */
       float     vertex[3];/* position of the start-vertex */
       float     ge_proc;  /* GEANT process for sec. production */
    };

/*  Last mod. for ffs_gepoint: $Date: 1998/10/14 11:41:54 $ */











