/*   ffs_bmpar.idl
*
*   Table type: ffs_bmpar
*
*        description: FFS beam parameter table                
*/

   struct ffs_bmpar {
       float     lumin;      /* beam luminosity (cm^-2 per second) */
       float     txing;      /* time between bunch crossings (ns) */
       float     xsec;       /* inelastic cross-section (mbarns) */
   };

/*  Last mod. for ffs_bmpar:   $Date: 1998/01/19 02:25:11 $ */

