/*   ffs_fspar.idl
*   Table type: ffs_fspar
*        description: FFS parameter table                     
*/

   struct ffs_fspar {    
       long      irmax;      /* number of inner sector rows */
       long      nrow;       /* total number of TPC rows */
       long      nsect;      /* total number of TPC sectors */
       float     alpha_hi;   /* max angle for scaling (deg) */
       float     alpha_lo;   /* min angle for scaling (deg) */
       float     dbase[2];   /* radius of first row */
       float     drivel;     /* drift velocity (cm/microsecond) */
       float     drmin;      /* merging criterion radial (pads) */
       float     dzmin;      /* merging criterion drift (time bins) */
       float     merge_r;    /* max merged size radial (pads) */
       float     merge_z;    /* max merged size drift (bins) */
       float     padlen[2];  /* pad length (cm) */
       float     padsep[2];  /* pad pitch (cm) */
       float     padwid[2];  /* pad width (cm) */
       float     reslim;     /* maximum cluster size (cm) */
       float     sigma0[2];  /* resolution intrinsic term */
       float     sigmad[2];  /* resolution drift term */
       float     sigmal;     /* resolution longitudinal diffusion */
       float     sigmat[2];  /* resolution tan-alpha term */
       float     sldiff;     /* longitudinal diffusion */
       float     sphi[4];    /* std. deviation azimuthal angle paramters */
       float     sprf_0[2];  /* prf intrinsic term */
       float     sprf_dr[2]; /* prf drift term */
       float     sprf_ta[2]; /* prf tan-alpha term */
       float     stime[4];   /* std. deviation arrival time parameters */
       float     timeb[4];   /* arrival time at anode parameters */
       float     tpclen;     /* total drift length (cm) */
       float     tshape;     /* shaping time (ns) */
       float     velh[4];    /* drift velocity parameters */
       float     zbmax;      /* total time bins */
   };

/*  Last mod. for ffs_fspar:   $Date: 1998/01/19 02:25:12 $  */

