/*   ffs_gaspar.idl
*   Table type: ffs_gaspar
*        description: FFS gas-parameter description                     
*/

   struct ffs_gaspar {    
	float	vdrift[4];  /* parameters of a P3-fit of drift-vel. */
	float	tdrift[4];  /* parameters of a P3-fit of drift-time */
	float	sig_rad[4]; /* parameters of a P3-fit of sigma(rad) */
	float	sig_azi[4]; /* parameters of a P3-fit of sigma(azi) */
	float	err_rad[4]; /* parameters of a P3-fit of rad error */
	float	err_azi[4]; /* parameters of a P3-fit of azi error */
   };

/*  Last mod. for ffs_gaspar:   $Date: 2000/02/07 13:05:52 $  */

