/*   fmg_fmgpar.idl
*   Table type: fmg_fmgpar
*        description: FMG parameter table                     
*/

   struct fmg_fmgpar {    
       long      n_points;   /* number of data points to calculate */
       float     start_field;/* smallest drift field to calculate */
       float     step_field; /* step size for drift field */
       float     dvdp_off;   /* offset for dv/dp-calculation (in Torr) */
       float     temperature;/* obvious */
       float     percent_ar; /* percentage of argon in chamber gas */
       float     percent_co2;/* percentage of CO2 in chamber gas */
       float     percent_ne; /* percentage of neon in chamber gas */
       float     percent_he; /* percentage of helium in chamber gas */
   };

/*  Last mod. for fmg_fmgpar:   $Date: 1999/07/29 14:58:05 $  */

