/*****************************************************************************/

/*   fpt_fptrack.idl
*
*   Table: fpt_fptrack
*        description: Output of fpt FTPC tracker
*
*/

   /*******************  Row struct *******************/
   struct fpt_fptrack {    
       long      id;          /* id of the row = a unique point id */
       long      row;         /* FTPC row number */
       long      r_track_id;  /* id of the reconstructed track */
       long      n_hits;      /* # of assigned hits to rec. track */
       long      n_used_ge_tr;/* # of GEANT tracks hits are taken for rec. */
       long      prim_tag;    /* 1=primary, 2=secondary, 3=shower */
       long      qg;          /* GEANT charge */
       long      ge_pid;      /* GEANT pid */
       long      ge_track_id; /* track_p of g2t_ftp_hit */ 
       float     x;        /* x-position of hit */
       float     y;        /* y-position of hit */
       float     z;        /* z-position of hit */
       float     pxg;      /* GEANT momentum in x-direction (locally) */
       float     pyg;      /* GEANT momentum in y-direction (locally) */
       float     pzg;      /* GEANT momentum in z-direction (locally) */
       float     p_v[3];   /* Vertex Momentum */
       float     p_tot_g;  /* total GEANT momentum */
       float     p_t_g;    /* transverse GEANT momentum */
       float     theta;    /* theta-angle */     
       float     twist;    /* twist */
       float     vertex[3];/* position of the start-vertex */
       float     ge_proc;  /* GEANT process for sec. production */
       float     percent;  /* largest percentage of hits of ONE G-track */
    };

/*  Last mod. for fpt_fptrack: $Date: 1997/12/31 14:34:15 $ */
