/*****************************************************************************/

/*   fpt_fptrack.idl
*
*   Table: fpt_fptrack
*        description: Output of fpt FTPC tracker
*
*/

   /*******************  Row struct *******************/
   struct fpt_fptrack {    
       long      flag;        /* status flag */
                              /* 0=from fppoints, 1=from gepoints */
       long      hitid[10];   /* id's of all points on track */
       long      nrec;        /* number of points on track */
       long      nfit;        /* number of points in momentum fit */
       long      ndedx;       /* number of points in dedx calc */
       long      q;           /* measured charge (+/- 1) */
       float     chisq[2];    /* chi squared of momentum fit */
       float     dedx;        /* dedx-value calculated for track */
       float     p[3];        /* calculated vertex momentum */
       float     v[3];        /* calculated vertex position */
       float     theta;       /* calc. angle to beamline at vertex*/
    };

/*  Last mod. for fpt_fptrack: $Date: 1998/03/30 09:37:27 $ */
