/*****************************************************************************/

/*   fpt_fptpar.idl
*
*   Table: fpt_fptpar
*        description: Parameters for the track finding in FTPC 
*
*/

   /*******************  Row struct *******************/
   struct fpt_fptpar {    
       long      debug[10];  /* Flags for debug print */
       long      padrows;    /* # of padrows in one TPC */
       float     sea_circ;   /* Search circle radius */
       float     merge_x;    /* Merge Criterion (x-dir) */
       float     merge_y;    /* Merge criterion (y-dir) */
       float     fan_angle;  /* ang.range, in which a last pl. hit is sear. */
       float     one_or_two; /* track only in one (=1) or both (=2) FTPCs */ 
       float     inner_r;    /* inner radius of the sensitive volume */
       float     outer_r;    /* outer radius of the sensitive volume */
       float     cord_crit;  /* tolerance by comparing the two cord lengths */
   };

/*  Last mod. for fpt_fptpar: $Date: 1998/01/19 02:25:13 $ */

