/*   fss_param.idl
*
*        Table type: fss_param
*        Description: FSS parameter table                     
*
*   Author: Wen G. Gong
*   Email: gong@mppmu.mpg.de
*   Date:  April 23, 1997
*
*/

   struct fss_param {    
      long  random_number_gen      ;
      long adc_threshold           ;/* D=      5   minimum ADC value */
      float chamber_r_min           ;/* D=      8.0  inner radius [cm]    */
      float chamber_r_max           ;/* D=     32.0  outer radius [cm]    */
      float chamber_phi_min         ;/* D=      0.0  min. phi [deg]    */ 
      float chamber_phi_max         ;/* D=     40.0  max. phi [deg]    */ 
      float chamber_z_min           ;/* D=    150.0  zmin [cm]    */ 
      float chamber_cham_length     ;/* D=    120.0  float chamber length [cm]*/ 
      float chamber_cath_voltage    ;/* D=   -10000.0 drift cathode voltage [V]    */
      float gas_attenuation         ;/* D=       0.0   attenuation [1/cm]    */
      float gas_gas_gain            ;/* D=    2000.0   gas gain         */
      float gas_avg_ion_pot         ;/* D=      26.0   ave ion pot [eV]    */
      long readout_number_plane    ;/* D=   10        number of readout planes   */
      float readout_pad_pitch       ;/* D=   0.20      pad pitch [cm]    */
      float readout_pad_length      ;/* D=   2.0       pad length [cm]    */
      float readout_sigma_prf       ;/* D=   600.0     pad-response-function sigma [um]    */
      float readout_shaper_time     ;/* D=   150.0     shaper time FWHM [ns]    */
      float readout_slice           ;/* D=   200.0     SCA time slice [ns]    */
   };
