/*   fss_gas.idl
*
*        Table type: fss_gas
*        Description: FSS gas parameter table                     
*
*   Author: Holm Huemmler
*   Email: hummler@mppmu.mpg.de
*   Date:  September 29, 98
*
*/

   struct fss_gas {    
      float efield                  ;/* electric field strength */
      float velocity_z              ;/* drift velocity */
      float diffusion_z             ;/* diffusion constant */
      float diffusion_x             ;/* diffusion constant */
      float diffusion_y             ;/* diffusion constant */
      float angle_lorentz           ;/* lorentz angle of drift electrons */
   };
