/*   fte_fteval.idl
*
*   Table: fteval
*        description: Output of tre FTPC momentum evaluator
*
*/

   /*******************  Row struct *******************/
   struct fte_fteval {    
       long      track;       /* id of the track */
       long      ge_pid;      /* GEANT part. ID */
       long      n_hits;      /* # of assigned hits to rec. track */
       long      n_ge_tr;     /* # of GEANT tracks hits are taken for rec. */
       long      qg;          /* GEANT charge */
       long      qr;          /* reconstructed charge */
       long      pseu_pri_tag;/* prim. tag of the first hit of a track */
       float     p_v[3];      /* Vertex Momentum */
       float     p_v_r[3];    /* Reconstructed Vertex Momentum */ 
       float     p_tot_g;     /* total GEANT momentum (average) */
       float     p_tot_r;     /* total reconstructed momentum */
       float     p_x_g;       /* GEANT momentum in x-direction (average) */
       float     p_x_r;       /* rec. momentum in x-direction */
       float     p_y_g;       /* GEANT momentum in y-direction (average) */
       float     p_y_r;       /* rec. momentum in y-direction */
       float     p_z_g;       /* GEANT momentum in z-direction (average) */
       float     p_z_r;       /* rec. momentum in z-direction */
       float     p_t_g;       /* transverse GEANT momentum */
       float     p_t_r;       /* rec. transverse momentum */
       float     y_pio_g;     /* GEANT pion-rapidity */
       float     y_pio_r;     /* rec. pion-rapidity */
       float     theta_g;     /* GEANT theta-angle */
       float     theta_r;     /* rec. theta-angle */
       float     twist_g;     /* GEANT twist-angle */
       float     twist_r;     /* rec. twist-angle */
       float     ver_r[3];    /* rec. vertex-position */
       float     c_stdv;      /* STDV of points to circ-fit */
    };

/*  Last mod. for fte_fteval: $Date: 1998/01/19 02:25:14 $ */
