/*   fv0_vertex.h
*   Table: fv0_vertex
*	description: Output of fv0 FTPC V0 finder
*/
 struct fv0_vertex {
  long id;               /* Primary key id */
  long id_vertex;        /* Foreign key id vertex */
  long idneg;            /* Foreign key id of negative track of the decay */
  long idpos;            /* Foreign key id of positive track of the decay */
  float dcan;            /* dca of negative track from vertex */
  float dcap;            /* dca of positive track from vertex */
  float dcapn;           /* dca of two tracks at V0 vertex */
  float dcav0;           /* measured dca of V0 from vertex */
  float neg_px;          /* momentum of neg track at the v0 vertex */
  float neg_py;
  float neg_pz;
  float pos_px;          /* momentum of pos track at the v0 vertex */
  float pos_py;
  float pos_pz;
 };

/*  Last mod. for fv0_vertex: $Date: 1999/04/02 20:55:45 $ */

