/*   exiam.idl
*    Module: exiam
*    Description: IDL file for the exiam module
*/
#include "PAM.idl"
#include "exi_exipar.idl"
#include "dst_track.idl"
#include "dst_vertex.idl"
#include "dst_v0_vertex.idl"
#include "dst_xi_vertex.idl"
#include "exi_aux.idl"

interface exiam : amiModule {
	STAFCV_T call
		( inout	exi_exipar	exipar
  	        , inout	dst_track    	globtrk
                , inout dst_vertex      vertex
                , in    dst_v0_vertex   v0_vertex
                , out   dst_xi_vertex   xi_vertex
		, out	exi_aux		exiaux
	);
   } ;

/*  Last mod. for exiout:  $Date: 1999/02/11 03:15:21 $ */



