//
// $Id: HbtTag.idl,v 1.1 2000/03/16 01:45:43 laue Exp $
//
// HBT Tag
//
// $Log: HbtTag.idl,v $
// Revision 1.1  2000/03/16 01:45:43  laue
// StHbtTagMaker added to the package; FL 03-15-2000
//
// Revision 1.2  1999/02/09 22:21:42  wenaus
// PWG tag definition fixes
//
// Revision 1.1  1999/02/09 21:42:22  wenaus
// Final (?) versions of MDC2 PWG tags
//
//

struct HbtTag {
    float chargedParticles_Means[5];
    float chargedParticles_Sigmas[5];
    
    float positiveParticles_Means[5];
    float positiveParticles_Sigmas[5];
    
    float negativeParticles_Means[5];
    float negativeParticles_Sigmas[5];
    
    float positivePions_Means[5];
    float positivePions_Sigmas[5];
    
    float negativePions_Means[5];
    float negativePions_Sigmas[5];
    
    float positiveKaons_Means[5];
    float positiveKaons_Sigmas[5];
    
    float negativeKaons_Means[5];
    float negativeKaons_Sigmas[5];
    
    float protons_Means[5];
    float protons_Sigmas[5];
    
    float antiProtons_Means[5];
    float antiProtons_Sigmas[5];
};
