#!/usr/local/bin/perl
# $Id: bfc,v 1.3 1999/05/21 19:48:24 fisyak Exp $
# $Log: bfc,v $
# Revision 1.3  1999/05/21 19:48:24  fisyak
# Add recognition of file name by . and no. of events to process from file name
#
# Revision 1.2  1999/05/20 21:58:31  didenko
# Replace cshell version by perl one
#
use Env;
use File::Basename;
system 'echo "Starting job execution at" `date` " on " $HOSTNAME';
print "STAR_LEVEL = $STAR_LEVEL\n";
die "No input Chain defined" if ! defined($ARGV[0]);
my $Chain = "";

for (my $i = 0;$i<=$#ARGV;$i++){
  if ($ARGV[$i] && ! ($ARGV[$i] =~ /\./)) {$Chain .= " " .  $ARGV[$i];}
}
my  $input_file;
if ($ACTUAL_INPUT0) {
  chomp ($ACTUAL_INPUT0);
  print "Input: ",$ACTUAL_INPUT0, "\n";
  $input_file = basename($ACTUAL_INPUT0);
  print "input: ",$input_file,"\n";
  my $OUTPUT_FILE0 = convert($ACTUAL_OUTPUT0);
  my $OUTPUT_FILE1 = convert($ACTUAL_OUTPUT1);
  my $OUTPUT_FILE2 = convert($ACTUAL_OUTPUT2);
  print "Output:", $ACTUAL_OUTPUT0,",",$ACTUAL_OUTPUT1,",",$ACTUAL_OUTPUT2,"\n";
  print "Output:", $OUTPUT_FILE0,",",$OUTPUT_FILE1,",",$OUTPUT_FILE2,"\n";
  my $output_file0 = basename($OUTPUT_FILE0);
  my $output_file1 = basename($OUTPUT_FILE1);
  my $output_file2 = basename($OUTPUT_FILE2);
  my $out_dir      = dirname ($OUTPUT_FILE0);
  print "Output:", $output_file0,",",$output_file1,",",$output_file2,"\n";
  print "Dirname:", $out_dir, "\n";
  if ($out_dir && !-d $out_dir) {mkdir $out_dir,0773;}
  if (-f $output_file0) {system 'rm $output_file0';}
  if (-f $output_file1) {system 'rm $output_file1';}
  if (-f $output_file2) {system 'rm $output_file2';}
  symlink $INPUT0      ,  $input_file;
  symlink $OUTPUT_FILE0,  $output_file0;
  symlink $OUTPUT_FILE1,  $output_file1;
  symlink $OUTPUT_FILE2,  $output_file2;
  symlink $output_file0,  $OUTPUT0;
  symlink $output_file1,  $OUTPUT1;
  symlink $output_file2,  $OUTPUT2;
}
else {
  for (my $i = 0;$i<=$#ARGV;$i++){
    if ($ARGV[$i] && $ARGV[$i] =~ /\./) {$input_file =  $ARGV[$i];}
  }
}
die "No input file has been defined" if ! $input_file;
my $NofEvents = 999;
if ($input_file =~ /evts/){
  my $dummy,  $evts, $ev;
  ($dummy, $dummy, $evts)  = split /_/, $input_file;
  ($ev, $dumm) = split /e/, $evts;
  if ($ev > 0 && $ev < 100000000) {$NofEvents = $ev;}
}
my $cmd = " root4star -b -q 'bfc.C(" . $NofEvents . ",\"" . $Chain . "\",\"" . $input_file . "\")\'";
print $cmd,"\n";
system $cmd;
system 'echo "Finished job execution at" `date` " on " `hostname`'; 

exit 0;
#______________________________________________________
sub convert($) {
  my $new_name = @_[0];
  $new_name =~ s'/home/starreco/reco'/disk00001/star'g;
  return $new_name;
}
#END
