#!/usr/local/bin/perl
use Env;
use File::Basename;
use File::Copy;
system 'echo "Starting job execution at" `date` " on " $HOSTNAME';
print "STAR_LEVEL = $STAR_LEVEL\n";
my $Chain = "";
die "No input Chain defined" if ! defined($ARGV[0]);
for (my $i = 0;$i<=$#ARGV;$i++){
  if ($ARGV[$i] && ! ($ARGV[$i] =~ /\./)) {$Chain .= " " .  $ARGV[$i];}
}
my  $input_file;
my  @ACTUAL_OUTPUTS = ($ACTUAL_OUTPUT0,
		       $ACTUAL_OUTPUT1,
		       $ACTUAL_OUTPUT2,

my @OUTPUTS = ($OUTPUT0,
	       $OUTPUT1,
	       $OUTPUT2,

my  @OUTPUT_FILES = ();
my  @output_files = ();
if ($ACTUAL_INPUT0) {
  chomp ($ACTUAL_INPUT0);
  print "Input: ",$ACTUAL_INPUT0, "\n";
  $input_file = basename($ACTUAL_INPUT0);
  print "input: ",$input_file,"\n";
  }
  print "ACTUAL_OUTPUTS = @ACTUAL_OUTPUTS\n";
  print "OUTPUT_FILES   = @OUTPUT_FILES\n";
  print "output_files   = @output_files\n";

  for (my $i = 0;$i<=$#ARGV;$i++){
    if ($ARGV[$i] && $ARGV[$i] =~ /\./) {$input_file =  $ARGV[$i];}
  }
die "No input file has been defined" if ! $input_file;
my $NofEvents = 200;

symlink "/star/data03/reco/StarDb", "StarDb";
my $cmd = " root4star -q -b 'bfc.C(200,\"in TpcT0\",\"" . $input_file . "\")\';
system 'echo "Start calibration job execution at" `date` " on " `hostname`'; 
print "$cmd\n";
system $cmd;
system 'echo "Finished calibration job execution at" `date` " on " `hostname`'; 
exit 0;
#______________________________________________________
__END__;





