#!/bin/csh

# This file will be kept up to date
# per library so we can create the links
# appropriate for the supported platform and
# the backward compatible ones. 
# Added comments a MUST (thanks)


#
# RedHat 7.2
#
if ( -e .i386_linux24) then
    if ( ! -e .rh73_gcc296) then
	echo "Creating RedHat 7.3 is support via RedHat 7.2 using the same compiler"
	ln -s .i386_linux24 .rh73_gcc296
    endif

    if ( ! -e .i386_redhat72) then
	echo "Creating Alternate RedHat 7.2 support (naming scheme changed at RH7.2)"
	ln -s .i386_linux24 .i386_redhat72
    endif
else
    echo "The base OS support directory, .i386_linux24, does not exists"
endif

# ----------
# RedHat 8.0
# ----------
if ( -e .rh80_gcc32) then
    # Generic Redhat support / alternate STAR_HOST_SYS
    if ( ! -e .i386_redhat80) then
	echo "Creating Generic Redhat support / alternate STAR_HOST_SYS for RH8.0"
	ln -s .rh80_gcc32 .i386_redhat80
    endif
    # alternate gcc support
    if ( ! -e .rh80_gcc322) then
	echo "Creating alternate gcc support for RH8.0"
	ln -s .rh80_gcc32 .rh80_gcc322
    endif
else
    echo "The base OS support directory, .rh80_gcc32, does not exists"
endif

# 
# Redhat 9.0
#
if ( -e .rh80_gcc32) then
    # RedHat 9 is supported via RedHat 8 using the same compiler
    if ( ! -e .rh9_gcc322) then
	echo "Creating RedHat 9 is supported via RedHat 8 using an assumed equivalence gcc 3.2 -> 3.2.2"
	ln -s .rh80_gcc32 .rh9_gcc322
    endif
else
    echo "The base OS support directory, .rh80_gcc32, does not exists"
endif

#
# Scientific Linux
#
if ( -e .sl302_gcc323) then
    # Support for earlier version seems strange but
    # in this case, kernel and gcc libs are the same
    if ( ! -e .sl301_gcc323) then
	echo "Forward compatibility assumed between SL301 -> SL302"
	ln -s .sl302_gcc323 .sl301_gcc323
    endif
    if ( ! -e .rh3_gcc323 ) then
	echo "RHE supported through SL3"
	ln -s .sl302_gcc323 .rh3_gcc323
    endif
else
    # A bit risky. Will get argument as confirmation
    # Note that those are bacward compatibility links
    # only.
    if ( $1 != "") then
	if ( -e .rh80_gcc322 ) then
	    ln -s .rh80_gcc322 .sl301_gcc323 && echo "SL301 compatbility link created"
	    ln -s .rh80_gcc322 .sl302_gcc323 && echo "SL302 compatbility link created"
	endif
    endif
endif
