#!/bin/sh
#  $Id: dropit,v 1.1 1998/02/17 18:06:47 fisyak Exp $
#  $Log: dropit,v $
#  Revision 1.1  1998/02/17 18:06:47  fisyak
#  Add dropit for PATH
#
if [ $# -eq 2 ]; then
   spath=$1
   drop=$2
elif [ $# -eq 1 ]; then
   spath=$PATH
   drop=$1
else
   spath="$PATH"; 
   drop=""
fi
if [ -x /bin/nawk ]; then
echo ${spath} | /bin/nawk '
BEGIN { FS=":"}
{  n=0; m=0;
   {for (i = 1; i<=NF; i++)
     {m=0; 
     for (j=1; j<i; j++) {
       if (length($i)==length($j)&&index($i,$j)>0) {m++; break;}};
     if (length(y)>0 && index($i,y)>0) m++;
     if (m==0) 
       if (length($i)>0) {if (n>0) {x=x":"$i} else {x=x""$i; n++}}}
   }
}
END {print x}
'  y="$drop"
else
  echo ${spath}
fi
