#!/opt/star/bin/perl
# List dst xdf files loaded to DB.
# Creates a file dstdelete.csh which will delete the files that
# have been loaded.
# T. Wenaus
$topPrefix="/disk1/star/";
#$topLevel="auau200";
#$topLevel="tfs_dst";
$topLevel = shift(@ARGV) || "auau200";
if ( open(SCRIPT,"> dstdelete.csh") ) {
    print "dstdelete.csh created to delete files loaded to DB and HPSS\n";
} else {
    print "Unable to create deletion script; cannot write locally\n";
}
$theTime = localtime(time());
print SCRIPT "# XDF DST deletion script generated at $theTime\n";
print "XDF DST files under $topPrefix$topLevel loaded to DB as of $theTime\n";
open(FILES, "cd $topPrefix; find $topLevel/ | grep 'dst\.xdf' |")
 or die "Failed on xdf seek\n";
$totalsize = 0;
$nfiles = 0;
$indb = 0;
while (<FILES>) {
  $fullpath = $_;
  @tokens = split(/\//);
  $totalsize += $tokens[4];
  $nfiles++;
  $fname = $tokens[$#tokens];
  $thepath = $topPrefix.$fullpath;
  $thepath =~ s/$fname//;
  chomp($fname);
  chomp($fullpath);
  $dbname = "/star/sol/db/stardb/dst/$fname.STAR.DB";
  if ( -e $dbname ) {
      $indb++;
#     if it is loaded, check whether it is on HPSS
      @tokens = split(/\//), $fname;
      $bimpact = $tokens[3];
      $yr = $tokens[4];
      $yr =~ s/ear//;
      $hadronic = $tokens[5];
      $hadronic =~ s/hadronic//;
      $sumfilename = $bimpact.$yr.$hadronic.".catalog";
      $sumfile = "/star/u2e/starreco/MDC1/summary/".$sumfilename;
      $hpssStatus = "??HPSS";
      if ( -e $sumfile ) {
          $setname = $fname;
          $setname =~ s/(_|_h_)dst.xdf//;
          open (SUMMARY, "grep $setname $sumfile |");
          $len = read SUMMARY, $str, 999;
          if ( $len == 0 ) {
              print "!!!!! No record of $setname in catalog $sumfilename\n";
          } else {
              if ( $str =~ /[0-9]+[ \t]+Done/i ) {
                  $hpssStatus = "onHPSS";
                  print SCRIPT "rm -f ".$topPrefix.$fullpath."\n";
              } else {
                  $hpssStatus = "NOTonHPSS";
              }
          }
      } else {
          print "!!!!! No file ".$sumfile."\n";
      }
      print $topPrefix.$fullpath." ".$hpssStatus."\n";
  }
}
print "Total of ",$nfiles," files under $topLevel, ",$indb," loaded into DB\n";
