#!/usr/bin/env perl

#
# This shift/noshit selection is always a mess ...
# Get around by fixing ROOT make file.
# (c) J. Lauret 2003
# 
#

$CERNL = $ENV{CERN_LEVEL};

if ( ! defined($CERNL) ){
    die "No CERN_LEVEL defined. Cannot proceed.\n";
}

if ( ! -e "config/Makefile.config"){
    if ( -e "etc/system.rootrc"){
	print "Will perform pre-make actions\n";

	#
	# Additional task include cleaning up the etc/ directory
	# and removing the links since the configure script will
	# regenerate and screw up the global setup. However, it 
	# will need to be re-created later
	#
	if ( -l "etc/system.rootrc"){ unlink("etc/system.rootrc");}
	if ( -l "etc/root.mimes"){    unlink("etc/root.mimes");}
	exit;

    } else {
	die "You are probably not in the proper directory\n";
    }
} else {
    # we can then restore things undone before
    print "Checking etc/ files\n";
    foreach $file (("system.rootrc","root.mimes")){
	if ( -l "etc/$file.new" && ! -l "etc/$file"){
	    print "  Adjusting etc/$file\n";
	    $link = readlink("etc/$file.new");
	    $link =~ s/\.new//;
	    if ( -f "etc/$file" ){  unlink("etc/$file");}
	    system("/bin/ln -s $link etc/$file");
	}
    }
}



if ( ! -e "/cern/$CERNL/lib/libpacklib_noshift.a"){
    die "/cern/$CERNL/lib/libpacklib_noshift.a does not exist. Would not know what to do...\n";
}


open(FI, "config/Makefile.config");
open(FO,">config/Makefile.config.new");

$done = 0;

while ( defined($line = <FI>) ){
    chomp($line);
    if ($line =~ m/CERNLIBS\s+:=\s*$/){
	print FO "CERNLIBS := /cern/$CERNL/lib/libpacklib_noshift.a /cern/$CERNL/lib/libkernlib.a\n";
	print    "CERNLIBS := /cern/$CERNL/lib/libpacklib_noshift.a /cern/$CERNL/lib/libkernlib.a\n";
	$done = 1;
    } elsif ( $line =~ m/BUILDHBOOK/){
	# Introduced at ROOT 4.04.02
	print FO "BUILDHBOOK := yes\n";
    } else {
	print FO "$line\n";
    }
}
close(FI);
close(FO);



if ($done){
    rename("config/Makefile.config",    "config/Makefile.config.old");
    rename("config/Makefile.config.new","config/Makefile.config");

    print "config/Makefile.config fixed\n";
} else {
    print "config/Makefile.config already fixed\n";
    unlink("config/Makefile.config.new");
}

