#! /usr/local/bin/tcsh -f
 set list = `crs_node_status.pl | awk '{if ($1 == "Job") {print m" "$4" "i"\n"m" "$5" "j}; m=$1; i=$3; j=$4;}'`
 while ($#list > 1)
   set node    = $list[1]; if ($#list > 1) shift list;
   set jobfile = $list[1]; if ($#list > 1) shift list;
   set jobno   = $list[1]; if ($#list > 1) shift list;
   set logfile = `echo $jobfile | awk -F_ '{print $4"_"$5"_"$6}'`
   echo node = $node logfile = $logfile jobfile = $jobfile  jobno = $jobno
   if ("$logfile" != "__") then
     find /star/scr2h/starreco/MDC1/auau200/hijing135/default/ -name "${logfile}*"  -exec ls -alF {} \;
   endif
#   find /star/scr2h/starreco/MDC1/auau200/hijing135/default/ -name "${logfile}_*"  -exec ls -alF {} \;
 end
