#! /usr/local/bin/tcsh
set PROCESS = root
set TOPHPSS_SINK =  /home/starsink/raw/auau200/hijing135/default
set TOPHPSS_RECO =  /home/starreco/reco/auau200/hijing135/default
set TOP_TEST     =  /star/scr2f/starreco/MDC1/tests/auau200/hijing135/default
set REQUEST      =  /star/u2e/starreco/MDC1/requests
set JOB_SUMMARY  =  /star/u2e/starreco/MDC1/summary
set JOB_LOG      =  /star/scr2h/starreco/MDC1/auau200/hijing135/default
#set SET          =   b0_3/year2a/hadronic_on
set SET          =   b0_20/year2a/hadronic_on
set input_file = `basename $1 .xdf`
set input_dir  = /disk1/star/auau200/hijing135/default/${SET}/g2t
set output_dir = /disk1/star/auau200/hijing135/default/${SET}/root
set log_dir    = ${JOB_LOG}/${SET}/root
if (! -d ${log_dir}) mkdir -p ${log_dir}
set batch = ${REQUEST}/${PROCESS}/`basename ${input_file}`
set log_file   = ${log_dir}/${batch}
cd ${REQUEST}
if (! -d ${PROCESS}) mkdir ${PROCESS}
cd ${PROCESS}
if (-f ${batch}) rm -f ${batch}
#if (-f ${batch}.C) rm -f ${batch}.C
cat > ${batch} <<EOF
#! /usr/local/bin/tcsh -f
#BSUB -R cas
source ${GROUP_DIR}/.stardev
cd  ${REQUEST}/${PROCESS}
Root.exe -b -q <<EOD
{
gROOT->LoadMacro("bfc.C");
const Char_t *file_in  ="${input_dir}/${input_file}.xdf";
const Char_t *file_out ="${output_dir}/${input_file}.xdf";
const Char_t *root_out ="${output_dir}/${input_file}.root";
const Int_t No = 1000;
bfc(file_in,file_out,root_out,No);
}
EOD
EOF
chmod +x ${batch}
#more ${batch}
set jobname = `basename ${batch}`
set jobname = `echo ${jobname} | cut -c1-9`
echo qsub -R cas -o ${log_file} -e ${log_file}  -J ${jobname} ${batch} 
bsub -R cas -o ${log_file} -e ${log_file}  -J ${jobname} ${batch}
