#! /bin/csh -f
#  set list = grep -l ` Segmentation violation` 
#  set list = grep -l ASU_ALLOC: ***Error***: No Space `
#  set list = grep -l DS_E_XDR_IO_ERROR'
#  set list = grep -l CANT_READ_FROM_STREAM '
#  set list = grep -l DSL_NODE_NOT_FOUND '
#  set list = grep -l ERROR_WRITING_DATASET'
#  set list = grep -l 'error\ in\ loading\ shared'
#  set list = grep -l 'No\ such\ file'
#  set list = grep -l 'No\ space\ left\ on\ device'
#  set list = grep -l 'total\ CPU\/event'
#  set list = grep -l E-o-D
#  set list = grep -l 'No\ Geant\ hits\ in\ TPC'
#  set list = grep -l 'Not\ enough\ tracks'
#  set list = grep -l 'Problem\ running\ tfs\_g2t'
#  set list = grep -l 'Problem\ on\ return\ from\ EVR\_AM'
#  set list = grep -l 'Problem\ on\ return\ from\ FILL_DST_RUN_SUMMARY'
#
# echo $tag "->" $list
# set list = `ls *evts`
# if (-z "$list") exit 0
#
 foreach tag (NoSpace ErrLoadLib CantRead CantOpen NoSpaceOnDev staging-failed HPSS-staging-problem SegViolation BreakBusErr SimulBreak done staging-problem NoGeantHitTPC NotEnTrackSVT tfsProblem evrProblem)
    switch ($tag)
    case "NoSpace":
#=============================
    set list = `grep -l 'ASU_ALLOC:\ \*\*\*Error\*\*\*\:\ No\ more\ memory\ available'  *evts`
    foreach file ($list)
    set ltime = `mod_time $file`
    if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
     case "ErrLoadLib":
#============================
     set list = `grep -l 'error\ in\ loading\ shared' *evts.err`
    foreach file ($list)
    set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
    case "CantRead":
#============================
    set list = `grep -l 'CANT_READ_FROM_STREAM' *evts.err`
    foreach file ($list)
     set ltime = `mod_time $file`
      if( $ltime > 3600) mv $file ${file}_${tag}
    end
    breaksw
    case "CantOpen":
#============================
     set list = `grep -l 'DSL_NODE_NOT_FOUND' *evts.err`
    foreach file ($list)
     set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
    case "NoSpaceOnDev":
#============================
    set list = `grep -l 'No\ space\ left\ on\ device' *evts.err`
    foreach file ($list)
    set ltime = `mod_time $file`
    if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw 
    case "staging-failed":
#===========================
    set list = `grep -l 'error\ in\ CFOPEN' *evts.err`
    foreach file ($list)
    set ltime = `mod_time $file`
    if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw 
    case "HPSS-staging-problem":
#===========================
    set list = `grep -l 'HPSS\ Staging\ problem' *evts`
    foreach file ($list)
    set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
    case "SegViolation":
#===========================
    set list = `grep -l '*\*\*\ Break \*\*\*\ Segmentation\ violation' *evts`
    foreach file ($list)
     set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw  
    case "BreakBusErr"
#===========================
    set list = `grep -l '*\*\*\ Break \*\*\*\ Bus\ error' *evts`
    foreach file ($list)
    set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
       case "SimulBreak"
#===========================
    set list = `grep -l '*\*\*\ Break \*\*\*\ Simulated\ break' *evts`
    foreach file ($list)
    set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw 
    case "done":
#===========================
    set list = `grep -l 'total\ CPU\/event' *evts`
    foreach file ($list)
    set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
     case "staging-problem":
#===========================
    set list = `grep -l E-o-D *evts`
    foreach file ($list)
    set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
    case "NoGeantHitTPC":
#============================
     set list = `grep -l 'No\ Geant\ hits\ in\ TPC' *evts`
    foreach file ($list)
     set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw
    case "NotEnTrackSVT":
#============================
     set list = `grep -l 'Not\ enough\ tracks' *evts`
    foreach file ($list)
     set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw  
       case "tfsProblem":
#===========================
    set list = `grep -l 'Problem\ running\ tfs\_g2t' *evts`
    foreach file ($list)
     set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw 
       case "evrProblem":
#===========================
    set list = `grep -l 'Problem\ on\ return\ from\ EVR\_AM' *evts`
    foreach file ($list)
     set ltime = `mod_time $file`
     if( $ltime > 3600)  mv $file ${file}_${tag}
    end
    breaksw 
    default:
#  ====================
    breaksw
  endsw
end
set list = `ls -1 *evts* | grep -v Aft`
