#!/bin/csh -f
set run = $1
shift
set batch = r`echo ${*} | sed -e 's/ //g' -e 's/-/_/g'`
echo ${batch}
rm -f ${batch}
cat > ${batch} <<EOF
${run} ${*}
EOF
more ${batch}
set PWD = `pwd`
echo /usr/local/bin/qsub -M ${USER} ${PWD}/${batch}
/usr/local/bin/qsub -M ${USER} ${PWD}/${batch}   
