#!/bin/csh

#
# Remove file depence for makers from
# the STAR environment
#
source ${GROUP_DIR}/star_cshrc.csh

echo "LEVEL = $STAR_LEVEL"
echo "STAR  = $STAR"

setenv NODEBUG 1
cons -r $*

unsetenv NODEBUG
cons -r $*

echo ""
