*
* $Id: incbeg.inc,v 1.1.1.1 2004/01/15 00:11:58 potekhin Exp $
*
* $Log: incbeg.inc,v $
* Revision 1.1.1.1  2004/01/15 00:11:58  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:28:39  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:19:49  cernlib
* Geant
*
*
*
* incbeg.inc
*
#if defined(CERNLIB_INCLUDE)
#if defined(CERNLIB_IBM)
#if 0
      INCLUDE '
#endif
#endif
#endif
