#!/usr/bin/env perl
Import qw ( env INCLUDE LIB BIN BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
$build =~ s/\\/\//g;
(my $obj_dir = DirPath '.') =~ s/\\/\//g;
(my $Dir = $obj_dir) =~ s/$build\///g;
my $ObjDir = "#" . $obj_dir; 
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $pkg = "agetof";
my $PKG  = $pkg . $env->{SUFEXE};
my $SO_PKG = $PKG . "." . $env->{SUFSOLIB};
my $LIBPKG = $PKG . "." . $env->{SUFLIB};
my @h_files = script::find_hfiles($Dir);
my $FC = $env->{FC};
my $FCPATH = $env->{FCPATH};
my $FFLAGS = $env->{FFLAGS};
my $FPPFLAGS = $env->{FPPFLAGS};
my $CPPFLAGS = $env->{CPPFLAGS};
my $FLIBS = $env->{FLIBS};
my $PGI = $env->{ENV}->{PGI};
my $PGILIBS = "";
my $CLIBS = $env->{CLIBS};
print "build $pkg with cons\n";
my $FC         = $env->{FC};
my $FEXTEND    = $env->{FEXTEND};
my $LD         = $env->{LD}; #!
my $LDFLAGS    = $env->{LDFLAGS};
#my $CERNLIBS   = $env->{CERNLIBS};
my $CERNLIBS   = "-L$ROOTSYS/lib -lminicern";
my $CXX_VERSION= $env->{CXX_VERSION};


#if ($FC eq 'pgf77') {# || $STAR_SYS =~ /x86_darwin/) 
#  $CERNLIBS = `cernlib kernlib`;
#  chomp($CERNLIBS);
#    $FC       = $env->{G77}; 
#    print "set FC => $FC ==============================\n" if $param::debug;
#    $FFLAGS   = $env->{G77FLAGS}; 
#    $FEXTEND  = $env->{G77EXTEND};
#}
my $LD        = $env->{LD}; #!
# if ($LD eq 'g++') {
#  $LD = "gcc";
# } 
#                                          or $LD eq 'icpc'
if ($LD eq $env->{CC} or $LD eq $env->{CXX} or $LD eq 'icpc') {$LD = $FC;}
if ($LD eq 'gcc' && $CXX_VERSION < 4 ) { 
    $LDFLAGS = "-Wl,-Bstatic";
}
my $Libraries = $CERNLIBS .  " " . $FLIBS . " " . $CLIBS;
if ($FC =~ m/g77/ || $FC =~ m/gfortran/) { 
  if ($env->{CXX_VERSION} == 3) {$Libraries .= " -lfrtbegin";}
#  $Libraries .= " " . $env->{LIBG2C};
}
# if ($FC eq 'ifort') { 
#  my $LIBIFCPATH    = `which ifort | sed -e 's|bin/ifort|lib|'`; chomp($LIBIFCPATH);
#  $Libraries .= " " . $LIBIFCPATH . "/for_main.o"; 
# }
$env2 = $env->clone('FC'           => $FC,
		    'LD'           => $LD,
		    'LDFLAGS'      => $LDFLAGS,
		    'FPPFLAGS'     => $FPPFLAGS,
		    'FFLAGS'       => $FFLAGS,
		    'FCPATH'       => $FCPATH,
		    'FEXTEND'      => "",
		    'CPPFLAGS'     => $CPPFLAGS,
		    'ObjDir'       => $obj_dir,
		    'Libraries'    => $Libraries
		   );
my @srcc = script::find_sources($Dir);# print "src = @srcc\n";
my @src = ();
foreach my $s (@srcc) {
    next if $s =~ /^cmt/;
    push @src, $s;
}
if ($#src > -1) {
    script::Keep $pkg;
    Program      $env2 $pkg, @src;
    Depends $env2 $pkg, $BIN . "/agetof.def";
    Install $env2 $BIN, $pkg;
    Install $env2 $BIN, "agetof.def";
    InstallAs $env2 $BIN . "/geant3", $BIN . "/" . $pkg;
    InstallAs $env2 $BIN . "/geant3.def", $BIN . "/agetof.def";
}  
