//:Copyright 1995, Lawrence Berkeley National Laboratory
//:>--------------------------------------------------------------------
//:FILE:	amiI.idl
//:DESCRIPTION:	AMI Interface Orbix-objects
//:AUTHOR:	cet - Craig E. Tull, cetull@lbl.gov
//:BUGS:	-- STILL IN DEVELOPMENT --
//:HISTORY:	03feb97-v001b-cet- rename file
//:HISTORY:	15dec95-v001a-cet- Recreation for real Moast
//:HISTORY:	24jul95-v000a-cet- creation
//:<--------------------------------------------------------------------

//:----------------------------------------------- INCLUDES           --
//#include "socI.idl"
#include "tdmI.idl"

//:----------------------------------------------- TYPEDEFS           --
typedef sequence<tdmTableI> TABLE_SEQ_T;
typedef sequence<string> STRING_SEQ_T;
typedef long PAM_PTR_T;
enum AMI_IO_MODE {
	AMI_INPUT_MODE,
	AMI_OUTPUT_MODE,
	AMI_UPDATE_MODE
};

//:=============================================== INTERFACE          ==
interface amiInvokerI : socObjectI {

//:----------------------------------------------- ATTRIBUTES         --
readonly attribute long rank;
readonly attribute PAM_PTR_T pFunction;

//:----------------------------------------------- FUNCTIONS          --
STAFCV_T call(inout TABLE_SEQ_T tbl);
STAFCV_T init();
STAFCV_T start();
STAFCV_T stop();
string tableSpec(in long ntbl);
AMI_IO_MODE tableMode(in long ntbl);
};

//:=============================================== INTERFACE          ==
interface amiBrokerI : socFactoryI {

//:----------------------------------------------- ATTRIBUTES         --
//:----------------------------------------------- FUNCTIONS          --
STAFCV_T callInvoker(in string name, in STRING_SEQ_T tables);

STAFCV_T deleteInvoker(in string name);
amiInvokerI findInvoker(in string name);
amiInvokerI getInvoker(in IDREF_T id);
amiInvokerI newInvoker(in string name, in STRING_SEQ_T types);
};

