/* rl1_ks.idl */
#include "PAM.idl"
#include "ctu_cor.idl"
#include "mwc_raw.idl"
/*#include "vps_raw.idl" */
#include "dst_TriggerDetectors.idl"

interface trg_fillDst : amiModule {
        STAFCV_T call
                ( in    ctu_cor              ctu_cor
                , in    mwc_raw              mwc_raw
/*                , in    vps_raw              vps_raw */
                , out   dst_TriggerDetectors detectors
        );
};
/*  Last mod. for rl1_ks: $Date: 1999/02/06 01:52:56 $ */

