/* trg_fillDst.idl */
#include "PAM.idl"
#include "ctu_cor.idl"
#include "mwc_raw.idl"
/*#include "vps_raw.idl" */
#include "dst_TrgDet.idl"

interface trg_fillDst : amiModule {
        STAFCV_T call
                ( inout ctu_cor              ctu_cor
                , inout mwc_raw              mwc_raw
                , inout dst_TrgDet           dst
        );
};

/*  Last mod. for trg_fillDst: $Date: 1999/07/11 19:34:56 $ */
