*
* $Id: csichv.inc,v 1.1 2018/11/19 20:43:51 perev Exp $
*
* $Log: csichv.inc,v $
* Revision 1.1  2018/11/19 20:43:51  perev
* 64bits add files
*
* Revision 1.1.1.1  1996/02/26 17:16:36  mclareni
* Comis
*
*
#ifndef CERNLIB_COMIS_CSICHV_INC
#define CERNLIB_COMIS_CSICHV_INC
*
*
* csichv.inc
*
      COMMON/CSICHV/ICHLA,ICHLZ,ICHD0,ICHD9,ICHSUSC,
*--     ichar         'A'   'Z'  '0'   '9'   '_'
     + ICHSX,ICHSE,ICHBLN,KBLN,ICHQUO,ICHSSC,ICHSEQ,ICHBRA,ICHKET,
*--     '#'   '!'    ' '  bbbb  ''''   ';'    '='    '('    ')'
     + ICHMINU,ICHPLUS,ICHCOMM
*--      '-'     '+'     ','


#endif
