*
* $Id: cspanm.inc,v 1.1 2018/11/19 20:43:51 perev Exp $
*
* $Log: cspanm.inc,v $
* Revision 1.1  2018/11/19 20:43:51  perev
* 64bits add files
*
* Revision 1.1.1.1  1996/02/26 17:16:36  mclareni
* Comis
*
*
#ifndef CERNLIB_COMIS_CSPANM_INC
#define CERNLIB_COMIS_CSPANM_INC
*
*
* cspanm.inc
*
      CHARACTER *8  QNAME, IQNAME, PNAME, LKNAME
      COMMON/CSPANM/QNAME, IQNAME, PNAME, LKNAME
      COMMON/CSPALN/LQN,   LIQN,   LPN,   LLKN

#endif
