*
* $Id: csutil.inc,v 1.1 2018/11/19 20:43:51 perev Exp $
*
* $Log: csutil.inc,v $
* Revision 1.1  2018/11/19 20:43:51  perev
* 64bits add files
*
* Comis
*
*
*
*
* csutil.inc
*
      integer acsjcal
      integer cscali_
      integer cs_shl_load
      integer cs_get_func
      integer finite
      integer csvptokn
      integer csvptokn
      integer getbyteb
      integer getbytef
      integer getfun2b
      integer getf2b

