*
* $Id: cswpar.inc,v 1.1 2018/11/19 20:43:51 perev Exp $
*
* $Log: cswpar.inc,v $
* Revision 1.1  2018/11/19 20:43:51  perev
* 64bits add files
*
* Revision 1.1.1.1  1996/02/26 17:16:35  mclareni
* Comis
*
*
#ifndef CERNLIB_COMIS_CSWPAR_INC
#define CERNLIB_COMIS_CSWPAR_INC
*
*
* cswpar.inc
*
      DOUBLE PRECISION DVP
      COMMON/CSWPAR/LORN,IREP,NPAR,ITP,IBP,JRESP,JCHP,NCHP
     +,IVP,RVP,DVP,JCHVP,NCHVP,IFPP,IBASEP,IPCB,IPCE

#endif
