//*-- Author :    Valery Fine   26/03/99  (E-mail: fine@bnl.gov)
// $Id: SubDetectorView.C,v 1.6 2000/04/07 17:07:09 fine Exp $
// $Log: SubDetectorView.C,v $
// Revision 1.6  2000/04/07 17:07:09  fine
// adjusted to the ROOT 2.24
//
// Revision 1.5  1999/06/14 08:48:35  fine
// Some bug fixed
//
// Revision 1.4  1999/05/21 15:33:55  kathy
// made sure Log & Id are in each file and also put in standard comment line with name of owner
//
// Revision 1.3  1999/05/20 19:57:08  fine
//  some clean up and protections
//
// Revision 1.2  1999/04/08 21:12:24  fine
// SubDetectorView macro has been introduced
//
// Revision 1.2  1999/03/29 19:17:54  fine
// x3d view has been activated. Some improvement as well
//=======================================================================
// owner: Valery Fine
// what it does: It shows how to select some particular portions of the
//               STAR geometry to draw it out
//=======================================================================

{
 // example to show how to generate the STAR/GEANT geometry sub-structure
 // To run this example one needs the access to Internet
 // To start this example launch ROOT as follows:
 //
 //*-*   root.exe SubDetectorView.C
 //

 //  Begin_Html <P ALIGN=CENTER> <IMG SRC="gif/StarBMTC.gif"> </P> End_Html // 
 
  gROOT->Reset();
  printf( " Loading share library\n");
  gSystem->Load("libSTAR");
  if (!gGeometry) new TGeometry;

  // Open remote GEANT geometry WebFile
  // generated by begin_html <a href=".././St_geant_Maker.html##St_geant_Maker:Work">St_geant_Maker::Work()</a>  method end_html

  TWebFile f("http://www.star.bnl.gov/~fine/star_year_2a.root");
  // read STAR geometry database remotely
  TVolume *hall = f.Get("HALL");
  if (!hall) {
    printf("Sorry, STAR hall was not found !\n");
    return;
  }

  hall->ls();
  TDataSetIter volume(hall);
  TVolume *nextNode = 0;
  // Mark the pieces of the whole detector to create sub-structure
 
  volume("HALL")->Mark();
  ((TVolume *)volume("HALL"))->SetVisibility(1);
  volume.Cd("HALL/CAVE");

  nextNode = (TVolume *)volume("SVTT/SCON");
  if (nextNode) {
     nextNode->Mark();
     nextNode->SetVisibility(1);
   }

   nextNode = (TVolume *)volume("SVTT/SCON/STAC");
   if (nextNode) {
     nextNode->Mark();
     nextNode->SetVisibility(1);
   }


   nextNode = (TVolume *)volume("SVTT/SCON/SHLA/SHMA/SHWA");
   if (nextNode) {
     nextNode->Mark();
     nextNode->SetVisibility(1);
   }

   nextNode = (TVolume *)volume("SVTT/SCON/SHLB/SHMB/SHWA");
   if (nextNode) {
     nextNode->Mark();
     nextNode->SetVisibility(1);
   }

   nextNode = (TVolume *)volume("MAGP/COIL/MCSE");
   if (nextNode) {
     nextNode->Mark();
     nextNode->SetVisibility(1);
   }
  // Mark the whole structure excluding one node
  
  TDataSetIter bmtc(volume("BTOF/BTOH/BSEC/BTRA/BXTR/BMTC"));
  TVolume *node =0;
  while( node = (TVolume *) bmtc())  {
    if( strcmp(node->GetName(),"BXSA"))   node->Mark();
  }
 
  // Create the "open" structure from the "closed" one
  TVolumeView *fullView = new TVolumeView(*hall);
  // Create the "open" sub-structure from the full one
  TVolumeView *s = new TVolumeView(fullView);

  TDataSetIter rangeIter(s);
  TVolumeView *bmtcNode  = rangeIter.FindByName("TPAD");
  Float_t min[3];
  Float_t max[3];
  if (bmtcNode) {
    bmtcNode->GetLocalRange(min,max);
    printf(" Range for %s node is x: %f-%f; y: %f-%f; z: %f-%f\n",
     bmtcNode->GetName(), min[0],max[0],min[1],max[1],min[2],max[2]);

    bmtcNode->GetGlobalRange(s,min,max);
    printf(" Range for %s node is x: %f-%f; y: %f-%f; z: %f-%f\n",
      s->GetName(), min[0],max[0],min[1],max[1],min[2],max[2]);
  }

  printf( " Creating an empty TCanvas object to draw in\n");

 
  s->Draw();
  gPad->Update();
#if 0
  TVirtualPad *thisPad = gPad;
  TView *view = thisPad->GetView(); 
  view->SetRange(min,max);
  thisPad->Modified();
  thisPad->Update();
#endif
} 
