/*   ev0_dst.idl
*       Module: ev0_dst
*        take ev0_aux table and write subset into dst_v0_vertex table
*/
#include "PAM.idl"
#include "ev0_aux.idl"
#include "dst_v0_vertex.idl"


interface ev0_dst : amiModule {
                STAFCV_T call
                        (in    ev0_aux        ev0out,
		         out   dst_v0_vertex  dst_v0_vertex);
};
/* Last mod for ev0_dst:  1998/11/16  */


