/*   ev0_eval2.idl
*       Module: ev0_eval2
*       Evaluation of ev0 performance
*/

#include  "PAM.idl"
#include  "stk_track.idl"
#include  "tpt_track.idl"
#include  "tte_eval.idl"
#include  "ev0_ev0out.idl"
#include  "g2t_track.idl"
#include  "g2t_vertex.idl"


interface ev0_eval2 : amiModule {
                STAFCV_T call
                        ( in    stk_track       svt_track
			, in    tpt_track       tpt_track
			, in    tte_eval        tte_eval
                        , inout   ev0_ev0out    ev0out
                        , in    g2t_track       g2t_track
                        , in    g2t_vertex      g2t_vertex
	);
};

/* Last mod for ev0_eval2: $Date: 1998/01/26 21:26:23 $ */

