/*   ev0_eval2.idl
*       Module: ev0_eval2
*       Evaluation of ev0 performance
*/

#include  "PAM.idl"
#include  "stk_track.idl"
#include  "tpt_track.idl"
#include  "tte_eval.idl"
#include  "dst_vertex.idl"
#include  "ev0_aux.idl"
#include  "ev0_eval.idl"
#include  "g2t_track.idl"
#include  "g2t_vertex.idl"


interface ev0_eval2 : amiModule {
                STAFCV_T call
                        ( in    stk_track       svt_track
			, in    tpt_track       tpt_track
			, in    tte_eval        tte_eval
                        , in    dst_vertex      vertex
                        , in    ev0_aux         ev0out
	                , out   ev0_eval        ev0_eval
                        , in    g2t_track       g2t_track
                        , in    g2t_vertex      g2t_vertex
	);
};

/* Last mod for ev0_eval2: $Date: 1998/05/08 15:06:41 $ */

