/*   ev0_direct.idl
*       Module: ev0_direct
*       fills globtrk with g2t_tracks directly
*/
#include "PAM.idl"
#include "g2t_svt_hit.idl"
#include "g2t_tpc_hit.idl"
#include "g2t_track.idl"
#include "g2t_vertex.idl"
#include "stk_track.idl"
#include "tpt_track.idl"
#include "tte_eval.idl"
#include "egr_globtrk.idl"


interface ev0_direct : amiModule {
                STAFCV_T call
                        ( in    g2t_svt_hit    svt_hit
                        , in    g2t_tpc_hit    tpc_hit
                        , in    g2t_track      track
                        , in    g2t_vertex     vertex 
			, out   stk_track      svt_track
                        , out   tpt_track      tpc_track
	                , out   tte_eval       tte_eval 
                        , inout egr_globtrk    globtrk
                );
};
/* Last mod for ev0_direct: $Date: 1998/01/26 21:26:22 $ */
