/*   ev0_am.idl
*       Module: ev0_am
*       no descriptions here
*/
#include "PAM.idl"
#include "ev0_ev0par.idl"
#include "egr_globtrk.idl"
#include "evr_privert.idl"
#include "ev0_aux.idl"
#include "dst_vertex.idl"
#include "ev0_track.idl"
#include "mft_control.idl"


interface ev0_am : amiModule {
                STAFCV_T call
                        ( in    ev0_ev0par      ev0par
                        , inout egr_globtrk    globtrk
                        , in    evr_privert    privert
		        , inout dst_vertex     vertex
                        , out   ev0_aux        ev0out
		        , inout ev0_track      trak
	                , in mft_control       bmag
                );
};
/* Last mod for ev0_am:  1998/5/7  */
