struct det_hit  {             /* detector hit description  */
  char   hit[8]; /*  encoded hit name                              */
  long   option; /*  encoded hit option (R-rounding,S-single step) */
  long   Nb;     /*  number of bit requested			   */
  float  Fmin;   /*  hit low limit				   */
  float  Fmax;   /*  hit upper limit				   */
  float  Origin; /*  Geant hit origin (-Fmin)			   */
  float  Factor; /*  Geant packing factor			   */
  long   Nbit;   /*  number of bit allocated			   */
  long   Iext;   /*  address of the Geant user step routine	   */
  long   Ifun;   /*  hit function code (1-18 at present)	   */
};
