struct det_user  {/* detector user hit description                                */
  long i0;        /* displacement for hit description part    = 10                */ 
  long N ;     	  /* Number of all hit descriptors (both in non- and cum. parts)  */ 
  long i1;     	  /* displacement for volume description part=10+10*Nh            */ 
  long Nva;    	  /* Number of all volume descriptors (branching or not)          */ 
  long i2;     	  /* displacement for the free space   = 10+10*Nh+3*Nv            */ 
  long Nvb;    	  /* number of real volume branchings for NUMBV                   */ 
  long Goption;	  /* Hit option: 1 - single step, 4 - Calorimetry                 */ 
  long Serial; 	  /* Valid serial number for this subset                          */ 
  long IdType; 	  /* USER detector number                                         */ 
  long Iprin;  	  /* current print flag both for HITS and DIGI                    */ 
};
