struct g2t_track {
  /* $Id: g2t_track.idl,v 1.18 2015/10/12 20:46:58 jwebb Exp $
     $Log: g2t_track.idl,v $
     Revision 1.18  2015/10/12 20:46:58  jwebb
     Hit definition and starsim to root interface for FTS.

     Revision 1.17  2014/05/14 20:01:23  jwebb
     More support for HCAL.  Also note... last checkin of g2t_volume_id was to support FMS preshower.

     Revision 1.16  2012/01/24 03:36:25  perev
     Add Etr

     Revision 1.15  2011/08/03 20:11:57  jwebb
     Add MTD to the g2t hit tables.

     Revision 1.14  2011/07/20 20:44:44  perev
     Fsc added

     Revision 1.13  2011/01/26 19:21:17  perev
     FPD ==> STAR Soft

     Revision 1.12  2006/09/22 20:16:42  potekhin
     Added HPD (R&D)

     Revision 1.11  2006/06/26 19:58:35  potekhin
     Include the gem barrel detector

     Revision 1.10  2005/06/30 16:52:16  potekhin
     Need to include the new IGT hits for the
     inner GEM based tracker (R&D by Gerrit, Nikolai et al)

     Revision 1.9  2005/04/15 14:51:54  potekhin
     Addition of the FGT (GEM) detector needs
     to be reflected in this file

     Revision 1.8  2005/03/24 00:48:54  potekhin
     Killed spurious comment deliminators (CVS fluke)

     Revision 1.7  2005/03/23 22:01:40  potekhin
     Add fst
  */


       long      eg_label;   /* generator track label (0 if GEANT track) */
       long      eg_pid;     /* event generator particle id */
       long      ge_pid;     /* GEANT particle id */
       long      hit_ctb_p;  /* Id of first ctb hit on track linked list */
       long      hit_eem_p;  /* Id of first eem hit on track linked list */
       long      hit_emc_p;  /* Id of first emc hit on track linked list */
       long      hit_esm_p;  /* Id of first esm hit on track linked list */
       long      hit_ftp_p;  /* Id of first ftp hit on track linked list */
       long      hit_gem_p;  /* Id of first gem hit on track linked list */
       long      hit_hpd_p;  /* Id of first hpd hit on track linked list */
       long      hit_ist_p;  /* Id of first ist hit on track linked list */
       long      hit_igt_p;  /* Id of first igt hit on track linked list */
       long      hit_fst_p;  /* Id of first fst hit on track linked list */
       long      hit_fgt_p;  /* Id of first fgt hit on track linked list */
       long      hit_fpd_p;  /* Id of first fpd hit on track linked list */
       long      hit_fsc_p;  /* Id of first fsc hit on track linked list */
       long      hit_mtd_p;  /* Id of first mtd hit on track linked list */
       long      hit_mwc_p;  /* Id of first mwc hit on track linked list */
       long      hit_pgc_p;  /* Id of first pgc hit on track linked list */
       long      hit_pmd_p;  /* Id of first psc hit on track linked list */
       long      hit_smd_p;  /* pointer to first SHM linked list hit */
       long      hit_ssd_p;  /* Id of first ssd hit on track linked list */
       long      hit_svt_p;  /* Id of first svt hit on track linked list */
       long      hit_pix_p;  /* Id of first pix hit on track linked list */
       long      hit_tof_p;  /* Id of first tof hit on track linked list */
       long      hit_tpc_p;  /* Id of first tpc hit on track linked list */
       long      hit_vpd_p;  /* Id of first vpd hit on track linked list */
       long      hit_etr_p;  /* Id of first etr hit on track linked list */
       long      hit_hca_p;  /* Id of first hca hit on track linked list */
       long      hit_fts_p;  /* Id of first hca hit on track linked list */
       long      id;         /* primary key */
       long      is_shower;  /* 1 if shower track, 0 if not */
       long      itrmd_vertex_p; /* First intermediate vertex */
       long      n_ctb_hit;  /* Nhits in ctb */
       long      n_eem_hit;  /* Nhits in eem (endcap em cal) */
       long      n_emc_hit;  /* Nhits in emc */
       long      n_esm_hit;  /* Nhits in esm (endcap shower max) */
       long      n_ftp_hit;  /* Nhits in forward tpc */
       long      n_gem_hit;  /* Nhits in gem barrel */
       long      n_hpd_hit;  /* Nhits in hpd */
       long      n_ist_hit;  /* Nhits in ist */
       long      n_igt_hit;  /* Nhits in igt */
       long      n_fst_hit;  /* Nhits in fst */
       long      n_fgt_hit;  /* Nhits in fgt */
       long      n_fpd_hit;  /* Nhits in fpd */
       long      n_fsc_hit;  /* Nhits in fsc */
       long      n_mtd_hit;  /* Nhits in mtd */
       long      n_mwc_hit;  /* Nhits in mwc */
       long      n_pgc_hit;  /* Nhits in pgc  ???  */
       long      n_pmd_hit;  /* Nhits in pmd (PMD) */
       long      n_smd_hit;  /* number of hits in shower max */
       long      n_ssd_hit;  /* Nhits in ssd */
       long      n_svt_hit;  /* Nhits in svt */
       long      n_pix_hit;  /* Nhits in pix */
       long      n_tof_hit;  /* Nhits in tof */
       long      n_tpc_hit;  /* Nhits in tpc */
       long      n_vpd_hit;  /* Nhits in vpd */
       long      n_etr_hit;  /* Nhits on etr */
       long      n_hca_hit;  /* Nhits on hca */
       long      n_fts_hit;  /* Nhits on hca */
       long      next_parent_p; /* Id of next parent track */
       long      next_vtx_trk_p; /* Next daughter track of start vertex */
       long      start_vertex_p; /* Id of start vertex of track */
       long      stop_vertex_p; /* Id of stop vertex of this track */
       float     charge;     /* Charge */
       float     e;          /* Energy */
       float     eta;        /* Pseudorapidity */
       float     p[3];       /* Momentum */
       float     pt;         /* Transverse momentum */
       float     ptot;       /* Total momentum */
       float     rapidity;   /* Rapidity */
   } ;
