struct g2t_gepart {          /* G2t_gepart */ 
       char      napart[32]; /* Name of particle */
       long      eg_pid;     /* event generator particle id */
       long      mode_p;     /* Id of first decay mode */
       long      n_modes;    /* number of decay modes */
       long      pdg_pid;    /* PDG particle id */
       long      pid;        /* GEANT particle id */
       long      reserved;   /* for future use */
       float     amass;      /* Mass (GeV/c^2) */
       float     charge;     /* Charge in e units */
       float     tlife;      /* Lifetime in sec */
};
