   struct g2t_svt_hit {          /* G2t_svt_hit */ 
       long      id;         /* Primary key */
       long      next_tr_hit_p;/* Pointer to next hit of same track */
       long      track_p;    /* Pointer to parent track */
       long      volume_id;  /* STAR volume id */
       float     de;         /* Energy loss */
       float     ds;         /* step size in volume */
       float     p[3];       /* Local momentum */
       float     tof;        /* Time of flight */
       float     x[3];       /* Hit position */
   };

