    struct g2t_event {          /* G2t_event */ 
       long      eg_label;   /* Event label from event generator */
       long      event_type; /* specifies trigger, pileup, cosmic, laser */
       long      ge_rndm[2]; /* geant random seeds at start of event */
       long      merge_info[10];/* as yet unspecified */
       long      n_event;    /* Event number */
       long      n_part_neut_east;/* number of participant neutrons */
       long      n_part_neut_west;/* number of participant neutrons */
       long      n_part_prot_east;/* number of participant protons */
       long      n_part_prot_west;/* number of participant protons */
       long      n_run;      /* Run number */
       long      n_track_eg_fs;/* Number of final state event gen. tracks */
       long      n_track_prim;/* Number of primary tracks (w/o parent) */
       long      polarization[10];/* polarization info, as yet unspecified */
       long      prim_vertex_p;/* Id of first primary vertex in event */
       float     b_impact;   /* Impact parameter */
       float     phi_impact; /* Azimuth of reaction plane */
       float     time_offset;/* time offset in seconds wrt trigger event */
   } ;
