   struct g2t_ftp_hit {          /* G2t_ftp_hit */ 
       long      id;         /* Primary key */
       long      next_tr_hit_p;/* Pointer to next hit on same track */
       long      track_type; /* hit from primary(1), secondary(2), shower(3) */
       long      track_p;    /* Pointer to parent track */
       long      volume_id;  /* STAR volume id */
       float     de;         /* Energy loss */
       float     p[3];       /* Local momentum at hit */
       float     tof;        /* Time of flight */
       float     x[3];       /* Position of hit */
   } ;

