 struct g2t_vertex {          /* G2t_vertex */ 
       char      ge_volume[4];/* GEANT volume name */
       long      daughter_p; /* Id of first daughter in linked list */
       long      eg_label;   /* generator label (or 0 if GEANT vertex) */
       long      eg_proc;    /* generator production mechanism (if any) */
       long      event_p;    /* pointer to event */
       long      ge_medium;  /* GEANT Medium */
       long      ge_proc;    /* >0 GEANT, =0 event generator */
       long      id;         /* primary key */
       long      is_itrmd;   /* flags intermediate vertex */
       long      n_daughter; /* Number of daughter tracks */
       long      n_parent;   /* number of parent tracks */
       long      next_itrmd_p;/* Id of next intermedate vertex */
       long      next_prim_v_p;/* Id of next primary vertex */
       long      parent_p;   /* Id of first parent track */
       float     eg_tof;     /* generator vertex production time */
       float     eg_x[3];    /* generator vertex coordinate (Cartesian) */
       float     ge_tof;     /* GEANT vertex production time */
       float     ge_x[3];    /* GEANT vertex coordinate (Cartesian) */
};
