    struct g2t_pythia {            /* G2t_pythia */ 
       long      subprocess_id;    /* Pythia subprocess Id */
       float     mand_s;           /* Mandelstam s of the hard subprocess */
       float     mand_t;           /* Mandelstam t of the hard subprocess */
       float     mand_u;           /* Mandelstam u of the hard subprocess */
       float     hard_p;           /* pT of the hard  subprocess in partonic CM frame */
       float     cos_th;           /* COS theta of hard subprocess in partonic  CM frame */
       float     bjor_1;           /* Bjorken x of 1st parton in after initial radiation */
       float     bjor_2;           /* Bjorken x of 2nd particle in after initial radiation */
   } ;
