 struct g2t_pmd_hit {          /* G2t_pmd_hit */ 
       long      id;         /* primary key */
       long      track_p;    /* Id of parent track */
       long      volume_id;  /* STAR volume identification */
       float     de;         /* energy deposition at hit */
       float     p[3];       /* local momentum */
       float     x[3];       /* coordinate (Cartesian) */
};
