struct g2t_hca_hit {         /* G2t_hca_hit */ 
       long      id;         /* Primary Key */
       long      track_p;    /* Pointer to parent track */
       long      volume_id;  /* STAR volume id */
       float     de;         /* Energy loss */
       float     deA;        /* Energy loss for column-2 */
       float     deB;        /* Energy loss for column-1 */
       float     deC;        /* Energy loss for column   */
       float     deD;        /* Energy loss for column+1 */
       float     x; /* x-position of hit (global) */
       float     y; /* y-position of hit (global) */
       float     z; /* z-position of hit (global) */
   };
