struct g2t_rch_hit {          /* g2t_rich_hit */ 
    long      id;         /* primary key */
    long      track_p;    /* Id of parent track */
    long      volume_id;  /* Identify whether left or right RICH plane */
    float     de;         /* energy deposition at hit */
    float     ds;         /* energy deposition over ds */
    float     p[3];       /* local momentum */
    float     tof;        /* time of flight */
    float     x[3];       /* coordinate (Cartesian) */
};
