/*
  $Id: g2t_fts_hit.idl,v 1.1 2015/10/12 20:46:58 jwebb Exp $
  $Log: g2t_fts_hit.idl,v $
  Revision 1.1  2015/10/12 20:46:58  jwebb
  Hit definition and starsim to root interface for FTS.


*/

struct g2t_fts_hit {        /* G2t_fts_hit */ 
       long      id;           /* Primary key */
       long      next_tr_hit_p;/* Pointer to next hit of same track */
       long      track_p;      /* Pointer to parent track */
       long      volume_id;    /* STAR volume id */
       float     de;           /* Energy loss */
       float     ds;           /* step size in volume */
       float     p[3];         /* track momentum */
       float     tof;          /* Time of flight */
       float     x[3];         /* Hit position */
   };

