struct g2t_mwc_hit {          /* G2t_mwc_hit */ 
       long      id;         /* primary key */
       long      next_tr_hit_p;/* Id of next hit on same track */
       long      track_p;    /* Id of parent track */
       long      volume_id;  /* STAR volume identification */
       float     de;         /* energy deposition within sens vol */
       float     ds;     /* path length within sensitive volume */
       float     p[3];       /* local momentum at center */
       float s_track;
       float     tof;        /* time of flight wrt primary interaction */
       float     x[3];       /* global coordinate at center of MWC */
};
