/* $Id: g2t_pythia.idl,v 1.2 2007/05/23 13:49:25 potekhin Exp $
   $Log: g2t_pythia.idl,v $
   Revision 1.2  2007/05/23 13:49:25  potekhin
   Need to add three more Pythia variables
   as per the Spin PWG request

*/
    struct g2t_pythia {            /* G2t_pythia */ 
       long      subprocess_id;    /* Pythia subprocess Id */
       float     mand_s;           /* Mandelstam s of the hard subprocess */
       float     mand_t;           /* Mandelstam t of the hard subprocess */
       float     mand_u;           /* Mandelstam u of the hard subprocess */
       float     hard_p;           /* pT of the hard  subprocess in partonic CM frame */
       float     cos_th;           /* COS theta of hard subprocess in partonic  CM frame */
       float     bjor_1;           /* Bjorken x of 1st parton in after initial radiation */
       float     bjor_2;           /* Bjorken x of 2nd particle in after initial radiation */
       long      mstu72;           /* Pythia variable MSTU72 */
       long      mstu73;           /* Pythia variable MSTU73 */
       long      mstp111;          /* Pythia variable MSTP111 */
   } ;
