 struct g2t_hits {              /* G2t general hit structure     */ 
       long      id;            /* primary key                   */
       long      next_tr_hit_p; /* Id of next hit on same track  */
       long      track_p;       /* Id of parent track            */
       long      volume_id;     /* STAR volume identification    */
       float     de;            /* energy deposition at hit      */
       float     ds;            /* path length within sensitive volume */
       float     x[3];          /* global coordinate (Cartesian) */
       float     p[3];          /* local track momentum          */
       float     e;             /* local track energy            */
       float     tof;           /* time of flight wrt primary interaction */
       float     s_track;       /* path length from track origin to hit */
   };
