/* $Id: g2t_igt_hit.idl,v 1.2 2006/06/26 17:43:21 potekhin Exp $
   $Log: g2t_igt_hit.idl,v $
   Revision 1.2  2006/06/26 17:43:21  potekhin
   added CVS tags

*/

struct g2t_igt_hit {        /* G2t_igt_hit */ 
       long      id;           /* Primary key */
       long      next_tr_hit_p;/* Pointer to next hit of same track */
       long      track_p;      /* Pointer to parent track */
       long      volume_id;    /* STAR volume id */
       float     de;           /* Energy loss */
       float     ds;           /* step size in volume */
       float     p[3];         /* track momentum */
       float     tof;          /* Time of flight */
       float     x[3];         /* Hit position */
   };

