 struct g2t_tpc_hit {          /* G2t_tpc_hit */ 
       long      id;         /* primary key */
       long      next_tr_hit_p;/* Id of next hit on same track */
       long      track_p;    /* Id of parent track */
       long      volume_id;  /* STAR volume identification */
       float     de;         /* energy deposition at hit */
       float     ds;         /* path length within padrow */
       float     p[3];       /* local momentum */
       float     tof;        /* time of flight */
       float     x[3];       /* coordinate (Cartesian) */
       float     lgam;       /* ALOG10(GEKin/AMass) */
       float     length;     /* track length up to this hit */
       float     adc;        /* signal in ADC  after digitization */
       float     pad;        /* hit pad position used in digitization */
       float     timebucket; /* hit time position -"- */
       long      np;         /* no. of primary electrons */
};
