struct g2t_esm_hit {         /* G2t_esm_hit, created 970502, ge */
        long id;             /* Primary Key */
        long track_p;        /* Pointer to parent track */
        long volume_id;      /* STAR volume id */
        float de;            /* Energy loss */
        float p[3];          /* Local momentum at hit */
        float x[3];          /* Position of hit */
};
