/* Generated particle table
   $Id: particle.idl,v 1.1 1998/04/10 18:07:10 nevski Exp $ 
   $Log: particle.idl,v $
   Revision 1.1  1998/04/10 18:07:10  nevski
   HEPEVT particle table

   Revision 1.1  1998/02/10 15:12:41  fisyak
   Particle table
 
*/
struct particle {
  long  isthep;      /* status code of the entry */
  long  idhep;       /* particle identity, accordingly to the PDG standard */
  long  jmohep[2];   /* pointer(s) to position where the mother(s) stored */
  long  jdahep[2];   /* pointers to position of the first/last daughter */
  float phep[5];     /* p4 and mass (GeV) */
  float vhep[4];     /* production vertex (mm) and time (mm/c) */ 
};