/* ssf_zero_supp.idl
 * 
 * Zero Suppression
 * 
 */
#include "PAM.idl"
#include "ssf_zero_par.idl"
#include "ssf_adc.idl"
#include "ssf_seq.idl"

interface ssf_zero_supp : amiModule {
   STAFCV_T call(in  ssf_zero_par zero_par,
                 in  ssf_adc      adc8,
                 in  ssf_seq      seq,
                 out ssf_adc      adc);
};

