/* ssf_8to10_init.idl
 * 
 * Initialization of inverse of the 
 * Conversion/Compression Routine 
 * for 8 bits ADC to 10 bit ADC values
 * 
 */
#include "PAM.idl"
#include "ssf_map.idl"

interface ssf_8to10_init : amiModule  {
   STAFCV_T call(in  ssf_map map10to8,
                 out ssf_map map8to10);
};
