/* ssf_mv_to_adc.idl
 * 
 * A-D Conversion
 * 
 */
#include "PAM.idl"
#include "ssf_mv.idl"
#include "ssf_adc.idl"

interface ssf_mv_to_adc : amiModule {
   STAFCV_T call(in ssf_mv mv, in ssf_adc adc10);
};
