/* ssf_10to8.idl
 * 
 * Conversion/Compression Routine for 10 bits ADC to 8 bit ADC values
 * 
 */
#include "PAM.idl"
#include "ssf_map.idl"
#include "ssf_adc.idl"

interface ssf_10to8 : amiModule {
   STAFCV_T call(in ssf_map map, in ssf_adc adc10, out ssf_adc adc8);
};
