/* ssf_8to10.idl
 * 
 * Conversion/Expension Routine for 8 bits ADC to 10 bit ADC values
 * 
 */
#include "PAM.idl"
#include "ssf_map.idl"
#include "ssf_adc.idl"

interface ssf_8to10 : amiModule {
   STAFCV_T call(in ssf_map map, in ssf_adc adc8, out ssf_adc adc10);
};
