/*	gl3Tpc.idl
*
*	Module: gl3Tpc
*	description: Implements Global Level 3 functionality
*/
#include "PAM.idl"
#include "gl3Para.idl"
#include "sl3Buffer.idl"
#include "tpt_track.idl"

interface gl3 : amiModule{
	STAFCV_T call
		( inout gl3Para     para
		, out   sl3Buffer   l3track
		, out   tpt_track   track 
		);
};
/* Last mod. for gl3: $Data$ */
