/*	sl3Tpc.idl
*
*	Module: sl3_tpc
*	description: Implements Sector Level 3 functionality
*/
#include "PAM.idl"
#include "sl3TpcPara.idl"
#include "sl3Buffer.idl"

interface sl3Tpc : amiModule{
	STAFCV_T call
		( inout sl3TpcPara para
                , inout sl3Buffer  slhit
		, out   sl3Buffer  l3Track
		);
};
/* Last mod. for sl3Tpc: $Data$ */
