/**
 * <hr>
 * STAR VPD module. <br>
 * Outputs simulated VPD data into STAF tables. <br>
 * Uses control parameter switches to output simulated physics quantities
 * into <a href=vps_sim.html>vps_sim</a> table and simulated raw detector
 * ADC and TDC response into <a href=vps_raw.html>vps_raw</a> table.
 * See <a href=vps_par.html>vps_par</a> for desription of control switches.
 * 
 * @author         Zoran Milosevich
 */

/* vps.idl */
#include "PAM.idl"
#include "g2t_vpd_hit.idl"
#include "vps_par.idl"
#include "vps_sim.idl"
#include "vps_raw.idl"

interface vps : amiModule {
        STAFCV_T call
                ( inout g2t_vpd_hit      gvhit
                , inout vps_par          vpar
                , inout vps_sim          vsim
                , inout vps_raw          vraw
        );
};
/*  Last mod. for vps: $Date: 1997/12/31 14:33:30 $ */

