/**
 * <hr>
 * VPV vertex locator output table. <br>
 *
 * @parm id - primary key
 * @parm neg_time - vpd minimum time eta<0
 * @parm pos_time - vpd minimum time eta>0
 * @parm vert - vpd determined vertex
 * @author         Zoran Milosevich
 */

/*   vpv_vert.idl
*   Table: vps_vert
*        description: VPD calculated vertex position     
*             more..:                                         
*/
   struct vpv_vert {          
       long      id;            /* primary key */
       long      neg_time;      /* vpd minimum time eta<0 */
       long      pos_time;      /* vpd minimum time eta>0 */
       float     vert;          /* vpd determined vertex */

   };

/*  Last mod. for vpv_vert:  Tue Oct 15 19:41:37 1996 */