#!/usr/bin/env perl
# $Id: Conscript,v 1.21 2016/04/27 11:29:09 jeromel Exp $
# $Log: Conscript,v $
Import qw ( env INCLUDE LIB BIN BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
my @GDIRS = qw( block cdf cgpack erdecks erpremc fiface fluka gbase gcons gdraw 
		geocad ggeom gheisha ghits ghrout ghutils giface 
		giopa gkine gphys gscan gstrag gtrak guser matx55 gxint 
		miface miguti neutron peanut );
$build =~ s/\\/\//g;# print "OBJ = $OBJ build = $build MAIN = $MAIN\n";
(my $ObjDir = DirPath '.') =~ s/\\/\//g;# print "ObjDir = $ObjDir\n";
(my $Dir = $ObjDir) =~ s/$build\///g; #print "Dir = $Dir\n";
$ObjDir = "#" . $ObjDir; #print "ObjDir = $ObjDir\n";
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $FC     = $env->{FC};
my $FCPATH = $env->{FCPATH};
my $FFLAGS = $env->{FFLAGS};# print "FFLAGS = $FFLAGS\n";
my $FPPFLAGS = $env->{FPPFLAGS};
my $CPPFLAGS = $env->{CPPFLAGS};
my $CPPPATH  = $env->{CPPPATH};
my $DEBUG   = $env->{DEBUG};# print "DEBUG = $DEBUG\n";
my $FDEBUG  = $env->{FDEBUG};
my $NOOPTIMIZED = $FDEBUG; $NOOPTIMIZED =~ s/-O2//g; $NOOPTIMIZED =~ s/-O//g;# print "FDEBUG = $FDEBUG, NOOPTIMIZED = $NOOPTIMIZED\n";
my $pkg  = geant321; 
my $PKG = $pkg;     print "Run cons in $Dir for $PKG\n";
my $SO_PKG = $PKG . "." . $env->{SUFSOLIB};# print "SO_PKG = $SO_PKG\n";
my $LIBPKG = "lib" . $PKG . "." . $env->{SUFLIB};
$FCPATH  = "#asps/Simulation/starsim/include" . $main::PATH_SEPARATOR . $Dir . "/include";
$CPPPATH  = $FCPATH;
$FPPFLAGS = "-DCERNLIB_TYPE -DCERNLIB_UNIX -DCERNLIB_BSLASH -DCERNLIB_DZDOC ".
  "-DCERNLIB_SHL -DCERNLIB_NONEWL -DCERNLIB_HIGZ -DCERNLIB_CG  -DCERNLIB_HADRON -DCERNLIB_COMIS";# -DCERNLIB_GCALOR";
$CPPFLAGS = $FPPFLAGS;
$FPPFLAGS .= " -DCERNLIB_MONITOR"; 
if ($FC =~ /pgf77/) { 
  $FC       = $env->{G77}; print "set FC => $FC ==============================\n" if $param::debug;
  $FFLAGS   = $env->{G77FLAGS}; 
  $FEXTEND  = $env->{G77EXTEND};
  $FPPFLAGS .= " -DCERNLIB_LINUX -DCERNLIB_LNX -DCERNLIB_QMGLIBC -DCERNLIB_BLDLIB";# -DCERNLIB_MYSQL";
  $FPPFLAGS .= " -DCPP_DATE=0 -DCPP_TIME=0 -DCPP_VERS=\"''\" -DCPP_TITLE_CH=\"''\"";
}
$CPPFLAGS   = $FPPFLAGS;
if ($STAR_SYS =~ /^rh80/) {
  $CPPFLAGS  .= " -Df2cFortran -DCERNLIB_QMGLIBC";
}
$env2 = $env->clone('FC'           => $FC,
		    'FPPFLAGS'     => $FPPFLAGS,
		    'FFLAGS'       => $FFLAGS,
		    'FCPATH'       => $FCPATH,
		    'FEXTEND'      => "",
		    'CPPFLAGS'     => $CPPFLAGS,
		    'CPPPATH'      => $CPPPATH,
		    'LIBPATH'      => $LIBPATH,
		    'LIBS'         => $LIBS,
		    'ObjDir'       => $obj_dir,
		    'Libraries'    => $Libraries);
$envNoDeb = $env2->clone('FDEBUG'    => $NOOPTIMIZED);
my @sources = ();
foreach my $d (@GDIRS){
  my $dir = $Dir . "/" . $d;    #  print "dir = $dir\n";
  my @src = find_sources($dir);
  foreach my $s (@src) { 
    next if $s =~ /\.cdf$/;
    next if $s =~ /gxint/;
    my $ss = $d . "/" . $s; # print "ss = $s  =>  $ss\n";
    next if $d eq 'gstrag' and $FPPFLAGS !~ /CERNLIB_ASHO/ and 
      ($s =~ /gasho\.F$/ || 
       $s =~ /goscmg\.F$/ || 
       $s =~ /gdifmg\.F$/ || 
       $s =~ /giasho\.F$/);
    if ($DEBUG ne $NOOPTIMIZED and 
	($d eq 'gstrag' or 
	 $d eq 'gphys' and $s =~ /gfshdc\.F$|gphot\.F$|gphoti\.F$|gphsg1\.F$|gphsg2\.F$|gphsgp\.F$|gphxsi\.F$|gphysi\.F/)) {
      my @objfiles = Objects $envNoDeb ($ss);
      push @sources, $objfiles[0];
    } else {
      push @sources, $ss; 
    }
  }
}
if ($#sources > -1) {
  if ($STAR_SYS !~ /alpha/) {Library      $env2 $LIBPKG, @sources;}
  else {
    my @objfiles = Objects $env2   @sources;
    Command $env2 ("input_object.list"), @objfiles, qq([perl] open(F, ">%>"); print F "%<"; close(F); 1);
    Command $env2 ($LIBPKG), ("input_object.list"), qq(%ARCOM);
  }
  Install $env2 $LIB, $LIBPKG;
}  
