// Author: Bertrand Bellenot   22/08/02

/*************************************************************************
 * Copyright (C) 1995-2002, Bertrand Bellenot.                           *
 * All rights reserved.                                                  *
 *                                                                       *
 * For the licensing terms see the LICENSE file.                         *
 *************************************************************************/

#ifndef ROOTSHOWERHELPTEXT_H
#include "RSHelpText.h"
#endif 

const char physics_txt[] =
"<tt>"
"<h2><center>Some physics recalls...<center></h2>"
"<h3>Radiation length:</h3>"
"High-energy electrons predominantly lose energy in matter by"
"bremsstrahlung, and high-energy photons by e + e - pair production."
"The characteristic amount of matter traversed for these related "
"interactions is called the radiation length X 0, usually measured "
"in g cm - 2 . It is the mean distance over which a high-energy "
"electron loses all but 1/e of its energy by bremsstrahlung, and "
"the e-folding distance for pair production by a high-energy photon "
"is 97 X0. It is also the appropriate scale length for describing "
"high-energy electromagnetic cascades."
"<p>"
"<h3>Electromagnetic cascades:</h3>"
"<p>When a high-energy electron or photon is incident on a thick absorber,"
"it initiates an electromagnetic cascade as pair production and "
"bremsstrahlung generate more electrons and photons with lower energy."
"The longitudinal development is governed by the high-energy part of "
"the cascade, and therefore scales as the radiation length in the "
"material. Electron energies eventually fall below the critical energy,"
"and then dissipate their energy by ionization and excitation rather "
"than by the generation of more shower particles."
"<P>"
"<h3>Energy loss by electrons:</h3>"
"<p>At low energies electrons and positrons primarily lose energy by "
"ionization, although other processes (Moller scattering, Bhabha "
"scattering, e + annihilation) contribute. "
"<p>While ionization loss rates rise logarithmically with energy,"
"bremsstrahlung losses rise nearly linearly (fractional loss is "
"nearly independent of energy), and dominates above a few tens of "
"MeV in most materials Ionization loss by electrons and positrons "
"differs from loss by heavy particles because of the kinematics, spin,"
"and the identity of the incident electron with the electrons which "
"it ionizes."
"<P>"
"<h3>Muon energy loss at high energy:</h3>"
"<p>At sufficiently high energies, radiative processes become more "
"important than ionization for all charged particles. For muons "
"and pions in materials such as iron, this 'critical energy' occurs "
"at several hundred GeV. Radiative effects dominate the energy loss "
"of energetic muons found in cosmic rays or produced at the newest "
"accelerators."
"<p>These processes are characterized by small cross sections, hard "
"spectra, large energy fluctuations, and the associated generation "
"of electromagnetic and (in the case of photonuclear interactions) "
"hadronic showers. As a consequence, at these energies the treatment "
"of energy loss as a uniform and continuous process is for many "
"purposes inadequate.";

const char simulation_txt[] =
"<center><h3>How to use this software...</h3></center>"
"<p>Choose Parameters into the menu Event to access to the parameters "
"setting dialog."
"<p>Into this dialog, you have access to all settable parameters of "
"the simulation :"
"    Particle :<br>"
"        You can choose the primary particle with its decay:<br>"

"<tt>"
"           Photon     <br>"
"           Electron   <br>"
"           Positron   <br>"
"           Muon-      <br>"
"           Muon+      <br>"
"           Tau-       <br>"
"           Tau+       <br>"
"           Pion0      <br>"
"           Pion+      <br>"
"           Pion-      <br>"
"           Eta        <br>"
"           Kaon+      <br>"
"           Kaon-      <br>"
"           Kaon Long  <br>"
"           Kaon Short <br>"
"           Rho0       <br>"
"           Rho+       <br>"
"           Rho-       <br>"
"           Omega      <br>"
"           Phi        <br>"
"           J/Psi      <br>"
"           W+         <br>"
"           W-         <br>"
"           Z0         <br>"
"</tt>"
"    Primary particle parameters :<br>"
"<tt>"
"        Primary particle's Energy (in GeV)<br>"
"        Magnetic field (in kGauss)<br>"
"</tt>"
"<p>Then you can start a simulation by pressing the button 'Start Simulation' "
"The cascade will be drawn into the first main tab ('Event Display'),"
"and the particles list will appear into the tree view at left. Into this "
"tree view, you can follow the cascade tree and on the particle branch, the "
"tooltip will indicate the particle energy (E0)."
"<P>"
"The track color corresponds to the particle energy, from red to blue."
"Note that the photons and neutrinos tracks are not shown."
"The status bar on the bottom of the main frame indicates the simulation "
"status :<br>"
"<tt>"
"     Waiting to start simulation <br>"
"     Done - Total particles : xxx - Waiting for next simulation <br>"
"</tt>"
"<P>You can access informations on current event by selecting Infos into the "
"Event menu."
"<p>Select 3D View into this same menu to have a 3D view of the event into "
"a new OpenGL window. It is also possible to do this with the context menu "
"(by clicking with the right button)."
"<p>It is possible to isolate a particle track by selecting the particle into "
"tree view at the left, then by clicking the 'Show Selection' button. This "
"will show the selected particle track into the tab 'Selected Track'.";

const char gRSHelpMsgBox[] = 
"<br>It appears that you have changed some parameters. These include :<br>"
"   - Primary Particle<br>"
"   - Initial Energy<br>"
"   - Magnetic Field<br>"
"   - Target Material<br>"
"   - Target Dimension<br>"
" \"Yes\" button - save resources into file ${HOME}/.rootshowerrc, and quit<br>"
" \"No\"  button - quit without saving<br>";

const char gSettingsHelp[] =
"<br>                  Help on Parameters Setting<br><br>"
"Into this dialog, you have access to every settable parameters<br>"
"of the simulation :<br>"
"    First tab : Matter<br>"
"        Here you can choose the target's material :<br>"
"        Iron, Aluminium, Argon, Neon, Nitrogen, Helium<br>"
"    Second tab : Particle<br>"
"        Here you can choose the primary particle with its decay:<br>"
"           Photon     <br>"
"           Electron   <br>"
"           Positron   <br>"
"           Muon-      <br>"
"           Muon+      <br>"
"           Tau-       <br>"
"           Tau+       <br>"
"           Pion0      <br>"
"           Pion+      <br>"
"           Pion-      <br>"
"           Eta        <br>"
"           Kaon+      <br>"
"           Kaon-      <br>"
"           Kaon Long  <br>"
"           Kaon Short <br>"
"           Rho0       <br>"
"           Rho+       <br>"
"           Rho-       <br>"
"           Omega      <br>"
"           Phi        <br>"
"           J/Psi      <br>"
"           W+         <br>"
"           W-         <br>"
"           Z0         <br>"
"    Third tab : Size<br>"
"        Here you can choose the target's dimensions (X,Y,Z)<br>"
"    Fourth tab : E0/B<br>"
"        In this tab, you can set the magnetic field (in kGauss)<br>"
"        and the primary particle's Energy (in MeV)";

const char gHelpLicense[] =
"<tt>"
"<h3>RootShower Software Terms and Conditions</h3>"
"<p>"
"The author hereby grant permission to use, copy, and distribute this "
"software and its documentation for any purpose, provided that existing "
"copyright notices are retained in all copies and that this notice is "
"included verbatim in any distributions. Additionally, the author grant "
"permission to modify this software and its documentation for any purpose, "
"provided that such modifications are not distributed without the explicit "
"consent of the author and that existing copyright notices are retained in "
"all copies. Users of the software are asked to feed back problems, benefits, "
"and/or suggestions about the software to the author (bellbert@scopus.ch).  "
"Support for this software - fixing of bugs, incorporation of new features -  "
"is done on a best effort basis. All bug fixes and enhancements will be made " 
"available under the same terms and conditions as the original software, "
"<p>"
"IN NO EVENT SHALL THE AUTHOR OR DISTRIBUTORS BE LIABLE TO ANY PARTY FOR "
"DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT "
"OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES THEREOF, "
"EVEN IF THE AUTHOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. "
"<p>"
"THE AUTHOR AND DISTRIBUTORS SPECIFICALLY DISCLAIM ANY WARRANTIES, "
"INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, "
"FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THIS SOFTWARE IS "
"PROVIDED ON AN \"AS IS\" BASIS, AND THE AUTHOR AND DISTRIBUTORS HAVE NO "
"OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR "
"MODIFICATIONS.";
