/* scf_am.idl
*   Module: scf_am
*        description: scf Ssd Cluster Finder module
*/

#include "PAM.idl"
#include "sdm_geom_par.idl"
#include "spa_strip.idl"
#include "sls_ctrl.idl"
#include "sdm_calib_db.idl"
#include "scf_ctrl.idl"
#include "scf_cluster.idl"

interface scf_am : amiModule {
        STAFCV_T call
                ( in    sdm_geom_par      geom_par
		, in    spa_strip         spa_strip
		, in    sls_ctrl          sls_ctrl
		, in    sdm_calib_db      noise
		, in    scf_ctrl          scf_ctrl
		, inout scf_cluster    	  cluster
        );
};
/*  Last mod. for scf_am: $Date: 2000/07/21 15:04:46 $ */


