#!/bin/bash

export myself=${0}
echo myself=$myself
export mypwd=${1}
echo mypwd=$mypwd
export mypwdanalysis=${2}
echo mypwdanalysis=$mypwdanalysis
export mydebug=${3}
echo mydebug=$mydebug
export mytag=${4}
echo mytag=$mytag
export myscript=${5}
echo myscript=$myscript
export myscratch=${6}
echo myscratch=$myscratch
export mynevents=${7}
echo mynevents=$mynevents
export myjobid=${8}
echo myjobid=$myjobid
export mygeometrytag=${9}
echo mygeometrytag=$mygeometrytag
export myconfig=${10}
echo myconfig=$myconfig
export mypathout=${11}
echo mypathout=$mypathout
export mykeepfzd=${12}
echo mykeepfzd=$mykeepfzd

cd "$myscratch"

export myscratchanalysis=${myscratch}${mypwdanalysis#$mypwd}                                                                                                                 

"$mypwdanalysis/StPi0Common/macros/copy" simulation "$mypwd" "$myscratch" "$mypwdanalysis" "$myscratchanalysis"
"$mypwdanalysis/StPi0Common/macros/configure" simulation "$myscratchanalysis" "$myscratch"

source "$myscratchanalysis/StPi0Common/macros/commands"

ls -al

env

export SCRIPTCMD=${myscript}
export SCRIPTCMD=${SCRIPTCMD//*\/}
export SCRIPTCMD=${SCRIPTCMD//.kumac}
run_command $mydebug starsim -m 0 -b "${myscratchanalysis}/StPi0Simulation/macros/${myscript}" \\'#'${SCRIPTCMD} nevent=$mynevents file="${myscratch}/${mytag}_${myjobid}.fzd" nparticles=1 geometrytag=$mygeometrytag

ls -al

run_command $mydebug root4star -b -q bfc.C`bash_escape_all '(1,'$mynevents',"'\`cpp_escape_quo $myconfig\`'","'${myscratch}'/'${mytag}'_'${myjobid}'.fzd")'`

mkdir -p "$mypathout"

copy_file_qa "${myscratch}/${mytag}_${myjobid}.event.root" "$mypathout/${mytag}_${myjobid}.event.root"
copy_file_qa "${myscratch}/${mytag}_${myjobid}.geant.root" "$mypathout/${mytag}_${myjobid}.geant.root"
if [[ "$mykeepfzd" == "yes" ]] ; then copy_file_qa "${myscratch}/${mytag}_${myjobid}.fzd" "$mypathout/${mytag}_${myjobid}.fzd" ; fi

ls -al
