#ifndef _RTSDBCONSTANTS_H_
#define _RTSDBCONSTANTS_H_

#define DB_MAX_STR_LEN 64
#define DB_MAX_NODES 200
#define DB_MAX_DICT_ENTRIES 1500
#define DB_TRIGGERS_MAX 64
//#define DB_TW_MAX (1<<16)
//#define DB_PW_MAX (1<<12)
#define DB_PW_COND_MAX (DB_TRIGGERS_MAX*4)
#define DB_MAX_REGISTERS 1500
#define DB_MAX_DETECTORS 20
#define DB_MAX_SUBDET 200
#define VARCHAR_LENGTH 2000

#endif
