# Sample Makefile.control - You should customize this file.
#
# Specify the ASPs and PAMs upon which this package depends.
ASPS := tnt ami dio dui tdm soc
PAMS := pam
#
# Specify special user libraries against which to link.
USER_LIBS := -ldsu -ldsl -lasu
#
# Choose flags controlling make.
DEBUG := TRUE
#SHARE := TRUE
MOTIF := TRUE
#
# Specify which CERN libraries against which to link, or take default.
CERNLIBS := pawlib graflib grafX11 packlib mathlib kernlib
#
