/* tcl_make_clusters.idl
* This is the clusterfinder module for the tpc
*/
#include "PAM.idl"
#include "tpg_pad_plane.idl"
#include "tss_tppad.idl"
#include "tss_tppixel.idl"
#include "tss_tpmcpix.idl"
#include "tcl_tpcluster.idl"
#include "tcl_tpseq.idl"

interface tcl_make_clusters : amiModule{
	STAFCV_T call (
		  in tpg_pad_plane  pad_plane
		, in tss_tppad	tppad
		, in tss_tppixel tppixel
		, in tss_tpmcpix tpmcpix
		, inout tcl_tpcluster tpcluster
		, inout tcl_tpseq tpseq
		);
};
/* last modified $Date: 1998/01/27 00:49:13 $ */

		
		
