/* tpeam.idl
* This is the hitfinder evaluator module for the tpc
*/
#include "PAM.idl"
#include "tcl_tphit.idl"
#include "g2t_track.idl"
#include "g2t_tpc_hit.idl"
#include "tss_tsspar.idl"
#include "tcl_tpcluster.idl"
#include "tcl_tpseq.idl"
#include "tss_tppixel.idl"
#include "tss_tpmcpix.idl"
#include "tpg_pad_plane.idl"
#include "tpg_detector.idl"
#include "tcl_tclpar.idl"
#include "tcl_tpc_index.idl"
#include "tcl_tpc_index_type.idl"

interface tpeam : amiModule{
	STAFCV_T call (
		  inout tcl_tphit tphit
		, in g2t_track g2t_track
		, in g2t_tpc_hit g2t_tpc_hit
		, in tss_tsspar tsspar
		, in tcl_tpcluster tpcluster
		, in tcl_tpseq tpseq
		, in tss_tppixel tppixel
		, in tss_tpmcpix tpmcpix
		, in tpg_pad_plane pad_plane
		, in tpg_detector detector
		, in tcl_tclpar tclpar
		, inout tcl_tpc_index tpc_index
		, inout tcl_tpc_index_type tpc_index_type
		);
};
/* last modified $Date: 1997/12/31 14:33:43 $ */

		
		
