/* tpham.idl
* This is the hitfinder module for the tpc
*/
#include "PAM.idl"
#include "tcl_tclpar.idl"
#include "tss_tsspar.idl"
#include "tpg_detector.idl"
#include "tpg_pad_plane.idl"
#include "tss_tppixel.idl"
#include "tss_tpmcpix.idl"
#include "tcl_tpseq.idl"
#include "tcl_tpcluster.idl"
#include "tcl_tphit.idl"
#include "tcl_tphit_aux.idl"

interface tpham : amiModule{
	STAFCV_T call (
		  in tcl_tclpar tclpar
		, in tss_tsspar tsspar
		, in tpg_detector detector
		, in tpg_pad_plane pad_plane
		, in tss_tppixel tppixel
		, in tss_tpmcpix tpmcpix
		, in tcl_tpseq	tpseq
		, inout tcl_tpcluster tpcluster
		, inout tcl_tphit tphit
		, inout tcl_tphit_aux tphit_aux
		);
};
/* last modified $Date: 1998/01/27 00:49:20 $ */

		
		
