*
* $Id: comcont.inc,v 1.1 1998/04/10 15:31:53 fisyak Exp $
*
* $Log: comcont.inc,v $
* Revision 1.1  1998/04/10 15:31:53  fisyak
* Move gstar into CVS
*
*
*
* comcont.inc
*
#if defined(CERNLIB_HADR)
*CMZ :          16/12/97  14.15.27  by  Pavel Nevski
*CMZ :  3.21/02 29/03/94  15.41.41  by  S.Giani
      DOUBLE PRECISION AOCMBC, CONTNT, SUMACN, CABINX, CABELX,
     &                 ANXNOR, ELXNOR, CONA13, SUMZMF
*-- Author :    A. Ferrari
#endif
