*
* $Id: comcont.inc,v 1.2 1998/04/16 16:58:42 fisyak Exp $
*
* $Log: comcont.inc,v $
* Revision 1.2  1998/04/16 16:58:42  fisyak
* 2nd pass with gstar
*
*
*
* comcont.inc
*
#if defined(CERNLIB_HADR)
*CMZ :          16/12/97  14.15.27  by  Pavel Nevski
*CMZ :  3.21/02 29/03/94  15.41.41  by  S.Giani
      DOUBLE PRECISION AOCMBC, CONTNT, SUMACN, CABINX, CABELX,
     &                 ANXNOR, ELXNOR, CONA13, SUMZMF
*-- Author :    A. Ferrari
#endif
