*
* $Id: fheavyt.inc,v 1.1 1998/04/10 15:31:54 fisyak Exp $
*
* $Log: fheavyt.inc,v $
* Revision 1.1  1998/04/10 15:31:54  fisyak
* Move gstar into CVS
*
*
*
* fheavyt.inc
*
#if defined(CERNLIB_HADR)
*CMZ :          16/12/97  14.01.37  by  Pavel Nevski
*CMZ :  3.21/02 29/03/94  15.41.41  by  S.Giani
*-- Author :    A. Ferrari
      DOUBLE PRECISION CXHEAV, CYHEAV, CZHEAV, TKHEAV, PHEAVY,
     &                 WHEAVY, AMHEAV
#endif
