*
* $Id: finuct.inc,v 1.2 1998/04/16 16:58:45 fisyak Exp $
*
* $Log: finuct.inc,v $
* Revision 1.2  1998/04/16 16:58:45  fisyak
* 2nd pass with gstar
*
*
*
* finuct.inc
*
#if defined(CERNLIB_HADR)
*CMZ :          16/12/97  14.01.37  by  Pavel Nevski
*CMZ :  3.21/02 29/03/94  15.41.41  by  S.Giani
*-- Author :    A. Ferrari
      DOUBLE PRECISION CXR, CYR, CZR, TKI, PLR, WEI, TV, TVCMS,
     &                 TVRECL, TVHEAV, TVBIND
#endif
