#!/usr/local/bin/perl
#use Env;
Import qw ( env INCLUDE LIB BIN  EXPORT BUILD OBJ);
(my $build = $BUILD) =~ s/\#//g;  #print "BUILD = $BUILD build = $build MAIN = $MAIN\n";
(my $Dir = DirPath '.') =~ s/$build\///g;
my $CPPPATH = "$Dir:$env->{CPPPATH}"; #print "CPPPATH = $CPPPATH\n";
$env2 = $env->clone(
		    'CPPPATH'      => $CPPPATH
		    );
my $PKG  = basename($Dir); print "Run cons in $Dir for $PKG\n";
my $SO_PKG = $PKG . ".so";
my @src  = find_sources($Dir);  #my $i=0; for my $s (@src) {print "i=",$i++," src = ",$s,"\n";}
LinkedModule $env2 $SO_PKG, @src;
Install $env2 $LIB, $SO_PKG;
