/**************************************************************************
*
* $Id: TofTag.idl,v 1.1 2001/10/10 15:18:21 geurts Exp $
*
***************************************************************************
*
* Description: The tof tag table. 
*
***************************************************************************
*
* $Log: TofTag.idl,v $
* Revision 1.1  2001/10/10 15:18:21  geurts
* TofTag introduced
*
*
**************************************************************************/

struct TofTag {
  long tofEventType; // differentiates Strobe Events from Physics Events
};
