      double precision DSTK,DCTK,DOM,DQ2,DW1J,DW2J,DTK,DPHK
     +                ,DSITKM,DSIMJ,DCVTKM
     +                ,DCVMJ,DDELMJ,DDETKM
      integer          NDXTKM,NDXMJ
      COMMON /GAMCOM/  DSTK,DCTK,DOM,DQ2,DW1J,DW2J,DTK,DPHK
     +                ,DSITKM(245,80),DSIMJ(80),DCVTKM(245,80)
     +                ,DCVMJ(80),DDELMJ(80),DDETKM(245,80)
     +                ,NDXTKM(80),NDXMJ
