//
// Parameters of staf interface to FTF graphics
//
struct gft_para {
   short     fillEvent    ;    // Fill event structures
   char      function[50] ;    // function to be executed
   char      pstr[50]     ;    // character parameter
   long      pint[10]     ;    // integer   parameters
   float     pflo[10]     ;    // float     parameters
};



