//   l3t_monitor  
//   Monitors tracking performance 
//
struct l3t_monitor  {
   short      sector       ;     // sector processed
   long       nPoints      ;     // # of space points in sector
   long       nTracks      ;     // # of reconstructed tracks 
   float      sTime        ;     // Time required for processing
};

