/*   rl0_ctrl.idl
*   Table: rl0_ctrl
*        description: Controls the level 0 emulation          
*/
   struct rl0_ctrl {               /* Rl0_ctrl_row_st */ 
       short       ctb_eta_pixels;  /* Number of pixels in eta for CTB */
       short       ctb_phi_pixels;  /* Number of pixels in phi for CTB*/ 
       short       mwc_eta_pixels;  /* Number of pixels in eta for MWC */
       short       mwc_phi_pixels;  /* Number of pixels in phi for MWC */

       short       nthres;         /* Multiplicity threshold */
       long        zdc_cut;        /* ZDC energy cut */
       float       fpga_gain[9];   /* Gain for FPGA trees */
   }; 

/*  Last mod. for rl0_ctrl: $Date: 1998/11/10 20:26:32 $*/

