/**
 * <hr>
 * autocorrelation analysis output table. <br>
 *
 * @parm id            - primary key
 * @parm autonull[100] - autocorrelation minus null hyp
 * @parm autocorr[100] - autocorrelation output
 * @parm c1[100]       - cos coefficient from null hyp
 * @parm s1[100]       - sin coefficient from null hyp
 * @parm power         - power value
 * @parm phase         - phase value
 * @author         Zoran Milosevich
 */

/*   rl1_pw_out.idl
*   Table: rl1_pw_out
*        description: autocorrelation analysis control parameters     
*             more..: 
*/
   struct rl1_pw_out {   
       long      id;                /* primary key */
       float     autonull[100];     /* autocorrelation minus null hyp. */
       float     autocorr[100];     /* autocorrelation output */
       float     c1[100];           /* cos coefficient from null hyp. */
       float     s1[100];           /* sin coefficient from null hyp. */
       float     power;             /* power value */
       float     phase;             /* phase value */
 
   };

/*  Last mod. for pw_out:   783377928 Fri Oct 28 16:58:48 1994 */

