/**
 * <hr>
 * ks-test control parameter table. <br>
 *
 * @parm id            - primary key
 * @parm ctb_eta       - Number of eta bins in CTB
 * @parm ctb_phi       - Number of phi bins in CTB
 * @parm mwc_eta       - Number of eta bins per endcap
 * @parm mwc_phi       - Number of phi bins per endcap
 * @parm n_bins        - Number of compressed 1-D bins
 * @parm on_off        - switch to turn module on
 * @parm time_loop     - number of analysis loops to perform 
 * @parm ref_data[100] - K-S test reference
 * @parm ref_data_flag - reference data flag
 * @parm threshold     - K-S test selectivity threshold
 * @author         Zoran Milosevich
 */

/*   rl1_ks_ctrl.idl
*   Table: rl1_ks_ctrl
*        description: ks-test control parameters     
*             more..:                                         
*/
   struct rl1_ks_ctrl {   
       long      id;                /* primary key */
       long      ctb_eta;           /* Number of eta bins in CTB */
       long      ctb_phi;           /* Number of phi bins in CTB */
       long      mwc_eta;           /* Number of eta bins per endcap */
       long      mwc_phi;           /* Number of phi bins per endcap */
       long      n_bins;            /* Number of compressed 1-D bins. */
       long      on_off;            /* switch to turn module on */
       long      time_loop;         /* number of analysis loops to perform */
       long      ref_data[100];     /* K-S test reference. */
       long      ref_data_flag;     /* reference data flag */
       float     threshold;         /* K-S test selectivity threshold. */
 
   };

/*  Last mod. for ks_ctrl:   759596937 Wed Jan 26 10:08:57 1994 */

