*
* $Id: fzhci.inc,v 1.1.1.1 2004/01/12 23:49:41 potekhin Exp $
*
* $Log: fzhci.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:41  potekhin
*
* Revision 1.1  2001/06/15 00:02:18  nevski
* merging differences between private cmz and this version
*
* Revision 1.1  2001/06/14 21:12:46  nevski
* parts of fzirec unavailable from cern includes
*
* Revision 1.1.1.1  1996/03/06 10:47:08  mclareni
* Zebra
*
*
*                Physical record header
*
* fzhci.inc
*
      COMMON /FZHCI/ MPHRI(5),JRECI,NTLRI,NFSTI,JMODI,NWRI
