*
* $Id: mtzca.inc,v 1.1.1.1 2004/01/12 23:49:41 potekhin Exp $
*
* $Log: mtzca.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:41  potekhin
*
* Revision 1.1  2001/03/25 17:50:33  nevski
* mzca splitted
*
*
#ifndef CERNLIB_ZEBRA_MTZCA_INC
#define CERNLIB_ZEBRA_MTZCA_INC
*
*     Process Master parameters types
*
* mtzca.inc
      INTEGER        NQSTOR,NQOFFT,NQOFFS,NQALLO, NQIAM
     +,              LQATAB,LQASTO,LQBTIS, LQWKTB,NQWKTB,LQWKFZ
     +,              MQKEYS,NQINIT,NQTSYS,NQM99,NQPERM
     +,              NQFATA,NQCASE,NQTRAC,KQSP
*

#endif
