#!/usr/bin/perl

## this snippet ensures only one copy running
## it locks itself...
#
# use Fcntl ':flock';
# use Carp;
# open my $self, '<', $0 or die "Couldn't open self: $!";
# flock $self, LOCK_EX | LOCK_NB or croak "This script is already running...";
#
## end snippet!

$LOGCMD = "rtsLog -d \"WARN\" -p 8004 -h \"172.16.0.1\" -c jevpHistoMother";
$LAUNCHCMD = "OnlTools/Jevp/launch JevpServerMain -production >& /dev/null &";

chdir "/home/evpops/cvs";
$jevp_pid = 0;

$num = `ps -ef | grep root4star | grep -v grep -c`;
chomp $num;

while($num > 0) {
    printf("$num root4star still running... I will kill it first...\n");
    system("$LOGCMD \"killing roo4star...\"");
    system("killall -9 root4star");

    sleep(2);
    $num = `ps -ef | grep root4star | grep -v grep -c`;
    chomp $num;

    if($num == 0) {
	printf("Successfully killed root4star...\n");
    }
}

printf("launching root4star...\n");
system("$LOGCMD \"started root4star...\"");
exec($LAUNCHCMD);


	

