#!/usr/bin/env perl
Import qw ( env INCLUDE LIB BIN BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
$build =~ s/\\/\//g;
(my $obj_dir = DirPath '.') =~ s/\\/\//g;
(my $Dir = $obj_dir) =~ s/$build\///g;
my $ObjDir = "#" . $obj_dir; 
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $pkg = "pgf77VMC";
my $SO_PKG = "lib" . $pkg . ".so";
my $FC = $env->{FC};
my @pgflibs = ();
my $ok = 0;
if ($FC eq 'ifort' or $FC eq 'ifc') {
#   my $lib = `which $FC`; chomp($lib);
# #  $lib =~ s|bin/ifort|lib|;
# #  $lib =~ s|/linux/bin|/compiler/lib|; $lib =~ s|/$FC||;
#   $lib =  File::Basename::dirname($lib);
# # /software/intel_17/compilers_and_libraries_2017.0.098/linux/bin/ia32/ifort
# # /software/intel_17/compilers_and_libraries_2017.0.098/linux/compiler/lib/ia32/libifcore.a
#   $lib =~ s|bin|compiler/lib|;
# #  @pgflibs = map $lib . "/" . $_, qw(libifcore.a libifcoremt.a libifport.a); print "pgflibs @pgflibs\n";
# #  @pgflibs = ("/usr/intel80/ifc/lib/libifcore.a","/usr/intel80/ifc/lib/libifcoremt.a");
#   @pgflibs = ($lib . "/" . "libifcore.a"); print "pgflibs @pgflibs\n";
# #  Command $env [ $SO_PKG ], @pgflibs, qq(cd $obj_dir; ar -x %1; ar -x %2; ar -x %3; rm for_main.o; %SO %SOFLAGS %SoOUT%>:f *.o;);
#   Command $env [ $SO_PKG ], @pgflibs, qq(cd $obj_dir; ar -x %1; %SO %SOFLAGS %SoOUT%>:f *.o;);
  $ok = 0;
} elsif ($FC eq 'pgf77') {
  @pgflibs = ($env->{ENV}->{PGILIB} . "/libpgftnrtl.a",
		 $env->{ENV}->{PGILIB} . "/libpgc.a",
		 $env->{ENV}->{PGILIB} . "/libpgnod_prof.a");
  Command $env [ $SO_PKG ], @pgflibs, qq(cd $obj_dir; ar -x %1; ar -x %2; ar -x %3; %SO %SOFLAGS %SoOUT%>:f *.o;);
  $ok = 1;
} elsif ($FC eq 'g77' or $FC eq 'gfortran') {
  my $CPPFLAGS = $env->{CPPFLAGS};
  $CPPFLAGS .= " -DWithoutPGI";
  $env2 = $env->clone('CPPFLAGS'     => $CPPFLAGS);
  LinkedModule $env2 $SO_PKG, qw(idisp.c);
  $ok = 1;
}
if ($ok) {Install $env $LIB, $SO_PKG;}
