/* tpi_pid.idl*/
#include "PAM.idl"
#include "tpipar.idl"
#include "dst_track.idl"
#include "dst_dedx.idl"
#include "epi_hypo_pid.idl"

interface tpi_pid : amiModule {
             STAFCV_T call
                     ( inout tpipar parm,  
                       inout dst_track gl,
                       inout dst_dedx dedx,
                       inout epi_hypo_pid hypo	
             );
     };
     /*  Last mod. for tde_new.idl $Date: 1998/11/03 15:14:19 $ */
