/*    emcTowerGain.idl
*
*  Table: emcTowerGain
*
*       description: *    //:  Table which contains gain information for emctower ADCs
*/ 


struct emcTowerGain { 

   long   year;             /*    year  */
   long   day;              /*    day  */
   long   run;              /*    run number (if necessary)  */
   float  Mean[4800];       /*    ADC Mean of emc tower  */
   float  RMS[4800];        /*    ADC RMS of emc tower  */
   float  Sum[4800];        /*    Spectrum integral */
   float  SumAbove30[4800]; /*    Spectrum integral above 30 adc counts */

 };  
