/* init_raw_table.idl
 * Translate tppad/tppixel tables into adc/x,y,z info (for diagnostic)
*/
#include "PAM.idl"
#include "tss_tsspar.idl"
#include "raw_sec_m.idl"
#include "raw_row.idl"

interface init_raw_table : amiModule {
   STAFCV_T call(
        in    tss_tsspar     tsspar,
        inout raw_sec_m      raw_sec_m,
        inout raw_row        raw_row_in,
        inout raw_row        raw_row_out);
    };
/* last modified: $Date: 1998/12/08 18:18:13 $ */
