/* reformat_new.idl
 * Translate tppad/tppixel tables into adc/x,y,z info (for diagnostic)
*/
#include "PAM.idl"
#include "tss_tsspar.idl"
#include "tcl_sector_index.idl" 
#include "type_index.idl"
#include "type_shortdata.idl"
#include "type_structtbl.idl"
#include "raw_sec_m.idl"
#include "raw_row.idl"
#include "raw_pad.idl"
#include "raw_seq.idl"

interface reformat_new : amiModule {
   STAFCV_T call(
        in    tss_tsspar     tsspar,
        in   tcl_sector_index   tfc_sector_index  , 
        in    type_index     indextbl,
        in    type_shortdata shortdata,
        in    type_structtbl structtbl,
        inout raw_sec_m      raw_sec_m,
        inout raw_row        raw_row_in,
        inout raw_pad        raw_pad_in,
        inout raw_seq        raw_seq_in,
        inout type_shortdata pixel_data_in,
        inout raw_row        raw_row_out,
        inout raw_pad        raw_pad_out,
        inout raw_seq        raw_seq_out,
        inout type_shortdata pixel_data_out);
    };
/* last modified: $Date: 1998/12/08 18:18:18 $ */
