/**********************************************************************/
/*	Convert "new" raw data format to tppad/tppixel tables	      */
/**********************************************************************/
#include "PAM.idl"
#include "tfc_fmtpar.idl"
#include "type_index.idl"
#include "type_bytedata.idl"
#include "type_shortdata.idl"
#include "type_structtbl.idl"
#include "type_gain_bad.idl"
#include "tfc_native_map.idl"
#include "tfc_valid.idl"
#include "tfc_native_pedestal.idl"
#include "tfc_native_gain.idl"
#include "tss_tppad.idl"
#include "tss_tppixel.idl"

interface reformat : amiModule {
   STAFCV_T call(
	inout tfc_fmtpar fmtpar,
	in type_index indextbl,
	in type_bytedata bytedata,
	in type_shortdata shortdata,
	in type_structtbl structtbl,
	in type_gain_bad gain_bad,
	inout tfc_native_map native_map,
	inout tfc_valid valid,
	inout tfc_native_pedestal pedestal,
	inout tfc_native_pedestal pulser,
	inout tfc_native_gain gain
	out tss_tppad tppad,
	out tss_tppixel tppixel);
   };
/* last modified: $Date: 1997/12/31 14:34:09 $ */
