/* tfc_stability.idl
 * reads pedestal values and calculates averages (for each chip)
 * over the course of a stability run
 */
#include "PAM.idl"
#include "tpc_pedestal.idl"
#include "tfc_tpc_gain.idl"
#include "tfc_pedstab_pars.idl"
#include "tfc_pedstab.idl"

interface tfc_stability : amiModule {
	STAFCV_T call(	in tpc_pedestal pedestal,
			in tfc_tpc_gain gain,
			in tfc_pedstab_pars pedstab_pars,
			inout tfc_pedstab pedstab);
};
/*  Last mod. for tfc_stability: $Date: 1998/05/08 15:18:53 $ */


