/* tfc_load_native_gains.idl
 * Loads native gains to the gain table*/

#include "PAM.idl"
#include "tcl_sector_index.idl"
#include "type_index.idl"
#include "type_gain_bad.idl"
#include "type_structtbl.idl"
#include "raw_sec_m.idl"
#include "raw_row.idl"
#include "type_floatdata.idl"

interface tfc_load_native_gains : amiModule {
   STAFCV_T call(
        in tcl_sector_index current_sector,
        in type_index       indextbl,
        in type_gain_bad    gain_bad,
        in type_structtbl   structtbl,
        out raw_sec_m       gain_sec_m,
        out raw_row         gain_row_in,
        out type_floatdata  gains_in,
        out raw_row         gain_row_out,
        out type_floatdata  gains_out);
   };


