/* xyz.idl
 * Translate tppad/tppixel tables into adc/x,y,z info (for diagnostic)
*/
#include "PAM.idl"
#include "tpg_pad_plane.idl"
#include "tpg_detector.idl"
#include "tss_tppixel.idl"
#include "tss_tppad.idl"
#include "tfc_adcxyz.idl"

interface xyz: amiModule{
	STAFCV_T call
		( in tpg_pad_plane	pad_plane
		, in tpg_detector	detector
		, in tss_tppixel	tppixel
		, in tss_tppad		tppad
		, out tfc_adcxyz	adcxyz
		);
	};

/* Created 25Nov96 Last modification: $Date: 1998/01/02 02:28:04 $ */

