*
* $Id: noarg.F,v 1.1 2009/02/25 00:08:27 fisyak Exp $
*
* $Log: noarg.F,v $
* Revision 1.1  2009/02/25 00:08:27  fisyak
* Clean up mess created after merging
*
* Revision 1.1  2005/06/09 00:05:17  fisyak
* Add stuff for reconstruction
*
* Revision 1.1  2005/05/26 22:28:16  fisyak
* Add stuff necessary for reconstruction packages
*
* Revision 1.1.1.1  1996/02/15 17:50:13  mclareni
* Kernlib
*
*
#include "kerngen/pilot.h"
      SUBROUTINE NOARG (NARGS)
C
C CERN PROGLIB# Z029    NOARG           .VERSION KERNFOR  4.19  880728
C ORIG. 01/12/86  HRR, DUMMY VERSION
C
      RETURN
      END
