/*  est_am.idl
*   Module est_am
*   Matches tpc projections and 4th layer svt hits 
*/

#include "PAM.idl"
#include "svg_geom.idl"
#include "svg_shape.idl"
#include "srs_activea.idl"
#include "srs_srspar.idl"
#include "svg_config.idl"
#include "tcl_tphit.idl"
#include "tpt_track.idl"
#include "scs_spt.idl"
#include "tte_eval.idl"
#include "tte_mctrk.idl"
#include "est_ctrl.idl"
#include "est_match.idl"
#include "g2t_track.idl"
#include "egr_egrpar.idl"

interface est_am : amiModule {
	STAFCV_T call
		(in svg_geom geom,
                 in svg_shape shape,
                 in srs_activea activea,
                 in srs_srspar srspar,
		 in svg_config config,
		 inout scs_spt scs_spt,
		 in tcl_tphit tphit,
		 in tpt_track tptrack,
		 in tte_eval eval,
		 in tte_mctrk ttemctrk,
		 inout est_ctrl est_ctrl,
		 inout est_match est_match,
		 in g2t_track g2t_track,
		 in egr_egrpar egrpar);
};

