/* scs_finder.idl  */

#include "PAM.idl"
#include "ssf_seq.idl"
#include "ssf_adc.idl"
#include "scs_par.idl"
#include "scs_cluster.idl"

interface scs_finder : amiModule {
	STAFCV_T call (
		in    ssf_seq      seq,
		in    scs_par      par,
		inout scs_cluster  clus);
};

