/* scs_fitter.idl  */


#include "PAM.idl"
#include "scs_par.idl"
#include "ssf_8to10map.idl"
#include "svg_geom.idl"
#include "svg_shape.idl"
#include "ssf_seq.idl"
#include "ssf_mv.idl"
#include "ssf_adc.idl"
#include "scs_cluster.idl"
#include "scs_merge.idl"
#include "scs_spt.idl"

interface scs_fitter : amiModule {
	STAFCV_T call (
		in    scs_par      par,
                in    ssf_8to10map map,
                in    svg_geom     geom,
		in    svg_shape    shape,
		in    ssf_seq      seq,
		in    ssf_mv       mv,
		in    ssf_adc      adc,
		inout scs_cluster  clus,
		inout scs_merge    merge,
                inout scs_spt      spt );
};

