/*  svm_am.idl
*   Module svm
*   Combines tpc and svt tracks using vector-to-vector
*    technique.
*/

#include "PAM.idl"
#include "stk_track.idl"
#include "tpt_track.idl"
#include "svm_ctrl.idl"
#include "svm_evt_match.idl"

interface svm_am : amiModule {
	STAFCV_T call
		(in stk_track svtin,
		 in tpt_track tpcin,
		 inout svm_ctrl vvctrl,
		 inout svm_evt_match evtin
		);
};

