/* egr_impactcl.idl
*  Module: egr_impactcl
*
*/

#include "PAM.idl"
#include "dst_vertex.idl"
#include "egr_egrpar.idl"
#include "dst_track.idl"

interface egr_impactcl   :        amiModule {
        STAFCV_T call
                ( in    dst_vertex      vertex
                , in    egr_egrpar      egrpar
                , out   dst_track       globtrk
        );
};
/* Last mod. for egr_impactcl: $Date: 2000/05/10 20:55:54 $ */
