/* egr_fitter.idl
*  Module: egr_fitter
*
*/

#include "PAM.idl"
#include "tcl_tphit.idl"
#include "dst_vertex.idl"
#include "tpt_track.idl"
#include "scs_spt.idl"
#include "egr_egrpar.idl"
#include "stk_track.idl"
#include "sgr_groups.idl"
#include "svm_evt_match.idl"
#include "dst_track.idl"

interface egr_fitter   :        amiModule {
        STAFCV_T call
                ( inout tcl_tphit       tphit
                , in    dst_vertex      privert
                , inout tpt_track       tptrack
	        , inout sgr_groups      tpc_group
                , inout scs_spt         svt_spt
                , in    egr_egrpar      egrpar
                , inout stk_track       svt_track
                , in    sgr_groups      svt_group
                , in    svm_evt_match   evt_match
                , out   dst_track       globtrk
        );
};
/* Last mod. for egr_fitter: $Date: 2000/02/25 02:37:45 $ */
