/* egr_fitter.idl
*  Module: egr_fitter
*
*/

#include "PAM.idl"
#include "tcl_tphit.idl"
#include "dst_vertex.idl"
#include "tpt_track.idl"
#include "tte_eval.idl"
#include "scs_spt.idl"
#include "egr_egrpar.idl"
#include "stk_track.idl"
#include "sgr_groups.idl"
#include "svm_evt_match.idl"
#include "dst_track.idl"
#include "dst_track_aux.idl"

interface egr_fitter   :        amiModule {
        STAFCV_T call
                ( inout tcl_tphit       tphit
                , in    dst_vertex      privert
                , inout tpt_track       tptrack
                , in    tte_eval        tpeval
                , inout scs_spt         svt_spt
                , in    egr_egrpar      egrpar
                , inout stk_track       svt_track
                , in    sgr_groups      svt_group
                , in    svm_evt_match   evt_match
                , out   dst_track       globtrk
	        , out   dst_track_aux   globtrk_aux
        );
};
/* Last mod. for egr_fitter: $Date: 1998/08/24 23:55:06 $ */
