/* egr_primfit.idl
*  Module: egr_primfit
*
*/

#include "PAM.idl"
#include "dst_vertex.idl"
#include "egr_egrpar.idl"
#include "dst_track.idl"

interface egr_primfit   :        amiModule {
        STAFCV_T call
                ( in    dst_vertex      vertex
                , in    egr_egrpar      egrpar
                , in    dst_track       globtrk
                , out   dst_track       primtrk
        );
};
/* Last mod. for egr_primfit: $Date: 2001/04/11 22:58:15 $ */
