/* 	tkf.idl
*  	Module: tkf
*	description:	Tpc charged Kaon Finder
*/
#include "PAM.idl"
#include "tkf_tkfpar.idl"
#include "tkf_tkfout.idl"
#include "g2t_vertex.idl"
#include "g2t_track.idl"
#include "g2t_tpc_hit.idl"
#include "tpt_track.idl"
#include "egr_globtrk.idl"
#include "tte_mctrk.idl"
#include "epi_glob_pid_eval.idl"

interface tkf:        amiModule {
        STAFCV_T call
                ( inout	tkf_tkfpar	tkfpar
                , inout	tkf_tkfout	tkfout
                , in	g2t_track		g2t_track
                , in	g2t_vertex	g2t_vertex
                , in	g2t_tpc_hit	tpch
                , in	tpt_track	tptrack
                , in	tte_mctrk		tpeval
                , in	egr_globtrk	globtrk
                , in	epi_glob_pid_eval	gpideval
        );
};
/* Last mod. for egr_fitter: $Date: 1998/01/26 21:33:13 $ */
   


