      INTERFACE TO SUBROUTINE FTF_EVALUATION [C,ALIAS:'_ftf_evaluation'] 
      END
	  INTERFACE TO SUBROUTINE FTF_KUIP_CLOSE_FILE 
	+ [C,ALIAS:'_FTF_kuip_close_file']       
	  END
      INTERFACE TO SUBROUTINE FTF_KUIP_FILL_PERFORMANCE_NTUPLE 
	+ [C,ALIAS:'_FTF_kuip_fill_performance_ntuple']  
	  END
	  INTERFACE TO SUBROUTINE ftf_kuip_fill_track_ntuple 
	+ [C,ALIAS:'_FTF_kuip_fill_track_ntuple']       
	  END 
      INTERFACE TO SUBROUTINE ftf_kuip_geometry_frame 
	+ [C,ALIAS:'_FTF_kuip_geometry_frame']       
	  END  
	  INTERFACE TO SUBROUTINE ftf_kuip_geometry_reset 
	+ [C,ALIAS:'_FTF_kuip_geometry_reset']       
	  END   
      INTERFACE TO SUBROUTINE ftf_kuip_geometry_new_cylinder 
	+ [C,ALIAS:'_FTF_kuip_geometry_new_cylinder']       
	  END 
      INTERFACE TO SUBROUTINE ftf_kuip_geometry_new_box 
	+ [C,ALIAS:'_FTF_kuip_geometry_new_box']       
	  END 
	  interface to subroutine ftf_kuip_open_file
	+ [c,alias:'_FTF_kuip_open_file']  
	  end
	  interface to subroutine ftf_kuip_print_hit
	+ [c,alias:'_FTF_kuip_print_hit']  
	  end
      interface to subroutine ftf_kuip_print_mc_tracks
	+ [c,alias:'_FTF_kuip_print_mc_tracks']  
	  end
	  interface to subroutine ftf_kuip_print_tracks
	+ [c,alias:'_FTF_kuip_print_tracks']  
	  end
	  interface to subroutine ftf_kuip_print_vol
	+ [c,alias:'_FTF_kuip_print_vol']  
	  end
	  interface to subroutine ftf_kuip_go
	+ [c,alias:'_FTF_kuip_go']  
	  end
	  interface to subroutine ftf_kuip_variable_set
	+ [c,alias:'_FTF_kuip_variable_set']  
	  end
	  interface to subroutine ftf_kuip_select_area
	+ [c,alias:'_FTF_kuip_select_area']  
	  end
	  interface to subroutine ftf_kuip_view_clear
	+ [c,alias:'_FTF_kuip_view_clear']  
	  end
	  interface to subroutine ftf_kuip_view_hits
	+ [c,alias:'_FTF_kuip_view_hits']  
	  end
      interface to subroutine ftf_kuip_view_detector
	+ [c,alias:'_FTF_kuip_view_detector']  
	  end
	  interface to subroutine ftf_kuip_view_reset
	+ [c,alias:'_FTF_kuip_view_reset']  
	  end
	  interface to subroutine ftf_kuip_view_fits
	+ [c,alias:'_FTF_kuip_view_fits']  
	  end
	  interface to subroutine ftf_kuip_data_set
	+ [c,alias:'_FTF_kuip_data_set']  
	  end
	  interface to subroutine ftf_kuip_view_mc_tracks
	+ [c,alias:'_FTF_kuip_view_mc_tracks']  
	  end
	  interface to subroutine ftf_kuip_view_set_phase
	+ [c,alias:'_FTF_kuip_view_set_phase']  
	  end
	  interface to subroutine ftf_kuip_pick_hit
	+ [c,alias:'_FTF_kuip_pick_hit']  
	  end
	  interface to subroutine ftf_kuip_view_tracks
	+ [c,alias:'_FTF_kuip_view_tracks']  
	  end
	  interface to subroutine ftf_kuip_zoom
	+ [c,alias:'_FTF_kuip_zoom']  
	  end