/*-------------------------------------------------------------------------*/
/*       Generated by onetparfsh.ace 
 *   Table: rl0mwc_cal
 */
#define RL0MWC_CAL_LEN 96
#define RL0MWC_CAL_NV 1
/*
 *       Last mod. for rl0mwc_cal:   758587281 Fri Jan 14 17:41:21 1994
 */

