/*-------------------------------------------------------------------------*/
/*       Generated by onetparfsh.ace 
 *   Table: rl0_data
 */
#define RL0_DATA_LEN 1
#define RL0_DATA_NV 11
/*
 *       Last mod. for rl0_data:   762211102 Fri Feb 25 16:18:22 1994
 */
