/*-------------------------------------------------------------------------*/
/*       Generated by onetparfsh.ace 
 *   Table: ks_ctrl
 */
#define KS_CTRL_LEN 1
#define KS_CTRL_NV 9
/*
 *       Last mod. for ks_ctrl:   759596937 Wed Jan 26 10:08:57 1994
 */
