/*-------------------------------------------------------------------------*/
/*       Generated by onetparfsh.ace 
 *   Table: pw_out
 */
#define PW_OUT_LEN 1
#define PW_OUT_NV 8
/*
 *       Last mod. for pw_out:   783377928 Fri Oct 28 16:58:48 1994
 */

