*
* $Id: fzcf.inc,v 1.1.1.1 2004/07/17 20:01:57 perev Exp $
*
* $Log: fzcf.inc,v $
* Revision 1.1.1.1  2004/07/17 20:01:57  perev
* STAR version of Geant321 TGeant3 etc
*
* Revision 1.1.1.1  2002/07/24 15:56:28  rdm
* initial import into CVS
*
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:54  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_FZCF_INC
#define CERNLIB_ZEBRA_FZCF_INC
*
*
* fzcf.inc
*
      COMMON /FZCF/  LUNF, MSTATF,MEDIUF,IFIFOF,IDAFOF,IACMOF,IUPAKF
     +,              IADOPF,IACTVF,INCBPF,LOGLVF,MAXREF, IOPTVF(24)

#endif
