#include "PAM.idl"
#include "svg_config.idl"
#include "g2t_svt_hit.idl"
#include "g2t_track.idl"

interface sal_get_sigma: amiModule 
{
STAFCV_T call(in svg_config config,
              in  g2t_svt_hit g2t_svt_hit,
              in  g2t_track g2t_track);
};
