#include "PAM.idl"
#include "g2t_vertex.idl"
#include "sal_vrtx.idl"

interface sal_getallver: amiModule 
{
    STAFCV_T call(in  g2t_vertex g2t_vertex,
                  out sal_vrtx sal_vrtx);
                                        
};
