/*************************************************************************
                     sal_main.idl
*************************************************************************/
#include "PAM.idl"
#include "svg_config.idl"
#include "svg_geom.idl"
#include "g2t_svt_hit.idl"
#include "sal_vrtx.idl"
#include "sal_geom.idl"

interface sal_main: amiModule 
{
 STAFCV_T call(in  svg_config config,
               in  svg_geom svg_geom, 
               in  sal_geom sal_geom_real,
               in  g2t_svt_hit g2t_svt_hit,
               in  sal_vrtx vertex,
               out sal_vrtx sal_vrtx_find, 
               out sal_geom sal_geom);
};
