/*****************************************************************************
*   Table: emc_calib_header
*        description: Table which contains calibration info
*        auther:      OGAWA, Akio
*/
   struct emc_calib_header { 
       long        date;          /* date */
       long        time;          /* time */
       long        flag;          /* flag */
       short       func;          /* function selection */
       short       det;           /* see emc_def.h */
       short   nmodule;           /* see emc_def.h */
       short      neta;           /* see emc_def.h */
       short      nsub;           /* see emc_def.h */
   };

/* 
   func=0   	Pedestal data
   func=1   	Linear function 
   func=otehrs	Not imprimented(yet)
*/
