/*****************************************************************************
*   Table: emc_cluster_par.idl
*        description: collects all previously hardwired stuff in ems and 
*                     allows parameters to be changed at the KUIP level...
*
*       K.Shestermanov 12/11/96
*/
   struct emc_cluster_par {
     float energy_cut;     /* energy cut for cluster finding */  
     float pt_cut;         /* Pt cut for cluster finding */
     float et_seed;        /* seed parameter for cluster finding */
     float emc_res_a;      /* energy resolution EMC s/e=a+b/e+c/sqrt(e) */
     float emc_res_b;      /* energy resolution EMC s/e=a+b/e+c/sqrt(e) */
     float emc_res_c;      /* energy resolution EMC s/e=a+b/e+c/sqrt(e) */
     float r_shower;       /* radius in the emc in eta-phi plane */
     float r_isol;         /* radius for isolation cut in eta-phi plane */
     float x_edge;         /* min. distance to edge of tower in phi [cm]*/
   };
