/*****************************************************************************
*   Table: emc_adc_cal
*        description: Table which contains pedestal/ADC callibrations
*        auther:      OGAWA, Akio
*/
   struct emc_adc_cal { 
       long        run;           /* run number */
       long        date;          /* date */
       long        time;          /* time */
       long        flag;          /* flag */
       long        det;           /* see emc_def.h */
       long        neta;          /* number of eta bin */
       long        nphi;          /* number of phi bin */
       short       ch[120][40];   /* ADC channel peak */
       short       dev[120][40];  /* ADC channel deviation */
   };

