/*****************************************************************************
*   Table: emc_energy
*        description: Table which contains energy matrix
*        auther:      OGAWA, Akio
*/
   struct emc_energy { 
       short     det;         /* >0 BEMC/EEMC, =0 gap between B&E, -1=outside*/
       short     module;      /* module# */
       short     ebin;        /* eta tower# */
       short     sub;         /* sub divison# */
       float     eta;         /* Pseudorapidity */
       float     phi;         /* Phi */
       float     energy;      /* total energy = twr + trk - chg */
       float     energy_twr;  /* energy from EMC tower */
       float     energy_trk;  /* energy from tracking */
       float     energy_chg;  /* estimated energy in EMC tower from charged particle */
       float     error;       /* estimated error on energy */
       long      n_track;     /* number of charged trks assign into this bin */
       long      n_charge;    /* number of charged trks which hit tower */
   };
