/*****************************************************************************
*   Table: emc_adcslope
*        description: Table which contains ADC to energy conversion parameters
*        auther:      OGAWA, Akio
*/
   struct emc_adcslope { 
       long        date;          /* date */
       long        time;          /* time */
       long        flag;          /* flag */
       long        det;           /* see emc_def.h */
       long        neta;          /* number of eta bin */
       long        nphi;          /* number of phi bin */
       long        fun;           /* function selection */
       float       p0[120][40];   /* pedestal for low energy ADC channel */
   };

