/*****************************************************************************
*   Table: emc_egrid_par
*        description: energy grid parameters              
*
*	OGAWA< Akio
*/
   struct emc_egrid_par {
     float chrg_eta_min;     /* Cut for eta minimum for charged track */
     float chrg_eta_max;     /* Cut for eta maximum for charged track */
     long  ideal_eta_nbin;   /* Size of energy matrix for ideal egrid */
     long  ideal_phi_nbin;   /* Size of energy matrix for ideal egrid */
   };

