/*
*   Table: emc_hits
*	See also emc_def.h for descriptions
*	A.OGAWA
*/
   struct emc_hits {
       short   det;      /* Detector number. See emc_def.h*/
       short   module;   /* Mmodule number */
       short   eta;      /* Pseudorapidity bin number */
       short   sub;      /* Sub divison */
       short   adc;      /* ADC channel */
       float   energy;   /* converted energy */
   };
