/*
*   Table: emc_gamma
*   Y.MATULENKO
*/
   struct emc_gamma {
     float   eta;       /* Pseudorapidity */
     float   phi;       /* Phi */
     float   energy;    /* energy */
     float   sigma_eta; /* width Pseudorapidity */
     float   sigma_phi; /* width Phi */
     float   energy_presh;    /* energy preshower*/
     float   energy_smd;      /* energy smd eta+fi*/
     short   indx;      /* 1 eta,2 phi,4 eta, 8 phi */
     short   eta1;      /* first  eta */
     short   eta2;      /* second eta */
     short   phi1;      /* first  phi */
     short   phi2;      /* second phi */
   };
