/*
*   Table: emc_cluster_index
*	See also emc_def.h for descriptions
*	A.OGAWA
*/
   struct emc_cluster_index {
     short   det;                  /* Detector number. See emc_def.h*/
     long    hit_id;               /* hit id */
     long    cluster_id;           /* cluster id */
     long    neighbour_cluster_id; /* neighbour_cluster id, -1 = none */
   };
