/*****************************************************************************
*   Table: emc_jetpar
*        description: jet recognition parameters              
*
*	OGAWA< Akio
*/
   struct emc_jetpar {
       long   init;         /* initialization flag */
       long   jetmethod;    /* jet finding algorithm (only =1 works right now) */
       long   jetweighting; /* =1 to use eta,phi weighting */
       float  cone_rad;     /* jet cone radius in cluster algorithm */
       float  ej_min;       /* energy cut for post-algorithm analysis */
       float  et_min;       /* min energy deposition to be collected */
       float  et_seed;      /* init. transverse energy in algorithm GeV */
       float  par[5];       /* possible extra params in algorithm */
       float  phi_dev;      /* back-to-back phi deviations for 2 jets */
       float  min_cone_move;/* stop moving cone when it moves less than this */
       float  max_cone_move;/* cone will not move more than this away from initiator*/
       long   mode_bg;      /* background subtraction mode off=0/on=1*/
       float  prec_bg;      /* stop iteration when bg level doesn's change this much*/
       float  eta_max;      /* minimum eta for jet */
       float  eta_min;      /* maxinum eta for jet */
   };

