/*
*   Table: emc_cluster
*	See also emc_def.h for descriptions
*	A.OGAWA
*/
   struct emc_cluster {
     short   det;       /* Detector number. See emc_def.h*/
     float   eta;       /* Pseudorapidity */
     float   phi;       /* Phi */
     float   energy;    /* energuy */
     float   sigma_eta; /* width in rapidity */
     float   sigma_phi; /* width in phi */
     short   nhits;     /* number of hits in cluster */
   };
