/*****************************************************************************
*   Table: emc_energy
*        description: Table which contains energy matrix
*        auther:      OGAWA, Akio
*/
   struct emc_energy { 
       long      det;         /* 1=barrel, 2=endcap, 3=charged track */
       long      ieta;        /* Pseudorapidity bin number */
       long      iphi;        /* Phi bin number */
       float     eta;         /* Pseudorapidity */
       float     phi;         /* Phi */
       float     energy;      /* Energy */
       float     error;       /* Estimated error on energy */
       long      n_track;     /* Number of charged trks which hit tower */
   };
