/*****************************************************************************
*   Table: emc_part_id_par.idl
*        description: collects all previously hardwired stuff in ems and 
*                     allows parameters to be changed at the KUIP level...
*
*       K.Shestermanov 25/11/99
*/
   struct emc_part_id_par {
     long  n_shower_e;     /* number of strips for shower loc. in smd in eta */
     long  n_shower_p;     /* number of strips for shower loc. in smd in phi */
     float r_shower;       /* radius of shower in the emc */
     float e_smd_cut;      /* cut on energy deposited in smd */
     float x_edge;         /* min. distance to edge of tower in phi [cm]*/
     float wid_z_cut;      /* cut on shower width in z direction */
     float wid_rphi_cut;   /* cut on shower width in rphi direction */
     float hi2_z_cut;      /* cut hi2 shower shape in z direction */
     float hi2_rphi_cut;   /* cut hi2 shower shape in r_phi direction */
     float trk_qual_cut;   /* cut on trackin hi2 */
     float delta_rphi;     /* cut on diff. emc and tracking in rphi */
     float delta_z;        /* cut on diff. emc and tracking in z */
     float e_p_min;        /* ratio energy deposited in EMC and track mom. */
     float e_p_max;        /* ratio energy deposited in EMC and track mom. */
   };
