/*****************************************************************************
*   Table: emc_elect.idl
*        description: Variables for the cluster in barrel EMC.
*             more..:                                         
*
*       K.Shestermanov  01/09/97
*/
   struct emc_elect { 
       long      p_cluster;  /* pointer on emc_cluster table */
       long      p_bsmde;    /* pointer on emc_hits_bsmde with max E. dep. */
       long      p_bsmdp;    /* pointer on emc_hits_bsmdp with max E. dep. */
       long      det_id;     /* det used in finder, 1234-1&2&3&4 (see det.h) */
       float     energy;     /* Energy of gamma */ 
       float     s_energy;   /* sigma of energy */
       float     p_cl[3];    /* Momentum vector for cluster , corrected */
       float     eta;        /* Pseudorapidity of cluster */
       float     sigma_eta;  /* sigma of eta */
       float     phi;        /* Phi angle for cluster */
       float     sigma_phi;  /* sigma of phi */
       float     x_cl[3];    /* coordinate for cluster hit in EMC. */
       float     x_p_loc;    /* local coordinate in module on phi direction */
       float     r_isol;     /* (Et(r<r_isol)-Et(em))/Et(em) */
       float     width_z;    /* Shower width in z(eta) direction */
       float     width_rphi; /* Shower width in r*phi direction */
       float     hi2_z;      /* hi2 for trans. cluster shape in SMD for z */ 
       float     hi2_rphi;   /* hi2 for trans. cluster shape in SMD for rp */
   };
