/*****************************************************************************
*   Table: emc_pizero.idl
*        description: Variables for the cluster in barrel EMC.
*             more..:                                         
*
*       K.Shestermanov  01/09/97
*/
   struct emc_pizero { 
       long      p_gamma1;   /* pointer on emc_gam table */
       long      p_gamma2;   /* pointer on emc_gam table */
       float     egam1;      /* energy of gamma1 */
       float     egam2;      /* energy of gamma2 */
       float     cosa;       /* cos angle between two gamma */
       float     pt;         /* Pt of pi_zero */ 
       float     mass;       /* invariant mass of pi_zero */
       float     sigma_mass; /* sigma of the invariant mass of pi_zero */
       float     eta;        /* Pseudorapidity of pi_zero */
       float     phi;        /* Phi angle for pi_zero */
   };
