/*****************************************************************************
*   Table: ems_jetlist
*        description: contains the jet information            
* 
*	W.J. Llope
*/
   struct ems_jetlist {
       long      id;         /* jet number */
       long      id_b;       /* Id of jet that sat. b-to-b criteria. */
       long      n_cells;    /* number of cells forming a jet */
       long      n_jet;      /* Number of jets in event. */
       float     e_j;        /* jet energy as obtained by jet-finder */
       float     eta;        /* eta position of a jet */
       float     eta_w;      /* weighetd eta position of a jet */
       float     jet_m;      /* jet mass; =0 if e**2-p**2 < 0 */
       float     p_j[3];     /* jet momentum vector */
       float     phi;        /* phi position of a jet */
       float     phi_w;      /* weighted phi position of a jet */
   };
