/*
*   Table: ems_hits_bsmd
*
*	K.Shestermanov
*/
   struct ems_hits_bsmd {
       long    eta_bin;        /* Pseudorapidity bin number, -10->10 */
       long    phi_bin;        /* Phi module number, 1->60 */
       long    type;           /* SMD tipe 1->3 */
       long    strip;          /* SMD strip number 1->75 (tipe 1,2) 1>15 - 3 */
       float   e_sum;          /* Energy deposited */
   };
