/*****************************************************************************
*   Table: ems_lvl0_bits
*
*	W.J. Llope
*/
   struct ems_lvl0_bits {
       long      four_tow[3];    /* 4 tower trigger bits. */
       long      glob_bits[3];   /* Global energy trigger bits. */
       long      lum_bits[3];    /* Luminosity monitoring trigger bits. */
       long      one_tow[3];     /* Single tower trigger bits. */
       long      sixteen_tow[3]; /* 16 tower trigger bits. */
       float     glob_adc;       /* Global level 0 ADC value. */
   };
