/*****************************************************************************
*   Table: ems_electron.idl
*        description: Variables for the electrons from Ws mod.
*             more..:                                         
*
*	W.J. Llope
*/
   struct ems_electron { 
       long      charge;     /* Charge for the electron trk. */
       long      id;         /* Primary key. */
       long      id_b;       /* Number of b-to-b structures. */
       long      n_cells;    /* Number of EMC towers in cluster. */
       long      n_elect;    /* Number of electrons found in this event. */
       long      pid_kine;   /* Particle id code from kine bank. */
       float     e_elect;    /* Energy of electron. */
       float     edep;       /* Energy deposited by electron in EMC. */
       float     eta;        /* Pseudorapidity of electron. */
       float     eta_trk;    /* Pseudorapidity for the electron trk. */
       float     eta_w;      /* Weighted value of pseudorapidity. */
       float     jet_m;      /* Jet mass. */
       float     p_elect[3]; /* Momentum vector for electron. */
       float     p_kine[3];  /* Momentum vector from kine bank. */
       float     phi;        /* Phi angle for electron */
       float     phi_trk;    /* Phi angle for the electron trk. */
       float     phi_w;      /* Weighted Phi for electron. */
       float     pt;         /* Pt value for the electron trk. */
       float     ptot;       /* Total momentum of the electron trk. */
       float     r_elect;    /* Radius parameter for electron. */
       float     x;          /* X coordinate for electron hit in EMC. */
       float     x_trk;      /* Last point on trk. */
       float     y;          /* Y coordinate for electron hit on EMC. */
       float     y_trk;      /* Last point on trk. */
       float     z;          /* Z coordinate for electron hit on EMC. */
       float     z_trk;      /* Last point on trk */
   };

