/*****************************************************************************
*   Table: ems_lvl0_thres
*
*	W.J. Llope
*/
   struct ems_lvl0_thres {
       float     one_tow_thres[3];     /* These 3 #s set 1 tower thresholds. */
       float     four_tow_thres[3];    /* These 3 #s set the 4 tower thresholds. */
       float     sixteen_tow_thres[3]; /* These 3 #s set the 16 tower thresholds. */
       float     glob_thres[3];        /* These 3 #s set the global thresholds. */
       float     lum_thres[4];         /* These 4 #s set thres. on # of towers. */
   };
