/***************************************************************************************
*   Table: ems_hits_bsmd
*
*	W.J. Llope
*/
   struct ems_hits_bsmd {
       long    rl;             /* right/left: =1 for Z<0, =2 for Z>0 */
       long    phi_bin;        /* Phi module number, 1 -> 60 */
       long    pswire;         /* psuedo-wire (0.5cm pitch), gives phi */
       long    psstrip;        /* psuedo-strip (0.5cm pitch), gives eta */
       float   edep;           /* Sum of deposited energy (GeV!)*/
   };
