/*
*   Table: ems_hits
*	See also emc_def.h for descriptions
*	A.OGAWA
*/
   struct ems_hits {
       short   det;      /* Detector number. See emc_def.h*/
       short   module;   /* Mmodule number */
       short   eta;      /* Pseudorapidity bin number */
       short   sub;      /* Sub divison */
       float   energy;   /* simulated energy */
       float   e_neut;   /* simulated neutral energy */
   };
