/***************************************************************************************
*   Table: ems_hits_esmd
*
*	OGAWA, Akio
*/
   struct ems_hits_esmd {
       long    rl;             /* right/left: =1 for Z<0, =2 for Z>0 */
       long    phi_mod;        /* Phi module number, 1 -> 60 */
       long    phi_strip;      /* phi subcell */
       long    eta_strip;      /* eta subcell */
       float   e_sum;           /* Sum of deposited energy (GeV!)*/
   };

