/*****************************************************************************
*   Table: ems_cal_control
*	emc calinration simulation control table     -OGAWA, Akio
*/
   struct ems_cal_control {
     long   det;           /* Detector number. See emc_def.h*/
     long   iseed;         /* seed for random number gen. =0 use default value */
     long   ped_channel;   /* mean pedestal for fake_pedestal */
     long   ped_var;       /* ch to ch pedestal variation for fake_pedestal */
     long   slope_fun;     /* slope function # for fake_adcslope */
     float  slope_ave;     /* average slope for fake_adcslope */
     float  slope_var;     /* slope variation for fake_adcslope */
     float  ped_width;     /* pedestal width for energy_to_adc */
     long   toy_sim_mode;  /* =0 pedestal, =1 gaussian */
     float  noise_level;   /* noise level for toy_simulator mode=0 */
     float  noise_width;   /* noise width for toy_simulator mode=0 */
     float  gaus_peak;     /* peak for toy_simulator mode=1 */
     float  gaus_width;    /* width for toy_simulator mode=1 */
     float  occupancy;     /* hit occupancy toy_simulator mode=1 */
   };
