/*****************************************************************************
*   Table: ems_control
*        description: collects all previously hardwired stuff in ems and 
*                     allows parameters to be changed at the KUIP level...
*
*	parameters marked "DB!!" *should* be obtained from the
*	database (which doesn't exist yet)...
*
*	W.J. Llope
*/
   struct ems_control {
     long  bemc_Ntowers;   /* can be 1200 or 4800 only (three depths either way) */
     float bemc_inner_r;   /* DB!! emc barrel inner radius */
     float bemc_max_z;     /* DB!! emc barrel maximum Z */
     float trk_qual_cut;   /* global track quality cut on chi2/DOF */
     float b_field;        /* DB!! magnetic field in kG */
     float sampfrac;       /* converts observed to incident energy */
   };
