/*****************************************************************************
*   Table: ems_jetpar
*        description: jet recognition parameters              
*
*	W.J. Llope
*/
   struct ems_jetpar {
       long      jetmethod;    /* jet finding algorithm (only =1 works right now) */
       long      jetweighting; /* =1 to use eta,phi weighting */
       float     cone_rad;     /* jet cone radius in cluster algorithm */
       float     ej_min;       /* energy cut for post-algorithm analysis */
       float     et_min;       /* min energy deposition to be collected */
       float     et_seed;      /* init. transverse energy in algorithm GeV */
       float     par[5];       /* possible extra params in algorithm */
       float     phi_dev;      /* back-to-back phi deviations for 2 jets */
   };
