/*****************************************************************************
*   Table: ems_control
*        description: collects all previously hardwired stuff in ems and 
*                     allows parameters to be changed at the KUIP level...
*
*	parameters marked "DB!!" *should* be obtained from the
*	database (which doesn't exist yet)...
*
*	W.J. Llope
*/
   struct ems_control {
     long  bemc_on;	   /*=1 on, else off*/
     long  bsmd_on;	   /*=1 on, else off*/
     long  eemc_on;        /*=1 on, else off*/
     long  esmd_on;        /*=1 on, else off*/
     long  bemc_Ntowers;   /* can be 1200 or 4800 only (three depths either way) */
     float bemc_inner_r;   /* DB!! emc barrel inner radius */
     float bemc_max_z;     /* DB!! emc barrel maximum Z */
     float eemc_inner_z;   /* DB!! emc endcap z position */
     float eemc_inner_r;   /* DB!! emc endcap inner radius */ 
     float eemc_outer_r;   /* DB!! emc endcap outer radius */ 
     float trk_qual_cut;   /* global track quality cut on chi2/DOF */
     float b_field;        /* DB!! magnetic field in kG */ 
     float sampfrac;       /* converts observed to incident energy */
     long  bemc_eta_nbin;    /* DB!! emc barrel eta # of bin */
     float bemc_eta_bin[41]; /* DB!! emc barrel eta binning  */
     long  bemc_phi_nbin;    /* DB!! emc barrel phi # of bin */
     long  eemc_eta_nbin;    /* DB!! emc endcap eta # of bin */
     float eemc_eta_bin[13]; /* DB!! emc endcap eta binning  */
     long  eemc_phi_nbin;    /* DB!! emc endcap phi # of bin */
     long bemc_adcbits;      /* barrel emc tower ADC bits */
     long bprs_adcbits;      /* barrel emc preshower ADC bits */
     long bsmd_adcbits;      /* barrel emc smd ADC bits */
     long eemc_adcbits;      /* endcap emc tower ADC bits */
     long eprs_adcbits;      /* endcap emc preshower ADC bits */
     long esmd_adcbits;      /* endcap emc smd ADC bits */
     long  chrg_eta_nbin;    /* Size of energy matrix for charged track */
     long  chrg_phi_nbin;    /* Size of energy matrix for charged track */
     float chrg_eta_min;     /* Cut for eta minimum for charged track */
     float chrg_eta_max;     /* Cut for eta maximum for charged track */
     long  ideal_jet_mode;   /* mode for idel jet finder 1=ideal,2=1-nuotrino,3=charged only */
   };

