/***************************************************************************************
*   Table: ems_hits_eemc
*
*	OGAWA, Akio
*/
   struct ems_hits_eemc {
       long    rl;             /* right/left: =1 for Z<0, =2 for Z>0 */
       long    tower_eta_bin;  /* Pseudorapidity bin number, 1->12 */
       long    tower_phi_bin;  /* Phi module number, 1 -> 60 */
       long    tower_dep;      /* Depth section, 1 -> 3, or 0=tower total */
       float   eb_sum;         /* Sum of energy with Birk's Law. */
       float   eb_neut;        /* Sum of energy from Neut. part. hits with Birk's Law*/
   };
