/*****************************************************************************
*   Table: ems_lvl0_adcs
*
*	W.J. Llope
*/
   struct ems_lvl0_adcs {
       long      eta_bin;    /* Eta bin identifier for isospin patch. */
       long      phi_bin;    /* Phi bin identifier for isospin patch. */
       float     iso_adc;    /* ADC value (energy dep.) for patch. */
   };
