/*
*   Table: ems_hits_bemc
*
*	K.Shestermanov
*/
   struct ems_hits_bemc {
       long    eta_bin;        /* Pseudorapidity bin number, -20->20  */
       long    phi_bin;        /* Phi module number, 1->120 */
       long    tower_dep;      /* Depth section, 1-preshower 2-tower total */
       float   e_sum;          /* Sum of energy with Birk's Law. */
       float   e_neut;         /* Sum of energy from Neut. part. hits with Birk's Law*/
   };
