/*****************************************************************************
*   Table: ems_emecor
*        description: Table which contains tower energies cor-
*             more..: rected for CPR of EMC barrel towers.    
*
*	W.J. Llope
*/
   struct ems_emecor { 
       long      eta_bin;    /* Pseudorapidity bin number, -20 -> 20 */
       long      phi_bin;    /* Phi module number, 0 -> 60 */
       float     echar_vert; /* Energy due to charged tracks at vertex. */
       float     eneut_cpr;  /* Neutral Energy deduced by subtracting. */
       float     eneut_mct;  /* Neutral Energy as given by g2t. */
       float     etot_2;     /* Energy due to trks with neutral via g2t */
       float     etot_3;     /* Energy at vertex via MKINE. */
       float     etot_sim;   /* Echarged from trks and E neut via CPR */
       float     num_char;   /* Number of charged trks which hit tower */
   };
