/*
*   Table: tpc_bemc
*	matching TPC's track with BEMC's towers  
*	Pavlinov A.I.
*/

   struct tpc_bemc {
       short   eta_bin;   /* Pseudorapidity bin number */
       short   phi_bin;   /* Phi module number */
       short   adc;       /* ADC channel */
       short   ntpc;      /* Number of matching TPC track to tower */
       short   flag;      /* Quality flag for TPC track */
       short   nrec;      /* Number of point assigned to track */
       float   pq;        /* Momentum of best TPC track*q   */
       float   dl;        /* Path length in tower */
       float   x1;        /* x-cord. of input point */
       float   y1;        /* y-cord. of input point */
       float   z1;        /* z-cord. of input point */
       float   x2;        /* x-cord. of input point */
       float   y2;        /* y-cord. of input point */
       float   z2;        /* z-cord. of input point */
   };
