/* tpg_main.idl
*  
*  Module: tpg_main 
*     Description: TPC geometry package.
* modified 05feb97 - mal - to include tpg_detector and tpg_pad
* tables
*/

#include "PAM.idl"
#include "tpg_pad_plane.idl"
#include "tpg_detector.idl"
#include "tpg_pad.idl"

interface tpg_main : amiModule {
          STAFCV_T call
                   (in tpg_pad_plane pad_plane,
		    in tpg_detector  tpg_detector,
	            in tpg_pad       tpg_pad);
};

/* Last mod. for tpg_main: $Date: 1998/01/27 01:56:46 $ */



















