/*	tpt_am.idl
*
*	Module: tpt_am
*	description: TPC tracking
*/
#include "PAM.idl"
#include "tpt_pars.idl"
#include "tpg_pad_plane.idl"
#include "tcl_tphit.idl"
#include "tpt_track.idl"

interface tpt_am : amiModule{
	STAFCV_T call
		( in    tpt_pars tpar
		, in    tpg_pad_plane pad_pl
		, inout tcl_tphit hit
		, out   tpt_track track
		);
};
/* Last mod. for tpt: $Data$ */
