/* tpt_sts.idl - tracking for the no B case */
#include "PAM.idl"
#include "tpt_spars.idl"
#include "tcl_tphit.idl"
#include "tpt_res.idl"
#include "tpt_strack.idl"

interface tpt_sts : amiModule {
          STAFCV_T call(   in    tpt_spars par,
			   inout tcl_tphit tphit,
			   out   tpt_res res,
			   out   tpt_res diff_res,
			   out   tpt_strack strack
                           );
};
