//:Copyright 1996, Lawrence Berkeley Laboratory
//:>--------------------------------------------------------------------
//:FILE:        socItypes.idl
//:DESCRIPTION: Service & Objcect Catalog type definition
//:AUTHOR:      cet - Craig E. Tull, cetull@lbl.gov
//:BUGS:        -- STILL IN DEVELOPMENT --
//:HISTORY:     24apr96-v000a-cet- creation from soc_i.idl
//:<--------------------------------------------------------------------

//:----------------------------------------------- INCLUDES           --

//:----------------------------------------------- TYPEDEFS           --
#ifndef SOCITYPES_IDL
#define SOCITYPES_IDL

typedef long IDREF_T;			/* reference ID */

typedef long SOC_PTR_T;			/* pointer type */

typedef sequence<char> CHAR_SEQ_T;
typedef sequence<octet> OCTET_SEQ_T;
typedef sequence<short> SHORT_SEQ_T;
typedef sequence<unsigned short> USHORT_SEQ_T;
typedef sequence<long> LONG_SEQ_T;
typedef sequence<unsigned long> ULONG_SEQ_T;
typedef sequence<float> FLOAT_SEQ_T;
typedef sequence<double> DOUBLE_SEQ_T;

typedef long VOID_T;			/* void* */

#endif /*SOCITYPES_IDL*/
