/* svg_am.idl
*     Module: svg_am
*     description fills SVT geometry tables
*/

#include "PAM.idl"
#include "svg_config.idl"
#include "svg_shape.idl"
#include "svg_geom.idl"

interface svg_am : amiModule {
      STAFCV_T call
      ( inout svg_config config
      , inout svg_shape  shape
      , out svg_geom   geom
      );
};
/* Last mod. for svg_am: $Date: 1998/04/09 21:13:09 $ */
