/* svg_am_ssd.idl
*     Module: svg_am_ssd
*     description extends SVT geometry tables with SSD geometry
*/

#include "PAM.idl"
#include "svg_geom.idl"

interface svg_am_ssd : amiModule {
      STAFCV_T call
      ( inout svg_geom   geom
      );
};
/* Last mod. for svg_am_ssd: $Date: 1999/02/14 19:26:59 $ */
