/*
*********************************************************
* Table:       controlEmcSimulatorMaker.idl
* Description: define keys for managing StEmcSimulatorMaker.
* Author     : Aleksei Pavlinov, WSU 
*              13-may-2002 - added staff for DB 
*              28-may      - changed short to long 
*********************************************************
*/
  struct  controlEmcSimulatorMaker{
    long  bemc;           /* switch for BEMC */
    long  eemc;           /* switch for EEMC */
    long  hist;           /* switch for hist */
    long  debug;          /* 0=debug of; >1=debug on */
    long  messLimit;      /* limit for warning message */
    long  keyDB[8];       /* key for DB */ 
    float pedCutOff[8];   /* pedestal cutoff for the hits (0 means no cutoff) */
    long  makeFullDet[8]; /* simulates pedestals where there is no hit */
    float calibOffSet[8]; /* calibration offset for every detector (systematic error) */
    float calibSpread[8]; /* calibration error for every detector */
    long  dateDB;         /* date for DB */ 
    long  timeDB;         /* time for DB */ 
  };
