/*
*********************************************************
* Table:       controlEmcPmtSimulator.idl
* Description: define data for transition
*              from deposit energy to ADC
* Author     : Aleksei Pavlinov, WSU 
*********************************************************
*/
  struct  controlEmcPmtSimulator{
    short mode;      /* Mode of work (from 0 to 4 */
    short maxAdc;    /* ADC bits */
    float maxEnergy; /* Max energy in BEMC tower (~60 GeV/c) at zero angle*/
    float sfCoeff[3];/* Polinomial coefficients */ 
    float depMip;    /* MIP deposit energy in Sc.layers at zero angle */ 
    float npheMip;   /* Number of PHE for MIP at zero angle */ 
    short typeOfPmt; /* */
  };
