/*
*********************************************************
* Table:       controlEmcSimulatorMaker.idl
* Description: define keys for managing StEmcSimulatorMaker.
* Author     : Aleksei Pavlinov, WSU 
*********************************************************
*/
  struct  controlEmcSimulatorMaker{
    short bemc;      /* switch for BEMC */
    short eemc;      /* switch for EEMC */
    short hist;      /* switch for hist */
    short debug;     /* 0=debug of; >1=debug on */
    short messLimit; /* limit for warning message */
  };
