###########################################################
# $Id: GNUmakefile,v 1.2 2000/04/05 16:09:10 lasiuk Exp $
###########################################################
name := StRrs

include local/GNUmakefile.architecture
CPPFLAGS += -I$(SCL_HOME) \
	    -I./include

include local/GNUmakefile.common
