###########################################################
# $Id: GNUmakefile,v 1.1 2000/02/08 16:36:44 lasiuk Exp $
###########################################################
name := StRrs

include local/GNUmakefile.architecture
CPPFLAGS += -I$(SCL_HOME)/include \
	    -I./include

include local/GNUmakefile.common
