#!/opt/star/bin/perl
Import qw ( env INCLUDE LIB BIN EXPORT BUILD OBJ);
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $DirPath = DirPath '.';# print "DirPath = $DirPath\n"; 
my $Dir = "StDb/include";   print "Build Tables for $Dir\n" unless ($param::quiet);
my @idlL = find_hfiles($Dir);  # print "@idlL\n"; 
my @Repo = Repository_List; # print "Repositories = |@Repo|\n";
foreach my $Rep (@Repo) {
  my $RepDir = $Rep . "/" . $Dir;# print "RepDir = $RepDir\n";
  my @idlR = find_hfiles($RepDir);
  foreach my $i (@idlR) {
    push @idlL, $i; 
  }
}
my @idl = sortu (@idlL); # print "idl = @idl\n"; 
my @idlT = ();
my @sources = (); 
my $DIR = cwd();# print "DIR = $DIR\n";
my $PKG = "StDbTables";
my $obj = $OBJ . "/" . $PKG;
my $share  = "#.share/" . $PKG;# print "share = $share\n";
my $include = $INCLUDE . "/tables"; #print "include = $include\n";
my $SHARE  = $DIR . "/.share/" . $PKG;
Link $DirPath =>  $SHARE; print "Link $DirPath =>  $SHARE\n" unless ($param::quiet);
my $SO_PKG = $PKG . "." . $env->{SUFSOLIB}; #print "SO_PKG = $SO_PKG\n";
my $LIBPKG = $PKG . "." . $env->{SUFLIB};
foreach my $idl (@idl) {#  print "$idl\n";
  next if $idl !~ /\.h$/;
  my $IDL = "#" . $Dir . "/" . $idl;# print "i=",$i++," idl = $idl IDL=$IDL\n";
  push @idlT, $IDL; 
}# print "idlT = @idlT\n";
Install $env $INCLUDE, @idlT; #print "Install $env $INCLUDE, @idlT\n";
#___________________________________
my $ROOTCINT_CPP = $INCLUDE . ":" . $INCLUDE . "/tables:" . $share;
   $ROOTCINT_CPP.= ":" . $env->{ENV}->{STAF} . "/inc:" . $env->{ENV}->{ROOTSRC};
   $env2 = $env->clone(
		    'DEBUG'      => ' ',
		    'CPPPATH'    =>$ROOTCINT_CPP
		    );
my $cscanner= find scan::cpp($env->{_cwd}, $ROOTCINT_CPP);# print "ROOTCINT_CPP = $ROOTCINT_CPP\n";
my $ROOTCINT_CPPPATH = $cscanner->iflags;# print "ROOTCINT_CPPPATH = $ROOTCINT_CPPPATH\n";

foreach my $idll (@idlT) { 
  my $stem     = basename ($idll, ".h"); # print "stem = $stem; idll: $idll\n";
  my $dir      = dirname ($idll); #print "dir = $dir\n"; 
  my $idl      = basename ($idll);
  my $idlh     = $INCLUDE . "/"    . $stem . ".h";
  my $idlH     = $include . "/St_" . $stem . "_Table.h";       #print "idlH: $idlH\n";
  my $idlC     = $share   . "/St_" . $stem . "_Table.cxx";     #print "idlC: $idlC\n";
  my $LinkDef  = $share   . "/"    . $stem . "LinkDef.h";      #print "LinkDef = $LinkDef\n";
  my $idlCintH = $share   . "/St_" . $stem . "_TableCint.h";   #print "idlCintH = $idlCintH\n";
  my $idlCintC = $share   . "/St_" . $stem . "_TableCint.cxx"; #print "idlCintC = $idlCintC\n";
  (my $IDL = $idll) =~ s/^\#//g; # print "IDL = $IDL\n";
  if (-r $IDL) { 
    my @Deps = ($idll);# print "Deps: $Deps[0]\n";
    if ($STAR_SYS !~ /^intel_wnt$/) {
      Command $env2 [$idlH],        @Deps, qq (ConstructTable.pl %1:f %>);
      push @Deps, $idlH;
      Command $env2 [$idlC],        @Deps, qq (ConstructTable.pl %1:f %>);
      Command $env2 [$LinkDef],     @Deps, qq (ConstructTable.pl %1:f %>);
    }
    @Deps = ();
    push @Deps, $idlh;
    push @Deps, $idlH;
    push @Deps, $LinkDef;
#    push @Deps, $INCLUDE . "/Stypes.h";
#    push @Deps, $INCLUDE . "/St_Table.h";
#    push @Deps, $INCLUDE . "/St_DataSet.h";
#    push @Deps, $INCLUDE . "/tableDescriptor.h";
    Depends $env2 [$idlCintH,$idlCintC], $LinkDef;
    if ($STAR_SYS !~ /^intel_wnt$/) {
      my @hh = ($idlH);
      Command $env2 [$idlCintC, $idlCintH], @Deps,  
      qq (rootcint.pl %>:d -f %>:f -c  "$ROOTCINT_CPPPATH -D__ROOT__" %1:f %2:f);
    }
    push @Deps, $idlCintC;
    push @Deps, $idlCintH;
    push @Deps, $idlC;
    my @src  = ($idlC,$idlCintH,$idlCintC);
    Install $env2 $obj, @src; #print "Install $env2 $obj, @src\n";
  }
  my $s;
  ($s = $idlC)     =~  s/$share/$obj/g; push @sources, $s;
  ($s = $idlCintC) =~  s/$share/$obj/g; push @sources, $s;
}
if ($#sources > -1) {
  if ($STAR_SYS =~ /^intel_wnt$/) {
    Library      $env2 $LIBPKG, @sources;  
    Install $env2 $LIB, $LIBPKG;
  }
  
  LinkedModule $env2 $SO_PKG, @sources;
  Install $env2 $LIB, $SO_PKG;
}
#________________________________________
