//:Copyright 1995, Lawrence Berkeley National Laboratory
//:>--------------------------------------------------------------------
//:FILE:	tbrI.idl
//:DESCRIPTION:	TBR Interface Orbix-objects
//:AUTHOR:	cet - Craig E. Tull, cetull@lbl.gov
//:BUGS:	-- STILL IN DEVELOPMENT --
//:HISTORY:	27mar96-v001a-cet- three interfaces
//:HISTORY:	11mar96-v000a-cet,hjw- creation
//:<--------------------------------------------------------------------

//:----------------------------------------------- INCLUDES           --
//:#include "socI.idl"
#include "tdmI.idl"

//:----------------------------------------------- TYPEDEFS           --

//:=============================================== INTERFACE          ==
interface tbrMotifViewerI : socObjectI {

//:----------------------------------------------- ATTRIBUTES         --
//:**NONE**
//:----------------------------------------------- FUNCTIONS          --
STAFCV_T viewDataset(in tdmDatasetI dataset);
STAFCV_T viewTable(in tdmTableI table);
};

//:=============================================== INTERFACE          ==
interface tbrAsciiViewerI : socObjectI {

//:----------------------------------------------- ATTRIBUTES         --
//:**NONE**
//:----------------------------------------------- FUNCTIONS          --
STAFCV_T getValue(in string variable, out string value);
STAFCV_T setValue(in string variable, in string value);
STAFCV_T printDataset(in tdmDatasetI dataset);
STAFCV_T printTable(in tdmTableI table);
};

//:=============================================== INTERFACE          ==
interface tbrFactoryI : socFactoryI {

//:----------------------------------------------- ATTRIBUTES         --

//:----------------------------------------------- FUNCTIONS          --
STAFCV_T deleteAsciiViewer(in string name);
STAFCV_T findAsciiViewer(in string name
		, out tbrAsciiViewerI viewer);
STAFCV_T getAsciiViewer(in IDREF_T id
		, out tbrAsciiViewerI viewer);
STAFCV_T newAsciiViewer(in string name);

STAFCV_T deleteMotifViewer(in string name);
STAFCV_T findMotifViewer(in IDREF_T id
		, out tbrMotifViewerI viewer);
STAFCV_T getMotifViewer(in string name
		, out tbrMotifViewerI viewer);
STAFCV_T newMotifViewer(in string name);

};
