/*  dst_bfc_status.idl        */
/*  Table: dst_bfc_status     */

/*  This table contains information (per event) on makers which 
 *  either set a warning (kStWarn) or error (kStErr) flag. One
 *  entry per failed maker. Could be empty.
 */

 struct dst_bfc_status  {
  char   maker_name[12];    /* Truncated maker name            */
  long   status;            /* Status number (warning,error)   */
 } ;
/*  Last mod. for dst_bfc_status:   $Date: 2000/05/25 20:01:16 $ */

