/*    $Id: gstar_readtab.idl,v 1.1 1998/05/12 01:13:06 nevski Exp $
      $Log: gstar_readtab.idl,v $
      Revision 1.1  1998/05/12 01:13:06  nevski
      new user inputs - mm and staf

      Fake module to make proper includes
*/
#include "PAM.idl"
#include "particle.idl"
#include "eg_gener.idl"
#include "eg_event.idl"
#include "eg_track.idl"
#include "eg_vertex.idl"

interface gstar_readtab : amiModule  { STAFCV_T call (in particle p); };
