/*
 * \class fgtEvDisFrame
 * \author S. Gliske, Jan 2012 (sgliske@anl.gov)
 *
 * Provides a GUI interface to step through event display histograms,
 * as generated by the macro fgtSingleEvents.C
 * 
 */


#include  <TGClient.h>
#include  <TCanvas.h>
#include  <TF1.h>
#include  <TRandom.h>
#include  <TGButton.h>
#include  <TGFrame.h>
#include  <TRootEmbeddedCanvas.h>
#include  <RQ_OBJECT.h>

class fgtEvDisFrame {
    RQ_OBJECT("fgtEvDisFrame")
private:
   enum { kEvent, kTimeBin, kDisc, kQuad, kNum = 4 };

   TGMainFrame         *mMain;
   TRootEmbeddedCanvas *mEcanvas;

   TGLayoutHints       *mLayHintMain, *mLayHintPlot, *mLayHintOptions, *mLayHintNum;
   TGLayoutHints       *mLayHintButton, *mLayHintRad;

   // frames
   TGHorizontalFrame   *mMainHortzFrame;
   TGVerticalFrame     *mOptFrame;
   TGVerticalFrame     *mNumFrame;
   TGHorizontalFrame   *mNumFrameInner[kNum];
   TGHorizontalFrame   *mButtonFrame;

   // numbers
   TGNumberEntry       *mNumEntry[kNum];
   TGLabel             *mNumLabel[kNum];
   TGGroupFrame        *mRadioFrame;
   TGRadioButton       *mRad1, *mRad2;

   // buttons
   TGTextButton        *mDrawButton;
   TGTextButton        *mExitButton;

   // message bar
   TGCompositeFrame    *mMessFrame;
   TGLabel             *mMessLabel;

   // for interfacing plots
   std::string         mLastName;
   std::stringstream   mSS;

   // for opening the histograms
   TFile *mTFile;
   TH2F *hPlast, *hRlast;


public:
   // constructor & deconstructor
   fgtEvDisFrame( const TGWindow *p,UInt_t w,UInt_t h, const Char_t *filename );
   virtual ~fgtEvDisFrame();

   // the real "action" functions
   void DoDraw();
   void HandleButtons();
   void GetHists( const std::string& name, TH2F* &hP, TH2F* &hR );
};

// initialize numbers
Int_t numinit[] = { 0, 2, 0, 0, 0 };
const Char_t *numlabel[50] = { "Event", "Time Bin", "Disc", "Quad", "Side" };

fgtEvDisFrame::fgtEvDisFrame(const TGWindow *p,UInt_t w,UInt_t h, const Char_t *filename ) 
   : hPlast(0), hRlast(0) {

   mTFile = new TFile( filename, "READ" );
   if( !mTFile || !mTFile->IsOpen() ){
      cerr << "ERROR opening file '" << filename << "'" << endl;
      return;
   };

   // style
   gROOT->SetStyle("Plain");

   // Create a main frame
   mMain = new TGMainFrame(p,w,h);

   // Make a hortz frame to divide in half
   mMainHortzFrame = new TGHorizontalFrame(mMain, 1000, 2000);
   mLayHintMain = new TGLayoutHints(kLHintsCenterY|kLHintsCenterX|kLHintsTop|kLHintsLeft|kLHintsExpandX|kLHintsExpandY,10,10,10,1);
   mMain->AddFrame( mMainHortzFrame, mLayHintMain );
 
   // Create canvas widget
   mEcanvas = new TRootEmbeddedCanvas("Ecanvas",mMainHortzFrame,700,600);

   // divide the canvas
   gStyle->SetOptStat(0);
   TCanvas *canPtr = mEcanvas->GetCanvas();
   canPtr->SetBorderSize(0);
   canPtr->Divide(2,1);
   canPtr->cd(1);
   gPad->SetBorderMode(0);
   gPad->SetTopMargin(0.01);
   gPad->SetRightMargin(0.16);
   gPad->SetLeftMargin(0.1);
   canPtr->cd(2);
   gPad->SetBorderMode(0);
   gPad->SetTopMargin(0.01);
   gPad->SetRightMargin(0.16);
   gPad->SetLeftMargin(0.15);

   // add the canvas with layout hints
   mLayHintPlot = new TGLayoutHints(kLHintsTop|kLHintsLeft|kLHintsExpandX|kLHintsExpandY,10,10,10,10);
   mMainHortzFrame->AddFrame(mEcanvas, mLayHintPlot);


   // now a frame for all the options
   mOptFrame = new TGVerticalFrame( mMainHortzFrame, 50, 50 );
   mLayHintOptions = new TGLayoutHints(kLHintsTop|kLHintsRight|kLHintsExpandY,10,10,10,10);
   mMainHortzFrame->AddFrame(mOptFrame, mLayHintOptions );

   // number entries
   mNumFrame = new TGVerticalFrame(mOptFrame, 200, 300);
   mLayHintNums = new TGLayoutHints(kLHintsCenterY|kLHintsExpandX, 2, 2, 2, 2);
   mOptFrame->AddFrame(mNumFrame, mLayHintNums );

   for( Int_t i = 0; i < kNum; ++i ){
      // frame
      mNumFrameInner[i] = new TGHorizontalFrame(mNumFrame, 200, 30);
      mNumFrame->AddFrame(mNumFrameInner[i], mLayHintNums);

      // label
      mNumLabel[i] = new TGLabel(mNumFrameInner[i], numlabel[i] );
      mNumFrameInner[i]->AddFrame(mNumLabel[i], mLayHintNums);

      // number entry
      mNumEntry[i] = new TGNumberEntry(mNumFrameInner[i], numinit[i], 12, i + 20,(TGNumberFormat::EStyle) 0);
      mNumFrameInner[i]->AddFrame(mNumEntry[i], mLayHintNums);

      // set to signal draw
      mNumEntry[i]->Connect("ValueSet(Long_t)","fgtEvDisFrame",this,"DoDraw()");
   };

   mNumEntry[kEvent]  ->SetLimits(TGNumberFormat::kNELLimitMin,    0, 100 );
   mNumEntry[kTimeBin]->SetLimits(TGNumberFormat::kNELLimitMinMax, 0, 4 );
   mNumEntry[kDisc]   ->SetLimits(TGNumberFormat::kNELLimitMinMax, 0, 5 );
   mNumEntry[kQuad]   ->SetLimits(TGNumberFormat::kNELLimitMinMax, 0, 3 );

   // Create a horizontal frame widget with buttons
   mButtonFrame = new TGHorizontalFrame(mOptFrame,200,40);
   mDrawButton = new TGTextButton(mButtonFrame,"&Draw");
   mDrawButton->Connect("Clicked()","fgtEvDisFrame",this,"DoDraw()");
   mButtonFrame->AddFrame(mDrawButton, new TGLayoutHints(kLHintsCenterX,5,5,3,4));

   mExitButton = new TGTextButton(mButtonFrame,"&Exit","gApplication->Terminate(0)");
   mButtonFrame->AddFrame(mExitButton, new TGLayoutHints(kLHintsCenterX,5,5,3,4));
   mOptFrame->AddFrame( mButtonFrame,  new TGLayoutHints(kLHintsCenterX,5,5,3,4));

   // message
   mMessFrame = new TGCompositeFrame( mOptFrame, 100, 100, kSunkenFrame);
   mOptFrame->AddFrame( mMessFrame,  new TGLayoutHints(kLHintsLeft|kLHintsLeft|kLHintsExpandX,3,3,3,3) );
   mMessLabel = new TGLabel( mMessFrame, "initializing the class" );
   mMessLabel->SetTextJustify( kTextCenterY|kTextLeft );
   mMessFrame->AddFrame( mMessLabel, new TGLayoutHints( kLHintsTop|kLHintsExpandX, 2,2,2,2 ));

   mRadioFrame = new TGGroupFrame( mNumFrame, "Octant" );
   mNumFrame->AddFrame( mRadioFrame, mLayHintNums );

   mRad1 = new TGRadioButton(mRadioFrame, "&Long Side", 81);
   mRad2 = new TGRadioButton(mRadioFrame, "&Short Side", 82);
   mRad1->SetState(kButtonDown);
   mRad2->SetState(kButtonUp);

   mLayHintRad = new TGLayoutHints( kLHintsCenterX, 2,2,2,2 );
   mRadioFrame->AddFrame( mRad1, mLayHintRad );
   mRadioFrame->AddFrame( mRad2, mLayHintRad );
   mRad1->Connect("Clicked()", "fgtEvDisFrame", this, "HandleButtons()");
   mRad2->Connect("Clicked()", "fgtEvDisFrame", this, "HandleButtons()");


  // Set a name to the main frame
  mMain->SetWindowName("Offline FGT Event Display");
  // Map all subwindows of main frame
//   mButtonFrame->MapWindow();
//   mNumFrame->MapSubwindows();
//   mOptFrame->MapSubwindows();
//   mMainHortzFrame->MapSubwindows();
  mMain->MapSubwindows();

  // Initialize the layout algorithm
  mMain->Resize(mMain->GetDefaultSize());

  cout << "Mapping main window" << endl;  
  // Map main frame
  mMain->MapWindow();

  // Draw the first
  DoDraw();
}

void fgtEvDisFrame::DoDraw() {
  TCanvas *canPtr = mEcanvas->GetCanvas();

  mSS.str("");
  mSS.clear();
  mSS << "h"
      << "_e" << mNumEntry[kEvent]->GetIntNumber()
      << "_t" << mNumEntry[kTimeBin]->GetIntNumber()
      << "_d" << mNumEntry[kDisc]->GetIntNumber()
      << "_q" << mNumEntry[kQuad]->GetIntNumber()
      << ( mRad1->GetState() ? 'L' : 'S' );
  std::string name = mSS.str();

  if( name != mLastName ){
     mMessLabel->SetText( "drawing" );

     TH2F *hP = 0, *hR = 0;
     GetHists( name, hP, hR );

     if( hP && hR ){
        gStyle->SetPalette(1);
        hP->GetYaxis()->SetBinLabel( 1, "inner" );
        hP->GetYaxis()->SetBinLabel( 2, "outer" );

        canPtr->cd(1);
        hP->GetYaxis()->SetLabelSize(0.06);
        hP->GetXaxis()->SetTitle("strip number");
        hP->SetTitle("#phi Strips");
        hP->SetMinimum( -500 );
        hP->SetMaximum( 1500 );
        hP->Draw("COLZ");
        FixTitle();

        canPtr->cd(2);
        hR->SetTitle("Radial Strips");
        hR->GetXaxis()->SetBinLabel( 1, "#phi in [0,#pi/4]" );
        hR->GetYaxis()->CenterTitle();
        hR->GetYaxis()->SetTitleOffset(1.5);
        hR->GetYaxis()->SetTitle("strip number");
        hR->GetXaxis()->SetLabelSize(0.06);
        hR->SetMinimum( -500 );
        hR->SetMaximum( 1500 );
        hR->Draw("COLZ");
        FixTitle();
        canPtr->Update();

        mSS.str("");
        mSS.clear();
        mSS << "Drew "
            << "e" << mNumEntry[kEvent]->GetIntNumber()
            << " t" << mNumEntry[kTimeBin]->GetIntNumber()
            << " d" << mNumEntry[kDisc]->GetIntNumber()
            << " q" << mNumEntry[kQuad]->GetIntNumber()
            << ' ' << ( mRad1->GetState() ? 'L' : 'S' );

        mMessLabel->SetText( mSS.str().data() );
        hPlast = hP;
        hRlast = hR;
     } else {
//         canPtr->cd(1);
//         gPad->GetListOfPrimitives()->RemoveAll();
//         canPtr->cd(2);
//         gPad->GetListOfPrimitives()->RemoveAll();
        canPtr->Clear();
        canPtr->Divide(2,1);
        canPtr->Update();

        mSS.str("");
        mSS.clear();
        mSS << "Error with "
            << "e" << mNumEntry[kEvent]->GetIntNumber()
            << " t" << mNumEntry[kTimeBin]->GetIntNumber()
            << " d" << mNumEntry[kDisc]->GetIntNumber()
            << " q" << mNumEntry[kQuad]->GetIntNumber()
            << ' ' << ( mRad1->GetState() ? 'L' : 'S' );

        mMessLabel->SetText( mSS.str().data() );
     };
  };
  mLastName = name;
};

fgtEvDisFrame::~fgtEvDisFrame() {
  // Clean up used widgets: frames, buttons, layouthints
  mMain->Cleanup();
  delete mMain;
}

void fgtEvDisFrame::HandleButtons(){
   // Handle different buttons.

   Int_t id = -1;
   if (id == -1) {
      TGButton *btn = (TGButton *) gTQSender;
      id = btn->WidgetId();
   }

   switch (id) {
   case 81:
      mRad2->SetState(kButtonUp);
      DoDraw();
      break;
   case 82:
      mRad1->SetState(kButtonUp);
      DoDraw();
      break;
   };
};


void fgtEvDisFrame::FixTitle(){
   gPad->Update();
   gPad->Modified();

   TPaveText *title = (TPaveText*)(gPad->GetPrimitive("title"));
   if( title ){
      title->SetX1NDC( 0.045 );
      title->SetX2NDC( 0.55 );
      title->SetY1NDC( 0.91 ) ;
      title->SetY2NDC( 0.999 );
      title->SetBorderSize(0);
      title->SetTextAlign( 12 );
      title->SetTextColor(kBlue);
      title->Draw();
   };
};

void fgtEvDisFrame::GetHists( const std::string& name, TH2F* &hP, TH2F* &hR ){
//    TH2F *hP = new TH2F( "hP", "",   360, 0, 360, 2, 0, 2 );
//    TH2F *hR = new TH2F( "hR", "", 1, 0, 0.7854, 280, 0, 280 ); // phi range diff
//    hP->Fill( 180, 0.1, 100 );
//    hP->Fill( 181, 0.1, 500 );
//    hP->Fill( 181, 1.1, 500 );
//    hP->Fill( 182, 0.1, 100 );
//    hR->Fill( 0.1, 180, 100 );
//    hR->Fill( 0.1, 181, 500 );
//    hR->Fill( 0.1, 182, 100 );

   hP = (TH2F*)mTFile->Get( (name + "_P").data() );
   hR = (TH2F*)mTFile->Get( (name + "_R").data() );
};

void fgtOfflineEventDisplay( const Char_t *filename ) {
   // Popup the GUI...
   new fgtEvDisFrame(gClient->GetRoot(),2000,2000, filename );
};

/*
 * $Id: fgtOfflineEventDisplay.C,v 1.1 2012/01/31 09:26:18 sgliske Exp $
 * $Log: fgtOfflineEventDisplay.C,v $
 * Revision 1.1  2012/01/31 09:26:18  sgliske
 * StFgtQaMakers moved to StFgtPool
 *
 * Revision 1.1  2012/01/24 06:30:46  sgliske
 * creation
 *
 */

