/*
*********************************************************
* Table:       controlADCtoE.idl
* Description: define keys for managing StEmcADCtoEMaker
* Author     : Aleksei Pavlinov, WSU 
*********************************************************
*/
struct  controlADCtoE
{
    short DeductPedestal[8];    /* switch for deducting pedestal */
    short Calibration[8];       /* switch for calibration */    
    float CutOff[8];            /* cutoff value for hits close to pedestal. -1 = none */
    short CutOffType[8];        /* cutoff type (0=energy, 1=pedestal RMS) */
    short OnlyCalibrated[8];    /* save only calibrated hits */
    short messLimit;            /* limit for warning message */
};
