/*  tfs_g2t.idl
*
*   Module: tfs_g2t
*         description: TPC fast simulator
*/

#include "PAM.idl"
#include "g2t_tpc_hit.idl"
#include "g2t_track.idl"
#include "tfs_fspar.idl"
#include "tfs_bmpar.idl"
#include "tfs_fsctrl.idl"
#include "tcl_tpc_index.idl"
#include "tcl_tpc_index_type.idl"
#include "tcl_tphit.idl"

interface tfs_g2t : amiModule {
        STAFCV_T call
                ( in    g2t_tpc_hit g2t_hit
                , in    g2t_track g2t_track
                , in    tfs_fspar par
                , in    tfs_bmpar bmpar
                , in    tfs_fsctrl ctrl
                , out   tcl_tpc_index tpc_index
                , in    tcl_tpc_index_type tpc_index_type
                , out   tcl_tphit tphit
                );
};
/* Last mod. for tfs_g2t: $Date: 1998/04/24 22:27:28 $ */
