/*  tfs_fill_tphit_pad_tmbk.idl
*
*   Module: tfs_fill_tphit_pad_tmbk
*         description: simulate the pad and time 
* 	               bucket information for tfs hit
*/

#include "PAM.idl"
#include "tpg_pad_plane.idl"
#include "tcl_tphit.idl"

interface tfs_fill_tphit_pad_tmbk : amiModule {
        STAFCV_T call (
                  in      tpg_pad_plane pad_plane
                , inout   tcl_tphit tphit
                );
};
