      INTEGER kUnknownId,kTpcId,kSvtId,kRichId,kFtpcWestId,kFtpcEastId
      INTEGER kTofPatchId,kCtbId,kSsdId,kBarrelEmcTowerId
      INTEGER kBarrelEmcPreShowerId,kBarrelSmdEtaStripId
      INTEGER kEndcapEmcTowerId,kEndcapEmcPreShowerId,kSsdId
      INTEGER kBarrelSmdPhiStripId,kZdcWestId,kZdcEastId
      INTEGER kEndcapSmdEtaStripId,kEndcapSmdPhiStripId,kMwpcWestId,kMwpcEastId
      INTEGER kTpcSvtId,kTpcSsdId,kTpcSsdsvtId,kSsdSvtId 

#include "StDetectorDefinitions.h"
      PARAMETER (kUnknownId = kUnknownIdentifier)
      PARAMETER (kTpcId = kTpcIdentifier)
      PARAMETER (kSvtId = kSvtIdentifier)
      PARAMETER (kRichId = kRichIdentifier)
      PARAMETER (kFtpcWestId = kFtpcWestIdentifier)
      PARAMETER (kFtpcEastId = kFtpcEastIdentifier)
      PARAMETER (kTofPatchId = kTofPatchIdentifier)
      PARAMETER (kCtbId = kCtbIdentifier)
      PARAMETER (kSsdId = kSsdIdentifier)
      PARAMETER (kBarrelEmcTowerId = kBarrelEmcTowerIdentifier)
      PARAMETER (kBarrelEmcPreShowerId = kBarrelEmcPreShowerIdentifier)
      PARAMETER (kBarrelSmdEtaStripId = kBarrelSmdEtaStripIdentifier)
      PARAMETER (kBarrelSmdPhiStripId = kBarrelSmdPhiStripIdentifier)
      PARAMETER (kEndcapEmcTowerId = kEndcapEmcTowerIdentifier)
      PARAMETER (kEndcapEmcPreShowerId = kEndcapEmcPreShowerIdentifier)
      PARAMETER (kEndcapSmdEtaStripId = kEndcapSmdEtaStripIdentifier)
      PARAMETER (kEndcapSmdPhiStripId = kEndcapSmdPhiStripIdentifier)
      PARAMETER (kZdcWestId = kZdcWestIdentifier)
      PARAMETER (kZdcEastId = kZdcEastIdentifier)
      PARAMETER (kMwpcWestId = kMwpcWestIdentifier)
      PARAMETER (kMwpcEastId = kMwpcEastIdentifier)
      PARAMETER (kTpcSsdId    = kTpcSsdIdentifier)
      PARAMETER (kTpcSvtId    = kTpcSvtIdentifier)
      PARAMETER (kTpcSsdSvtId = kTpcSsdSvtIdentifier)
      PARAMETER (kSsdSvtId    = kSsdSvtIdentifier)








