      INTEGER  kUndefinedMethodId,kTruncatedMeanId
      INTEGER  kEnsembleTruncatedMeanId,kLikelihoodFitId
      INTEGER  kWeightedTruncatedMeanId,kOtherMethodId  
#include "StDedxDefinitions.h"        
      PARAMETER (kUndefinedMethodId = kUndefinedMethodIdentifier)
      PARAMETER (kTruncatedMeanId = kTruncatedMeanIdentifier)
      PARAMETER (kEnsembleTruncatedMeanId = 
     +           kEnsembleTruncatedMeanIdentifier) 
      PARAMETER (kLikelihoodFitId = kLikelihoodFitIdentifier)
      PARAMETER (kWeightedTruncatedMeanId = 
     +           kWeightedTruncatedMeanIdentifier)
      PARAMETER (kOtherMethodId = kOtherMethodIdentifier)
