      INTEGER  kUndefinedFinderId,kSvtGrouperId
      INTEGER  kSvtStkId,kTpcStandardId
      INTEGER  kSvtTpcSvmId,kSvtTpcEstId
      INTEGER  kUndefinedQualityId,kGrouperPassId
      INTEGER  kStkPassId,kSvmPassId,kEstPassId
      INTEGER  kUndefinedFitterId,kHelix2StepId
      INTEGER  kHelix3DId,kKalmanFitId
      INTEGER  kLine2StepId,kLine3DId

#include "StDedxDefinitions.h" 
      PARAMETER (kUndefinedFinderId = kUndefinedFinderIdentifier)
      PARAMETER (kSvtGrouperId = kSvtGrouperIdentifier)
      PARAMETER (kSvtStkId =  kSvtStkIdentifier)
      PARAMETER (kTpcStandardId = kTpcStandardIdentifier)
      PARAMETER (kSvtTpcSvmId = kSvtTpcSvmIdentifier)
      PARAMETER (kSvtTpcEstId = kSvtTpcEstIdentifier)
      PARAMETER (kUndefinedQualityId = 
     +           kUndefinedQualityIdentifier)
      PARAMETER (kGrouperPassId = kGrouperPassIdentifier)
      PARAMETER (kStkPassId = kStkPassIdentifier)
      PARAMETER (kSvmPassId = kSvmPassIdentifier)
      PARAMETER (kEstPassId = kEstPassIdentifier
      PARAMETER (kUndefinedFitterId = kUndefinedFitterIdentifier)
      PARAMETER (kHelix2StepId = kHelix2StepIdentifier)
      PARAMETER (kHelix3DId = kHelix3DIdentifier)
      PARAMETER (kKalmanFitId = kKalmanFitIdentifier)
      PARAMETER (kLine2StepId = kLine2StepIdentifier)
      PARAMETER (kLine3DId = kLine3DIdentifier)
