/* emc_part_id.idl		K.Shestermanov 08/20/99 */

#include "PAM.idl"
#include "emc_cluster.idl"
#include "emc_cluster_index.idl"
#include "emc_hits.idl"
#include "ems_control.idl"
#include "emc_part_id_par.idl"
#include "calb_calg.idl"
#include "calb_calr.idl"
#include "dst_track.idl"
#include "emc_gam.idl"
#include "emc_elect.idl"

interface emc_part_id : amiModule {
	STAFCV_T call
        ( in emc_cluster emc_cluster
        , in emc_cluster_index emc_cluster_index
        , in emc_hits emc_hits_bsmde
        , in emc_hits emc_hits_bsmdp
        , in ems_control ems_control
        , in emc_part_id_par emc_part_id_par
        , in calb_calg calb_calg
        , in calb_calr calb_calr
        , in dst_track dst_track
        , out emc_gam emc_gam
        , out emc_elect emc_elect
	);
};











