/* emc_pi_zero.idl		K.Shestermanov 08/20/99 */

#include "PAM.idl"
#include "emc_gam.idl"
#include "ems_control.idl"
#include "emc_part_id_par.idl"
#include "emc_pizero.idl"

interface emc_pi_zero : amiModule {
	STAFCV_T call
        ( in emc_gam emc_gam
        , in ems_control ems_control
        , in emc_part_id_par emc_part_id_par
        , out emc_pizero emc_pizero
	);
};











