/* emc_cl_finder.idl		K.Shestermanov 08/20/99 */

#include "PAM.idl"
#include "emc_energy.idl"
#include "ems_control.idl"
#include "emc_cluster_par.idl"
#include "calb_calg.idl"
#include "calb_calr.idl"
#include "emc_cluster.idl"
#include "emc_cluster_index.idl"

interface emc_cl_finder : amiModule {
	STAFCV_T call
        ( in emc_energy emc_energy
        , in ems_control ems_control
        , in emc_cluster_par emc_cluster_par
        , in calb_calg calb_calg
        , in calb_calr calb_calr
        , out emc_cluster emc_cluster
        , out emc_cluster_index emc_cluster_index
	);
};











