/* emc_egrid.idl		OGAWA, Akio */

#include "PAM.idl"
#include "emc_hits.idl"
#include "dst_track.idl"
#include "ems_control.idl"
#include "emc_egrid_par.idl"
#include "emc_energy.idl"

interface emc_egrid : amiModule {
	STAFCV_T call
        ( in emc_hits  emc_hits_bemc
        , in emc_hits  emc_hits_eemc
        , in dst_track   dst_track
        , in ems_control ems_control
        , in emc_egrid_par emc_egrid_par
        , out emc_energy emc_energy
	);
};
