#!/usr/local/bin/perl
use Env;
Import qw ( env INCLUDE LIB BIN OBJ );
$pwd = DirPath '.';
#my @list = find ($pwd);
#print "list = ",@list,"\n";
my $PKG  = basename($pwd); print "Run cons for ",$PKG,"\n";
#for my $dir (@paths) { print $dir::cwd->lookupdir($pwd)->{srcdir},"\n";}
my $SO_PKG = $PKG . ".so";
my $CPPFLAGS = cppflags();
#scan::cpp::iflags(); print "IFLAGS = ",$IFLAGS," iflags = ",$iflags,"\n";
my @CintFiles = ($PKG . "_Cint.cxx", $PKG . "_Cint.h", $PKG . "_LinkDef.h");
my @Defs = find_files_by_extention("*.h*");
Command $env [@CintFiles], @Defs,  qq( RootCint.pl "%>" "%<" "$CPPFLAGS" );
my @src = find_files_by_extention("*.c*");
@src[$#src] = $CintFiles[0]; 
LinkedModule $env $SO_PKG, @src;
Install $env $LIB, $SO_PKG;
