/* stk_am_fit.idl
*  Module: stk_am_fit
*  	description: svt track fitting module for real (imperfect) tracks
*/

#include "PAM.idl"
#include "stk_stkpar.idl"
#include "scs_spt.idl"
#include "stk_vtx.idl"
#include "sgr_groups.idl"
#include "stk_track.idl"

interface stk_am_fit : amiModule {
	STAFCV_T call
		( in    stk_stkpar      stkpar
		, in    scs_spt         spt
		, in    stk_vtx		vtx
                , inout sgr_groups      groups
		, inout stk_track       track
		);
	};
/* Last mod. for  stk_am_fit: $Date: 1997/12/31 14:33:37 $ */


