/* stk_am_direct.idl
*  Module: stk_am_direct
*  	description: fill perfect tracks (all hits correct)
*/

#include "PAM.idl"
#include "g2t_track.idl"
#include "scs_spt.idl"
#include "stk_track.idl"
#include "sgr_groups.idl"
#include "svg_geom.idl"

interface stk_am_direct : amiModule {
	STAFCV_T call
		( in    g2t_track       g2t_track
		, in    scs_spt         spt
                , inout sgr_groups      mcgroups
                , inout stk_track       mctrack
		, in    svg_geom        geom
		);
	};
/* Last mod. for  stk_am_direct: $Date: 1997/12/31 14:33:37 $ */

