/* stk_am_kine.idl
*  Module: stk_am_kine
*  	description: calculates kine parameters for real (imperfect) tracks
*/

#include "PAM.idl"
#include "sgr_groups.idl"
#include "stk_vtx.idl"
#include "stk_track.idl"
#include "stk_kine.idl"

interface stk_am_kine : amiModule {
	STAFCV_T call
		( in    stk_vtx		vtx
                  inout sgr_groups     groups
		, in    stk_track       track
		, out   stk_kine        kine 
		);
	};
/* Last mod. for  stk_am_kine: Wed Aug 20 10:49:18 EDT 1997 */
