/* stk_am_helix.idl
*  Module: stk_am_helix
*  	description: calculate kine observables according to helix parameters
*/
#include "PAM.idl"
#include "g2t_track.idl"
#include "scs_spt.idl"
#include "stk_vtx.idl"
#include "stk_ctrack.idl"
#include "g2t_gepart.idl"
#include "stk_hlx.idl"

interface stk_am_helix : amiModule {
	STAFCV_T call
		( inout g2t_track       g2t_track
		, inout scs_spt         spt
		, inout stk_vtx		vtx
		, inout stk_ctrack      ctrack
		, in    g2t_gepart      g2t_gepart
		, in    stk_hlx         hlx
		);
	};
/* Last mod. for  stk_am_helix: $Date: 1997/12/31 14:33:38 $ */
