/* stk_am_fill4.idl
*  Module: stk_am_fill4
*  	description: current version of track filling code for four layers
*/

#include "PAM.idl"
#include "scs_spt.idl"
#include "stk_vtx.idl"
#include "sgr_groups.idl"
#include "stk_track.idl"
#include "stk_filler.idl"
#include "svg_config.idl"
#include "svg_geom.idl"

interface stk_am_fill4 : amiModule {
	STAFCV_T call
		( in    scs_spt         spt
		, in    stk_vtx		vtx
                , inout sgr_groups      groups
                , inout stk_track       track
		, inout stk_filler      filler
		, inout svg_config      config
		, inout svg_geom        geom
		);
	};
/* Last mod. for  stk_am_fill4: Wed Aug 20 10:49:18 EDT 1997 */






