/* Last mod. for g2t: $Date: 1999/10/20 18:30:29 $ */

/*          g2t_get_event.idl
*           Module: g2t_get_event
*/
#include "PAM.idl"
#include "g2t_event.idl"
interface g2t_get_event: amiModule {STAFCV_T call(out g2t_event g2t_event); };




