#!/usr/bin/env perl
Import qw ( env INCLUDE LIB BIN BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
$build =~ s/\\/\//g;
(my $obj_dir = DirPath '.') =~ s/\\/\//g;
(my $Dir = $obj_dir) =~ s/$build\///g;
my $ObjDir = "#" . $obj_dir; 
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $pkg = "g2Root";
my $PKG  = $pkg . $env->{SUFEXE};
my $SO_PKG = $PKG . "." . $env->{SUFSOLIB};
my $LIBPKG = $PKG . "." . $env->{SUFLIB};
my @h_files = script::find_hfiles($Dir);

my $FC       = $env->{FC};
my $FCPATH   = $env->{FCPATH};
my $FFLAGS   = $env->{FFLAGS};
my $FPPFLAGS = $env->{FPPFLAGS};
my $CPPFLAGS = $env->{CPPFLAGS};
my $FLIBS    = $env->{FLIBS};
my $PGI      = $env->{ENV}->{PGI};
my $PGILIBS  = "";
my $CLIBS    = $env->{CLIBS};

my $FC       = $env->{FC};
my $FEXTEND  = $env->{FEXTEND};
my $LD       = $env->{LD};
my $LDFLAGS  = $env->{F77LDFLAGS};
my $CERNLIBS = $env->{CERNLIBS};


if ($FC eq 'pgf77') { 
  $FC       = $env->{G77}; 
  $FFLAGS   = $env->{G77FLAGS}; 
  $FEXTEND  = $env->{G77EXTEND};
  print "set FC => $FC ==============================\n" if $param::debug;
}

# Get ld def
my $LD        = $env->{LD}; 
if ($LD eq $env->{CC} or $LD eq $env->{CXX}) {
    $LD = $FC;
}
$LDFLAGS .= " -lstdc++";

print "build $pkg with cons LDFLAGS now = $LDFLAGS\n";



#if ($LD eq 'gcc') {$LDFLAGS = "-Wl,-Bstatic";}
my $Libraries = $CERNLIBS .  " " . $FLIBS . " " . $CLIBS;

#if ($FC eq 'g77' || $FC eq 'gfortran') { 
#  if ($env->{CXX_VERSION} == 3) {$Libraries .= " -lfrtbegin";}
#  $Libraries .= " " . $env->{LIBG2C};
#}

if ($FC =~ m/g77/ || $FC =~ m/gfortran/) { 
    $Libraries .= " ".$env->{FLIBS};
}


#if ($FC eq 'ifort') { 
#  my $LIBIFCPATH    = `which ifort | sed -e 's|bin/ifort|lib|'`; chomp($LIBIFCPATH);
#  $Libraries .= " " . $LIBIFCPATH . "/for_main.o"; 
#}
$env2 = $env->clone('FC'           => $FC,
		    'LD'           => $LD,
		    'LDFLAGS'      => $LDFLAGS,
		    'FPPFLAGS'     => '',
		    'FFLAGS'       => $FFLAGS,
		    'FCPATH'       => '',
		    'FEXTEND'      => "",
		    'CPPFLAGS'     => $CPPFLAGS,
		    'ObjDir'       => $obj_dir,
		    'Libraries'    => $Libraries
		   );
my @srcc = script::find_sources($Dir);# print "src = @srcc\n";
my @src = ();
foreach my $s (@srcc) {
  next if $s =~ /^cmt/;
  push @src, $s;
}
if ($#src > -1) {
  script::Keep $pkg;
  Program      $env2 $pkg, @src;
  Install $env2 $BIN, $pkg;
}  
