/********************************************************************
* BaseDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BaseDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableBaseDict();
extern void G__cpp_setup_inheritanceBaseDict();
extern void G__cpp_setup_typetableBaseDict();
extern void G__cpp_setup_memvarBaseDict();
extern void G__cpp_setup_globalBaseDict();
extern void G__cpp_setup_memfuncBaseDict();
extern void G__cpp_setup_funcBaseDict();
extern void G__set_cpp_environmentBaseDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "StjBEMC.h"
#include "StjBEMCNull.h"
#include "StjBEMCTree.h"
#include "StjBEMCTxt.h"
#include "StjDijetCut.h"
#include "StjDijetCutAsymmetricPt.h"
#include "StjDijetCutDPhi.h"
#include "StjDijetCutEta.h"
#include "StjDijetCutEta3MinusEta4.h"
#include "StjDijetCutTrgBHT.h"
#include "StjDijetCutTrgBJP.h"
#include "StjDijetList.h"
#include "StjDijetListCut.h"
#include "StjDijetPrint.h"
#include "StjEEMC.h"
#include "StjEEMCNull.h"
#include "StjEEMCTxt.h"
#include "StjFormDijet.h"
#include "StjFourVecCut.h"
#include "StjFourVecCutPt.h"
#include "StjFourVecCutTrgBHT.h"
#include "StjFourVecCutTrgBJP.h"
#include "StjFourVecList.h"
#include "StjFourVecListCut.h"
#include "StjFourVecPrint.h"
#include "StjJetCut.h"
#include "StjJetCutDetectorEta.h"
#include "StjJetCutEta.h"
#include "StjJetCutNFourVecs.h"
#include "StjJetCutPt.h"
#include "StjJetCutTrgBHT.h"
#include "StjJetCutTrgBJP.h"
#include "StjJetList.h"
#include "StjJetListCut.h"
#include "StjJetPrint.h"
#include "StjMC.h"
#include "StjMCNull.h"
#include "StjMCParticleCut.h"
#include "StjMCParticleCutEta.h"
#include "StjMCParticleCutEtaForStatus.h"
#include "StjMCParticleCutStatus.h"
#include "StjMCParticleList.h"
#include "StjMCParticleListCut.h"
#include "StjMCParticleListToFourVecList.h"
#include "StjMCParticlePrint.h"
#include "StjMCParticleToFourVec.h"
#include "StjMCTree.h"
#include "StjTPC.h"
#include "StjTPCNull.h"
#include "StjTPCTree.h"
#include "StjTPCTxt.h"
#include "StjTowerEnergyCorrectionForTracks.h"
#include "StjTowerEnergyCut.h"
#include "StjTowerEnergyCut2003BemcTower.h"
#include "StjTowerEnergyCutAdc.h"
#include "StjTowerEnergyCutBemcStatus.h"
#include "StjTowerEnergyCutBemcWestOnly.h"
#include "StjTowerEnergyCutEnergy.h"
#include "StjTowerEnergyCutEt.h"
#include "StjTowerEnergyList.h"
#include "StjTowerEnergyListCut.h"
#include "StjTowerEnergyListVariation.h"
#include "StjTowerEnergyPrint.h"
#include "StjTowerEnergyToFourVec.h"
#include "StjTowerEnergyToTLorentzVector.h"
#include "StjTowerEnergyVariation.h"
#include "StjTowerEnergyVariationEnergy.h"
#include "StjTrackCut.h"
#include "StjTrackCutDca.h"
#include "StjTrackCutDcaPtDependent.h"
#include "StjTrackCutEta.h"
#include "StjTrackCutFlag.h"
#include "StjTrackCutNHits.h"
#include "StjTrackCutPossibleHitRatio.h"
#include "StjTrackList.h"
#include "StjTrackListCut.h"
#include "StjTrackPrint.h"
#include "StjTrackToFourVec.h"
#include "StjTrackToTLorentzVector.h"
#include "StjTrackTowerEnergyListToFourVecList.h"
#include "StjDijetListTrigger.h"
#include "StjDijetListTriggerBJP2.h"
#include "StjDijetListTriggerBHT2.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BaseDictLN_TClass;
extern G__linked_taginfo G__BaseDictLN_TBuffer;
extern G__linked_taginfo G__BaseDictLN_TMemberInspector;
extern G__linked_taginfo G__BaseDictLN_TObject;
extern G__linked_taginfo G__BaseDictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BaseDictLN_string;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergy;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjTowerEnergycOallocatorlEStjTowerEnergygRsPgR;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjTowerEnergycOallocatorlEStjTowerEnergygRsPgRcLcLiterator;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjTowerEnergycOallocatorlEStjTowerEnergygRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjBEMC;
extern G__linked_taginfo G__BaseDictLN_StjBEMCNull;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyListReader;
extern G__linked_taginfo G__BaseDictLN_StjBEMCTree;
extern G__linked_taginfo G__BaseDictLN_StjBEMCTxt;
extern G__linked_taginfo G__BaseDictLN_StjFourVec;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjFourVeccOallocatorlEStjFourVecgRsPgR;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjFourVeccOallocatorlEStjFourVecgRsPgRcLcLiterator;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjFourVeccOallocatorlEStjFourVecgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjJet;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjJetcOallocatorlEStjJetgRsPgR;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjJetcOallocatorlEStjJetgRsPgRcLcLiterator;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjJetcOallocatorlEStjJetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjDijet;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjDijetcOallocatorlEStjDijetgRsPgR;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjDijetcOallocatorlEStjDijetgRsPgRcLcLiterator;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjDijetcOallocatorlEStjDijetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjDijetCut;
extern G__linked_taginfo G__BaseDictLN_StjDijetCutAsymmetricPt;
extern G__linked_taginfo G__BaseDictLN_StjDijetCutDPhi;
extern G__linked_taginfo G__BaseDictLN_StjJetCut;
extern G__linked_taginfo G__BaseDictLN_StjJetCutEta;
extern G__linked_taginfo G__BaseDictLN_StjDijetCutEta;
extern G__linked_taginfo G__BaseDictLN_StjDijetCutEta3MinusEta4;
extern G__linked_taginfo G__BaseDictLN_StjFourVecCut;
extern G__linked_taginfo G__BaseDictLN_StjFourVecListCut;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjFourVecCutmUcOallocatorlEStjFourVecCutmUgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjFourVecCutmUcOallocatorlEStjFourVecCutmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjTrg;
extern G__linked_taginfo G__BaseDictLN_StjJetCutTrgBHT;
extern G__linked_taginfo G__BaseDictLN_StjDijetCutTrgBHT;
extern G__linked_taginfo G__BaseDictLN_StjTrgBEMCJetPatchTowerIdMap;
extern G__linked_taginfo G__BaseDictLN_StjJetCutTrgBJP;
extern G__linked_taginfo G__BaseDictLN_StjDijetCutTrgBJP;
extern G__linked_taginfo G__BaseDictLN_StjDijetListCut;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjDijetCutmUcOallocatorlEStjDijetCutmUgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjDijetCutmUcOallocatorlEStjDijetCutmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjDijetPrint;
extern G__linked_taginfo G__BaseDictLN_StjEEMC;
extern G__linked_taginfo G__BaseDictLN_StjEEMCNull;
extern G__linked_taginfo G__BaseDictLN_StjEEMCTxt;
extern G__linked_taginfo G__BaseDictLN_StjFormDijet;
extern G__linked_taginfo G__BaseDictLN_StjFourVecCutPt;
extern G__linked_taginfo G__BaseDictLN_StjFourVecCutTrgBHT;
extern G__linked_taginfo G__BaseDictLN_StjFourVecCutTrgBJP;
extern G__linked_taginfo G__BaseDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjFourVecPrint;
extern G__linked_taginfo G__BaseDictLN_StjJetCutDetectorEta;
extern G__linked_taginfo G__BaseDictLN_StjJetCutNFourVecs;
extern G__linked_taginfo G__BaseDictLN_StjJetCutPt;
extern G__linked_taginfo G__BaseDictLN_StjJetListCut;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjJetCutmUcOallocatorlEStjJetCutmUgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjJetCutmUcOallocatorlEStjJetCutmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjJetPrint;
extern G__linked_taginfo G__BaseDictLN_StjMCParticle;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjMCParticlecOallocatorlEStjMCParticlegRsPgR;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjMCParticlecOallocatorlEStjMCParticlegRsPgRcLcLiterator;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjMCParticlecOallocatorlEStjMCParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjMC;
extern G__linked_taginfo G__BaseDictLN_StjMCNull;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleCut;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleCutEta;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleCutEtaForStatus;
extern G__linked_taginfo G__BaseDictLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleCutStatus;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleListCut;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjMCParticleCutmUcOallocatorlEStjMCParticleCutmUgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjMCParticleCutmUcOallocatorlEStjMCParticleCutmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleListToFourVecList;
extern G__linked_taginfo G__BaseDictLN_StjMCParticlePrint;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleToFourVec;
extern G__linked_taginfo G__BaseDictLN_StjMCParticleListReader;
extern G__linked_taginfo G__BaseDictLN_StjMCTree;
extern G__linked_taginfo G__BaseDictLN_StjTrack;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjTrackcOallocatorlEStjTrackgRsPgR;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjTrackcOallocatorlEStjTrackgRsPgRcLcLiterator;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjTrackcOallocatorlEStjTrackgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjTPC;
extern G__linked_taginfo G__BaseDictLN_StjTPCNull;
extern G__linked_taginfo G__BaseDictLN_StjTrackListReader;
extern G__linked_taginfo G__BaseDictLN_StjTPCTree;
extern G__linked_taginfo G__BaseDictLN_StjTPCTxt;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCorrectionForTracks;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCut;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCut2003BemcTower;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCutAdc;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCutBemcStatus;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCutBemcWestOnly;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCutEnergy;
extern G__linked_taginfo G__BaseDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BaseDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BaseDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BaseDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyCutEt;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyListCut;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjTowerEnergyCutmUcOallocatorlEStjTowerEnergyCutmUgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjTowerEnergyCutmUcOallocatorlEStjTowerEnergyCutmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyVariation;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyListVariation;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjTowerEnergyVariationmUcOallocatorlEStjTowerEnergyVariationmUgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjTowerEnergyVariationmUcOallocatorlEStjTowerEnergyVariationmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyPrint;
extern G__linked_taginfo G__BaseDictLN_TLorentzVector;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyToTLorentzVector;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyToFourVec;
extern G__linked_taginfo G__BaseDictLN_StjTowerEnergyVariationEnergy;
extern G__linked_taginfo G__BaseDictLN_StjTrackCut;
extern G__linked_taginfo G__BaseDictLN_StjTrackCutDca;
extern G__linked_taginfo G__BaseDictLN_StjTrackCutDcaPtDependent;
extern G__linked_taginfo G__BaseDictLN_StjTrackCutEta;
extern G__linked_taginfo G__BaseDictLN_StjTrackCutFlag;
extern G__linked_taginfo G__BaseDictLN_StjTrackCutNHits;
extern G__linked_taginfo G__BaseDictLN_StjTrackCutPossibleHitRatio;
extern G__linked_taginfo G__BaseDictLN_StjTrackListCut;
extern G__linked_taginfo G__BaseDictLN_vectorlEStjTrackCutmUcOallocatorlEStjTrackCutmUgRsPgR;
extern G__linked_taginfo G__BaseDictLN_reverse_iteratorlEvectorlEStjTrackCutmUcOallocatorlEStjTrackCutmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseDictLN_StjTrackPrint;
extern G__linked_taginfo G__BaseDictLN_StjTrackToTLorentzVector;
extern G__linked_taginfo G__BaseDictLN_StjTrackToFourVec;
extern G__linked_taginfo G__BaseDictLN_StjTrackTowerEnergyListToFourVecList;
extern G__linked_taginfo G__BaseDictLN_pairlEvectorlEStjTrackcOallocatorlEStjTrackgRsPgRcOvectorlEStjTowerEnergycOallocatorlEStjTowerEnergygRsPgRsPgR;
extern G__linked_taginfo G__BaseDictLN_StjDijetListTrigger;
extern G__linked_taginfo G__BaseDictLN_StjDijetListTriggerBJP2;
extern G__linked_taginfo G__BaseDictLN_StjDijetListTriggerBHT2;

/* STUB derived class for protected member access */
typedef vector<StjTowerEnergy,allocator<StjTowerEnergy> > G__vectorlEStjTowerEnergycOallocatorlEStjTowerEnergygRsPgR;
typedef vector<StjFourVec,allocator<StjFourVec> > G__vectorlEStjFourVeccOallocatorlEStjFourVecgRsPgR;
typedef vector<StjJet,allocator<StjJet> > G__vectorlEStjJetcOallocatorlEStjJetgRsPgR;
typedef vector<StjDijet,allocator<StjDijet> > G__vectorlEStjDijetcOallocatorlEStjDijetgRsPgR;
typedef vector<StjMCParticle,allocator<StjMCParticle> > G__vectorlEStjMCParticlecOallocatorlEStjMCParticlegRsPgR;
typedef vector<StjTrack,allocator<StjTrack> > G__vectorlEStjTrackcOallocatorlEStjTrackgRsPgR;
