* $Id: helvar.inc,v 1.1.1.1 2004/01/12 23:49:39 potekhin Exp $
* $Log: helvar.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:39  potekhin
*
* Revision 1.1  2001/02/27 10:15:04  nevski
*  first working release
*
*--   helix parameters
      LOGICAL                                           TRAPPED
      REAL            BCONST,XS,YS,ZS,RS,CF,SF,TL,TT,EL
      COMMON /HELVAR/ BCONST,XS,YS,ZS,RS,CF,SF,TL,TT,EL,TRAPPED
*     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
