* $Id: irecflg.inc,v 1.1.1.1 2004/01/12 23:49:39 potekhin Exp $
* $Log: irecflg.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:39  potekhin
*
* Revision 1.1  2001/02/27 10:15:05  nevski
*  first working release
*
*C   - INNER TRACKER reconstruction control
      INTEGER         LU,IPNOW,IPRIN,IPDEB,IGEOM,IHIST,
     1                    IGRAP,ISIMU,IDIGI,IANAL,IRS
      COMMON/IRECFLG/ LU,IPNOW,IPRIN,IPDEB,IGEOM,IHIST,
     1                    IGRAP,ISIMU,IDIGI,IANAL,IRS
*C     --------------------------------
