/*	l3t_tpc.idl
*
*	Module: l3t_tpc
*	description: Fast tracking interface
*/
#include "PAM.idl"
#include "l3t_tpc_para.idl"
#include "tcl_tphit.idl"
#include "tpt_track.idl"
#include "l3t_monitor.idl"

interface l3t_tpc : amiModule{
	STAFCV_T call
		( inout l3t_tpc_para para
                , inout tcl_tphit    hit
		, out   tpt_track    track
		, out   l3t_monitor  monitor
		);
};
/* Last mod. for l3t_tpc: $Data$ */
