/*	rft.idl
*
*	Module: rft
*	description: Fast tracking interface for FTPC
*/
#include "PAM.idl"
#include "r_ftpc_ctrl.idl"
#include "trg_fcl_fppoint.idl"
#include "tpt_track.idl"

interface r_ftpc : amiModule{
	STAFCV_T call
		( in    r_ftpc_ctrl ctrl
		, inout trg_fcl_fppoint point
		, out   tpt_track   fptrack
		);
};
/* Last mod. for r_ftpc: $Data$ */
