/*	r_tpc.idl
*
*	Module: r_tpc
*	description: Fast tracking interface
*/
#include "PAM.idl"
#include "tcl_tphit.idl"
#include "tpt_track.idl"

interface r_tpc : amiModule{
	STAFCV_T call
		( inout tcl_tphit hit
		, out   tpt_track track
		);
};
/* Last mod. for r_tpc: $Data$ */
