#!/bin/bash

export myself=${0}
echo myself=$myself
export mypwd=${1}
echo mypwd=$mypwd
export mypwdanalysis=${2}
echo mypwdanalysis=$mypwdanalysis
export mydebug=${3}
echo mydebug=$mydebug
export myscript=${4}
echo myscript=$myscript
export myscriptfinal=${5}
echo myscriptfinal=$myscriptfinal
export mytag=${6}
echo mytag=$mytag
export myconfig=${7}
echo myconfig=$myconfig
export myscratch=${8}
echo myscratch=$myscratch
export mypathout=${9}
echo mypathout=$mypathout
export mypathfinal=${10}
echo mypathfinal=$mypathfinal
export myfilelist=${11}
echo myfilelist=$myfilelist
export myrequestid=${12}
echo myrequestid=$myrequestid
export myjobid=${13}
echo myjobid=$myjobid
export mynprocesses=${14}
echo mynprocesses=$mynprocesses
export mydocons=${15}
echo mydocons=$mydocons
export mydomake=${16}
echo mydomake=$mydomake
export mycompiledpath=${17}
echo mycompiledpath=$mycompiledpath
export myfinal=${18}
echo myfinal=$myfinal
export myweightfile=${19}
echo myweightfile=$myweightfile
export mysleep=${20}
echo mysleep=$mysleep
export mydiscardstdout=${21}
echo mydiscardstdout=$mydiscardstdout

cd "$myscratch"

export NEED_RUN_TEMP=no
if [[ "${myfinal//*temp*/yes}" == "yes" ]] ; then export NEED_RUN_TEMP=yes ; fi
export NEED_RUN_FINAL=no
if [[ "${myfinal//*final*/yes}" == "yes" ]] ; then export NEED_RUN_FINAL=yes ; fi

if [[ ( "$NEED_RUN_TEMP" != "yes" ) && ( "$NEED_RUN_FINAL" != "yes" ) ]] ; then exit 0 ; fi

export myscratchanalysis=${myscratch}${mypwdanalysis#$mypwd}

if [[ ( "$mydocons" == "yes" ) || ( "$mydomake" == "yes" ) ]] ; then export COPY_COMPILED='-compiled' ; else export COPY_COMPILED='compiled' ; fi
if [[ "$NEED_RUN_TEMP" == "yes" ]] ; then export COPY_ANALYSIS='analysis' ; else export COPY_ANALYSIS='analysisFinal' ; fi

"$mypwdanalysis/StPi0Common/macros/copy" "$COPY_ANALYSIS" "$COPY_COMPILED" "$mypwd" "$myscratch" "$mypwdanalysis" "$myscratchanalysis"
"$mypwdanalysis/StPi0Common/macros/configure" "$COPY_ANALYSIS" "$myscratchanalysis" "$myscratch"

source "$myscratchanalysis/StPi0Common/macros/commands"

if [[ "$NEED_RUN_TEMP" == "yes" ]] ; then cp -fr "$myfilelist" "$myscratch/filelist_$myjobid.list" ; fi
if [[ ( "$NEED_RUN_FINAL" == "yes" ) && ( "$NEED_RUN_TEMP" != "yes" ) ]] ; then cp -fr "$myfilelist" "$myscratch/filelistFinal_$myjobid.list" ; fi

if [[ ( "$mycompiledpath" != "" ) && ( -d "$myscratch/$mycompiledpath" ) ]] ; then echo "No need to make or cons" ; else if [[ "$mydocons" != "yes" ]] ; then export mydomake='yes' ; fi ; fi

ls -al

if [[ "$mydocons" == "yes" ]] ; then cons ; fi
if [[ "$mydomake" == "yes" ]] ; then make ; fi

if [[ "$NEED_RUN_TEMP" == "yes" ]]
then

    export STDOUTFILE=${myscratch}/root_${mytag}_temp_${myjobid}.out
    if [[ "${mydiscardstdout}" == "true" ]] ; then export STDOUTFILE='/dev/null' ; fi
    run_command $mydebug root -b -q load_libs.C "$myscript"+`bash_escape_all '("@'${myscratch}'/filelist_'$myjobid'.list","'${myscratchanalysis}'/StPi0Analysis/macros/'${myweightfile}'","'${myscratch}'/root_'${mytag}'_temp_'$myjobid'.root","'\`cpp_escape_quo $myconfig\`'")'` &> ${STDOUTFILE}

    cat "${STDOUTFILE}"

    ls -al

    if [[ "$NEED_RUN_FINAL" == "yes" ]]
    then
	export NEED_RUN_FINAL=no
	
	if [[ "$mynprocesses" == "1" ]]
	then

	    echo "Only one process"
    	    mv -f "${myscratch}/root_${mytag}_temp_$myjobid.root" "${myscratch}/${mytag}_final_${myjobid}.root"

	else

	    if [[ "$mysleep" == "yes" ]]
	    then
		export DELAY=`get_random_number 2`
		echo "Sleeping $DELAY seconds..."
		sleep --version
		date
		sleep $DELAY
		date
	    fi

	    if ( resubmit "$myrequestid" "\"${mypathout}\" \"${myscratch}\"" 'no' "${mypwd}" )
	    then

    		echo "All jobs finished well, proceed to dataFinal..."
    	        rm -fr "${myscratch}/filelistFinal_$myjobid.list" ; touch "${myscratch}/filelistFinal_$myjobid.list"
    	        ls -1 --indicator-style=none "${mypathout}/${mytag}_temp_${myrequestid}_*.root" >> "${myscratch}/filelistFinal_$myjobid.list"
    	        ls -1 --indicator-style=none "${myscratch}/root_${mytag}_temp_${myjobid}.root" >> "${myscratch}/filelistFinal_$myjobid.list"

	        export NEED_RUN_FINAL=yes

	    fi

	fi
    fi

else

    export NEED_RUN_FINAL=yes

fi

if [[ "$NEED_RUN_FINAL" == "yes" ]]
then

    run_command $mydebug root -b -q load_libs.C "$myscriptfinal"`bash_escape_all '("@'${myscratch}'/filelistFinal_'$myjobid'.list","'${myscratch}'/'${mytag}'_final_'${myjobid}'.root")'`

fi

if [[ "$NEED_RUN_TEMP" == "yes" ]] ; then mv -f "${myscratch}/root_${mytag}_temp_${myjobid}.root" "${myscratch}/${mytag}_temp_${myjobid}.root" ; fi

mkdir -p "$mypathout"
mkdir -p "$mypathfinal"

if [[ -f "${myscratch}/${mytag}_temp_${myjobid}.root" ]] ; then copy_file_qa "${myscratch}/${mytag}_temp_${myjobid}.root"  "$mypathout/${mytag}_temp_${myjobid}.root" ; fi
if [[ -f "${myscratch}/${mytag}_final_${myjobid}.root" ]] ; then copy_file_qa "${myscratch}/${mytag}_final_${myjobid}.root" "$mypathfinal/${mytag}.root" ; fi

ls -al
