*
* $Id: gtasho.inc,v 1.1.1.2 2009/02/01 17:10:21 fisyak Exp $
*
* $Log: gtasho.inc,v $
* Revision 1.1.1.2  2009/02/01 17:10:21  fisyak
* Merge with .DEV2
*
* Revision 1.1.1.1  2008/12/10 20:47:19  fisyak
* Merge with macos version
*
* Revision 1.1.1.1  2005/05/25 22:37:33  fisyak
* Alice version of geant3 (-minicern)
*
* Revision 1.1.1.1  2002/07/24 15:56:26  rdm
* initial import into CVS
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:33  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTASHO_INC
#define CERNLIB_GEANT321_GTASHO_INC
*
*
* gtasho.inc
*
#if !defined(CERNLIB_INCLUDE)
      REAL         ZMED,AMED,DMED,E0MED,ZSMED,ESMED,ALFA,
     *             STEP,PLIN,PLOG,BE2,PLASM,TRNSMA,
     *             BOSC,AOSC,EOSC,ZOSC,EMEAN,CMGO,EMGO,EMGOMI
      INTEGER      NSMED,IOSC,NOSC,NMGO,NMGOMA
C
#endif

#endif
