*
* $Id: gtcuts.inc,v 1.1.1.2 2009/02/01 17:10:21 fisyak Exp $
*
* $Log: gtcuts.inc,v $
* Revision 1.1.1.2  2009/02/01 17:10:21  fisyak
* Merge with .DEV2
*
* Revision 1.1.1.1  2008/12/10 20:47:19  fisyak
* Merge with macos version
*
* Revision 1.1.1.1  2002/07/24 15:56:26  rdm
* initial import into CVS
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTCUTS_INC
#define CERNLIB_GEANT321_GTCUTS_INC
*
*
* gtcuts.inc
*
#if !defined(CERNLIB_INCLUDE)
      REAL          CUTGAM,CUTELE,CUTNEU,CUTHAD,CUTMUO,BCUTE,BCUTM
     +             ,DCUTE ,DCUTM ,PPCUTM,TOFMAX,GCUTS
C
#endif

#endif
