*
* $Id: gtpara.inc,v 1.1.1.3 2009/02/18 20:33:08 fisyak Exp $
*
* $Log: gtpara.inc,v $
* Revision 1.1.1.3  2009/02/18 20:33:08  fisyak
* *** empty log message ***
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:34  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTPARA_INC
#define CERNLIB_GEANT321_GTPARA_INC
*
*
* gtpara.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER    BITPHI, BITTET, BITPOT
      LOGICAL    SYMPHI, SYMTEU, SYMTED
#endif

#endif
