*
* $Id: mupsca.inc,v 1.1.1.3 2009/02/18 20:33:08 fisyak Exp $
*
* $Log: mupsca.inc,v $
* Revision 1.1.1.3  2009/02/18 20:33:08  fisyak
* *** empty log message ***
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:45  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_MUPSCA_INC
#define CERNLIB_GEANT321_MUPSCA_INC
*
*
* mupsca.inc
*
      COMMON/MUPSCA/ERFGM

#endif
