*
* $Id: nuciod.inc,v 1.1.1.3 2009/02/18 20:33:09 fisyak Exp $
*
* $Log: nuciod.inc,v $
* Revision 1.1.1.3  2009/02/18 20:33:09  fisyak
* *** empty log message ***
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_NUCIOD_INC
#define CERNLIB_GEANT321_NUCIOD_INC
*
* *** Used in /NUCIO under control of PATCHY flag "SINGLE"
*
* nuciod.inc
*
      DOUBLE PRECISION TECM,AMASS,PCM,WGT
C

#endif
