*
* $Id: pcodim.inc,v 1.2 2013/02/22 20:14:17 fisyak Exp $
*
* $Log: pcodim.inc,v $
* Revision 1.2  2013/02/22 20:14:17  fisyak
* Freeze
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_PCODIM_INC
#define CERNLIB_GEANT321_PCODIM_INC
*
*
* pcodim.inc
*
C --- DIMENSION STMTS. FOR GEANT/GHEISHA PARTICLE CODE CONVERSIONS ---
C --- KIPART(I)=GHEISHA CODE CORRESPONDING TO GEANT   CODE I ---
C --- IKPART(I)=GEANT   CODE CORRESPONDING TO GHEISHA CODE I ---
C
      DIMENSION KIPART(79),IKPART(40)
C

#endif
