#!/bin/csh 
set indir=$1
set file=$2
set readmudst=$3
set nev=$4
set histdir=hist

echo file=$indir/$file readmudst=$readmudst nev=$nev histdir=$histdir

#stardev
set dir=$cwd
set sys=$STAR_HOST_SYS
set tmpdir=/tmp/akio/fms2015

if ( ! -e $histdir) then
  mkdir $histdir
endif

if ( ! -e $tmpdir ) then
  mkdir -p $tmpdir
endif
cd $tmpdir

if ( ! -e .$sys ) then
  ln -s $dir/.$sys 
endif

if ( ! -e runMudst.C) then
  ln -s $dir/runMudst.C
endif

if ( ! -e FmsGain.txt) then
  ln -s $dir/FmsGain.txt 
endif

if ( ! -e load.C) then
  ln -s $dir/load.C
endif

if ( ! -e $file ) then
  /bin/cp $indir/$file .
endif

root4star -b -q 'runMudst.C("'$file'")'

set histfile=`echo $file | sed s/MuDst/fmsfps/g`;
cp $histfile $dir/$histdir/
