/*:Copyright 1996, Lawrence Berkeley National Laboratory
**:>--------------------------------------------------------------------
**:FILE:        levI.idl
**:DESCRIPTION: Interface Definition Language for LEV.
**:AUTHOR:      cet - Craig E. Tull, cetull@lbl.gov
**:BUGS:        -- STILL IN DEVELOPMENT --
**:HISTORY:     03feb97-v000b-cet- rename file
**:HISTORY:     15jul96-v000a-cet,hw- creation
**:<--------------------------------------------------------------------
*/

//:----------------------------------------------- INCLUDES           --
// #include "socI.idl"
#include "tdmI.idl"

//:----------------------------------------------- TYPEDEFS           --

//:#####################################################################
//:=============================================== INTERFACE          ==
interface levFactoryI: socFactoryI {
//:----------------------------------------------- ATTRIBUTES         --
readonly attribute tdmTableI env; /* environment table */
readonly attribute tdmTableI versions; /* of asps, pams, kumacs, etc? */

//:----------------------------------------------- FUNCTIONS          --
STAFCV_T registerVersion(in string name, in string type
		, in string version);
STAFCV_T timeStamp(in string stamp);

};      /* levFactoryI */

