#!/bin/bash

#
# The signal handler kills the child processes
#

#if [ $# -eq 0 ]; then
#    echo "Usage:   launch_reanalyze <server>";
#    exit
#fi

# get main function and shift args as appropriate...

args="$1 $2"
cmdstr="OnlTools/Jevp/StJevpPresenter/evpMonitorBaseScript.C(\"${args}\")"

echo "Main program: $cmdstr"


root4star -q -b "$cmdstr"
