#!/bin/bash

#
# The signal handler kills the child processes
#

#if [ $# -eq 0 ]; then
#    echo "Usage:   launch_reanalyze <server>";
#    exit
#fi

# get main function and shift args as appropriate...

#server=$1

#echo "Main program:"


OnlTools/Jevp/launch JevpServerMain & 
