#!/bin/bash

#
# The signal handler kills the child processes
#
function handle_interrupt {
    #echo "Got an interrupt: $1"

    for child in $(ps h -o pid --ppid $$); do
	comm="$(ps h -o comm $child)"
       
	if [ "$comm" != "" ]; then
	    #echo "Killing child process $child:  Command = $comm"
	    kill $child
	fi
    done 

    #echo "Now process $$ is dead..."
    exit
}


trap "handle_interrupt CHLD" CHLD
trap "handle_interrupt INT" INT
trap "handle_interrupt TERM" TERM
trap "handle_interrupt HUP" HUP

if [ $# -eq 0 ]; then
    echo "Usage:   launch <program>";
    exit
fi

# get main function and shift args as appropriate...

mainfunction=$1
#echo "Main program:  $mainfunction"
shift



#echo "shellname is $shellname"

if [ -e $shellname ]; then
    rm -f $shellname
fi

# now build args into a string
cnt=$#
let cnt=$cnt+1
#echo "CNT = $cnt"

argstring="   char* args[$cnt]; args[0]=\"$mainfunction::main\";"
i=1
pause=0

# default port is 8499....
port=8499



while [ $# -gt 0 ]; do
    if [ $1 = "-pause" ]; then
	pause=1
    fi

    if [ $1 = "-port" ]; then
	#echo "launch found port $2"
	port=$2
    fi

    argstring="$argstring  args[$i] = \"$1\";"
    let i=$i+1;
    shift;
done

# need a shell script to execute...
myaccount=`whoami`;
shellname="/tmp/${mainfunction}_${myaccount}_${port}_root.C"

#echo "launch with port = $port:  shellname = $shellname"

#echo "-----"
#echo -e "ARGSTRING:  $argstring"
#echo "-----"

serv=`echo "$mainfunction" | grep -i -c server`
pres=`echo "$mainfunction" | grep -i -c EvpMain`
test=`echo "$mainfunction" | grep -i -c MainTest`

evplibs="   gSystem->Load("\""PDFUtil"\""); "
#evplibs="$evplibs   gSystem->Load("\""StJevpPlot"\""); "
#evplibs="$evplibs   gSystem->Load("\""StJevpBuilders"\""); "

#echo "Server = $serv"
#echo "pres = $pres"

#if [ $serv -ne 0 ]; then
#    evplibs="$evplibs   gSystem->Load("\""StJevpServer"\""); "
#fi

#if [ $pres -ne 0 ]; then
#    evplibs="$evplibs   gSystem->Load("\""StJevpServer"\"");  "
#    evplibs="$evplibs   gSystem->Load("\""StJevpPresenter"\"");  "
#    evplibs="$evplibs   gSystem->Load("\""libQtRootGui.so"\"");  "
#fi

#if [ $test -ne 0 ]; then
#    evplibs="$evplibs   gSystem->Load("\""StJevpServer"\"");  "
#    evplibs="$evplibs   gSystem->Load("\""StJevpPresenter"\"");  "
#    evplibs="$evplibs   gSystem->Load("\""libQtRootGui.so"\"");  "
#fi

evplibs="$evplibs   gSystem->Load("\""Jevp"\"");  "
evplibs="$evplibs   gSystem->Load("\""libQtRootGui.so"\"");  "

cat >${shellname}<<ROOTMACRO
{

printf("a\n");
  gROOT->Macro("Load.C");
printf("b\n");
  gSystem->Load("RTS");
printf("c\n");
  if (gROOT->IsBatch()) {
     printf("Loading QT librares\n");
     gSystem->Load("libQtCore.so");
     gSystem->Load("libQtGui.so");
     gSystem->Load("libGui.so");
     gSystem->Load("libGQt.so");
     gSystem->Load("libQt3Support.so");
  }
  gSystem->Load("StDaqLib");
  gSystem->Load("StDbLib");
printf("e\n");
  gSystem->Load("StEEmcUtil");
printf("f\n");
  gSystem->Load("StEmcUtil");
printf("g\n");
  gSystem->Load("StStrangeMuDstMaker");
  gSystem->Load("StMuDSTMaker");
  gSystem->Load("St_db_Maker");
  gSystem->Load("StTriggerUtilities");
  gSystem->Load("StEEmcPoolmuEztPanitkin");
  gSystem->Load("StBEMCPlots");
  gSystem->Load("StMcEvent");


${evplibs}

${argstring}

  ${mainfunction}::main($cnt, args);
}
ROOTMACRO

touch $shellname

if [ $pause -eq 1 ]; then
    root4star -q -b $shellname
else 
    if [ $test -eq 1 ]; then
	root4starN $shellname
    else
	echo "Shell is: $shellname \n"
        root4star -q -b -l $shellname &
	#echo "boo\n"
        wait
    fi
fi

#echo "I am process $$, but root ended"

exit
