#
# Truely a insane makefile
#
# Only use if you're trying to install the executable image int /RTScache
# for operation in the actual DAQ/Online environment
# 

install: 
	cd ~/cvs/; cons; cd ~/cvs/OnlTools/Jevp
	cp Conscript.batty Conscript; cd ~/cvs/; cons; cd ~/cvs/OnlTools/Jevp; rm -f Conscript
	cp ~/cvs/.sl53_gcc432/obj/OnlTools/Jevp/WritePDFToDB /RTScache/lib/LINUX/i686/