/* sci_ana_inj.idl
*   Module: sci_ana_inj
*        description: Analysis of charge injection data.
*/

#include "PAM.idl"
#include "sci_par.idl"
#include "sci_bad_anodes.idl"
#include "sci_raw.idl"
#include "sci_clus.idl"
#include "sci_inj.idl"

interface sci_ana_inj : amiModule {
        STAFCV_T call
                (in     sci_par         par,
                 inout  sci_bad_anodes  bad_anodes,
                 in     sci_raw         raw,
                 in     sci_clus        clus,
                 out    sci_inj         inj
        );
};
/*  Last mod. for sci_ana_inj: $Date: 1998/01/26 22:12:44 $ */


