./compareRootFiles "B0PythiaDecay1" "rootFiles/B0PythiaDecay1.root" "oldRootFiles/B0PythiaDecay1.root" "B^{0} #rightarrow #bar{cd}_{0} ud_{0}"
./compareRootFiles "B0PythiaDecay2" "rootFiles/B0PythiaDecay2.root" "oldRootFiles/B0PythiaDecay2.root" "B^{0} #rightarrow #bar{cd}_{1} ud_{1}"
./compareRootFiles "B0PythiaDecay3" "rootFiles/B0PythiaDecay3.root" "oldRootFiles/B0PythiaDecay3.root" "B^{0} #rightarrow #bar{cs}_{0} ud_{0}"
./compareRootFiles "B0PythiaDecay4" "rootFiles/B0PythiaDecay4.root" "oldRootFiles/B0PythiaDecay4.root" "B^{0} #rightarrow #bar{cs}_{1} ud_{1}"
./compareRootFiles "B0PythiaDecay5" "rootFiles/B0PythiaDecay5.root" "oldRootFiles/B0PythiaDecay5.root" "B^{0} #rightarrow u #bar{d} #bar{c} d (weak)"
./compareRootFiles "B0PythiaDecay6" "rootFiles/B0PythiaDecay6.root" "oldRootFiles/B0PythiaDecay6.root" "B^{0} #rightarrow u #bar{d} #bar{c} d"
./compareRootFiles "B0PythiaDecay7" "rootFiles/B0PythiaDecay7.root" "oldRootFiles/B0PythiaDecay7.root" "B^{0} #rightarrow u #bar{s} #bar{c} d"
./compareRootFiles "B0PythiaDecay8" "rootFiles/B0PythiaDecay8.root" "oldRootFiles/B0PythiaDecay8.root" "B^{0} #rightarrow u #bar{c} #bar{d} d (weak)"
./compareRootFiles "B0PythiaDecay9" "rootFiles/B0PythiaDecay9.root" "oldRootFiles/B0PythiaDecay9.root" "B^{0} #rightarrow u #bar{c} #bar{s} d (weak)"
./compareRootFiles "B0PythiaDecay10" "rootFiles/B0PythiaDecay10.root" "oldRootFiles/B0PythiaDecay10.root" "B^{0} #rightarrow c #bar{s} #bar{c} d"
./compareRootFiles "B0PythiaDecay11" "rootFiles/B0PythiaDecay11.root" "oldRootFiles/B0PythiaDecay11.root" "B^{0} #rightarrow c #bar{d} #bar{c} d"
./compareRootFiles "B0PythiaDecay12" "rootFiles/B0PythiaDecay12.root" "oldRootFiles/B0PythiaDecay12.root" "B^{0} #rightarrow u #bar{d} #bar{u} d (weak)"
./compareRootFiles "B0PythiaDecay13" "rootFiles/B0PythiaDecay13.root" "oldRootFiles/B0PythiaDecay13.root" "B^{0} #rightarrow c #bar{s} #bar{u} d (weak)"
./compareRootFiles "B0PythiaDecay14" "rootFiles/B0PythiaDecay14.root" "oldRootFiles/B0PythiaDecay14.root" "B^{0} #rightarrow u #bar{u} #bar{d} d (weak)"
./compareRootFiles "B0PythiaDecay15" "rootFiles/B0PythiaDecay15.root" "oldRootFiles/B0PythiaDecay15.root" "B^{0} #rightarrow d #bar{d} #bar{d} d (weak)"
./compareRootFiles "B0PythiaDecay16" "rootFiles/B0PythiaDecay16.root" "oldRootFiles/B0PythiaDecay16.root" "B^{0} #rightarrow s #bar{s} #bar{d} d (weak)"
./compareRootFiles "B0PythiaDecay17" "rootFiles/B0PythiaDecay17.root" "oldRootFiles/B0PythiaDecay17.root" "B^{0} #rightarrow u #bar{u} #bar{s} d (weak)"
./compareRootFiles "B0PythiaDecay18" "rootFiles/B0PythiaDecay18.root" "oldRootFiles/B0PythiaDecay18.root" "B^{0} #rightarrow d #bar{d} #bar{s} d (weak)"
./compareRootFiles "B0PythiaDecay19" "rootFiles/B0PythiaDecay19.root" "oldRootFiles/B0PythiaDecay19.root" "B^{0} #rightarrow s #bar{s} #bar{s} d (weak)"
./compareRootFiles "B0PythiaDecay20" "rootFiles/B0PythiaDecay20.root" "oldRootFiles/B0PythiaDecay20.root" "B^{0} #rightarrow #bar{s} d"
