./genExampleRootFiles TauolaFiles/tauolaDecay1.dec rootFiles/tauolaDecay1.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay2.dec rootFiles/tauolaDecay2.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay3.dec rootFiles/tauolaDecay3.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay4.dec rootFiles/tauolaDecay4.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay5.dec rootFiles/tauolaDecay5.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay6.dec rootFiles/tauolaDecay6.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay7.dec rootFiles/tauolaDecay7.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay8.dec rootFiles/tauolaDecay8.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay9.dec rootFiles/tauolaDecay9.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay10.dec rootFiles/tauolaDecay10.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay11.dec rootFiles/tauolaDecay11.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay12.dec rootFiles/tauolaDecay12.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay13.dec rootFiles/tauolaDecay13.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay14.dec rootFiles/tauolaDecay14.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay15.dec rootFiles/tauolaDecay15.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay16.dec rootFiles/tauolaDecay16.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay17.dec rootFiles/tauolaDecay17.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay18.dec rootFiles/tauolaDecay18.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay19.dec rootFiles/tauolaDecay19.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay20.dec rootFiles/tauolaDecay20.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay21.dec rootFiles/tauolaDecay21.root tau- 100000
./genExampleRootFiles TauolaFiles/tauolaDecay22.dec rootFiles/tauolaDecay22.root tau- 100000
