/*  sca_makeref.idl
*   This is the staf interface file for sca_makeref.cc, the ensemble 
*   average calculation module in the sca package
*
*   written by Dhammika Weerasundara -- dhammika@gibbs.npl.washington.edu
*/
#include "PAM.idl"
#include "sca_switch.idl"
#include "sca_out.idl"

interface sca_makeref : amiModule{
        STAFCV_T call (
                  in	sca_switch		sca_switch   ,   
                  inout	sca_out		        sca_ensemble_ave);
};
/* last mod. for sca_makeref.idl : $Date: 1998/08/10 22:03:20 $ */
