/*  sca_filter.idl
*   This is the staf interface file for sca_filter.cc, the filter 
*   module in the sca package
*
*   written by L. D. Carr -- lcarr@u.washington.edu
*/
#include "PAM.idl"
#include "dst_track.idl"
#include "sca_in.idl"
#include "sca_filter_const.idl"
#include "sca_switch.idl"
#include "sca_const.idl"

interface sca_filter : amiModule{
        STAFCV_T call (
                  in	dst_track		dstTrack     ,   
                  in	sca_filter_const	filter_const ,   
                  in	sca_switch		sca_switch   ,   
                  in	sca_const       	sca_const    ,  
                  out	sca_in			sca_in  );
};
/* last mod. for sca_filter.idl : $Date: 1998/08/05 22:04:14 $ */
