/* vps.idl */
#include "PAM.idl"
#include "g2t_vpd_hit.idl"
#include "vps_par.idl"
#include "vps_sim.idl"
#include "vps_raw.idl"

interface vps : amiModule {
        STAFCV_T call
                ( inout g2t_vpd_hit      gvhit
                , inout vps_par          vpar
                , inout vps_sim          vsim
                , inout vps_raw          vraw
        );
};
/*  Last mod. for vps: $Date: 1998/02/10 15:07:33 $ */

