/* rl1_pw.idl */
#include "PAM.idl"
#include "rl0_data.idl"
#include "rl1_pw_ctrl.idl"
#include "rl1_pw_out.idl"

interface rl1_pw : amiModule {
        STAFCV_T call
                ( inout rl0_data         lvl0
                , inout rl1_pw_ctrl      clb
                , inout rl1_pw_out       l1b
        );
};
/*  Last mod. for rl1_pw: $Date: 1998/02/17 17:09:36 $ */

