#!/bin/csh -f
# $Id: module_html,v 1.3 1998/04/28 21:41:27 fisyak Exp $ 
# $Log: module_html,v $
# Revision 1.3  1998/04/28 21:41:27  fisyak
# split pages
#
# Revision 1.2  1998/04/20 21:45:58  fisyak
# Module description
#
# Revision 1.1  1998/04/19 21:00:33  fisyak
# Add cross reference module documentation
#
# $Date: 1998/04/28 21:41:27 $
set idl=$1
set pam = `basename $idl .idl`
set listc  = "$idl:r.*"
set listh  = "$pam:r.h"
set listi  = "$pam:r.inc"
set ref = "`grep -l $listh $listc`  `grep -l $listi $listc`"
set reff = `echo $ref | sed -e 's/\/afs\/rhic\/star\/packages\//http:\/\/www.rhic.bnl.gov\/afs\/rhic\/star\/doc\/www\/packages_l\//'`
gawk -v ref="$reff" -f ./module_html.awk $idl
exit




