#!/bin/csh
# $Id: star_html,v 1.3 1998/04/27 21:01:56 fisyak Exp $
# $Log: star_html,v $
# Revision 1.3  1998/04/27 21:01:56  fisyak
# Update structure
#
# Revision 1.2  1998/04/20 21:46:11  fisyak
# Module description
#
# Revision 1.1  1998/04/19 21:00:35  fisyak
# Add cross reference module documentation
#
set all_idl = `find $STAR/pams -name "*.idl"`
set list_idlm = `egrep -l 'interface' $all_idl`
set list_idl  = `egrep -l 'struct '   $all_idl`
echo "<HTML>"
echo "<HEAD>"
echo "<TITLE>List of STAR pams and tables</TITLE>"
echo "</HEAD>"
echo "<BODY>"
echo "<H2>List of STAR pams</H2>"
echo "<hr>"
echo "<hr>"
set domain = ""
set package = ""
# list of all modules
 foreach idlm ($list_idlm) 
   set dom = `echo $idlm | gawk -F / '{for (i=1;i<=NF;i++) {if(index($i,"pams")>0) {l=i+1; print $l;break;}}};'`
   if ($dom != $domain) then
      if ("$domain" !="") echo '</ol>'
      set domain = $dom;
      echo '<H3>Domain '$domain'</H3>'
      echo "<hr> <ol>"
      set count = 0
      set README = $STAR/pams/$domain/README
      if (-r $README) then
        echo '<pre>'
        cat  $README
        echo '</pre>
      endif
      set DOC = $STAR/pams/$domain/doc
      if (-r $DOC) then
        set hid = `echo $DOC | sed -e 's/\/afs\/rhic\/star\/packages\//http:\/\/www.rhic.bnl.gov\/afs\/rhic\/star\/doc\/www\/packages_l\//'`
        echo '<a href="'$hid'">Its documentation</a>'
      endif
   endif
   set dir = `dirname $idlm`
   if ($dir != $package) then 
   if (-r $dir/README) then
     echo '<pre>'
     cat  $dir/README
     echo '</pre>'
   endif
   if (-r $dir/doc) then
     set hid = `echo $dir/doc | sed -e 's/\/afs\/rhic\/star\/packages\//http:\/\/www.rhic.bnl.gov\/afs\/rhic\/star\/doc\/www\/packages_l\//'`
     echo '<a href="'$hid'">Its documentation</a>'
   endif
   set package = $dir
   endif
   set id = `basename $idlm .idl`
   echo '<li><a href="#'$id'_mod"><strong>'$id'</strong></a> &nbsp; &nbsp; &nbsp;'
   set count = `expr $count + 1`;
 end
 echo '</ol>'
echo "<hr>"
echo "<H2>List of STAR tables</H2>"
echo "<hr>"
echo "<hr>"
set count = 0
set domain = ""
 foreach idl ($list_idl) 
   set dom = `echo $idl | gawk -F / '{for (i=1;i<=NF;i++) {if(index($i,"pams")>0) {l=i+1; print $l;break;}}};'`
   if ($dom != $domain) then
      set domain = $dom;
      echo '<H3>Domain '$domain'</H3>'
      echo "<hr>"
      set count = 0
   endif

   set id = `basename $idl .idl`
   echo '<a href="#'$id'_tab"><strong>'$id'</strong></a> &nbsp; &nbsp; &nbsp;'
   set count = `expr $count + 1`;
#   if ($count >= 5) then
#       echo "<br>"
#       set count = 0;
#   endif
 end
echo "<H2>List of STAR pams</H2>"
echo "<hr>"
echo "<ol>"
 foreach idl ($list_idlm) 
   set id = `basename $idl .idl`
   set hid = `echo $idl | sed -e 's/\/afs\/rhic\/star\/packages\//http:\/\/www.rhic.bnl.gov\/afs\/rhic\/star\/doc\/www\/packages_l\//'`
   echo '<li>Module <a name="'$id'_mod"><strong>'$id'</strong></a> defined in <a href="'$hid'">'$idl'</a>'
echo '<BR>'
echo '<TABLE CELLPADDING=3 BORDER="1">'
echo '<TR><TD>Module</TD><TD>Input tables</TD><TD>Output tables</TD></TR>'
   ./module_html   $idl
echo '</TABLE>'                                                                                                 
 end
echo "</ol>"
echo "<hr>"
echo "<H2>List of STAR tables</H2>"
echo "<hr>"
echo "<ol>"
 foreach idl ($list_idl) 
   set id = `basename $idl .idl`
   set hid = `echo $idl | sed -e 's/\/afs\/rhic\/star\/packages\//http:\/\/www.rhic.bnl.gov\/afs\/rhic\/star\/doc\/www\/packages_l\//'`
   echo '<li> Table <a name="'$id'_tab"><strong>'$id'</strong></a> is defined in <a href="'$hid'">'$idl'</a> and used by the following modules:'
   set idlm_idl = `egrep -l ${id}.idl $list_idlm`
   foreach idlm ($idlm_idl)
     set did = `basename $idlm .idl`
     echo '<a href="#'$did'_mod">'$did'</a> &nbsp;&nbsp;&nbsp;&nbsp;'
   end
 end
echo "</ol>"
echo "<hr>"
echo "</BODY>"
echo "</HTML>"
