
include ../rtsmakefile.def


all :
	@echo "No compilation in this directory..."

clean :

install :

depend :
	@$(MAKEDEPEND)

# DO NOT DELETE

fcfAfterburner.o: ../../include/rtsLog.h
fcfAfterburner.o: ../../include/fcfClass.hh
fcfAfterburner.o: ../../include/rts.h
fcfAfterburner.o: ../../include/TPC/padfinder.h
fcfClass.o: ../../include/rts.h
fcfClass.o: ../../include/rtsSystems.h
fcfClass.o: ../../include/fcfClass.hh
fcfClass.o: ../../include/rtsLog.h
