*
* $Id: blank.inc,v 1.1.1.1 2004/01/15 00:12:22 potekhin Exp $
*
* $Log: blank.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:22  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:44  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_BLANK_INC
#define CERNLIB_GEANT321_BLANK_INC
*
*CMZ :  3.21/02 29/03/94  15.41.37  by  S.Giani
*-- Author :

#endif
