*
* $Id: depnuc.inc,v 1.1.1.1 2004/01/15 00:12:23 potekhin Exp $
*
* $Log: depnuc.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:23  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:45  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:38  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_DEPNUC_INC
#define CERNLIB_GEANT321_DEPNUC_INC
*
*
* depnuc.inc
*
*                                                                     *
*=== depnuc ==========================================================*
*                                                                     *
      LOGICAL LLASTN, LLAST1
      COMMON /FKDEPN/    EKLAST, AMLAST, PXLAST, PYLAST, PZLAST,
     &                   EKINC , AMINC , PXXINC, PYYINC, PZZINC,
     &                   KTLAST, KTINC , LLASTN, LLAST1
 

#endif
