*
* $Id: forcn.inc,v 1.1.1.1 2004/01/15 00:12:23 potekhin Exp $
*
* $Log: forcn.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:23  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:47  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:39  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_FORCN_INC
#define CERNLIB_GEANT321_FORCN_INC
*
*
* forcn.inc
*
*                                                                      *
*=== forcn ============================================================*
*                                                                      *
      COMMON /FKFORC/ FKEY
 

#endif
