*
* $Id: gcdlin.inc,v 1.1.1.1 2004/01/15 00:12:23 potekhin Exp $
*
* $Log: gcdlin.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:23  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:47  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GCDLIN_INC
#define CERNLIB_GEANT321_GCDLIN_INC
*
*
* gcdlin.inc
*
      COMMON/GCDLIN/NCWORD(2),JCADNT,JBUF1,JBUF2
      EQUIVALENCE (JBUF1,JCDLST),(JCADNT,JCDFRS)
*

#endif
