*
* $Id: gcsetf.inc,v 1.1.1.1 2004/01/15 00:12:24 potekhin Exp $
*
* $Log: gcsetf.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:24  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:49  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GCSETF_INC
#define CERNLIB_GEANT321_GCSETF_INC
*
*
* gcsetf.inc
*
      COMMON/GCADII/NPLACE,NUNIT1,N1,NUNIT2
*
      COMMON/GCADIC/BLKSTR,JVSTR
      CHARACTER*500 BLKSTR
      CHARACTER*80  JVSTR
*

#endif
