*
* $Id: gcxlun.inc,v 1.1.1.1 2004/01/15 00:12:24 potekhin Exp $
*
* $Log: gcxlun.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:24  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:34  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GCXLUN_INC
#define CERNLIB_GEANT321_GCXLUN_INC
*
*
* gcxlun.inc
*
#if !defined(CERNLIB_INCLUDE)
      COMMON/GCXLUN/LUNIT(128)
*
#endif
*
* gcxlun.inc
*
#if defined(CERNLIB_INCLUDE)
*
#include "geant321/incbeg.inc"
     +   gcxlun
#include "geant321/incend.inc"
#endif

#endif
