*
* $Id: gtasho.inc,v 1.1.1.1 2004/01/15 00:12:24 potekhin Exp $
*
* $Log: gtasho.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:24  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:33  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTASHO_INC
#define CERNLIB_GEANT321_GTASHO_INC
*
*
* gtasho.inc
*
#if !defined(CERNLIB_INCLUDE)
      REAL         ZMED,AMED,DMED,E0MED,ZSMED,ESMED,ALFA,
     *             STEP,PLIN,PLOG,BE2,PLASM,TRNSMA,
     *             BOSC,AOSC,EOSC,ZOSC,EMEAN,CMGO,EMGO,EMGOMI
      INTEGER      NSMED,IOSC,NOSC,NMGO,NMGOMA
C
#endif

#endif
