*
* $Id: gtbank.inc,v 1.1.1.1 2004/01/15 00:12:25 potekhin Exp $
*
* $Log: gtbank.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:25  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTBANK_INC
#define CERNLIB_GEANT321_GTBANK_INC
*
*
* gtbank.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER IQ,LQ,NZEBRA,IXSTOR,IXDIV,IXCONS,LMAIN,LR1,JCG
      INTEGER KWBANK,KWWORK,IWS
      REAL GVERSN,ZVERSN,FENDQ,WS,Q
C
#endif

#endif
