*
* $Id: gtcons.inc,v 1.1.1.1 2004/01/15 00:12:25 potekhin Exp $
*
* $Log: gtcons.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:25  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:32  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTCONS_INC
#define CERNLIB_GEANT321_GTCONS_INC
*
*
* gtcons.inc
*
#if !defined(CERNLIB_INCLUDE)
      REAL          PI,TWOPI,PIBY2,DEGRAD,RADDEG,CLIGHT,BIG,EMASS
      REAL          EMMU,PMASS,AVO
C
#endif

#endif
