*
* $Id: gtcurs.inc,v 1.1.1.1 2004/01/15 00:12:25 potekhin Exp $
*
* $Log: gtcurs.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:25  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTCURS_INC
#define CERNLIB_GEANT321_GTCURS_INC
*
*
* gtcurs.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER INTFLA
      REAL    SIZD2,FACHV,HALF,SAVPLX,SAVPLY,YPLT,XPLT
*
#endif

#endif
