*
* $Id: gtfdim.inc,v 1.1.1.1 2004/01/15 00:12:25 potekhin Exp $
*
* $Log: gtfdim.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:25  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:36  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTFDIM_INC
#define CERNLIB_GEANT321_GTFDIM_INC
*
*
* gtfdim.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER NPROC,NMPTOT
      REAL TSEQTO,TOTMBY,TSEQ,TLAT,TNET,X1MIN,X1MAX,
     +     Y1MIN,Y1MAX,Z1MIN,Z1MAX,XCUT,YCUT,ZCUT
#endif

#endif
