*
* $Id: gtflag.inc,v 1.1.1.1 2004/01/15 00:12:25 potekhin Exp $
*
* $Log: gtflag.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:25  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTFLAG_INC
#define CERNLIB_GEANT321_GTFLAG_INC
*
*
* gtflag.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER       IDEBUG,IDEMIN,IDEMAX,ITEST,IDRUN,IDEVT,IEORUN
     +        ,IEOTRI,IEVENT,ISWIT,IFINIT,NEVENT,NRNDM
C
#endif

#endif
