*
* $Id: gthil2.inc,v 1.1.1.1 2004/01/15 00:12:25 potekhin Exp $
*
* $Log: gthil2.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:25  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:33  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTHIL2_INC
#define CERNLIB_GEANT321_GTHIL2_INC
*
*
* gthil2.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER LARETT,JTICK,JMYLL,JFIMOT,JFISCA,JFINAM,
     +        JAASS1,JAASS2,JAASS3,JAASS4,
     +        JTICKS,JMYLLS,JMYMOT
#endif

#endif
