*
* $Id: gtkine.inc,v 1.1.1.1 2004/01/15 00:12:26 potekhin Exp $
*
* $Log: gtkine.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:26  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTKINE_INC
#define CERNLIB_GEANT321_GTKINE_INC
*
*
* gtkine.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER       IKINE,ITRA,ISTAK,IVERT,IPART,ITRTYP,NAPART,IPAOLD
      REAL          PKINE,AMASS,CHARGE,TLIFE,VERT,PVERT
C
#endif

#endif
