*
* $Id: gtlink.inc,v 1.1.1.1 2004/01/15 00:12:27 potekhin Exp $
*
* $Log: gtlink.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:27  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTLINK_INC
#define CERNLIB_GEANT321_GTLINK_INC
*
*
* gtlink.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER       JDIGI ,JDRAW ,JHEAD ,JHITS ,JKINE ,JMATE ,JPART
     +      ,JROTM ,JRUNG ,JSET  ,JSTAK ,JGSTAT,JTMED ,JTRACK,JVERTX
     +      ,JVOLUM,JXYZ  ,JGPAR ,JGPAR2,JSKLT
C
#endif

#endif
