*
* $Id: gtlist.inc,v 1.1.1.1 2004/01/15 00:12:27 potekhin Exp $
*
* $Log: gtlist.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:27  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:32  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTLIST_INC
#define CERNLIB_GEANT321_GTLIST_INC
*
*
* gtlist.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER       NHSTA,NGET ,NSAVE,NSETS,NPRIN,NGEOM,NVIEW,NPLOT
     + ,NSTAT,LHSTA,LGET ,LSAVE,LSETS,LPRIN,LGEOM,LVIEW,LPLOT,LSTAT
C
#endif

#endif
