*
* $Id: gtmutr.inc,v 1.1.1.1 2004/01/15 00:12:27 potekhin Exp $
*
* $Log: gtmutr.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:27  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:50  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:34  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTMUTR_INC
#define CERNLIB_GEANT321_GTMUTR_INC
*
*
* gtmutr.inc
*
#if !defined(CERNLIB_INCLUDE)
*
      INTEGER NCVOLS,NSHIFT,KSHIFT,ICUBE,NAIN,JJJ,NIET,IVOOLD,
     +        IWPOIN,IHPOIN,IVECVO,IOLDSU,ICGP,IPORNT
      REAL    GXMIN,GXMAX,GYMIN,GYMAX,GZMIN,GZMAX,GXXXX,GYYYY,GZZZZ
      REAL    CLIPMI,CLIPMA,ABCD,BMIN,BMAX,CGB,CGB1,GBOOM
      REAL    PORGX,PORGY,PORGZ,POX,POY,POZ,PORMIR,PORMAR
#endif

#endif
