*
* $Id: gtpixe.inc,v 1.1.1.1 2004/01/15 00:12:28 potekhin Exp $
*
* $Log: gtpixe.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:28  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:51  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:36  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTPIXE_INC
#define CERNLIB_GEANT321_GTPIXE_INC
*
*
* gtpixe.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER LIMPRE,IFLAPE,ICOLOR,IXXX,IYYY,
     +        ISSEEN,ISCOLO,ISLSTY,ISLWID,ISFILL,
     +        IMAP,JON,NMAP
      REAL UUU,VVV,ZUV,ZNMAP1
#endif

#endif
