*
* $Id: gtsets.inc,v 1.1.1.1 2004/01/15 00:12:28 potekhin Exp $
*
* $Log: gtsets.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:28  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:51  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:33  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTSETS_INC
#define CERNLIB_GEANT321_GTSETS_INC
*
*
* gtsets.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER       IHSET,IHDET,ISET,IDET,IDTYPE,NVNAME,NUMBV
C
#endif

#endif
