*
* $Id: gttmed.inc,v 1.1.1.1 2004/01/15 00:12:28 potekhin Exp $
*
* $Log: gttmed.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:28  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:51  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:33  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTTMED_INC
#define CERNLIB_GEANT321_GTTMED_INC
*
*
* gttmed.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER       NUMED,NATMED,ISVOL,IFIELD,IUPD,ISTPAR,NUMOLD
      REAL          FIELDM,TMAXFD,STEMAX,DEEMAX,EPSIL,STMIN,CFIELD,PREC
      INTEGER       JMIN,NPCKOV,IMCKOV,ITCKOV
      REAL          THRIND,PMIN,DP,DNDL
C
#endif

#endif
