*
* $Id: gtursb.inc,v 1.1.1.1 2004/01/15 00:12:28 potekhin Exp $
*
* $Log: gtursb.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:28  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:51  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTURSB_INC
#define CERNLIB_GEANT321_GTURSB_INC
*
*
* gtursb.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER NUMNDS,IADDI,NUMND2,NNPAR,IISELT
*
#endif

#endif
