*
* $Id: gtvol1.inc,v 1.1.1.1 2004/01/15 00:12:28 potekhin Exp $
*
* $Log: gtvol1.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:28  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:51  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:33  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTVOL1_INC
#define CERNLIB_GEANT321_GTVOL1_INC
*
*
* gtvol1.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER NAMES1,NUMBR1,LVOLU1
#endif

#endif
