*
* $Id: hetc5.inc,v 1.1.1.1 2004/01/15 00:12:29 potekhin Exp $
*
* $Log: hetc5.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:29  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:51  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:39  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_HETC5_INC
#define CERNLIB_GEANT321_HETC5_INC
*
*
* hetc5.inc
*
*                                                                      *
*=== hetc5 ============================================================*
*                                                                      *
      COMMON /FKHET5/ APR,ZPR,EX,UU,EREC
 

#endif
