*
* $Id: incdek.inc,v 1.1.1.1 2004/01/15 00:12:29 potekhin Exp $
*
* $Log: incdek.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:29  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:51  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:36  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_INCDEK_INC
#define CERNLIB_GEANT321_INCDEK_INC
*
#if defined(CERNLIB_INCLUDE)
*CMZ :  3.21/02 29/03/94  15.41.25  by  S.Giani
*-- Author :
#endif

#endif
