*
* $Id: labcos.inc,v 1.1.1.1 2004/01/15 00:12:29 potekhin Exp $
*
* $Log: labcos.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:29  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:52  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:40  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_LABCOS_INC
#define CERNLIB_GEANT321_LABCOS_INC
*
*
* labcos.inc
*
*                                                                      *
*=== labcos ===========================================================*
*                                                                      *
      COMMON /FKLABC/ COSLBP(3),COSLBR(3)
 

#endif
