*
* $Id: mapat.inc,v 1.1.1.1 2004/01/15 00:12:29 potekhin Exp $
*
* $Log: mapat.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:29  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:52  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:40  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_MAPAT_INC
#define CERNLIB_GEANT321_MAPAT_INC
*
*
* mapat.inc
*
 
      DOUBLE PRECISION  AOCMBM , AMSS , ZTAR   , RHO    , ZLIN , ZLEL
     &                , ZLRAD  , ZUL
 

#endif
