*
* $Id: mapoll.inc,v 1.1.1.1 2004/01/15 00:12:29 potekhin Exp $
*
* $Log: mapoll.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:29  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:52  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:44  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_MAPOLL_INC
#define CERNLIB_GEANT321_MAPOLL_INC
*
*
* mapoll.inc
*
      COMMON/MAPOLL/ETA,ETATH,ETAUSD,DEADWT(5),XTRA(10),ITERS,IFR,IFG,
     1ITSTR,NEWNM,NGEOM,NMEM,NMEMR,NMEMG,INALB,NDEAD(5),NPSCL(13)

#endif
