*
* $Id: mconst.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: mconst.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:52  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:44  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_MCONST_INC
#define CERNLIB_GEANT321_MCONST_INC
*
*
* mconst.inc
*
#include "geant321/mparam.inc"
      COMMON/MCONST/NNR,NQ,NGR,NTSTW,MGPREG,MGP1,M1M,NI,NNUC,NCOL

#endif
