*
* $Id: metlsp.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: metlsp.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:52  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:40  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_METLSP_INC
#define CERNLIB_GEANT321_METLSP_INC
*
*
* metlsp.inc
*
C***********************************************************************
C     INCLUDE FILE: METLSP COPY                   CREATED 11/12/86 BY PA
C     CHANGES: NONE
C     INCLUDED IN THE FOLLOWING SUBROUTINES OR FUNCTIONS: NOT UPDATED
C
C     DESCRIPTION OF THE COMMON BLOCK(S) AND VARIABLE(S)
C
C***********************************************************************
      PARAMETER (IDMAX2=1133)
      COMMON/FKMETL/ IS,ITS(IDMAX2),CXS(IDMAX2),CYS(IDMAX2),CZS(IDMAX2),
     *ELS(IDMAX2),PLS(IDMAX2)
 

#endif
