*
* $Id: mrecoi.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: mrecoi.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:53  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:45  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_MRECOI_INC
#define CERNLIB_GEANT321_MRECOI_INC
*
*
* mrecoi.inc
*
      COMMON/MRECOI/NAMEXR,MTNR,NZR,NCOLR,AR,ER,UR,VR,WR,XR,YR,ZR,
     1WATER,AGER,ENIR,UNIR,VNIR,WNIR,ENOR,UNOR,VNOR,WNOR,WTNR,QR

#endif
