*
* $Id: nuciod.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: nuciod.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:53  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_NUCIOD_INC
#define CERNLIB_GEANT321_NUCIOD_INC
*
* *** Used in /NUCIO under control of PATCHY flag "SINGLE"
*
* nuciod.inc
*
      DOUBLE PRECISION TECM,AMASS,PCM,WGT
C

#endif
