*
* $Id: papropt.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: papropt.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:53  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:41  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_PAPROPT_INC
#define CERNLIB_GEANT321_PAPROPT_INC
*
*
* papropt.inc
*
      DOUBLE PRECISION AM, AMDISC, THALF,BIASDC, BIASIN
 

#endif
