*
* $Id: part2t.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: part2t.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:53  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_PART2T_INC
#define CERNLIB_GEANT321_PART2T_INC
*
*
* part2t.inc
*
      DOUBLE PRECISION AAM, GA, TAU, AAMDSC
 

#endif
