*
* $Id: partt.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: partt.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:54  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_PARTT_INC
#define CERNLIB_GEANT321_PARTT_INC
*
*
* partt.inc
*
      DOUBLE PRECISION AM, GA, TAU, AMDISC
 

#endif
