*
* $Id: pawct.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: pawct.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:54  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:35  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_PAWCT_INC
#define CERNLIB_GEANT321_PAWCT_INC
*
*
* pawct.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER NWPAW,IXPAWC,IHBOOK,IXHIGZ,IXKUIP,IFENCE,LLMAIN,IQQ,LQQ
      REAL WWS,QQ
#endif

#endif
