*
* $Id: s_coscom.inc,v 1.1.1.1 2004/01/15 00:12:30 potekhin Exp $
*
* $Log: s_coscom.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:30  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:54  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_S_COSCOM_INC
#define CERNLIB_GEANT321_S_COSCOM_INC
*
*
* s_coscom.inc
*
      COMMON/COSCOM/AA,BB,CC,DD,RR
C

#endif
