*
* $Id: s_kginit.inc,v 1.1.1.1 2004/01/15 00:12:31 potekhin Exp $
*
* $Log: s_kginit.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:31  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:55  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:44  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_S_KGINIT_INC
#define CERNLIB_GEANT321_S_KGINIT_INC
*
*       *** NVE 09-FEB-1988 ***
*
* s_kginit.inc
*
C --- INITIALIZATION FLAGS FOR VARIOUS GHEISHA ROUTINES ---
      COMMON /KGINIT/ KGINIT(50)
C

#endif
