*
* $Id: split.inc,v 1.1.1.1 2004/01/15 00:12:31 potekhin Exp $
*
* $Log: split.inc,v $
* Revision 1.1.1.1  2004/01/15 00:12:31  potekhin
*
* Revision 1.1.1.1  1997/11/03 15:29:55  atlascvs
* Importing CERNLIB version 08.21.
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_SPLIT_INC
#define CERNLIB_GEANT321_SPLIT_INC
*
*
* split.inc
*
*
*=== split ============================================================*
*
*----------------------------------------------------------------------*
*                                                                      *
*     Created on 10 december 1991  by    Alfredo Ferrari & Paola Sala  *
*                                                   Infn - Milan       *
*                                                                      *
*     Last change on 10-dec-91     by    Alfredo Ferrari               *
*                                                                      *
*     This is the original common split of Hadrin                      *
*                                                                      *
*     Included in the following routines:                              *
*                                                                      *
*                CALUMV                                                *
*                DATESH                                                *
*                HADRIV                                                *
*                RCHANV                                                *
*                BLKDT3                                                *
*                HADDEN                                                *
*                CALUMO                                                *
*                RCHANW                                                *
*                                                                      *
*----------------------------------------------------------------------*
*
      COMMON / FKSPLI  / WT     (460), NZK  (460,3)
 

#endif
