/* l3Clufi.idl */
#include "PAM.idl"
#include "hitarray.idl"
#include "pixelarray.idl"

interface l3Clufi : amiModule {
        STAFCV_T call
                (
		   in   pixelarray    pixels  
                ,  out  hitarray     hits
                
        );
};

