/*     
*
*  
*/

#include "PAM.idl"
#include "tcl_tphit.idl"
#include "hitarray.idl"

interface l3totphit: amiModule {
        STAFCV_T call
                ( in    hitarray   hitarray
                , out    tcl_tphit tpHit
                    );
};
