/* ems_lvl0.idl		W.J. Llope */

#include "PAM.idl"
#include "ems_control.idl"
#include "ems_hits_bemc.idl"
#include "ems_lvl0_thres.idl"
#include "ems_lvl0_adcs.idl"
#include "ems_lvl0_bits.idl"

interface ems_lvl0 : amiModule {
	STAFCV_T call
        ( in ems_control ems_control
        , in ems_hits_bemc ems_hits_bemc
        , in ems_lvl0_thres ems_lvl0_thres
        , out ems_lvl0_adcs ems_lvl0_adcs
        , out ems_lvl0_bits ems_lvl0_bits
	);
};

