/* ems_elect.idl		W.J. Llope */

#include "PAM.idl"
#include "ems_hits_bemc.idl"
#include "egr_globtrk.idl"
#include "ems_control.idl"
#include "ems_electron.idl"

interface ems_elect : amiModule {
	STAFCV_T call
        ( in ems_hits_bemc ems_hits_bemc
        , in egr_globtrk egr_globtrk
        , in ems_control ems_control
        , out ems_electron ems_electron
	);
};

