/* ems_interface2.idl		OGAWA, AKio */

#include "PAM.idl"
#include "g2t_event.idl"
#include "g2t_vertex.idl"
#include "g2t_track.idl"
#include "g2t_emc_hit.idl"

#include "ems_control.idl"
#include "ems_hits_bemc.idl"
#include "ems_hits_bsmd.idl"
#include "ems_hits_eemc.idl"
#include "ems_hits_esmd.idl"

interface ems_interface2 : amiModule {
	STAFCV_T call
        ( in g2t_event g2t_event
        , in g2t_vertex g2t_vertex
        , in g2t_track g2t_track
        , in g2t_emc_hit g2t_emc_hit
        , in g2t_emc_hit g2t_smd_hit
        , in g2t_emc_hit g2t_eem_hit
        , in g2t_emc_hit g2t_esm_hit
        , in ems_control ems_control
        , out ems_hits_bemc ems_hits_bemc
        , out ems_hits_bsmd ems_hits_bsmd
        , out ems_hits_eemc ems_hits_eemc
        , out ems_hits_esmd ems_hits_esmd
	);
};



