/* ems_interface.idl		       */

#include "PAM.idl"
#include "g2t_vertex.idl"
#include "g2t_track.idl"
#include "g2t_emc_hit.idl"

#include "ems_hits_bemc.idl"
#include "ems_hits_bsmd.idl"

interface ems_interface : amiModule {
	STAFCV_T call
        ( inout g2t_vertex         g2t_vertex
        , inout g2t_track          g2t_track
        , inout g2t_emc_hit        emc_hit
        , inout g2t_emc_hit        smd_hit
        , inout ems_hits_bemc      hits_bemc
        , inout ems_hits_bsmd      hits_bsmd
	);
};

