/* ems_erj.idl		W.J. Llope */

#include "PAM.idl"
#include "ems_control.idl"
#include "ems_emecor.idl"
#include "ems_jetpar.idl"
#include "ems_jetlist.idl"

interface ems_erj : amiModule {
	STAFCV_T call
        ( in ems_control ems_control
        , in ems_emecor ems_emecor
        , in ems_jetpar ems_jetpar
        , out ems_jetlist ems_jetlist
	);
};


