#!/opt/star/bin/perl
#use Env;
Import qw ( env INCLUDE LIB BIN  EXPORT BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
$build =~ s/\\/\//g;# print "OBJ = $OBJ build = $build MAIN = $MAIN\n";
(my $ObjDir = DirPath '.') =~ s/\\/\//g;# print "ObjDir = $ObjDir\n";
(my $Dir = $ObjDir) =~ s/$build\///g; #print "Dir = $Dir\n";
$ObjDir = "#" . $ObjDir; #print "ObjDir = $ObjDir\n";
(my $obj_dir = $ObjDir) =~ s/^\#//g;# print "obj_dir = $obj_dir\n";
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $pkg  = root4star;
my @GDIRS = (".","../agi/gst/agsim","../agi/gst/geant","../agi/gst/zebra");
my $PKG  = $pkg . $env->{SUFEXE};
my $SO_PKG = $PKG . "." . $env->{SUFSOLIB};# print "SO_PKG = $SO_PKG\n"; 
my $LIBPKG = $PKG . "." . $env->{SUFLIB};
$CPPPATH = $env->{CPPPATH} . ":#asps/agi";#:" . $env->{ENV}->{CERN_ROOT} . "/include:";
$CPPFLAGS = $env->{CPPFLAGS} . " -DCERNLIB_DZDOC -DCERNLIB_NONEWL -DCERNLIB_SHL -DCERNLIB_HADRON -DSTAF ";
if ($STAR_SYS =~ /egcs$/) {$CPPFLAGS .= " -DPrivateMalloc";}
print "build root4star with cons\n";
print "CPPPATH = \t$CPPPATH \nCPPFLAGS = \t$CPPFLAGS\n";
my $CXXFLAGS = $env->{CXXFLAGS};
if ($STAR_SYS =~ /^sun4x_5.$/) {$CXXFLAGS .= " -ptr" . $obj_dir;}
$env2 = $env->clone('CPPPATH'      => $CPPPATH,
		    'CPPFLAGS'     => $CPPFLAGS,
		    'CXXFLAGS'     => $CXXFLAGS
		   );
my @sources = ();
foreach my $d (@GDIRS){
  my $dir = $Dir . "/" . $d;#      print "dir = $dir\n";
  my @src  = find_sources($dir);#  my $i=0; for my $s (@src) {print "i=",$i++," src = ",$s,"\n";}
  foreach my $s (@src) {
    my $ss = $d . "/" . $s;# print "ss = $ss\n";
    next if $ss =~ /\/gst\/agsim\/agdummy\.g/ || $ss =~ /traceqc/;
    push @sources, $ss; 
  }
}
if ($#sources > -1) {
#  if ($STAR_SYS =~ /^intel_wnt$/) {
#    Library      $env2 $LIBPKG, @sources;  
#    Install $env2 $LIB, $LIBPKG;
#  }
  Program      $env2 $pkg, @sources;
  Install $env2 $BIN, $pkg;
}  
