/*  dst_monitor_had.idl
*   Table: dst_monitor_had
*/
   struct dst_monitor_had  {
       float     pressure;      /* pressure (mb)                                */
       float     gain[..];      /* e.g.  gas_gain                               */
       float     v_drift[..];   /* drift velocity                               */
       float     temp[..];      /* e.g. gas temperature, probes                 */
       float     mag_field[..]; /* field ON/OFF, probes                         */
   } ;
/*  Last mod. for dst_monitor_had:   $Date: 1998/03/27 14:21:00 $ */

