/*  dst_event.idl
*   Table: dst_event
*/
   struct dst_event  {
       long      event_type;    /* e.g. Au+Au, p+p, laser ..                    */
       long      n_run;         /* Run number                                   */
       long      n_event[2];    /* Event number, 64 bits                        */
       long      trig_mask;     /* Trigger mask                                 */
       long      date;          /* Date                                         */
       long      time;          /* Time                                         */
   } ;
/*  Last mod. for dst_event:   $Date: 1998/03/27 14:20:59 $ */

