/*  dst_mon_soft_tpc.idl           */
/*  Table: dst_mon_soft_tpc        */

/*  This table contains TPC event reconstruction monitoring quantities
 *  which are used to determine the general quality of the event
 *  reconstruction production chain (BFC).  It is filled with information
 *  for one event per table row.  This table is intended for both
 *  simulations and experimental data.
 */

 struct dst_mon_soft_tpc  {
  long   n_clus_tpc_tot;     /* Total number clusters in TPC         */
  long   n_clus_tpc_in[24];  /* Tot. # clus in TPC, inner sectors    */
  long   n_clus_tpc_out[24]; /* Tot. # clus in TPC, outer sectors    */
  long   n_pts_tpc_tot;      /* Tot. # space pts in TPC              */
  long   n_pts_tpc_in[24];   /* Tot. # space pts in TPC, inner sect. */
  long   n_pts_tpc_out[24];  /* Tot. # space pts in TPC, outer sect. */
  long   n_trk_tpc[2];       /* Total # tracks in TPC; tanl&lt;0,=&gt;0    */
  float  chrg_tpc_drift[10]; /* Charge deposited in TPC in along z   */
  float  chrg_tpc_tot;       /* Tot. charge deposition in TPC        */
  float  chrg_tpc_in[24];    /* Tot. charge dep. in TPC, inner sect. */
  float  chrg_tpc_out[24];   /* Tot. charge dep. in TPC, outer sect. */
  float  hit_frac_tpc[2];    /* Frac. hits used in TPC, tanl&lt;0,=&gt;0   */
  float  avg_trkL_tpc[2];    /* Avg. track length (cm) TPC,          */
                             /* -OR- Avg. # pts assigned,  tanl&lt;0,=&gt;0*/
  float  res_pad_tpc[2];     /* Avg. resid, pad direct, TPC          */
                             /* -OR- Avg. chisq(1) of fit,tanl&lt;0,=&gt;0 */
  float  res_drf_tpc[2];     /* Avg. resid, drift dir,  TPC          */
                             /* -OR- Avg. chisq(2) of fit,tanl&lt;0,=&gt;0 */
 } ;
/*  Last mod. for dst_mon_soft_tpc:   $Date: 1999/10/05 02:49:26 $ */

