/*  dst_rch_pixel.idl         */
/*  Table: dst_rch_pixel      */

/*  This table contains the ADC values for the pads hit in the RICH detector;
 *  it is filled with one table row per hit for each event.  The module and 
 *  channel numbers in the RICH detector are packed into the
 *  'pad' variable via the algorithm:
 *
 *       'pad' = 2^10*module + channel
 */

 struct dst_rch_pixel  {
  short pad;   /* Packed module and channel numbers (see above)  */
  short adc;   /* ADC value for the hit                          */
 } ;
/*  Last mod. for dst_pixel::   $Date: 1999/09/27 16:54:09 $ */

