/*  dst_xi_vertex.h
 *  Table: dst_xi_vertex
 *  Subscripts: b = bachelor pion or kaon
 *              v0 = lambda or antilambda
 */

   struct dst_xi_vertex {
	long id;                /* primary key id */
	long id_xi;             /* foreign key cascade vertex id */
 	long id_v0;             /* foreign key neutral daughter vertex id */
	long id_b;              /* foreign key charged daughter track id */
	float dca;              /* dca of two tracks at xi vertex */
	float rv;               /* dist. between prim. and decay vtx. */
	float b_b;              /* impact of charged track to prim. vertex */
	float b_v0;             /* impact of neutral track to prim. vertex */
	float b_xi;             /* impact of xi to prim. vertex */
        float px_b;             /* bachelor momentum at decay vertex */
        float py_b;             
        float pz_b;             
   };
