/*  dst_monitor_soft_global.idl           */
/*  Table: dst_monitor_soft_global        */

/*  This table contains Global event reconstruction monitoring quantities
 *  which are used to determine the general quality of the event
 *  reconstruction production chain (BFC).  It is filled with information
 *  for one event per table row.  This table is intended for both
 *  simulations and experimental data.
 */

 struct dst_monitor_soft_global  {
  long   n_trk_match[2];   /* Total # SVT-TPC tracks matched,tanl&lt;0,=&gt;0*/
  long   prim_vrtx_ntrk;   /* # tracks used in primary vertex fit       */
  float  prim_vrtx_cov[6]; /* Primary vrtx covariance matrix            */
  float  prim_vrtx_chisq;  /* Primary vertex chi-square of fit          */
 } ;
/*  Last mod. for dst_monitor_soft_global:   $Date: 1999/09/27 16:54:07 $ */

