/*   dst_tkf_vertex.h
*   Table: dst_tkf_vertex
*/
 struct dst_tkf_vertex {
  long  id;         /* Primary key */
  long  id_vertex;  /* Foreign key to dst_vertex entry */
  long  idd;        /* Foreign key to daughter in dst_track */
  long  idp;        /* Foreign key to parent in dst_track */
  long  pidd;       /* (geant convention) daughter PID */
  long  pidp;       /* (geant convention) parent PID */
  float dca;        /* 3d dca of two helices */
  float dcad;       /* dca of daughter from event vertex */
  float dcap;       /* dca of parent from event vertex */
  float dlf;        /* distance between last par-first daug.hit */
  float dlv;        /* distance between last parent point/vertex */
  float dE[3];      /* delta energy for different decay hypotheses */
  float p[3];       /* parent momentum */
  float pd[3];      /* daughter momentum */
  float theta;      /* reconstructed decay angle of kink */
  float theta_cm;   /* reconstructed CM decay angle */
 };
/*  Last mod. for dst_tkf_vertex:   $Date: 1999/06/21 22:21:26 $ */

