/*  dst_vertex.idl           */
/*   Table: dst_vertex       */

 struct dst_vertex  {
  long      id;            /* Primary key                             */
  long      iflag;         /* bitmask of e.g. quality information     */
  long      det_id;        /* detector id where vertex was found      */
  long      vtx_id;        /* vertex type                             */
  long      n_daughters;   /* number of charged daughter tracks       */
  float     x;             /* vertex coordinates in                   */
  float     y;             /*   STAR reference                        */
  float     z;             /*   system                                */
  float     sigma[3];      /* position uncertainty (x,y,z )           */
  float     pchi2;         /* P(chi^2,ndf) of vertex fit              */
  long      id_aux_ent;    /* F.key into auxiliary vertex table       */
 } ;
/*  Last mod. for dst_vertex:   $Date: 1998/06/03 22:26:50 $ */
