/*  dst_mon_soft_emc.idl           */
/*  Table: dst_mon_soft_emc        */

/*  This table contains EMC event reconstruction monitoring quantities
 *  which are used to determine the general quality of the event
 *  reconstruction production chain (BFC).  It is filled with information
 *  for one event per table row.  This table is intended for both
 *  simulations and experimental data.
 */

 struct dst_mon_soft_emc  {
  float  energy_emc;         /* Total energy (or ADC sum) in EMC     */
 } ;
/*  Last mod. for dst_mon_soft_emc:   $Date: 1999/10/05 02:49:24 $ */

