/*  dst_monitor_hard.idl           */
/*  Table: dst_monitor_hard        */

 struct dst_monitor_hard  {
  long      exp_run;      /* Experimental Run ID number              */
  long      gas;          /* gas mixture used in TPCs                */
  float     tpc_volts;    /* TPC central membrane voltage            */
  float     pressure;     /* pressure (mb)                           */
  float     gain[4];      /* e.g.  gas_gain                          */
  float     v_drift[4];   /* drift velocity                          */
  float     temp[4];      /* e.g. gas temperature, probes            */
  float     mag_field[4]; /* field ON/OFF, probes                    */
 } ;
/*  Last mod. for dst_monitor_hard:   $Date: 1998/06/03 13:52:01 $ */
