/*  dst_point.idl
*   Table: dst_point
*/
   struct dst_point  {
       long      id;            /* Foreign key                                  */
       long      iflag;         /* bitmask of e.g. quality information          */
       long      position;      /* sec, row prosition and pad, time sizes       */
       long      charge;        /* total charge and max_adc                     */
       float     x;
       float     y;
       float     z;
       long      sigma;         /* position uncertainty - 3 values              */
       long      variance;      /* width of cluster     - 2 values              */
       long      id_track;      /* track id to which this point belongs         */
   } ;
/*  Last mod. for dst_point:   $Date: 1998/03/27 14:21:00 $ */

/* ====================================================================================*/

/* Packing Conventions:                                                         */
/* position contains in the following information in the specified bits:        */
/* 0-3          detector id                                                     */
/* 4-10         sector (ladder) number                                          */
/* 11-20        row (layer-wafer) number                                        */
/* 21-24        number of pads */
/* 25-30        number of time slices from end to end                           */


/* charge contains the following information in the specified bits:             */
/* 0-23         Integrated/summed charge                                        */
/* 24-31        The maximum ADC value contained in the cluster                  */


/* sigma and variance are packed in the following manner:                       */
/* sigma = (int) (sig_x*1000+0.5) + (int) (sig_y*1000+0.5) * 1000 * 10  +       */
/*         (int) (sig_z*1000+0.5) * 1000000 * 10                                */
/* variance = (int) (var_x*1000+0.5) + (int) (var_y*1000+0.5) * 1000 * 10       */
/* where sig_x/y and var_x/y are *positive* values in the range [0,10] cm       */
/* with 3 digit precision for an overall possible resolution of 10 microns.     */
/* Notice that although sigma and variance are only two dimensional, sigma      */
/* is projected into three cartesian coord. in order to be compatible with the  */
/* TPC hit finder.                                                              */



/* Example of unpacking routine                                                 */
/* #define PNTA    1000            ! Shifting amount                            */
/* #define PNT_VAR_MAX 9.999       ! Maximum value you can pack into var        */

/* UNPACKING:                                                                   */
/* Usage example:                                                               */
/* sig_x = PNT_VAR_X(point.sigma);                                              */

/* Programmer's note:                                                           */
/* The extra * 10's are to take into account for the fact that our              */
/* numbers may be greater than 1.  They must still be less than                 */
/* 10, however or the values will overlap.  The casting is in a                 */
/* very specific order to ensure truncation at the proper time.                 */

/* #define PNT_VAR_X(v)    (((v) % (PNTA * 10)) / (float)PNTA )                 */
/* #define PNT_VAR_Y(v)    (((v) / (PNTA * 10)) / (float)PNTA )                 */


   
