/*  dst_summary_param.idl         */  
/*  Table: dst_summary_param      */  

 struct dst_summary_param  {
  float  eta_bins[6];     /* Pseudorapidity bins, lower->upper ranges      */
  float  pt_bins[6];      /* Trans. momen. bins, lower->upper ranges       */
  float  mt_bins[6];      /* Trans. mass bins, lower->upper ranges         */
  long   n_phi_bins;      /* # of phi bins, start at phi=0, max # is 8     */
 } ;
/*  Last mod. for dst_event:   $Date: 1998/11/30 20:48:34 $ */
