/*  dst_tof.idl
*   Table: dst_tof
*/
   struct dst_tof  {
       long      iflag;         /* quality flag                         */
       long      id_det;        /* detector element id                  */ 
       float     x;             /*                                      */
       float     y;             /*                                      */
       float     pathl;         /* tracklength from target to hit       */
       float     charge;        /* normalized charge of hit             */
       float     tof;           /* tof  from target to hit              */
       float     sig_tof;       /* sigma of tof                         */
       float     beta;          /* pathl/tof (/c)                       */
       float     sig_beta;      /* sigma of beta                        */
       float     mass2;         /* squared mass                         */
       float     sig_mass2;     /* sigma of mass**2                     */
       float     id_track;      /* track id associated to this tof entry*/
   } ;
/*  Last mod. for dst_tof:   $Date: 1998/03/27 14:21:01 $ */

