/* dst_TriggerDetectors.idl      */
/* Table: dst_TriggerDetectors   */

 struct dst_TriggerDetectors {
  float     nCtb[240];      /* CTB counter # mips                    */
  float     timeCtb[240];   /* CTB counter corrected time            */
  float     nMwc[96];       /* MWC sector # mips                     */
  float     adcVPD[48];     /* VPD counter ADC                       */
  float     timeVPD[48];    /* VPD corrected time                    */
  float     TimeEastVpd;    /* vpd minimum east time                 */
  float     TimeWestVpd;    /* vpd minimum west time                 */
  float     vertexZ;        /* Z position as determined by the VPD   */  
  float     adcZDC[6];      /* ZDC ADCs                              */
  float     tdcZDC[6];      /* ZDC TDCs                              */
  float     adcZDCEast;     /* Sum east ZDC ADCs                     */
  float     adcZDCWest;     /* Sum west ZDC ADCs                     */
  float     adcZDCsum;      /* Sum ZDC ADCs                          */
} ;
/*  Last mod. for dst_TriggerDetectors:   $Date: 1998/06/03 13:52:00 $ */
