/*  dst_sl3_event_summary.idl         */
/*  Table: dst_sl3_event_summary.idl  */

/*  This table contains TPC sector specific Level 3 information per event */

struct  dst_sl3_event_summary{
   short processorId ;   /* processor where the sector was reconstructed */
   float vertex[3];      /* xyz coordinates of the vertex used for track */
                         /* finding                                      */
   short id_param;       /* the parameter set used in the tracker */
   long  nHits ;         /* number of clusters in the sector */
   long  nTracks;        /* number of tracks found by the tracker */
   long  nPrimaryTracks ;/* number of primary tracks found by the tracker */
   float cpuTime ;       /* cpu Time used by the tracker  */
   };
