/*  dst_monitor_soft_svt.idl           */
/*  Table: dst_monitor_soft_svt        */

/*  This table contains SVT-SSD event reconstruction monitoring quantities
 *  which are used to determine the general quality of the event
 *  reconstruction production chain (BFC).  It is filled with information
 *  for one event per table row.  This table is intended for both
 *  simulations and experimental data.
 */

 struct dst_monitor_soft_svt  {
  long   n_clus_svt[4];      /* Total number clusters in each SVT layer   */
  long   n_pts_svt[4];       /* Tot. # space pts in each SVT layer        */
  long   n_trk_svt;          /* Total # tracks in SVT                     */
  float  chrg_svt_tot[4];    /* Tot. charge deposition in each SVT layer  */
  float  hit_frac_svt[4];    /* Frac. hits used in each SVT layer         */
  float  avg_trkL_svt;       /* Avg. track length (cm) SVT                */
                             /* -OR- Avg. # pts assigned                  */ 
  float  res_pad_svt;        /* Avg. residual, pad direction, SVT         */
                             /* -OR- Avg. chisq(1) of fit,                */
  float  res_drf_svt;        /* Avg. resid., drift direction, SVT         */
                             /* -OR- Avg. chisq(2) of fit,                */
 } ;
/*  Last mod. for dst_monitor_soft_svt:   $Date: 1999/09/27 16:54:07 $ */

