/*  dst_run_header.idl           */    
/*  Table: dst_run_header        */  

 struct dst_run_header  {
  char   event_type[20];  /* Event type: collision, cosmic, lasers...   */
  long   run_id;          /* Unique production run ID number            */
  long   trig_mask;       /* Trigger mask                               */
  float  luminosity[2];   /* Mean and std.dev. luminosity for events    */
  float  sqrt_s;          /* CM total energy per NN pair (GeV)          */
  long   east_a;          /* A of east moving ion                       */
  long   east_z;          /* Z of east moving ion                       */
  float  east_pol[3];     /* N,L,S polarization components, east ion    */
  float  east_pol_cov[6]; /* Polarization covariance matrix, east ion   */
  long   west_a;          /* A of west moving ion                       */
  long   west_z;          /* Z of west moving ion                       */
  float  west_pol[3];     /* N,L,S polarization components, west ion    */
  float  west_pol_cov[6]; /* Polarization covariance matrix, west ion   */
 } ;
/*  Last mod. for dst_event:   $Date: 1998/08/31 15:11:13 $ */
