/*  dst_mon_soft_ftpc.idl           */
/*  Table: dst_mon_soft_ftpc        */

/*  This table contains FTPC event reconstruction monitoring quantities
 *  which are used to determine the general quality of the event
 *  reconstruction production chain (BFC).  It is filled with information
 *  for one event per table row.  This table is intended for both
 *  simulations and experimental data.
 */

 struct dst_mon_soft_ftpc  {
  long   n_clus_ftpc[2];     /* Tot. # clus in FTPC, east/west       */
  long   n_pts_ftpc[2];      /* Tot. # space pts in FTPC, east/west  */
  long   n_trk_ftpc[2];      /* Total # tracks in FTPC east/west     */
  float  chrg_ftpc_tot[2];   /* Tot. charge dep. in FTPC, east/west  */
  float  hit_frac_ftpc[2];   /* Frac. hits used in FTPC, east/west   */
  float  avg_trkL_ftpc[2];   /* Avg. track length (cm) FTPC,east/west*/
                             /* -OR- Avg. # pts assigned             */ 
  float  res_pad_ftpc[2];    /* Avg. residual, pad direction,FTPC E/W*/
  float  res_drf_ftpc[2];    /* Avg. resid., drift direction,FTPC E/W*/
 } ;
/*  Last mod. for dst_mon_soft_ftpc:   $Date: 1999/10/05 02:49:24 $ */

