/*  dst_mon_soft_ctb.idl           */
/*  Table: dst_mon_soft_ctb        */

/*  This table contains CTB_TOF event reconstruction monitoring quantities
 *  which are used to determine the general quality of the event
 *  reconstruction production chain (BFC).  It is filled with information
 *  for one event per table row.  This table is intended for both
 *  simulations and experimental data.
 */

 struct dst_mon_soft_ctb  {
  long   mult_ctb_tot;       /* Total mult. (or ADC sum) in CTB      */ 
 } ;
/*  Last mod. for dst_mon_soft_ctb:   $Date: 1999/10/05 02:49:24 $ */

