/*  dst_monitor_soft.idl           */
/*  Table: dst_monitor_soft        */

 struct dst_monitor_soft  {
  long   n_event[2];         /* Unique 64 bit event ID number;       */
                             /* F. key to dst_event_header           */
  long   prod_run;           /* Prod. run #, F.key to dst_run_header */
  long   n_clus_tpc_tot;     /* Total number clusters in TPC         */
  long   n_clus_tpc_in[24];  /* Tot. # clus in TPC, inner sectors    */
  long   n_clus_tpc_out[24]; /* Tot. # clus in TPC, outer sectors    */
  long   n_clus_svt;         /* Total number clusters in SVT         */
  long   n_clus_ftpc[2];     /* Tot. # clus in FTPC, east/west       */
  long   n_pts_tpc_tot;      /* Tot. # space pts in TPC              */
  long   n_pts_tpc_in[24];   /* Tot. # space pts in TPC, inner sect. */
  long   n_pts_tpc_out[24];  /* Tot. # space pts in TPC, outer sect. */
  long   n_pts_svt;          /* Tot. # space pts in SVT              */
  long   n_pts_ftpc[2];      /* Tot. # space pts in FTPC, east/west  */
  float  chrg_tpc_drift[10]; /* Charge deposited in TPC in along z   */
  float  chrg_tpc_tot;       /* Tot. charge deposition in TPC        */
  float  chrg_tpc_in[24];    /* Tot. charge dep. in TPC, inner sect. */
  float  chrg_tpc_out[24];   /* Tot. charge dep. in TPC, outer sect. */
  float  chrg_svt_tot;       /* Tot. charge deposition in SVT        */
  float  chrg_ftpc_tot[2];   /* Tot. charge dep. in FTPC, east/west  */
  long   mult_ctb_tot;       /* Total mult. (or ADC sum) in CTB      */ 
  float  energy_emc;         /* Total energy (or ADC sum) in EMC     */
  long   n_trk_tpc[2];       /* Total # tracks in TPC; tanl<0,.ge.0  */
  long   n_trk_svt;          /* Total # tracks in SVT                */
  long   n_trk_ftpc[2];      /* Total # tracks in FTPC east/west     */
  long   n_trk_match[2];     /* Total # SVT-TPC tracks matched,<0,>0 */
  float  hit_frac_tpc[2];    /* Frac. hits used in TPC, tanl<0,.ge.0 */
  float  hit_frac_svt;       /* Frac. hits used in SVT               */
  float  hit_frac_ftpc[2];   /* Frac. hits used in FTPC, east/west   */
  float  avg_trkL_tpc[2];    /* Avg. track length (cm) TPC, <0,.ge.0 */
                             /* -OR- Avg. # pts assigned,   <0,.ge.0 */
  float  avg_trkL_svt;       /* Avg. track length (cm) SVT           */
                             /* -OR- Avg. # pts assigned             */ 
  float  avg_trkL_ftpc[2];   /* Avg. track length (cm) FTPC,east/west*/
  float  res_pad_tpc[2];     /* Avg. resid, pad direct, TPC <0,.ge.0 */
                             /* -OR- Avg. chisq(1) of fit,  <0,.ge.0 */
  float  res_drf_tpc[2];     /* Avg. resid, drift dir,  TPC <0,.ge.0 */
                             /* -OR- Avg. chisq(2) of fit,  <0,.ge.0 */
  float  res_pad_svt;        /* Avg. residual, pad direction, SVT    */
                             /* -OR- Avg. chisq(1) of fit,           */
  float  res_drf_svt;        /* Avg. resid., drift direction, SVT    */
                             /* -OR- Avg. chisq(2) of fit,           */
  float  res_pad_ftpc[2];    /* Avg. residual, pad direction,FTPC E/W*/
  float  res_drf_ftpc[2];    /* Avg. resid., drift direction,FTPC E/W*/
  long   prim_vrtx_qual[10]; /* Primary vertex fit quality parameters*/
  long   prim_vrtx_ntrk;     /* # tracks used in primary vertex fit  */
  float  cpu_time[20];       /* cpu time for various modules (sec)   */
 } ;
/*  Last mod. for dst_monitor_soft:   $Date: 1998/08/12 16:34:59 $ */
