/*  dst_summary_param.idl         */  
/*  Table: dst_summary_param      */  

/*  This table contains the bin domain parameters used in the event summary 
 *  table for all events processed in the BFC production run.  The information
 *  for one BFC production run is put into one row of this table.  This
 *  table is intended for both simulation runs and experimental data
 *  reconstruction runs.
 *
 *  Up to 10 bins in pt, eta and phi are allowed.  The following define
 *  the domains of the bins; the numerical values must be listed in
 *  monotonically increasing order.  If fewer than 10 bins are needed
 *  the user may simply set the last several parameters to the same value.
 *
 *  Bin domains are defined as follows:
 *
 *  For pt and eta:
 * ----------------
 *
 *          Bin #           Domain
 *            1           &lt;= bin[0]
 *            2            &gt; bin[0] &amp;&amp; &lt;= bin[1]
 *           ...             ...
 *            n            &gt; bin[n-2]
 *
 *  For phi (azimuthal angle):
 *  --------------------------
 *
 *          Bin #           Domain
 *            1            &gt; bin[0] &amp;&amp; &lt;= bin[1]
 *            2            &gt; bin[1] &amp;&amp; &lt;= bin[2]
 *           ...             ...
 *            n            &gt; bin[n-1] &amp;&amp; &lt;= bin[0]
 */

 struct dst_summary_param  {
  long   bfc_run_id;      /* Unique BFC run ID, F.key to run_header        */
  float  eta_bins[9];     /* Pseudorapidity bin domain limits              */
  float  pt_bins[9];      /* Transverse momentum bin domain limits (GeV/c) */
  float  phi_bins[10];    /* Azimuthal angle bin domain limits (deg)       */ 
 } ;
/*  Last mod. for dst_summary_param:   $Date: 1999/09/27 16:54:10 $ */

