
/*  dst_mon_soft_l3.idl   */
/*  Table: dst_mon_soft_l3 */

/*  This table contains Level 3 run information       */

struct dst_mon_soft_l3{
    long id_algorithm;        /* id of the algorithm used in global l3 */
    long id_hardware;         /* id of the hardware configuration */
    
    /* The following once are per TPC sector */
    short processorId[24] ;   /* processor where the sector was reconstructed */
    float vertex[3][24];      /* xyz coordinates of the vertex used for track */
                              /* finding                                      */
    short id_param[24];       /* the parameter set used in the tracker */
    long  nHits[24] ;         /* number of clusters in the sector */
    long  nTracks[24];        /* number of tracks found by the tracker */
    long  nPrimaryTracks[24] ;/* number of primary tracks found by the tracker */
    float cpuTime[24] ;       /* cpu Time used by the tracker  */

    /* For all TPC */
    long    nTotalHits ;         /* total number of clusters in the event */
    long    nTotalTracks;        /* total number of tracks found by the tracker */
    long    nTotalPrimaryTracks; /* number of primary tracks found by the tracker */
    short   triggermask;         /* the result of the trigger inquiry */
};
/*  Last mod. for dst_mon_soft_l3:   $Date: 1999/10/05 02:49:25 $ */

