/*  dst_vertex.idl
*   Table: dst_vertex
*/
   struct dst_vertex  {
       long      id;            /* Foreign key                                  */
       long      iflag;         /* bitmask of e.g. quality information          */
       long      id_det;        /* detector id                                  */
       long      id_vtx;        /* vertex type                                  */
       float     x;
       float     y;             /* vertex coordinates in STAR reference system  */
       float     z;
       long      sigma;         /* position uncertainty (x,y,z packed)          */
       float     pchi2;         /* P(chi^2,ndf) of vertex fit                   */
       long      id_aux_vert;   /* id of auxilliary vertex table                */
   } ;
/*  Last mod. for dst_vertex:   $Date: 1998/05/08 20:25:01 $ */
