/*  dst_vertex.idl           */
/*   Table: dst_vertex       */

/*  This table contains event reconstruction information about the
 *  various candidate vertices, including the primary vertex, V0,
 *  cascade, kinks and others.  It is filled with information for one
 *  event with one vertex candidate per table row. 
 *
 *  When alternate tracking algorithms (e.g. 3D helix, Kalman, etc.)
 *  result in different assignments of space points to tracks,
 *  additional instances of this table can be filled.  Or, additional
 *  rows can be added to the same instance with an additional,
 *  unique range of primary key (id) values.
 *
 *  Description of selected variables:
 *  ----------------------------------
 *       n_daughters     For the primary vertex this counts only tracks
 *                       from dst_track with SVT, and/or SSD, and/or TPC
 *                       segments (i.e. no FTPC tracks) that were used
 *                       in the fit.  The obvious values for the other
 *                       vertex types are used as expected.
 *
 *       iflag           For primary vertex this indicates the fitting
 *                       iteration and error reporting as follows (see
 *                       documentation for module evr_am.F):
 *                          = x1 for normal, successfully found primary vertex
 *                              during the 3rd iteration
 *                          = -x3 for initial seed value
 *                          = -x2 for first iteration value
 *                          = -x1 for second iteration value
 *                          = -x4 for failed fit with Determinant of G = 0.0,
 *                               occuring during any iteration.
 *                          = -x5 for failed error covariance matrix evaluation
 *                               during fit with Determinant of E = 0.0,
 *                               occuring during any iteration.
 *                             x is the event vertex number (for pileups). Zero
 *                               means one vertex, x=1 is one extra etc.
 *                             iflag=iflag+100   for TPC-prevertex finding
 *                             iflag=iflag+1000  for SVT-prevertex finding
 *                             iflag=iflag+10000 for FTPC-prevertex finding 
 *
 *                       (Values for V0, cascade, kinks to be determined).
 * 
 *                         
 *       det_id          Indicates which detector(s) contributed space
 *                       points to the parent/daughter tracks using a packing
 *                       algorithm and the detector ID definitions in
 *                       StDetectorDefinitions.h
 *
 *                       Vertex Type      Meaning of 'det_id'
 *                       -----------      -------------------
 *                       Primary     Comprehensive list of detectors
 *                                   (only among SVT, SSD and TPC) which
 *                                   contributed space points to all
 *                                   tracks initially selected for
 *                                   primary vertex finding using
 *                                   StDetectorDefinitions.h
 *                       V0          100*{value of det_id for (+) daugh. trk}
 *                                   +   {value of det_id for (-) daugh. trk}
 *                       Cascade     100*{V0 det_id value as above}
 *                                   + {value of det_id for batchelor trk}
 *                       Kink        100*{value of det_id for parent trk}
 *                                   +   {value of det_id for daughter track}
 *                                             
 *
 *       covar[6]        Vertex fitting covariance matrix where:
 *                       ______|___________
 *                          x  |  1  2  4     
 *                          y  |  2  3  5       covar(i)
 *                          z  |  4  5  6    
 */

 struct dst_vertex  {
  float     x;             /* vertex coordinates in                        */
  float     y;             /*   STAR (global)                              */
  float     z;             /*   coordinate system in (cm)                  */
  float     covar[6];      /* vertex position error covariance matrix      */
  float     chisq[2];      /* Chi-square per degree of freedom and probab. */
                           /* of chisq P(chi^2,ndf) of vertex fit          */
  long      id;            /* Primary key                                  */
  long      iflag;         /* bitmask of e.g. quality information, content */
                           /* varies depending on vertex type (see above)  */
  long      det_id;        /* Packed daughter track info (see above)       */
  long      id_aux_ent;    /* Foreign key into auxiliary vertex table(s)   */
  long      vtx_id;        /* vertex type ID, use StVertexDefinitions.h    */
  long      n_daughters;   /* number of charged daughter tracks (see above)*/
 } ;
/*  Last mod. for dst_vertex:   $Date: 2000/02/01 17:09:27 $ */

