/*  dst_track.idl
*   Table: dst_track
*   Comment: Parameters are given in the STAR reference system. The track parameters
*            are given at the d.c.a. (fitted) from event vertex.
*/
   struct dst_track  {
       long      id;            /* Foreign key                                  */
       long      iflag;         /* bitmask quality information                  */
       long      id_det;        /* detector id                                  */
       long      n_point;       /* number of points                             */
       long      n_max_point;   /* maximum number of points possible            */
       long      n_fit_point;   /* number of points used in fit                 */
       float     phi0;          /* phi angle at start                           */
       float     r0;            /* r reference radius at start                  */
       float     z0;            /* z-coord. at start                            */
       float     psi;           /* momentum angle at start                      */
       float     tanl;          /* tan(dip) =pz/pt at start                     */
       float     invpt;         /* 1/pt at start                                */
       float     covar[15];     /* covariance matrix                            */
       float     x_first[3];    /* coord. of first measured point               */
       float     x_last[3];     /* coord. of last measured point                */
       float     charge[2];     /* 'truncated mean' charge and variance         */
       long      id_particle;   /* id of corresponding entry in particle table  */
       long      id_vertex;     /* vertex id to which this track belongs        */
   } ;
/*  Last mod. for dst_track:   $Date: 1998/03/27 14:21:02 $ */

