/*  dst_monitor_soft.idl
*   Table: dst_monitor_soft
*/
   struct dst_monitor_soft  {
       long      n_points[..];  /* number of reconstructed points               */
       long      n_tracks[..];  /* number or reconstructed tracks               */
       long      n_vertex_track;/* number of tracks associated to event vertex  */
       float     sum_charge[..];/* sum of all charge                            */
       float     avg_res_x[..]; /* average residuals in x                       */
       float     avg_res_y[..]; /* average residuals in y                       */
   } ;
/*  Last mod. for dst_monitor_soft:   $Date: 1998/03/27 14:21:00 $ */

