/*  dst_scalers.idl
*   Table: dst_scalers
*/
   struct dst_scalers  {
       long      lumin_table[4096];     /* Luminosity look up table     */
       long      strobe_table[4096];    /* RHIC strobe look up table    */
       long      trigger_table[4096];   /* CTB etc info look up table   */
       long      spare_table[4096];     /* spare                        */
       long      prescalers[10];        /* prescaler information        */
   } ;
/*  Last mod. for dst_scalers:   $Date: 1998/03/27 14:21:01 $ */

