/*  dst_monitor.idl
*   Table: dst_monitor
*/
   struct dst_monitor  {
       float     pressure;      /* pressure (mb)                                */
       float     gain[..];      /* e.g.  gas_gain                               */
       float     v_drift[..];   /* drift velocity                               */
       float     temp[..];      /* e.g. gas temperature, probes                 */
       float     mag_field[..]; /* field ON/OFF, probes                         */
       long      n_points[..];  /* number of reconstructed points               */
       long      n_tracks[..];  /* number or reconstructed tracks               */
       long      n_vertex_track;/* number of tracks associated to event vertex  */
       float     sum_charge[..];/* sum of all charge                            */
       float     avg_res_x[..]; /* average residuals in x                       */
       float     avg_res_y[..]; /* average residuals in y                       */
   } ;
/*  Last mod. for dst_monitor:   $Date: 1998/03/27 14:20:59 $ */

