/*  dst_run_summary.idl         */  
/*  Table: dst_run_summary      */  

/*  This table contains crude, overall event reconstruction summary
 *  information about a given BFC production run.  The information for
 *  one BFC production run is put into one row of this table.  This table is
 *  intended for both simulation runs and experimental data reconstruction
 *  runs.
 *
 *  Note that the production software version, run control parameters,
 *  calibrations constants, magnetic field map, etc. are to be accessed
 *  through the STAR Data Base, not here.
 *
 *  The mean and standard deviation multiplicities (or energy deposition
 *  in the case of the EMC) for each detector subsystem for all events
 *  successfully processed in the BFC production run are stored in the
 *  variables mean_mult and rms_mult where the array index used
 *  for each detector is determined by the detector ID assignment defined
 *  in StDetectorDefinitions.h .
 */

 struct dst_run_summary  {
  long   bfc_run_id;      /* Unique BFC run ID, F.key to run_header          */
  long   n_events_tot;    /* Total number of events in the BFC prod. run     */
  long   n_events_good;   /* Total number events successfully processed      */
  long   date[2];         /* Start/stop date for processing                  */
  long   time[2];         /* Start/stop time of day (sec)                    */
  float  cpu_total;       /* Total cpu sec for production run                */
  float  east_pol_L;      /* Avg magnitude of east beam Longitudinal Pol     */
  float  east_pol_T;      /* Avg magnitude of east beam Transverse Pol       */
  float  west_pol_L;      /* Avg magnitude of west beam Longitudinal Pol     */
  float  west_pol_T;      /* Avg magnitude of west beam Transverse Pol       */
  float  luminosity;      /* Avg luminosity during experiment for events     */
                          /* in production run, 1.0/[cm^2 sec]               */
  float  eta[2];          /* Mean and std.dev. of &lt;eta&gt; for all events */
  float  pt[2];           /* Mean and std.dev. of &lt;pt&gt; for all events  */
  float  num_vert[2];     /* Mean and std.dev. of total # vertices           */
  float  mean_mult[30];   /* Mean multiplicity (energy) per detector for run */ 
  float  rms_mult[30];    /* RMS multiplicity (energy) per detector for run  */
 } ;
/*  Last mod. for dst_run_summary:   $Date: 1999/09/27 16:54:09 $ */

