/*egr_propagete.idl              */
/*  Table: egr_propagate           */

/* 
 */

 struct egr_propagate  {
  float       r;      /* reference radius */
  float       x[3];   /* coordinates of target points */
  float       z;      /* constant z of target plane */
  short       iflag;  /* switch:propagate to point/radius/plane */
};
