/*   egr_egrpar.idl
*   Table: egr_egrpar
*/
    struct egr_egrpar {
       long      debug[9];   /* flags for debug printing */
       long      minfit;     /* min no. of points on track */
       long      mxtry;      /* max no. of attempts to fit */
       long      useglobal;    /* set if to usematching to be used */
       long      scenario;   /* Specifies egr running scenarios */
       long      useemc;     /* set if EMC used in refit */
       long      usesvt;     /* set if SVT used in refit */
       long      usetof;     /* set if TOF used in refit */
       long      usetpc;     /* set if TPC used in refit */
       long      usevert;    /* Set if primary vertex used in refit */
       float     prob[2];    /* probability cut in fit */
       float     svtchicut;  /* SVT chi2 cut for adding SVT-only tracks */
   } ;
/*  Last mod. for egrpar: $Date: 1997/12/31 14:33:28 $ */

