/*   epi_hypo_pid.idl
*   Table: epi_hypo_pid
*        description: Contains all mass hypotheses for each   
*/

   struct epi_hypo_pid {
       long      det;        /* detector:1-5 for svt,tpc,tof,emc,xtpc */
       long      gid;        /* Geant pid code # for this hypothesis */
       long      id;         /* identifier for rows corres. to globtrk */
       long      id_global_pid;/* foreign key to global pid table */
       long      method;     /* report options in detec. specific pid */
       float     nsigma;     /* # std.dev. from mean;(+)higher;(-)lower */
       float     prob;       /* Probability for this mass hypothesis */
       float     weight;     /* calculated weight for this detector &trk */
   } ;
/*  Last mod. for hypo_pid:  $Date: 1997/12/31 14:33:28 $ */

