/*   epi_epipar.idl
*   Table: epi_epipar
*        description: Control parameters for global PID module
*/

   struct epi_epipar {
       long      ctrl_conflict; /* =0 ignores conflicts,=1 resolves conflic     */
       long      ctrl_sharp;    /* sharpness filter option                      */
       long      ctrl_wt;       /* selects relative weights for detectors       */
       float     nsig_max;      /* #sigma cut-off                               */
       float     qfact_min;     /* min. fraction of tpc trk - mc to be good     */
       float     sharp_min;     /* minimum sharpness cut-off                    */
       float     w_emc;         /* Relative detector weight for the EMC         */
       float     w_svt;         /* Relative detector weight for the SVT         */
       float     w_tof;         /* Relative detector weight for the TOF         */
       float     w_tpc;         /* Relative detector weight for the TPC         */
       float     w_xtpc;        /* Relative detector weight for the XTPC        */
       float     weight_min;    /* min. weight cut-off used in conflict res     */
   } ;
/*  Last mod. for epipar: $Date: 1997/12/31 14:33:28 $ */

