/*   est_ev.idl
*   Table: est_ev
*/
  struct est_ev {
	long	id;     /* id de est_match */
	long	idtpc; /* id de tptrack*/ 
	long    id_mctrsvt[10]; /* idmctrack de scs_spt */
	long	id_mctrtpc;  /* idmctrack de tpc */
	long	ng;	/* nbre de points dans scs_spt */
	long	nf;	/* nbre de points trouves par est */
	long	nc;	/* nbre de points trouves corrects */
	long	nseg;	/* nbre de segments dans la tpc-trace*/
	long	layer;
	long	binpt;	
	float 	q;
	float	tanl;   /* tanl de est_match*/
	float	tanl_old;
	float	r0;
	float 	r0_old;
	float   z0;
 	float   z0_old;
	float	chisq[2];
	float	phi0;
	float 	psi;
	long	pid;    /* particle id from geant */
	long	t2flag;  /* flag de est */
	float	invpt;   /* invp_tpc de est_match */
	float	ginvpt;   /* pas encore rempli */
	long 	status;  /* status */
	long 	sec; /* vertex id =1 primary track <>1 secondary */
	long	comp; /* complet ou non */
	float   tpc_dedx[2]; /*dedx de la tpc*/
	float   perf_de[10]; /*de scs_spt pour les perf_scs_id*/
	float   svt_de[10]; /*de scs_spt pour les id_hit*/
	long	svt_h[10];
	long	perf_h[10];
	long	nrec;
	long	id_det[10]; 	
   } ;
 
/*  Last mod. for est_match Sun Nov 23 13:53:54 MET 1997 */

