/*   est_ctrl.idl
*   Table: est_ctrl
*	almost the same as svm_ctrl
*/
  struct est_ctrl {
	long 	  ktrl1;	/* control switch for printing */
	long	  pass;
	long	  nhole[8];
        float 	  apmin[14];
        float     afacmax1[14];
        float     afacmax2[14];
        float     afacmax3[14];
        float     afacmax4[14];
        long	  stupid;     /* =1 - perfect tracking, =0 - real tracking */
        float     ext[14];        
       	float     ptcut;	     /* minimum pt value for the tracker */
	float     tanl_cut;
	long      pid_cut;
       	long	  min_nrec;   /* minimum number of tpc points in track to be taken into account */
       	long 	  max_nrec;   /* maximum number of tpc points in track to be taken into account */
       	long	  maxloop;    /* number of loops in pt */
       	long	  minlay;     /* innermost layer to scan */
       	long	  maxlay;     /* outermost layer to scan */
       	long	  mxfnd;       /* maximum number of found hits per tracks */
	long	  maxass;		/* maximum of sharing for a given hit */
       	float	  aphi1[14];   /* difference in phi for each pt step */
	float	  az1[14];		/* difference in z for each pt step */
       	float	  aphi2[14];   /* difference in phi for each pt step */
	float	  az2[14];		/* difference in z for each pt step */
       	float	  aphi3[14];   /* difference in phi for each pt step */
	float	  az3[14];		/* difference in z for each pt step */
       	float	  aphi4[14];   /* difference in phi for each pt step */
	float	  az4[14];		/* difference in z for each pt step */
	long	  current_loop;	/* current loop in pt */
	long	  prerefit[14];	/* flag for prerefitting */
        float     bmag;       /* magnetic field (T) */
        float     rifc;       /* radial position of tpc IFC (cm) */
        float     rlgas;      /* radiation length of gas (cm) */
        float     rlifc;      /* radiation length of tpc IFC (cm) */
        float     rltpc_gas;  /* Radiation length of TPC gas (cm) */
	float     tifc;       /* thickness of tpc inner field cage (cm) */
        long      layer;	     /* current layer */
	float 	  svt_er;     /* svt resolution error */
   } ;

/*  Last mod. for svm_ctrl: $Date: 1999/02/18 00:23:15 $  */


