/*   est_match.idl
*   Table: est_match
*/
  struct est_match {
	long	id;
	long	id_tpctrack;
	long	pid; /* particle id from geant */
	long 	sec; /* vertex id =1 primary track <>1 secondary */
	long	id_hit[10];
	long	n_svt_hits;
	long	binpt;
	float	z_4th[10];
	float	phi_4th[10];
	float	r_4th[10];
	long 	id_det[10];
	float   ang_det[10];  /* angle of the detector */
	long    id_mctrtpc;
	long	id_mctrsvt[10];
	float 	phi_err[10];
	float	z_err[10];
/*	float 	err_fac[10];*/         /* error factor for each point */
	float 	dist[10];*/
	long	rflag[10]; /* refitter flag for each point */
	float 	q;
	float 	r0;
	float	phi0;
	float	z0;	
	float 	psi;
	float	tanl;
	float	invp;	
	float 	invp_tpc;	/* original tpc invp */
	long	perf_svt_hits;
	float 	perf_svt_x[10];
	float 	perf_svt_y[10];
	float 	perf_svt_z[10];
	float 	perf_proj_x[10];
	float 	perf_proj_y[10];
	float 	perf_proj_z[10];
	long	perf_svt_waf[10];
	long	perf_scs_id[10];
	long	layer; 	/* last layer */
	long	flag;   /* =1 track already used */
   } ;
 
/*  Last mod. for est_match Sun Nov 23 13:53:54 MET 1997 */

