/*  ev0_track3
*  Local track table for ev0
*/


      struct ev0_track3{
        long id;
	long det_id;
        long pid;
        float r0;
        float phi;
        float z0;
        float psi;
        float tanl;
        float q;
        float xc[2];
        float rc;
	float dca;
	float dcachis;
	float p;
	float sagitta;
        float chisq;
        float ndef;
        float cov[15];
      };