/*  ev0_track
*  Local track table for ev0
*/


      struct ev0_track{
        long id;
        long pid;
        float r0;
        float phi;
        float z0;
        float psi;
        float tanl;
        float q;
        float xc[2];
        float rc;
	float dca;
	float p;
	float sagitta;
      };