/*  event_header.idl        */
/*  Table: event_header     */

/*  This table contains minimal information to uniquely identify an
 *  event.  The information in this table does not depend on results
 *  of any offline analysis and is fixed for all time.  It is filled
 *  with information for one event per table row.  This table is intended
 *  for both simulations and experimental data.
 */

 struct event_header  {
  char   event_type[40];    /* Event type: collision, cosmic, lasers...    */
  long   n_event;           /* Unique  event ID number                     */
  long   exp_run_id;        /* Reference to the experiment run ID number   */
  long   time;              /* Unique time stamp for event                 */
  long   trig_mask;         /* Trigger mask                                */
  long   bunch_cross;       /* Beam-Beam bunch crossing number             */
 } ;
/*  Last mod. for event_header:   $Date: 1999/10/01 02:14:07 $ */

