/*   evr_evrpar.idl
*   Table: evr_evrpar
*/
 struct evr_evrpar {
       long      match;      /* use TPC-SVT matched tracks */
       long      minhit;     /* minimum no. of hits */
       long      use;        /* which tracks are used */
       float     cut2;       /* select tracks for 2nd vertex fit */
       float     cut3;       /* select tracks for 3rd vertex fit */
       float     cutxy;      /* select tracks for vertex fitting */
       float     cutz;       /* select tracks for vertex fitting */
       float     ptmin;      /* minimum pt of individual tracks */
   } ;

/*  Last mod. for evrpar: $Date: 1997/12/31 14:33:28 $ */


