/*   evr_privert.idl
*   Table: evr_privert
*/
 struct evr_privert{
       char      use[16];    /* which tracks were used */
       long      id;         /* primary key for primary vertices */
       long      match;      /* matched TPC-SVT tracks */
       long      ndegf;      /* no. deg. of freedom for fit */
       long      ntch;       /* no. of charged tracks attached */
       float     chisq;      /* chisq of primary vertex fit */
       float     covar[6];   /* Covariance matrix of primary vertex fit */
       float     ptmin;      /* minimum pt of individual tracks */
       float     x;          /* x coordinate of primary vertex */
       float     y;          /* y coordinate of primary vertex */
       float     z;          /* z coordinate of primary vertex */
   } ;
/*  Last mod. for privert: $Date: 1997/12/31 14:33:28 $  */

