/*   exi_exipar.idl
*   Table: exi_exipar
*   description: Execution flow control parameters for   
*                cascade reconstruction                  
*/

   struct exi_exipar {
       long      use_pid;    /* logical flag to control usage of global pid */
       float     dca_max;    /* cut on dca between the two tracks */
       float     bxi_max;    /* cut on impact param. of xi from prim. vertex */
       float     rv_xi;      /* cut on min. dist. of decay from prim. vertex */
       float     rv_v0;      /* cut on min. dist. of decay from prim. vertex */
       float     dmass;      /* v0 mass cut +/- [dmass] */
       float     bpn_v0;     /* cut on v0 pion daught. impact param. */
       float     pchisq;     /* cut on chi^2 probability of vertex fit*/
   } ;
/*  Last mod. for exi_exipar: $Date: 1999/02/12 19:12:57 $ */

