/*  exi_aux.h
 *  Table: exi_aux
 *  Subscripts: b = bachelor pion or kaon
 *              v0 = lambda or antilambda
 *              xi = cascade
 *              om = omega
 */

   struct exi_aux {
	long id;                /* primary key id */
	long id_xi;             /* foreign key cascade vertex id */
	long id_b;              /* foreign key charged daughter track id */
	long id_v0;             /* foreign key neutral daughter vertex id */
        long det_id;            /* detector id flag */
	long gpid_b;            /* global pid of charged track of the decay */
	long ndegf;             /* number of degrees of freedom for fit */
        long charge;            /* charge */
	float dca;              /* dca of two tracks at xi vertex */
	float rv;               /* radial dist. between prim. and decay vtx. */
	float b_b;              /* impact of charged track to prim. vertex */
	float b_v0;             /* impact of neutral track to prim. vertex */
	float b_xi;             /* impact of xi to prim. vertex */
	float sag_b;            /* sagitta of charged track */
	float px;               /* mometum of xi at decay vertex */
	float py;
	float pz;
	float px_b;             /* momentum of charged track at xi vertex */
	float py_b;
	float pz_b;
	float px_v;             /* momentum of neutral track at xi vertex */
	float py_v;
	float pz_v;
	float alpha;            /* Armenteros variable */
	float ptarm;            /* Armenteros pt */
	float mass_xi;          /* invariant mass of cascade */
	float mass_om;          /* invariant mass of omega */
        float mass_v0;          /* invariant mass of v0 */
	float rap_xi;           /* rapidity of cascade */
	float rap_om;           /* rapidity of omega */
	float tau_xi;           /* proper lifetime of cascade */
	float tau_om;           /* proper lifetime of omega */
	float costh;            /* cosine of cms decay angle */
   };
