//
// $Id: FlowTag.idl,v 1.1 1999/02/09 21:42:21 wenaus Exp $
//
// Event by event flow tag
//
// $Log: FlowTag.idl,v $
// Revision 1.1  1999/02/09 21:42:21  wenaus
// Final (?) versions of MDC2 PWG tags
//
//

struct FlowTag {
    float qVector[3][2];
    float qxa[5], qxb[5], qxc[5], qxd[5];
    float qya[5], qyb[5], qyc[5], qyd[5];
    long  na[5], nb[5], nc[5], nd[5];
    float spta[5], sptb[5], sptc[5], sptd[5];
};
