//
// $Id: FlowTag.idl,v 1.2 1999/11/16 20:59:40 snelling Exp $
//
// Event by event flow tag
//
// $Log: FlowTag.idl,v $
// Revision 1.2  1999/11/16 20:59:40  snelling
// Removed unused tags and added 6th harmonic
//
// Revision 1.1  1999/02/09 21:42:21  wenaus
// Final (?) versions of MDC2 PWG tags
//
// The tags are defined for 4 subevents (a,b,c,d) and 6 harmonics

struct FlowTag {
  float qxa[6], qxb[6], qxc[6], qxd[6];     /* x component Q vector */
  float qya[6], qyb[6], qyc[6], qyd[6];     /* y component Q vector */
  long  na[6], nb[6], nc[6], nd[6];         /* multiplicity */
  float spta[6], sptb[6], sptc[6], sptd[6]; /* sum pt */
};
