// 
// $Id HeavyTag.idl$
// Tags for Heavy Flavor
// 
// Notes:
// - Cuts for Tracks:
// flag>0
// tpc fit points >=15
// |eta|<1.5
// 
//
// $Log: HeavyTag.idl,v $
// Revision 1.1  2004/07/29 14:06:26  jeromel
// Added HeavyTag table from MC
//

struct HeavyTag {
  long   mNumberOfTracksAboveThres[3];   // prim tracks with p > threshold (m_charm, m_bottom, 7 GeV)
  long   mNumberOfTrackToTowerMatches;   // prim tracks with p>2 GeV pointing to tower with ADC>100
  float  mLargestPairMass;               // largest invariant mass from unlike-sign pairs in event
};
  
