//
// $Id: HighPtTag.idl,v 1.2 1999/02/09 21:42:23 wenaus Exp $
//
// High Pt / Spectra group tag
//
// $Log: HighPtTag.idl,v $
// Revision 1.2  1999/02/09 21:42:23  wenaus
// Final (?) versions of MDC2 PWG tags
//
// Revision 1.1  1999/02/08 14:48:57  wenaus
// New tag tables
//

struct HighPtTag {
    long  Ntracks_gt_thres[4];    /* no. trks,      total and above 3 Pt thresholds*/
    long  Ntracks_lt_thres[4];    /* no. trks,      below 4 P thresholds */
    long  Npion_pos_gt_thres[4];  /* no. pion+,     total and above 3 Pt thresholds*/
    long  Nkaon_pos_gt_thres[4];  /* no. kaons+,       "    "    "   "  "     " */
    long  Nprot_pos_gt_thres[4];  /* no. protons+,     "    "    "   "  "     " */
    long  Npion_neg_gt_thres[4];  /* no. pions-,     total and above 3 Pt thresholds*/
    long  Nkaon_neg_gt_thres[4];  /* no. kaons-,       "    "    "   "  "     " */
    long  Nprot_neg_gt_thres[4];  /* no. anti-protons,     "    "    "   "  "     " */
    long  Nsmdclus_w_track;    /* no. SMD clusters with tracks */
    long  Nsmdclus_wout_track; /* no. SMD clusters without tracks */
    long  Ntracks_towerEp;     /* no. trks, EMC tower-E/track-p above 0.8 */
    long  Nv0_gt_thres[4];     /* no. v0's,        "    "    "   "  "     " */
    long  Nrich_gt_thres[4];   /* no. trks,        " " " " " ", point to RICH */
    long  Ntof_gt_thres[4];    /* no. trks,        " " " " " ", point to TOF */
    long  Nemc_gt_thres[4];    /* no. EMC towers,total and above 3  E thresholds*/
    long  Nftpc_gt_thres[4];   /* no. FTPC trks, total and above 3 Pt thresholds*/
    float CTB_mult[3];          /* [1]= total no. chgd part. in CTB */
                                /* [2]= CTB mult, slats in front of EMC */
                                /* [3]= CTB mult, slats in front of RICH */
    float ZDC[2];               /* ZDC signal sums, east and west */
    float EMC_Et;               /* EMC total transverse energy */
    float EMC_Echgd;            /* EMC total charged energy */
    float EMC_Eneut;            /* EMC total neutral enrgy */
    float Ntracks_with_strange_dedx;
    float Njets_gt_thres[4];   
};
