//
// $Id: HighPtTag.idl,v 1.3 2004/07/30 23:02:53 calderon Exp $
//
// High Pt / Spin group tags
//
// $Log: HighPtTag.idl,v $
// Revision 1.3  2004/07/30 23:02:53  calderon
// Revision for processing of RunIV data.
//
// Revision 1.2  1999/02/09 21:42:23  wenaus
// Final (?) versions of MDC2 PWG tags
//
// Revision 1.1  1999/02/08 14:48:57  wenaus
// New tag tables
//

struct HighPtTag {
    float HighPtTrack;       /* Pt of Highest Pt Track */
    float MaxRawEtBEMCTower; /* Maximum Tower Raw Et of BEMC */ 
    float MaxRawEtEEMCTower; /* Maximum Tower Raw Et of EEMC */ 
};
