/*  particle_dst_param.idl
 *
 *  Table:  particle_dst_param
 *
 *  This table is used with the particle_dst_filler module.
 *  It contains momentum space acceptance limits and a switch
 *  control to determine if neutral particles are transmitted
 *  to the dst_track table output.
 *
 */

  struct particle_dst_param   {
   long   switch_neutrals;  /* if=0, neutrals not copied, =1 then copy */
   float  pt_min;           /* pt minimum acceptance in GeV/c          */
   float  pt_max;           /* pt maximum acceptance in GeV/c          */
   float  eta_min;          /* pseudorapidity minimum acceptance       */
   float  eta_max;          /* pseudorapidity maximum acceptance       */
   float  phi_min;          /* azimuthal minimum acceptance in degrees */
   float  phi_max;          /* azimuthal maximum acceptance in degrees */
 } ;
/*  Last mod. for particle_dst_param:   $Date: 1998/08/27 23:04:24 $ */
