//
// $Id: PCollTag.idl,v 1.4 1999/02/09 22:21:42 wenaus Exp $
//
// Peripheral collections group tag
//
// $Log: PCollTag.idl,v $
// Revision 1.4  1999/02/09 22:21:42  wenaus
// PWG tag definition fixes
//
// Revision 1.3  1999/02/09 21:42:23  wenaus
// Final (?) versions of MDC2 PWG tags
//
// Revision 1.2  1999/02/08 18:46:01  wenaus
// Fix structure name
//
// Revision 1.1  1999/02/08 14:48:57  wenaus
// New tag tables
//

struct PCollTag {
    long chargedMultiplicity;
    long numberOfPhotonClusters;
    long numberOfElectronsInEmc;
    long numberOfMwpcHits;
    float        vectorSumOfPt;
    float        primaryVertex[3];
    float        zdc1Energy;
    float        zdc2Energy;
};
