//
// $Id: PCollTag.idl,v 1.3 1999/02/09 21:42:23 wenaus Exp $
//
// Peripheral collections group tag
//
// $Log: PCollTag.idl,v $
// Revision 1.3  1999/02/09 21:42:23  wenaus
// Final (?) versions of MDC2 PWG tags
//
// Revision 1.2  1999/02/08 18:46:01  wenaus
// Fix structure name
//
// Revision 1.1  1999/02/08 14:48:57  wenaus
// New tag tables
//

struct PCollTag {
    unsigned int chargedMultiplicity;
    unsigned int numberOfPhotonClusters;
    unsigned int numberOfElectronsInEmc;
    unsigned int numberOfMwpcHits;
    float        vectorSumOfPt;
    float        primaryVertex[3];
    float        zdc1Energy;
    float        zdc2Energy;
};
