/*  point_track_index.idl                 */
/*  Table: point_track_index              */

/*  This table contains event reconstruction information about the
 *  space point to track relationships.  This is filled whenever
 *  multiple track instances are saved in the DST which may have
 *  different space point assignments.  This table is filled with
 *  one row for each space point - track assignment.  A new 
 *  instantiation is written for each track table instance that uses
 *  different point-track assignments.  This includes different
 *  track fitting methods applied to the same set of 'seed' tracks in
 *  which different space points have been removed by outlier cuts.
 */

 struct point_track_index  {
  long      id_point;      /* F.key to dst_point table       */
  short     id_track;      /* F.key to dst_track table       */ 
 } ;
/*  Last mod. for point_track_index: $Date: 1999/12/23 19:29:13 $ */

