/*  run_header.idl           */    
/*  Table: run_header        */  

/*  This table contains minimal information to identify and briefly
 *  characterize each offline reconstruction production run using the
 *  BFC or similar production chain.  The information for one BFC
 *  production run is put into one row of this table.  This table is
 *  intended for both simulation runs and experimental data reconstruction
 *  runs.
 *
 *  A fundamental requirement is that the event type (e.g. A+A collision,
 *  p+p collision, A+A peripheral, TPC event, EMC only event, calibrations,
 *  etc.) and trigger be the same for all events in the production run.
 *  Average beam polarization magnitudes and average beam-beam collision 
 *  luminosity are included for the experimental run period corresponding
 *  to the events in the production run.  Quantitative values for the 
 *  specific run time and bunch crossing must be obtained from the Conditions 
 *  Data Base.  The magnetic field values used by each tracking detector
 *  in the track fitting procedure is stored here also, where this implies
 *  that only one magnet field map is allowed per BFC production run.
 */

 struct run_header  {
  char   event_type[40];  /* Event type: collision, cosmic, lasers...   */
  long   bfc_run_id;      /* Unique BFC production run ID number        */
  long   exp_run_id;      /* Reference to the experiment run ID number  */
  long   trig_mask;       /* Trigger mask for events in BFC prod. run   */
  long   east_a;          /* A of east moving ion                       */
  long   east_z;          /* Z of east moving ion                       */
  long   west_a;          /* A of west moving ion                       */
  long   west_z;          /* Z of west moving ion                       */
  float  sqrt_s;          /* CM total energy per NN pair (GeV)          */
  float  mag_field[4];    /* Magnetic field used by TPC, SVT-SSD,       */
                          /* FTPC-East and FTPC-West, respect. in Tesla */
 } ;
/*  Last mod. for run_header:   $Date: 1999/09/27 16:54:11 $ */

