//
// $Id: ScaTag.idl,v 1.2 1999/02/09 21:42:24 wenaus Exp $
//
// Scale correlation analysis tag
//
// $Log: ScaTag.idl,v $
// Revision 1.2  1999/02/09 21:42:24  wenaus
// Final (?) versions of MDC2 PWG tags
//
// Revision 1.1  1999/02/08 14:48:58  wenaus
// New tag tables
//

struct ScaTag {
    float scaAnalysisMatrix[3][4][12];          
    float chargedParticles_Means[10];
    float chargedParticles_Sigmas[10];
};
