/*   smdst_v0.h
*   Table: smdst_v0
*/
   struct smdst_v0 {
	long id; /* Primary key id */
        long run; /* run number */
        long event[2]; /* event number */
	long id_vertex; /* vertex id */
	long pidp; /* global pid of positive track of the decay */
	long pidn; /* global pid of negative track of the decay */
        long npn;    /* number of points (packed) on the neg daughter */
        long npp;    /* number of points (packed) on the pos daughter */
        long nflag;   /* flag info from dst track for neg daughter */
        long pflag;   /* flag info from dst track for pos daughter */
	float alpha; /* Armenteros variable */
	float ptarm; /* Armenteros pt */
	float bn; /* impact param of negative track from vertex */
	float bp; /* impact param of positive track from vertex */
	float dca; /* dca of two tracks at V0 vertex */
	float bv0; /* impact param of V0 from vertex */
	float mala; /* Inv. mass of rec. lambda */
	float malb; /* Inv. mass of rec. lambda-bar */
	float mak0; /* Inv. mass of rec. k0s */
	float pxn; /* measured momentum of neg track at v0 ver */
	float pyn;
	float pzn;
	float pxp; /* measured momentum of pos. track at v0 vtx */
	float pyp;
	float pzp;
	float px; /* px,py,pz of V0 at reconstr. vertex */
	float py;
	float pz;
	float x; /* x,y,z position of vertex */
	float y;
	float z;
	float dv0; /* distance of v0 decay from main vertex */
	float sagp; /* Sagitta of +ve track */
	float sagn; /* Sagitta of -ve track */
	float rapla; /* Rapidity if a lambda */
	float raplb; /* Rapidity if a lambda-bar */
	float rapk0; /* Rapidity if a k0s */
	float theta; /* Opening angle of decay in the lab coords */
   } ;
/*  Last mod. for smdst_v0:   $Date: 1999/10/01 21:36:40 $ */








