//
// Strangeness group tags
//

struct StrangeTag {
    long  NV0;             // no. v0's

    long  NbelowK0;        // no. v0's with mass just below k0
    long  NK0;             // no. v0's with mass near k0
    long  NaboveK0;        // no. v0's with mass just above k0
    long  NbelowLa;        // no. v0's with mass just below lambda
    long  NLa;             // no. v0's with mass near lambda
    long  NaboveLa;        // no. v0's with mass just above lambda
    long  NbelowLb;        // no. v0's with mass just below lambda-bar
    long  NLb;             // no. v0's with mass near lambda-bar
    long  NaboveLb;        // no. v0's with mass just above lambda-bar
    long  NbelowXi;        // no. cascade with mass just below Xi
    long  NXi;             // no. cascade with mass near Xi
    long  NaboveXi;        // no. cascade with mass just above Xi
    long  NbelowXibar;     // no. cascade with mass just below Xi-bar
    long  NXibar;          // no. cascade with mass  Xi-bar
    long  NaboveXibar;     // no. cascade with mass just above Xi-bar
    long  NbelowOm;        // no. cascade with mass just below Omega
    long  NOm;             // no. cascade with mass near Omega
    long  NaboveOm;        // no. cascade with mass just above Omega
    long  NbelowOmbar;     // no. cascade with mass just below Omega-bar
    long  NOmbar;          // no. cascade with mass  Omega-bar
    long  NaboveOmbar;     // no. cascade with mass just above Omega-bar

    float MaxPtK0;         // maximum pt v0s consistent with K0
    float MaxPtLa;         // maximum pt v0s consistent with lambda
    float MaxPtLb;         // maximum pt v0s consistent with lambda-bar
    float MaxPtXi;         // maximum pt v0s consistent with Xi
    float MaxPtXibar;      // maximum pt v0s consistent with Xi-bar
    float MaxPtOm;         // maximum pt v0s consistent with Omega
    float MaxPtOmbar;      // maximum pt v0s consistent with Omega-bar

    long  NKinkPos;        // no. of positive kink candidates
    long  NKinkNeg;        // no. of negative kink candidates

    float MaxPtKinkPos;    // maximum pt postive kink candidates
    float MaxPtKinkNeg;    // maximum pt negative kink candidates

    float range;           /* range used for defining below,near,above mass
                            below = { mass(1 - 3*range) , mass(1 -   range) }
                            near  = { mass(1 -   range) , mass(1 +   range) }
                            below = { mass(1 +   range) , mass(1 + 3*range) } */
};
