/*   tkf_tkfpar.idl
*   Table: tkf_tkfpar
*        description: input cuts for tkf package mainly       
*                              contains various starting values        
*/
	struct tkf_tkfpar {
       float     dcaParentDaughterMax;  
       float     parentPtMin;   
       float     vertexRMax2D;  
       float     vertexRMin2D;  
       float     thetaMin;
       short     numOfPadRows;  	
       float     parentDipAngleMax;	
       float     impactCut;
       float     parentLastDaughterStart2D;
       float     parentLastDaughterStartZ;
       float     projectPointZDiff;
       float     distanceKinkParent2D;
       float     distanceKinkDaughter2D;
       float     distanceKinkParentZ;
       float     distanceKinkDaughterZ;
 } ;
/*  Last mod. for tkf_tkfpar:   $Date: 1999/06/21 22:21:27 $  */

