/*   tkf_tkfout.idl
*   Table: tkf_tkfout
*        description: Output table from kink finder. Contains 
*            	      reconstructed parameters of kink candidates
*/
   struct tkf_tkfout {
       long      flag;       /* Quality flag */
       long      iaux[3];    /* integer auxiliary variables */
       long      id;         /* foreign key */
       long      itrk_d;     /* track id of daughter */
       long      itrk_p;     /* track id of parent track */
       long      itrue;      /* evaluation flag for background/contamin. */
       long      mcid_d;     /* mc track number for daughter */
       long      mcid_p;     /* mc track number for parent (mkine) */
       long      mcpidd;     /* mc pid for daughter */
       long      mcpidp;     /* mc pid for parent (GEANT conventions) */
       long      ndf;        /* number of degrees of freedom/vertex fit */
       long      npointd;    /* number or points on daughter track */
       long      npointp;    /* number of points on parent track */
       long      pidd;       /* (geant) daughter PID */
       long      pidp;       /* (geant convention) parent PID */
       float     aux[3];     /* auxiliary variables */
       float     chi2;       /* chi square per ndf */
       float     dca;        /* distance of closest approach at vertex */
       float     dcad;       /* dca of daughter from event vertex */
       float     dcap;       /* dca of parent from event vertex */
       float     dlf;        /* distance between last par-first daug.hit */
       float     dlv;        /* distance between last parent point/verte */
       float     hypo[3];    /* delta_mass for different PID hypotheses */
       float     ld;         /* radius where daughter track  stops */
       float     lp;         /* radius where parent track stops */
       float     p[3];       /* parent momentum */
       float     pd[3];      /* daughter momentum */
       float     pt;         /* parent pt */
       float     ptd;        /* daughter pt */
       float     pz;         /* parent pz (beam direction) */
       float     pzd;        /* daughter pz */
       float     r;          /* decay vertex radial (transverse)distance */
       float     sd;         /* radius where daughter track starts */
       float     sp;         /* radius where parent starts */
       float     tau;        /* proper lifetime of parent */
       float     theta;      /* reconstructed decay angle of kink */
       float     theta_cm;   /* reconstructed CM decay angle */
       float     x[3];       /* decay vertex coordinates */
       float     x_true[3];  /* true (MC) decay vertex coordinates */
       float     y;          /* parent rapidity */
   } ;
/*  Last mod. for tkf_tkfout:   $Date: 1997/12/31 14:33:28 $ */

