struct LaserTrack  {
  long Sector;
  long Mirror;
  long ZBoundle;
  long NoTracks; // no of laser tracks reconstracted by tpt
  float psi;
  float Dpsi;
  float tanl;
  float Dtanl;
  float xl;
  float Dxl;
  float yl;
  float Dyl;
  float zl;
  float Dzl;
};

