/*  dst_point_filler.idl  
 *  
 *  Module: dst_point_filler
 *
 *  Description:  DST level space point compression/filler module
 *                for TPC and SVT space points.
 */

#include "PAM.idl"
#include "tcl_tphit.idl"
#include "scs_spt.idl"
#include "dst_point.idl"

interface dst_point_filler : amiModule {
             STAFCV_T call
                     ( in    tcl_tphit      tcl_tphit, 
                       in    scs_spt        scs_spt,
                       out   dst_point      dst_point 
             );
     };
     /*  Last mod. for dst_point_filler $Date: 1998/08/24 23:55:16 $ */
