/*  dst_monitor_soft_filler.idl  
 *  
 *  Module: dst_monitor_soft_filler
 *
 *  Description:  DST level software reconstruction monitor 
 */

#include "PAM.idl"
#include "tcl_tpcluster.idl"
#include "tcl_tphit.idl"
#include "scs_spt.idl"
#include "fcl_fppoint.idl"
#include "tpt_track.idl"
#include "stk_track.idl"
#include "fpt_fptrack.idl"
#include "svm_evt_match.idl"
#include "ctu_cor.idl"
#include "dst_vertex.idl"
#include "dst_event_summary.idl"
#include "dst_mon_soft_ftpc.idl"
#include "dst_mon_soft_glob.idl"
#include "dst_mon_soft_svt.idl"
#include "dst_mon_soft_tpc.idl"

interface dst_monitor_soft_filler : amiModule {
             STAFCV_T call
                     ( in     tcl_tpcluster     tcl_tpcluster,
                       in     tcl_tphit         tcl_tphit,
                       in     scs_spt           scs_spt,
                       in     fcl_fppoint       fcl_fppoint,
                       in     tpt_track         tpt_track,
                       in     stk_track         stk_track,
                       in     fpt_fptrack       fpt_fptrack,
                       in     svm_evt_match     svm_evt_match,
                       in     ctu_cor           ctu_cor,
                       in     dst_vertex        dst_vertex,
                       in     dst_event_summary dst_event_summary,
                      out     dst_mon_soft_ftpc dms_ftpc,
                      out     dst_mon_soft_glob dms_global,
                      out     dst_mon_soft_svt  dms_svt,
                      out     dst_mon_soft_tpc  dms_tpc
             );
     };
     /*  Last mod. for dst_monitor_soft_filler $Date: 2000/03/01 17:12:16 $ */
