/*  dst_dedx_filler.idl  
 *  
 *  Module: dst_dedx_filler
 *
 *  Description:  DST level dE/dx information filler for TPC tracks
 */

#include "PAM.idl"
#include "tpt_track.idl"
#include "stk_track.idl"
#include "dst_dedx.idl"

interface dst_dedx_filler : amiModule {
             STAFCV_T call
                     ( in     tpt_track     tpt_track,
                       in     stk_track     stk_track,
                       out    dst_dedx      dst_dedx
             );
     };
     /*  Last mod. for dst_dedx_filler $Date: 1998/08/24 23:55:14 $ */
