/*  particle_dst_filler.idl
 *
 *  Module: particle_dst_filler
 *
 *  Description:  DST level filler module that copies particles from
 *                the 'particle' table into the dst_track table.
 *                Momentum space acceptance cuts in {pt,eta,phi}
 *                can be included; all particles or just the charged
 *                particles can be transfered.
 */

#include "PAM.idl"
#include "particle_dst_param.idl"
#include "particle.idl"
#include "dst_track.idl"

interface particle_dst_filler : amiModule {
             STAFCV_T call
                     ( in     particle_dst_param  par,
                       in     particle            particle,
                       out    dst_track           dst_track
             );
     };
     /*  Last mod. for particle_dst_filler $Date: 1998/08/27 23:04:38 $ */

