//:Copyright 1995, Lawrence Berkeley National Laboratory
//:>--------------------------------------------------------------------
//:FILE:	dui_i.idl
//:DESCRIPTION:	Dataset Unix-like Interface Orbix-objects
//:AUTHOR:	cet - Craig E. Tull, cetull@lbl.gov
//:BUGS:	-- STILL IN DEVELOPMENT --
//:HISTORY:	08dec95-v004a-cet- move cwd & root from tdm to dui,
//					change base class to socObject
//:HISTORY:	29nov95-v003a-cet- extract from tdm_i.idl
//:<--------------------------------------------------------------------

//:----------------------------------------------- INCLUDES           --
#include "tdm_i.idl"

//:----------------------------------------------- TYPEDEFS           --

//:=============================================== INTERFACE          ==
interface duiDispatcher_i : tdmFactory_i {

//:----------------------------------------------- ATTRIBUTES         --
attribute string cwd;
readonly attribute tdmDataset_i cwdDO;
readonly attribute tdmDataset_i rootDO;

//:----------------------------------------------- FUNCTIONS          --
STAFCV_T cd(in string dirPath);
STAFCV_T cp(in string fromPath, in string toPath);
STAFCV_T ls(in string path, out string result);
STAFCV_T mkdir(in string dirPath);
STAFCV_T mkTable(in string filePath, in string spec, in long rows);
STAFCV_T mv(in string fromPath, in string toPath);
STAFCV_T pwd(out string result);
STAFCV_T rm(in string filePath);
STAFCV_T rmdir(in string dirPath);

//STAFCV_T cvtRelAbs(in string relPath,out string absPath);

//STAFCV_T findDatasetPath(in string dirPath, out tdmDataset_i dataset);
//STAFCV_T findTablePath(in string filePath, out tdmTable_i table);
};

