/* File btof_modr.idl
* 
* mrpc-based TOF (TOFr) settings
*
*/
  struct  btof_modr   { 
    float system[2];     /*  - usage counter                           */
    float Height;        /*  Module height (r)                         */ 
    float Width; 	 /*  Module width (phi)                        */
    float Length;	 /*  Module length (z)                         */
    float Center; 	 /*  Module detector center in (phi)           */
    float mrpcX[33]; 	 /*  mrpc Xpositions                           */
    float mrpcZ[33];	 /*  mrpc Zpositions                           */
    float mrpcA[33];	 /*  mrpc angles                               */
    float HCHgt;  	 /*  Honeycomb->Height (r)                     */
    float HCWid;  	 /*  Honeycomb->Width (phi)                    */
    float HCLen;  	 /*  Honeycomb->Length (z)                     */
    float PCBHgt; 	 /*  PCboard->Height (r)                       */
    float PCBWid; 	 /*  PCboard->Width  (phi)                     */
    float PCBLen;	 /*  PCboard->Length (z)                       */
    float MYHgt;  	 /*  Mylar->Height                             */
    float MYWid;  	 /*  Mylar->Width                              */
    float MYLen;  	 /*  Mylar->Length                             */
    float GRHgt;  	 /*  Graphite->Height                          */
    float GRWid;  	 /*  Graphite->Width                           */
    float GRLen;	 /*  Graphite->Length                          */
    float OGHgt;  	 /*  Outer glass->Height                       */
    float OGWid;  	 /*  Outer glass->Width                        */
    float OGLen;  	 /*  Outer glass->Length                       */
    float IGHgt;  	 /*  Inner glass->Height                       */
    float IGWid;  	 /*  Inner glass->Width                        */
    float IGLen;	 /*  Inner glass->Length                       */
    float SPRMin; 	 /*  Separator Tube->RMin                      */
    float SPRMax; 	 /*  Separator Tube->RMax                      */
    float SPLen;  	 /*  Separator Tube->Length                    */
    float WGRMin; 	 /*  Wedge tube: RMin                          */
    float WGRMax; 	 /*  Wedge tube->RMax                          */
    float WGLen;	 /*  Wedge tube->Length                        */
    float FEEH;   	 /*  tofr fee pcb thickness                    */
    float HBWid;  	 /*  Slim honeycomb support box width          */
    float NGap;          /*  Number of gaps in MRPC                    */
};
