/* File btof_toff.idl
 *
 * scintillator-based TOF patch (TOFp) settings
 *
*/
  struct  btof_toff   { 
    float system[2];    /*  - usage counter                           */
    float BoxWidth;     /*  - width of the 5w box                     */
    float SlatLen;      /*  - slat length                             */
    float Slat01z;      /*  - 5_wide_slat Z position for row 1        */
    float Slat02z;      /*  - 4_wide_slat Z position for row 2        */
    float Slat03z;      /*  - 4_wide_slat Z position for row 3        */
    float Slat04z;      /*  - 4_wide_slat Z position for row 4        */
    float Slat05z;      /*  - 4_wide_slat Z position for row 5        */
    float Slat06z;      /*  - 4_wide_slat Z position for row 6        */
    float Slat07z;      /*  - 4_wide_slat Z position for row 7        */
    float Slat08z;      /*  - 4_wide_slat Z position for row 8        */
    float Slat09z;      /*  - 4_wide_slat Z position for row 9        */
    float Slat10z;      /*  - 4_wide_slat Z position for row 10       */
    float SlatThck;     /*  - scintillator slab thicknesses           */
    float SlatWid;      /*  - scintillator slab width                 */
    float SlatAng;      /*  - slat assy. angle w.r.t. tray            */
    float PmtLen;       /*  - PMT length                              */
    float PmtMaxR;      /*  - PMT max radius                          */
    float PmtMinR;      /*  - PMT min radius                          */
    float BaseLen;      /*  - Base length                             */
    float BaseMaxR;     /*  - Base max radius                         */
    float BaseMinR;     /*  - Base min radius                         */
    float SockLen;      /*  - thickness of socket                     */
    float CellWid;      /*  - Cell width                              */
    float CellHgt;      /*  -  Cell height                            */
    float ElecHgt;      /*  -  FEE Board height in tray               */
    float ElecThck;     /*  - FEE Board thickness                     */
    float ElecWid;      /*  - FEE Board width                         */
    float ElecLen;      /*  - FEE Board length                        */
    float ElecZ[10];    /*  - FEE Z position                          */
    float Elec01z;      /*  - FEE Z position for row 1                */
    float Elec02z;      /*  - FEE Z position for row 2                */
    float Elec03z;      /*  - FEE Z position for row 3                */
    float Elec04z;      /*  - FEE Z position for row 4                */
    float Elec05z;      /*  - FEE Z position for row 5                */
    float Elec06z;      /*  - FEE Z position for row 6                */
    float Elec07z;      /*  - FEE Z position for row 7                */
    float Elec08z;      /*  - FEE Z position for row 8                */
    float Elec09z;      /*  - FEE Z position for row 9                */
    float Elec10z;      /*  - FEE Z position for row 10               */
    float RailThck;     /*  - Cooling loop rail thickness             */
    float RailWid;      /*  - Cooling loop rail width                 */
    float CoolInnR;     /*  - Cooling loop pipe outer radius          */
    float CoolOutR;     /*  - Cooling loop pipe outer radius          */ 
  };
