/* File btof_btog.idl
 *
 * Barrel Trigger (CTB/TOF) basic dimensions
 *
*/
  struct  btof_btog   { 
    float system[2];    /*  - usage counter                           */
    float version;      /*  - GEOMETRY VERSION                        */
    float rmin;         /*  - MINIMUM CTB/TOF SYSTEM RADIUS (AS BUILT */
    float rmax;         /*  - MAXIMUM CTB/TOF SYSTEM RADIUS           */
    float dz;           /*  - CTB/TOF TUBE HALF LENGTH                */
    float choice;       /*  - 1(CTB),4(TOFp),5(TOFp+TOFr),6(full TOFR)*/
    float posit1;       /*  - position of TOFp tray                   */
    float posit2;       /*  - position of TOFr tray                   */
};
