/* spa_am.idl
*   Module: spa_am
*        description: spa Ssd Pedestal Annihilation module
*/

#include "PAM.idl"
#include "sdm_geom_par.idl"
#include "sdm_calib_par.idl"
#include "sls_strip.idl"
#include "spa_strip.idl"
#include "sls_ctrl.idl"
#include "sdm_calib_db.idl"
#include "sdm_condition_db.idl"

interface spa_am : amiModule {
        STAFCV_T call
                ( in    sdm_geom_par      geom_par
		, inout sdm_calib_par     cal_par   
		, in    sls_strip         sls_strip
		, in    sls_ctrl          ctrl
		, inout spa_strip         spa_strip
		, in    sdm_calib_db      noise
		, in    sdm_condition_db  condition
        );
};
/*  Last mod. for spa_am: $Date: 2000/07/21 15:03:36 $ */


