/* adc_to_energy		OGAWA, Akio */

#include "PAM.idl"
#include "emc_pedestal.idl"
#include "emc_adcslope.idl"
#include "emc_adc.idl"

interface adc_to_energy : amiModule {
	STAFCV_T call
      	( in emc_pedestal     emc_pedestal
	 ,in emc_adcslope     emc_adcslope
	 ,out emc_adc         emc_adc
	);
};
