/*toy_simulator		OGAWA, Akio */

#include "PAM.idl"
#include "ems_control.idl"
#include "ems_cal_control.idl"
#include "emc_adc.idl"

interface toy_simulator : amiModule {
	STAFCV_T call
        ( in    ems_control      ems_control
	, in    ems_cal_control  ems_cal_control
	, out   emc_adc          emc_adc
	);
};
