# Makefile.user - user customization of SLM
#? - Customize this file to override SLMakefile behavior.
######################################################################
#
mytarget:
	@echo "Put any special make targets in this file."
#
