 /*   mwc_raw.idl
 *   Table: mwc_raw
 *         description: Table for raw output of MWC
 */

   struct mwc_raw {         
       long       sector;     /* One of 384 MWC sectors */
       long       count ;     /* Count of fired wires in sector */
   };

/*  Last mod. for mwc_raw:   $Date: 1998/02/17 16:41:50 $ */

