/*   mwc_pars.idl
 *    (onetasth.ace)
 *  Table: mwc_pars
 *        description: New parameter table for mws 
 *        author: Vladimir Morozov, Dec 11 2000
 */

   /*******************  Row struct *******************/
   struct mwc_pars {
       long ogain;                  /* outer sector anode gain */
       long igain;                  /* inner sector anode gain */
       long tr;                     /* ns rize time for SAS chip */
       long delay;                  /* ns signal transmission time to DSMs */
       float vgain;                 /* 24mv SAS output per 6750 electrons */
       float drift1;                /* mm ns drift from gg to ground plane */
       float drift2;                /* mm ns drift from gp to the anode */
       float mip_deds;              /* Gev mm de ds for a MIP in P10 */
       float threshold;             /* Volts, anode threshold */


   };

/*  Last mod. for mwc_pars:    2000/12/11
 18:42:45 $ */






