/*   mwc_sector.idl
*                                           
*        Description: MWC Monte Carlo sector information
*/

   struct mwc_sector { 
       long       index;      /* Index for Sectors */
       long       nhit;       /* # charged particles going through sect. */
       long       sector;     /* sector index */
       long       iphi;       /* phi index for sector location */
       long       ieta;       /* eta index for sector location */
       float      de;         /* Deposited energy */       
   };
/*  Last mod. for mwc_sector:   $Date: 2002/04/08 22:11:11 $*/

