/*   mwc_mwpar.idl
 *    (onetasth.ace)
 *  Table: mwc_mwpar
 *        description: Parameter table for mws 
 */

   /*******************  Row struct *******************/
   struct mwc_mwpar {
       float     gain;       /* Variation in Scale Factor */
       float     de_thresh;  /* Threshold for de hit  */
       float     tof_thresh; /* Threshold for tof of hit */
       float     num_adcs_out; /*Number of adcs to DSM tree */
       float     num_wires_adc; /* Number of wires per adc */
       long      wires; /* Whether to use hits or de */  };

/*  Last mod. for mwc_mwpar:   $Date: 1997/12/31 14:34:25 $ */

