 /*   mwc_cor.idl
 *   Table: mwc_cor
 *         description: Table for corrected MWC output
 */

   struct mwc_cor {         
       long       sector;     /* One of 384 MWC sectors */
       long       no_mip;     /* ADC value for wires hit in sector */
   };

/*  Last mod. for mwc_cor:   $Date: 1998/02/17 16:41:49 $ */

