 /*   mwc_raw.idl
 *   Table: mwc_raw
 *         description: Table for raw output of MWC
 */

   struct mwc_raw {         
       long       sector;     /* One of 384 MWC sectors */
       long       adc;        /* ADC value for wires hit in sector */
   };

/*  Last mod. for mwc_raw:   $Date: 1997/12/31 14:34:25 $ */

