/*   mwc_mpar.idl
 *    (onetasth.ace)
 *  Table: mwc_mwpar
 *        description: Parameter table for mws 
 */

   /*******************  Row struct *******************/
   struct mwc_mpar {
       float     gain;            /* Variation in Scale Factor */
       float     de_thresh_in;    /* Threshold for de hit inner sector */
       float     de_thresh_out;   /* Threshold for de hit outer sector */
       float     tof_thresh;      /* Threshold for tof of hit */
       float     num_counts_out;  /* Number of adcs to DSM tree */
       float     num_wires_count; /* Number of wires per adc */
       float     el_noise_width;  /* Width of Gaussian for electronic noise in
				     units of minimum ionizing de */
       float     min_ion;         /* Minimum ionization */
   };

/*  Last mod. for mwc_mpar:   $Date: 1999/02/10 18:42:45 $ */






