      INTEGER  kUndefinedVtxId,kEventVtxId,kV0VtxId
      INTEGER  kXiVtxId,kKinkVtxId,kOtherVtxId   
#include "StVertexDefinitions.h"        
      PARAMETER (kUndefinedVtxId = kUndefinedVertexIdentifier)
      PARAMETER (kEventVtxId = kEventVertexIdentifier)
      PARAMETER (kV0VtxId = kV0DecayIdentifier) 
      PARAMETER (kXiVtxId = kXiDecayIdentifier)
      PARAMETER (kKinkVtxId = kKinkDecayIdentifier)
      PARAMETER (kOtherVtxId = kOtherTypeIdentifier)
