*
* $Id: incbeg.inc,v 1.1.1.3 2009/02/18 20:32:46 fisyak Exp $
*
* $Log: incbeg.inc,v $
* Revision 1.1.1.3  2009/02/18 20:32:46  fisyak
* *** empty log message ***
*
* Revision 1.1.1.1  2002/06/16 15:18:35  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:15  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:19:49  cernlib
* Geant
*
*
*
* incbeg.inc
*
#if defined(CERNLIB_INCLUDE)
#if defined(CERNLIB_IBM)
#if 0
      INCLUDE '
#endif
#endif
#endif
