*
* $Id: incbeg.inc,v 1.1.1.2 2009/02/01 17:10:14 fisyak Exp $
*
* $Log: incbeg.inc,v $
* Revision 1.1.1.2  2009/02/01 17:10:14  fisyak
* Merge with .DEV2
*
* Revision 1.1.1.1  2008/12/10 20:46:27  fisyak
* Merge with macos version
*
* Revision 1.1.1.1  2005/05/25 22:37:23  fisyak
* Alice version of geant3 (-minicern)
*
* Revision 1.1.1.1  2002/07/24 15:56:18  rdm
* initial import into CVS
*
* Revision 1.1.1.1  2002/06/16 15:18:35  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:15  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:19:49  cernlib
* Geant
*
*
*
* incbeg.inc
*
#if defined(CERNLIB_INCLUDE)
#if defined(CERNLIB_IBM)
#if 0
      INCLUDE '
#endif
#endif
#endif
