*
* $Id: incend.inc,v 1.1.1.1 2005/05/25 22:37:23 fisyak Exp $
*
* $Log: incend.inc,v $
* Revision 1.1.1.1  2005/05/25 22:37:23  fisyak
* Alice version of geant3 (-minicern)
*
* Revision 1.1.1.1  2002/07/24 15:56:18  rdm
* initial import into CVS
*
* Revision 1.1.1.1  2002/06/16 15:18:35  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:15  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:19:49  cernlib
* Geant
*
*
*
* incend.inc
*
#if defined(CERNLIB_INCLUDE)
#if defined(CERNLIB_IBM)
#if 0
     +'
#endif
#endif
#endif
