#!/usr/bin/python
# -*- coding: utf-8 -*-

# PURPOSE
# Filter the list of triggers in the file "offlinebits.txt" generated by *GetTrigList.csh*
#
# DESCRIPTION
# This is a quick and dirty script to read *offlinebits.txt* file and separate the different trigger names, then sort them by offline trigger ID. Sorting in this way should produce a time linear list. The only exception being with triggers with ID < 890000. This is not an issue however since triggers with IDs less than that are not production triggers in Run 22. It will write two files one called "FcsTrigList.out" which has a summary of the triggers and the sorted and unsorted list. The other is "FcsSortedTrig.txt", which is just the sorted version of the file "offlinebits.txt"
#
# AUTHOR
# David Kapukchyan
#
# LOG
# @[September 11, 2024] > First instance

import numpy as np
import pandas as pd

#@[September 13, 2024] > [Add column names when not in file](https://sparkbyexamples.com/pandas/pandas-add-column-names-to-dataframe/)
column_names = ["Name", "TrigId", "RunStart", "RunEnd"]
#Read file with space separator](https://stackoverflow.com/questions/19632075/how-to-read-file-with-space-separated-values-in-pandas)
TrigList = pd.read_csv('offlinebits.txt',sep="\s+",names=column_names)

#print(TrigList)
#print('\n')

#Remove duplicates from dataframe to generate an array of all fcs triggers by name
FcsTrigDuplicateList = TrigList["Name"].duplicated(keep='first')
FcsTrigList = TrigList.copy()
#print('\n')
for i in range(0,len(FcsTrigDuplicateList)):
    if FcsTrigDuplicateList[i]:
        #print(f"Found Duplicate for {FcsTrigList.iloc[i,0]} - removing")
        FcsTrigList.drop(i,axis=0,inplace=True)
#print(FcsTrigList)
#print('\n')

File = open("FcsTrigList.out",mode='wt',buffering=1) #The '1' at the end means only keep one line in python buffer before writing to file
FileSorted = open("FcsSortedTrig.txt",mode='wt',buffering=1) #The '1' at the end means only keep one line in python buffer before writing to file
FcsTrigList = FcsTrigList["Name"].to_numpy()
#print( FcsTrigList )
File.write("Total Triggers: ")
File.write( str(len(FcsTrigList)) )
File.write('\n')
for trig in FcsTrigList:
    print(trig)
    File.write(trig);
    File.write('\n');
print('\n')
File.write('\n')

#Testing how to sort a given column
#FcsDiJpAsy = (TrigList.loc[ TrigList["Name"]=="fcsDiJPAsy" ]).copy()
#FcsDiJpAsy.sort_values("TrigId",inplace=True)
#print(FcsDiJpAsy)

#@[September 12, 2024] > [How to write dataframe to file](https://stackoverflow.com/questions/31247198/python-pandas-write-content-of-dataframe-into-text-file)
File.write("Full Sorted trigger list\n")
File.write("Name TrigId RunStart RunEnd\n")   #Match header in original file
for trig in FcsTrigList:
    df = (TrigList.loc[ TrigList["Name"]==trig ]).copy(deep=True)
    df.sort_values("TrigId",inplace=True)
#    print(df)
    File.write( df.to_string(header=False,index=False) )
    FileSorted.write( df.to_string(header=False,index=False) )
    File.write('\n')
    FileSorted.write('\n')
#    print('\n')
File.write('\n')
FileSorted.write('\n')

File.write("Production Sorted trigger list\n")
File.write("Name TrigId RunStart RunEnd\n")   #Match header in original file
#@[September 12, 2024] > [storing a datatframe in a dictionary](https://stackoverflow.com/questions/38241729/python-storing-a-dataframe-as-value-associated-with-key-in-dictionary)
ProdDfMap = {}
for trig in FcsTrigList:
    proddf = (TrigList.loc[ (TrigList["Name"]==trig) & (TrigList["TrigId"]>=890000) ])
    if not proddf.empty:
        ProdDfMap[trig] = proddf.copy(deep=True)
        ProdDfMap[trig].sort_values("TrigId",inplace=True)
        print(ProdDfMap[trig])
        File.write( ProdDfMap[trig].to_string(header=False,index=False) )
        File.write('\n')
        print('\n')
#print('\n')
File.write('\n')

File.close()

#print( ProdDfMap["fcsDiJP"].iat[1,2] )
#print('\n')

#Save all the trigger names, ids, and run ranges into a text file.
#Make a C++ class that will read and store this information. Then you feed it a runnumber and it generates from its internal database the correct map of names to offline trigger ids

#firstruns = numpy.empty
#for key1 in ProdDfMap:
#    for key2 in ProdDfMap:
#        firstruns.append
#    print( key, " ", ProdDfMap[key].iat[0,2] )
#print('\n')




