#!/bin/csh -f

# Help
if ($#argv == 0 || $#argv > 3 || "$1" == "help" || "$1" == "-h") then
    /bin/cat <<EOF

 Usage is:
   % setup 'Package' {version}

 where packages stands for one of
   cvmfs|afs                        reset the environment to switch between
                                    afs or cvmfs based install. Warning: this
                                    will remove all ENV variable and reload 
                                    the STAR login.

   debug|DEBUG                      switch the environment to the debug version of 
                                    the STAR software
   nodebug|NODEBUG|-O3              switch the environment to the nodebug (optimized) 
                                    of the STAR software
   64bits|64b|32bits|32b            Switch to 64 or 64 bits env

   gprof|GRPOF                      enables/disables gprof profiling environment
   nogprof|NOGPROF                  non-optimized version will be implied when enabled


   Grid|OSG                         Setup Grid environment
   geant4        {version}          load Geant4 env
   root|ROOT     {version}          load or change root version
   cern|CERN     {version} {InstallRoot} 
                                    Re-define CERN related ENV variables
				    

   parasoft|PARASOFT|insure|ISURE   load the Insure++ toolkit environment
   gcc           {version}          set environment to use gcc (or alternative version)
   icc|ifc|ifort {version}          set environment to use Intel compilers
   PGI|pgi                          set PGI path for using its compiler

   alt|noalt                        adds/remove OPTSTAR/alt from path

EOF
    exit 0
endif

set pkg = $1; shift;
set version  = 0;
set location = 0;
if ( $#argv > 0 ) set version  = $1
if ( $#argv > 1 ) set location = $2
#echo "==================== setup $pkg $version $location ===================="
setenv oldSTAR_HOST_SYS $STAR_HOST_SYS

source $GROUP_DIR/unix_programs.csh

switch ($pkg)
    case "cvmfs":
    case "afs":
      if ( -r $HOME/.login ) then
	#set saved_home=$HOME
	#set saved_display=$DISPLAY
	#unsetenv *
	#setenv HOME     $saved_home
	#setenv DISPLAY  $saved_display
	unsetenv star_login_csh star_cshrc_csh 
	unsetenv STAR OPTSTAR XOPTSTAR optstar xoptstar
	unsetenv PATH LD_LIBRARY_PATH GROUP_DIR GROUP_PATH GROUPPATH
	unsetenv ROOT ROOTSYS
	unsetenv STAF* STAR_* 
	unsetenv XROOTDSYS XrdSecPWDALOGFILE XrdSecPWDSRVPUK
	unsetenv CERN QTDIR CLHEP_BASE_DIR
	if ( $?WNOSG ) then
	    set test1=`echo $WNOSG | $GREP afs`
	    set test2=`echo $WNOSG | $GREP cvmfs`
	    # if defined as AFS and we we asked for cvmfs, undefine
	    if ( "$test1" != "" && $pkg == "cvmfs") then
		unsetenv WNOSG
	    endif	
	    # if defined as CVMFS and we we asked for afs, undefine
	    if ( "$test2" != "" && $pkg == "afs") then
		unsetenv WNOSG
	    endif
        endif

	if ( $pkg == "cvmfs") then
	    setenv    USE_CVMFS 1
	else
	    unsetenv  USE_CVMFS
        endif
	source $HOME/.cshrc
      endif
      breaksw

    case "64bits":
    case "64b":
      setenv USE_64BITS 1
      unsetenv OPTSTAR
      unsetenv XOPTSTAR
      if (-x $GROUP_DIR/dropit ) then
	setenv PATH            `$GROUP_DIR/dropit $STAR_HOST_SYS /opt/star`
        setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH $oldSTAR_HOST_SYS /opt/star ^/usr/lib`
      endif
#      setup $xSTARCMPL
      source $GROUP_DIR/STAR_SYS
#      setenv CERN /cern64
      setup cern
#      setenv CERN /afs/rhic.bnl.gov/.asis/x8664_sl5/cern64
#      setenv CERN /afs/rhic.bnl.gov/star/packages/.DEV2/misc/sl53_x8664_gcc451
      unsetenv CERN_ROOT
      unsetenv OPTSTAR
      unsetenv QTDIR
      source $GROUP_DIR/group_env.csh
      setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH $oldSTAR_HOST_SYS ^/usr/lib /opt/star`
      setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/usr/lib64:/usr/lib64/mysql
#      setenv ValeryOptStar /afs/rhic.bnl.gov/star/users/fine/data08/STAR/OPTSTAR/.$STAR_HOST_SYS
#      setenv LD_LIBRARY_PATH $ValeryOptStar/lib:$OPTSTAR/lib:$LD_LIBRARY_PATH
#      setenv PATH $ValeryOptStar/bin:$OPTSTAR/bin:$PATH
#      setenv QTDIR $ValeryOptStar/Qt4
#      if ($?QTDIR) setenv QTDIR $OPTSTAR/qt4
#      setenv PATH $QTDIR/bin:$PATH
#      setenv LD_LIBRARY_PATH $QTDIR/lib:$LD_LIBRARY_PATH
       source ${GROUP_DIR}/.starver $STAR_LEVEL
     breaksw

    case "32bits":
    case "32b":
      setenv USE_64BITS 0
      unsetenv OPTSTAR
      unsetenv XOPTSTAR
#      setup $xSTARCMPL
      if (-x $GROUP_DIR/dropit ) then
	setenv PATH            `$GROUP_DIR/dropit $STAR_HOST_SYS /opt/star`
        setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH $oldSTAR_HOST_SYS /opt/star ^/usr/lib64`
      endif
#      setenv OPTSTAR /afs/rhic.bnl.gov/star/packages/.DEV2/misc/opt/star/$STAR_HOST_SYS
      source $GROUP_DIR/STAR_SYS
#      setenv CERN /cern
      setup cern
      unsetenv CERN_ROOT
      unsetenv OPTSTAR
      unsetenv QTDIR
      source $GROUP_DIR/group_env.csh 
      setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH $oldSTAR_HOST_SYS lib64 lib`
#      setenv ValeryOptStar /afs/rhic.bnl.gov/star/users/fine/data08/STAR/OPTSTAR/.$STAR_HOST_SYS
#      setenv LD_LIBRARY_PATH $ValeryOptStar/lib:$OPTSTAR/lib:$LD_LIBRARY_PATH
#      setenv PATH $ValeryOptStar/bin:$OPTSTAR/bin:$PATH
#      setenv QTDIR $ValeryOptStar/Qt4
#      setenv PATH $QTDIR/bin:$PATH
#      setenv LD_LIBRARY_PATH $ValeryOptStar/Qt4/lib:$LD_LIBRARY_PATH
#      if ($?QTDIR) setenv QTDIR $OPTSTAR/qt4
#      setenv PATH $QTDIR/bin:$PATH
#      setenv LD_LIBRARY_PATH $QTDIR/lib:$LD_LIBRARY_PATH
#      setup $xSTARCMPL
#       source ${GROUP_DIR}/.starver $STAR_LEVEL
      breaksw


    case "PGI":
    case "pgi":
#% setenv PGI /software/pgi
#% set path=(/software/pgi/linux86-64/18.10/bin $path)
#% setenv MANPATH "$MANPATH":/software/pgi/linux86-64/18.10/man
#% setenv LM_LICENSE_FILE /software/pgi/license.dat:"$LM_LICENSE_FILE"      # PGI compiler - this may be used
    if ( ! $?PGI) then
      if(-d /software/pgi) then
	setenv PGI /software/pgi
	setenv USE_64BITS 1
	setenv PGI_V linux86-64/18.10
	if (-d $PGI/$PGI_V/bin) then
	  setenv PATH `${GROUP_DIR}/dropit -p $PGI/$PGI_V/bin -p $PATH`
	  setenv PGILIB $PGI/$PGI_V/lib
	  if ( -d $PGI/$PGI_V/man) then
	    setenv MANPATH `${GROUP_DIR}/dropit -p ${MANPATH} -p ${PGI}/${PGI_V}/man`
          endif
          setenv LM_LICENSE_FILE $PGI/license.dat
	else
	  unsetenv PGI
	endif
      endif
    endif
    breaksw

    case "OSG":
    case "Grid":
	# Support for OSG - Try to locate things from OSG including Worker Node
	if ( ! $?OSG ) then 
	    if ( -r /opt ) then
		set LOSG=`ls -d /opt/* | $GREP OSG | tail -1`
		if ( "$LOSG" != "") setenv OSG $LOSG
	    endif
	endif
	if ( $?OSG ) then
	    if ( -r $OSG/setup.csh ) then
		# there will alos be a java version coming along but
		# it may be defined prior from /usr/java
		source $OSG/setup.csh
		setenv SAVED_PATH `echo $PATH | sed "s/:/ /g"`
	    endif
	else
	    # Unfortunately, the WN package loads the whole blabla with
	    # java, python and even perl all ...
	    if ( $?WNOSG ) then
		if ( -r $WNOSG/setup.csh ) then
		    setenv GSAVED_PATH   $PATH
		    setenv GSAVED_LDPATH $LD_LIBRARY_PATH
		    # trash the path
		    setenv PATH  /bin:/usr/bin
		    # trash LD
		    unsetenv LD_LIBRARY_PATH
		    # load definitions
		    source $WNOSG/setup.csh
		    # redefine path and ld path
		    setenv PATH             ${GSAVED_PATH}:${PATH}
		    setenv LD_LIBRARY_PATH  ${GSAVED_LDPATH}:${LD_LIBRARY_PATH}
	        endif
	    endif
        endif
	breaksw


    # Geant4 - check first
    case "geant4":
       if ( $version != 0 ) then
	    set v =".$version"
       else
	    set v = ""
       endif
       if ( -r  ${OPTSTAR}/geant4$v ) then
	    setenv G4PATH ${OPTSTAR}/geant4$v
	    if ( -r  $G4PATH/bin/geant4.csh ) then
		setenv G4BIN ${G4PATH}/bin
		setenv saved_path $cwd
		cd $G4PATH/bin/ && source geant4.csh
		cd $saved_path
	    else
		if ( $?DECHO ) echo "Geant4 setup script was not found"
	    endif
       else
	    if ( $?DECHO ) echo "Geant4 version $version is not installed"
       endif
       breaksw


    # Root setup
    case "root":
    case "ROOT":
	if (-f $GROUP_DIR/rootenv.csh) then
	    if ( -x $GROUP_DIR/dropit) then
		setenv MANPATH         `$GROUP_DIR/dropit -p ${MANPATH} ROOT`
		setenv PATH            `$GROUP_DIR/dropit -p ${PATH} ROOT`
		setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p ${LD_LIBRARY_PATH} ROOT`
	    endif
	    if ($version != 0) setenv ROOT_LEVEL $version
	    source $GROUP_DIR/rootenv.csh
	endif
	breaksw

    # CERN in case of alternate CERN_ROOT
    case "CERN":
    case "cern":
#    echo "CERN in case of alternate CERN_ROOT"
	if ( $location != 0 ) then
	    # use the specified location, no double check
	    setenv CERN $location
        else
	    # try to determine the location according to pre-2010 logic
	    if ( ! $?USE_64BITS ) then
		# this is also defined in STAR_SYS but ensuring
		# a default value is needed for the test below
		setenv USE_64BITS 0
	    endif
	    if ( ! $?CERN ) then
		# Define one value - some of the path below are historical
		if ( $USE_64BITS == 1) then
		    set x="/cern64 /cern ${AFS_RHIC}/asis/@sys/cern64 ${AFS_RHIC}/asis/@sys/cern /usr/local/cern64 /usr/local/cern /common/star/cern64 /common/star/cern /software/fisyak/STAR/cern64"
		else
		    set x="/cern ${AFS_RHIC}/asis/@sys/cern /usr/local/cern /common/star/cern /software/fisyak/STAR/cern"
		endif
            else
		# Either it was set before by the search above or there is an 
		# external definition. In all cases, if it ends by 64, set as-is
		# otherwise append
		set test=`echo $CERN | $GREP 64`
		if ( "$test" != "") then
		    # strip it
		    setenv CERN `echo ${CERN} | sed "s/64//"`
		endif
		if ( $USE_64BITS == 1 ) then
		    set x="${CERN}64 ${CERN}"
                else
		    set x="${CERN}"
		endif
		unset test
	    endif

	    # NOW we have "x" defined as a search path or a unique path
	    # In case of a unique path set by a site, this will redefine to itself
	    # But this odditiy is needed to deal with the 64 bits convention
	    # ${CERN} ${CERN}64
	    foreach d ($x)
		if ( -r  $d ) then
		    setenv CERN $d
		    break
		endif
	    end
	    unset x d
	    if ( ! $?CERN ) then
		# this can happen only when the full search path finds nothing
		if ( $?DECHO ) echo "Could not find a valid path for defining CERN, default to /cern"
		setenv CERN /cern
	    endif
        endif
	
	if ( $version != 0 ) then
	    # if specified, use specific version
	    if ( -r  $CERN/$version ) then
		setenv CERN_LEVEL $version 
	    endif
	else
	    # define to pro if not defined
	    if ( ! $?CERN_LEVEL ) then
		setenv CERN_LEVEL pro
	    endif
	endif

	# Finally, check of existence of this path and revert to 
	# pro if not found
	if ( ! -r $CERN/$CERN_LEVEL ) then
	    if ( $?DECHO ) echo "$self :: $CERN/$CERN_LEVEL not found, switch to pro"
		setenv CERN_LEVEL pro
		setenv CERN_ROOT "$CERN/$CERN_LEVEL"
	    endif
	    # << ?? if I fix this endif bock, all goes to hell
	    #    there is a missing if/endif sequence somewhere
	    setenv CERN_ROOT $CERN/$CERN_LEVEL
	endif
	breaksw

    # Parasoft/Isure++ software
    case "insure":
    case "INSURE":
    case "parasoft":
    case "PARASOFT":
	if (-f $GROUP_DIR/parasoftenv.csh) source $GROUP_DIR/parasoftenv.csh
	breaksw
	

    # use of the Intel compiler
    case "icc":
    case "ifc":
    case "ifort":
	unsetenv GPROF  # don't know about -qp ; perhaps later
	if ( -f $GROUP_DIR/intelcc.csh  )  source $GROUP_DIR/intelcc.csh $version
	if ( $?optstar != 0)  setenv  OPTSTAR  $optstar
	if ( $?xoptstar != 0 ) setenv XOPTSTAR  $xoptstar
	if ( $?STARCMPL && -x $GROUP_DIR/dropit ) then
	    setenv PATH            `$GROUP_DIR/dropit $STAR_HOST_SYS`
	    setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH $STAR_HOST_SYS`
	    unsetenv QTDIR
	endif 
	if ( $?DECHO ) echo "setup icc 0: PATH = $PATH"
	if ( $?DECHO ) echo "setup icc 0: LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
	source $GROUP_DIR/intelcc.csh
	if ( $?DECHO ) echo "setup icc 1: PATH = $PATH"
	if ( $?DECHO ) echo "setup icc 1: LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
	setenv STARCMPL "icc";  setenv xSTARCMPL "icc"; source ${GROUP_DIR}/.starver $STAR_LEVEL
	if ( $?DECHO ) echo "setup icc 2: PATH = $PATH"
	if ( $?DECHO ) echo "setup icc 2: LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
	breaksw

    case "gcc*":
      if ( $?DECHO ) echo "===================== case gcc $pkg =============="
      if ( -x $GROUP_DIR/dropit ) then
	setenv PATH            `$GROUP_DIR/dropit alt $STAR_HOST_SYS gcc /opt/rh/devtoolset`
	setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH alt $STAR_HOST_SYS gcc /opt/rh/devtoolset`
      endif
      setenv  STARCMPL "gcc"
      setenv xSTARCMPL $pkg; # "gcc";
      if ($?QTDIR)    unsetenv QTDIR
      if ($?OPTSTAR)  unsetenv OPTSTAR
      if ($?XOPTSTAR) unsetenv XOPTSTAR
      if ($?devtools) unsetenv devtools
      if ( $?DECHO ) echo "setup:reset PATH = $PATH"
      if ( $?DECHO ) echo "setup:reset LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
      if ( $?DECHO ) echo "pkg = $pkg"
      if (-e /cvmfs/sft.cern.ch/lcg/contrib/${pkg}/x86_64-centos7/setup.csh) then
        source /cvmfs/sft.cern.ch/lcg/contrib/${pkg}/x86_64-centos7/setup.csh
      else 
# specific compiler 
      switch ($pkg)
	case "gcc451":
	setenv PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc451/bin:$PATH
	if (! $USE_64BITS) then
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc451/lib:/usr/lib/mysql:$LD_LIBRARY_PATH
	else
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc451/lib64:/usr/lib64/mysql:$LD_LIBRARY_PATH
	endif
	breaksw
	case "gcc452":
	if ( -x $GROUP_DIR/dropit ) then
	    setenv PATH            `$GROUP_DIR/dropit alt $STAR_HOST_SYS gcc4`
	    setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH alt $STAR_HOST_SYS gcc4`
	endif
	setenv PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc452/bin:$PATH
	if (! $USE_64BITS) then
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc452/lib:/usr/lib/mysql:$LD_LIBRARY_PATH
	else
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc452/lib64:/usr/lib64/mysql:$LD_LIBRARY_PATH
	endif
	breaksw
	case "gcc45*":
	setenv PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc45/bin:$PATH
	if (! $USE_64BITS) then
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc45/lib:/usr/lib/mysql:$LD_LIBRARY_PATH
	else
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc45/lib64:/usr/lib64/mysql:$LD_LIBRARY_PATH
	endif
	breaksw
	case "gcc471":
	if ( -x $GROUP_DIR/dropit ) then
	    setenv PATH            `$GROUP_DIR/dropit alt $STAR_HOST_SYS gcc4`
	    setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH alt $STAR_HOST_SYS gcc4`
	endif
	    setenv PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc471/bin:$PATH
	if (! $USE_64BITS) then
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc471/lib:/usr/lib/mysql:$LD_LIBRARY_PATH
	else
	    setenv LD_LIBRARY_PATH /afs/rhic.bnl.gov/rcassoft/x8664_sl5/gcc471/lib64:/usr/lib64/mysql:$LD_LIBRARY_PATH
	endif
	breaksw
	case "gcc5*":
	setenv USE_64BITS 1
	setenv devtools /opt/rh/devtoolset-4
	if (-r ${devtools}) then
	  setenv PATH  ${devtools}/root/usr/bin:${PATH}
	  setenv LD_LIBRARY_PATH  ${devtools}/root/usr/lib64:${devtools}/root/usr/lib:${LD_LIBRARY_PATH}
	  setenv INFOPATH  ${devtools}/root/usr/share/info
	  setenv PCP_DIR   ${devtools}/root
          setenv PERL5LIB  ${devtools}/root/usr/lib64/perl5/vendor_perl:${devtools}/root/usr/lib/perl5:${devtools}/root/usr/share/perl5/vendor_perl:${PERL5LIB}
	  setenv PYTHONPATH  ${devtools}/root/usr/lib64/python2.7/site-packages:${devtools}/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-3/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-3/root/usr/lib/python2.6/site-packages
	  setenv PKG_CONFIG_PATH  	
	  setenv XDG_CONFIG_DIRS  ${devtools}/root/etc/xdg:/etc/xdg
	  setenv XDG_DATA_DIRS  ${devtools}/root/usr/share:/usr/local/share:/usr/share
          setenv X_SCLS  `basename $devtools`
	endif
	breaksw
	case "gcc6*":
	setenv USE_64BITS 1
	setenv devtools /opt/rh/devtoolset-6
	if (-r ${devtools}) then
	  setenv PATH  ${devtools}/root/usr/bin:${PATH}
	  setenv LD_LIBRARY_PATH  ${devtools}/root/usr/lib64:${devtools}/root/usr/lib:${LD_LIBRARY_PATH}
	  setenv INFOPATH  ${devtools}/root/usr/share/info
	  setenv PCP_DIR   ${devtools}/root
          setenv PERL5LIB  ${devtools}/root/usr/lib64/perl5/vendor_perl:${devtools}/root/usr/lib/perl5:${devtools}/root/usr/share/perl5/vendor_perl:${PERL5LIB}
	  setenv PYTHONPATH  ${devtools}/root/usr/lib64/python2.7/site-packages:${devtools}/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-3/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-3/root/usr/lib/python2.6/site-packages
	  setenv PKG_CONFIG_PATH  	
	  setenv XDG_CONFIG_DIRS  ${devtools}/root/etc/xdg:/etc/xdg
	  setenv XDG_DATA_DIRS  ${devtools}/root/usr/share:/usr/local/share:/usr/share
          setenv X_SCLS  `basename $devtools`
	endif
	breaksw
	case "gcc7*":
	setenv USE_64BITS 1
	setenv devtools /opt/rh/devtoolset-7
	if (-r ${devtools}) then
	  setenv PATH  ${devtools}/root/usr/bin:${PATH}
	  setenv LD_LIBRARY_PATH  ${devtools}/root/usr/lib64:${devtools}/root/usr/lib:${LD_LIBRARY_PATH}
	  setenv INFOPATH  ${devtools}/root/usr/share/info
	  setenv PCP_DIR   ${devtools}/root
          setenv PERL5LIB  ${devtools}/root/usr/lib64/perl5/vendor_perl:${devtools}/root/usr/lib/perl5:${devtools}/root/usr/share/perl5/vendor_perl:${PERL5LIB}
	  setenv PYTHONPATH  ${devtools}/root/usr/lib64/python2.7/site-packages:${devtools}/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-3/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-3/root/usr/lib/python2.6/site-packages
	  setenv PKG_CONFIG_PATH  	
	  setenv XDG_CONFIG_DIRS  ${devtools}/root/etc/xdg:/etc/xdg
	  setenv XDG_DATA_DIRS  ${devtools}/root/usr/share:/usr/local/share:/usr/share
          setenv X_SCLS  `basename $devtools`
	endif
	breaksw
#	case "gcc83*":
#	setenv USE_64BITS 1
#	setenv devtools /net/l409/software/fisyak/STAR/sources/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-8.3.0-opnwtdjumg2hxo4ljvnx77ugb6afmvj3
#	if (-r ${devtools}) then
#	  setenv PATH  ${devtools}/root/usr/bin:${PATH}
#	  setenv LD_LIBRARY_PATH  ${devtools}/root/usr/lib64:${devtools}/root/usr/lib:${LD_LIBRARY_PATH}
#	  setenv INFOPATH  ${devtools}/root/usr/share/info
#	  setenv PCP_DIR   ${devtools}/root
#          setenv PERL5LIB  ${devtools}/root/usr/lib64/perl5/vendor_perl:${devtools}/root/usr/lib/perl5:${devtools}/root/usr/share/perl5/vendor_perl:${PERL5LIB}
#	  setenv PYTHONPATH  ${devtools}/root/usr/lib64/python2.7/site-packages:${devtools}/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-3/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-3/root/usr/lib/python2.6/site-packages
#	  setenv PKG_CONFIG_PATH  	
#	  setenv XDG_CONFIG_DIRS  ${devtools}/root/etc/xdg:/etc/xdg
#	  setenv XDG_DATA_DIRS  ${devtools}/root/usr/share:/usr/local/share:/usr/share
#          setenv X_SCLS  `basename $devtools`
#	endif
#	breaksw
	case "gcc8*":
	setenv USE_64BITS 1
	setenv devtools /opt/rh/devtoolset-8
	if (-r ${devtools}) then
	  setenv PATH  ${devtools}/root/usr/bin:${PATH}
	  setenv LD_LIBRARY_PATH  ${devtools}/root/usr/lib64:${devtools}/root/usr/lib:${LD_LIBRARY_PATH}
	  setenv INFOPATH  ${devtools}/root/usr/share/info
	  setenv PCP_DIR   ${devtools}/root
          setenv PERL5LIB  ${devtools}/root/usr/lib64/perl5/vendor_perl:${devtools}/root/usr/lib/perl5:${devtools}/root/usr/share/perl5/vendor_perl:${PERL5LIB}
	  setenv PYTHONPATH  ${devtools}/root/usr/lib64/python2.7/site-packages:${devtools}/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-3/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-3/root/usr/lib/python2.6/site-packages
	  setenv PKG_CONFIG_PATH  	
	  setenv XDG_CONFIG_DIRS  ${devtools}/root/etc/xdg:/etc/xdg
	  setenv XDG_DATA_DIRS  ${devtools}/root/usr/share:/usr/local/share:/usr/share
          setenv X_SCLS  `basename $devtools`
	endif
	breaksw
	case "gcc9*":
	setenv USE_64BITS 1
#	setenv devtools /net/l409/software/fisyak/STAR/sources/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-9.2.0-tuxi4uvc6t25bafj674q4saybld2lmx2
#	setenv devtools /net/l409/software/fisyak/STAR/sources/spack/opt/spack/linux-rhel7-ivybridge/gcc-4.8.5/gcc-9.2.0-dfiaotqw57quyo4tjitm6izunjo76wjx
	setenv devtools /opt/rh/devtoolset-9
	if (-r ${devtools}) then
#	  setenv PATH  ${devtools}/bin:${PATH}
#	  setenv LD_LIBRARY_PATH  ${devtools}/lib64:${devtools}/lib:${LD_LIBRARY_PATH}
	  setenv PATH  ${devtools}/root/usr/bin:${PATH}
	  setenv LD_LIBRARY_PATH  ${devtools}/root/usr/lib64:${devtools}/root/usr/lib:${LD_LIBRARY_PATH}
	  setenv INFOPATH  ${devtools}/share/info
	  setenv PCP_DIR   ${devtools}/root
          setenv PERL5LIB  ${devtools}/lib64/perl5/vendor_perl:${devtools}/lib/perl5:${devtools}/share/perl5/vendor_perl:${PERL5LIB}
	  setenv PYTHONPATH  ${devtools}/lib64/python2.7/site-packages:${devtools}/lib/python2.7/site-packages:/opt/rh/devtoolset-3/lib64/python2.6/site-packages:/opt/rh/devtoolset-3/lib/python2.6/site-packages
	  setenv PKG_CONFIG_PATH  	
	  setenv XDG_CONFIG_DIRS  ${devtools}/root/etc/xdg:/etc/xdg
	  setenv XDG_DATA_DIRS  ${devtools}/share:/usr/local/share:/usr/share
          setenv X_SCLS  `basename $devtools`
	endif
	breaksw
	default:
	breaksw
        endsw # for specfic local gcc version
      endif
      $STARCMPL --version | head -1
       source ${GROUP_DIR}/.starver $STAR_LEVEL
      if ( $?DECHO ) echo "setup:set PATH = $PATH"
      if ( $?DECHO ) echo "setup:set LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
      if ( $?DECHO ) echo "setup:========== end of gcc set ============="
      breaksw # for all gcc
    # debug / nodebug
    case "-o3":
    case "-O3":
	unsetenv GPROF
	setenv NODEBUG "-O3"
	source ${GROUP_DIR}/.starver $STAR_LEVEL
	setenv ROOTBUILD nodebug
	breaksw
    case "nodebug":
    case "NODEBUG":
	unsetenv GPROF
	setenv NODEBUG yes
        source ${GROUP_DIR}/.starver $STAR_LEVEL
	setenv ROOTBUILD nodebug
	breaksw
    case "debug":
    case "DEBUG":
	unsetenv NODEBUG
	if ( -x $GROUP_DIR/dropit ) then
	    setenv PATH            `$GROUP_DIR/dropit BIN`
	    setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH LIB`
	endif
	 source ${GROUP_DIR}/.starver $STAR_LEVEL
	setenv ROOTBUILD debug
	breaksw


    # grpof / nogrpof
    case "gprof":
    case "GPROF":
	setenv GPROF "yes"
	unsetenv NODEBUG
	 source ${GROUP_DIR}/.starver $STAR_LEVEL
	breaksw

    case "nogprof":
    case "NOGPROF":
	unsetenv GPROF       
	if ( -x $GROUP_DIR/dropit ) then
	    setenv PATH            `$GROUP_DIR/dropit GBIN`
	    setenv LD_LIBRARY_PATH `$GROUP_DIR/dropit -p $LD_LIBRARY_PATH GLIB`
	endif
	 source ${GROUP_DIR}/.starver $STAR_LEVEL
	breaksw
    default:
      echo "No valid package found for $pkg key"
      breaksw
endsw
if ( $?DECHO ) echo "End of setup ================================"
