#include <stdio.h>
#if !defined(sun) && !defined(WIN32)
#include <strings.h>
#else
#include <string.h>
#endif
#include <stdlib.h>
#include "stic.h"
#define PP printf(
#define FF fprintf(ff,
extern char gCvsVersion[];
extern char gPamUp[],gPam[];
void TemplateFBegin(char *fn,FILE *ff) {
FF"CC:>--------------------------------------------------------------------\n");
FF"CC: FILE:       %s\n",fn);
FF"CC: HISTORY:\n");
FF"CC:             00jan96-v000a-hpl- Created by stic Version\n");
FF"CC: %s\n",gCvsVersion);
FF"CC:<--------------------------------------------------------------------\n");
FF"\n");
}
void TemplateFMiddle(FILE *ff) {
FF"CC:>--------------------------------------------------------------------\n");
FF"CC: ROUTINE:    %s\n",gPamUp);
FF"CC: DESCRIPTION: Physics Analysis Module FORTRAN 77 template.\n");
FF"CC:             This is a FORTRAN 77 Physics Analysis Module template\n");
FF"CC:             automatically generated by stic Version\n");
FF"CC:       %s\n",gCvsVersion);
FF"CC:             from %s.idl.\n",gPam);
FF"CC:             Please edit comments and code.\n");
FF"CC: AUTHOR:     hpl - H.P. Lovecraft, hplovecraft@cthulhu.void\n");
FF"CC: ARGUMENTS:\n");
}
void TemplateFEnd(FILE *ff) {
FF"CC: RETURNS:    STAF Condition Value\n");
FF"CC:>--------------------------------------------------------------------\n");
FF"\n");
FF">>>>>>>>>>>>>>> This file will not compile as is. <<<<<<<<<<<<<<<\n");
FF">>>>> The following code is for example purposes only.      <<<<<\n");
FF">>>>> Please remove it and put your own analysis code in    <<<<<\n");
FF">>>>> its place.                                            <<<<<\n");
FF">>>>>>>>>>>>>>> This file will not compile as is. <<<<<<<<<<<<<<<\n");
FF"\n");
FF"      INTEGER*4 I,J\n");
FF"\n");
FF"C: Unsuccessful completion of analysis module...\n");
FF"      %s = STAFCV_BAD\n",gPamUp);
FF"      RETURN\n");
FF"\n");
FF"C: Successful completion of analysis module...\n");
FF"      %s = STAFCV_OK\n",gPamUp);
FF"      RETURN\n");
FF"\n");
FF"C: Sanity check of header for table \"ttt\"...\n");
FF"      IF( ( ttt_h.maxlen .LE. 0 ) .OR.\n");
FF"     +    ( ttt_h.nok .GT. ttt_h.maxlen ) ) THEN\n");
FF"         %s = STAFCV_BAD\n",gPamUp);
FF"         RETURN\n");
FF"      ENDIF\n");
FF"\n");
FF"C: Show data of INTEGER*4 scalar column \"sss\" of table \"ttt\"...\n");
FF"      DO I = 1 , ttt_h.nok\n");
FF"         WRITE(6,*)' sss = ',ttt(I).sss\n");
FF"      ENDDO\n");
FF"\n");
FF"C: Show data of INTEGER*4 3d-vector column \"vvv\" of table \"ttt\"...\n");
FF"      DO I = 1 , ttt_h.nok\n");
FF"         DO J = 1 , 3\n");
FF"             WRITE(6,*)' vvv(',J,') = ',ttt(I).vvv(J)\n");
FF"         ENDDO\n");
FF"      ENDDO\n");
FF"\n");
FF"      %s=STAFCV_OK\n",gPamUp);
FF"      RETURN\n");
FF"      END\n");
}
void TemplateCBegin(FILE *ff) {
  FF
  "/*:>--------------------------------------------------------------------\n"
  );
  FF"**: FILE:       %s.c.template\n",gPam);
  FF"**: HISTORY:\n");
  FF"**:             00jan93-v000a-hpl- Created by stic Version\n");
  FF"**: %s\n",gCvsVersion);
  FF
  "**:<------------------------------------------------------------------*/\n"
  );
}
void TemplateCMiddle(char *filename,FILE *ff) {
  FF
  "/*:>--------------------------------------------------------------------\n"
  );
  FF"**: ROUTINE:    %s_\n",gPam);
  FF"**: DESCRIPTION: Physics Analysis Module ANSI C template.\n");
  FF"**:             This is an ANSI C Physics Analysis Module template\n");
  FF"**:             automatically generated by stic from %s.\n",
  filename);
  FF"**:             Please edit comments and code.\n");
  FF"**: AUTHOR:     hpl - H.P. Lovecraft, hplovecraft@cthulhu.void\n");
  FF"**: ARGUMENTS:\n");
}
void TemplateCEnd(FILE *ff) {
  FF"**: RETURNS:    STAF Condition Value\n");
  FF
  "**:>------------------------------------------------------------------*/\n"
  );
  FF"\n");
  FF">>>>>>>>>>>>>>> This file will not compile as is. <<<<<<<<<<<<<<<\n");
  FF">>>>> The following code is for example purposes only.      <<<<<\n");
  FF">>>>> Please remove it and put your own analysis code in    <<<<<\n");
  FF">>>>> its place.                                            <<<<<\n");
  FF">>>>>>>>>>>>>>> This file will not compile as is. <<<<<<<<<<<<<<<\n");
  FF"\n");
  FF"    long i,j;\n");
  FF"\n");
  FF"/* Unsuccessful completion of analysis module... */\n");
  FF"    return STAFCV_BAD;\n");
  FF"\n");
  FF"/* Successful completion of analysis module... */\n");
  FF"    return STAFCV_OK;\n");
  FF"\n");
  FF"/* Sanity check of header for table \"ttt\"... */\n");
  FF"    if( ( ttt_h->maxlen <= 0 ) ||\n");
  FF"       ( ttt_h->nok > ttt_h->maxlen ) ){\n");
  FF"       return STAFCV_BAD;\n");
  FF"    }\n");
  FF"\n");
  FF"/* Show data of long scalar column \"sss\" of table \"ttt\"... */\n");
  FF"    for( i=0; i<ttt_h->nok; i++ ){\n");
  FF"        printf(\" sss = %%d\\n\",ttt[i].sss);\n");
  FF"    }\n");
  FF"\n");
  FF"/* Show data of long 3d-vector column \"vvv\" of table \"ttt\"... */\n");
  FF"    for( i=0; i<ttt_h->nok; i++ ){\n");
  FF"       for( j=0; j<3; j++ ){\n");
  FF"           printf(\" vvv[%%d] = %%d\\n\",j,ttt[i].vvv[j]);\n");
  FF"       }\n");
  FF"    }\n");
  /* FF"   printf(\"%s: ##### Stopping #####\\n\");\n",gPamUp); */
  FF"\n");
  FF"   return STAFCV_OK;\n");
  FF"}\n");
}
