/*   Table type: sca_prior.idl
*   written by L. D. Carr -- lcarr@u.washington.edu
*/

   /*******************  Row struct *******************/
   struct sca_prior {
  	float  	w;
  	long 	marker;
   };
/*  Last mod. for sca_prior.idl :  $DATE$ */
