/*   Table type: sca_out.idl
*   written by L. D. Carr -- lcarr@u.washington.edu
*/

/*******************  Row struct *******************/
  struct sca_out {
    long   index;
    float scale_x;          /* log10(binsize/datasize) in x */
    float scale_y;          /* log10(binsize/datasize) in y */
    float rank;             /* entropy is this rank (q) Renyi entropy */
    float volume;           /* Correlation integral C_q (volume) */
                            /* C_q = sum over occup. bins of (n_i/N)^q */
    float entropy;          /* S_q = 1/(1-q) log10 [C_q] */
    float dim;              /* negative slope of entropy in scale */
    float info;             /* Difference I_q from reference entropy */
                            /* I_q = S_q - S_qref */
    float dim_lower;        /* Dimension lowering; diff. from refr. */
                            /* delta d_q = d_q - d_qref */
    long evn;                /* event number */
    long run;                /* run number */
   };
/*  Last mod. for sca_out.idl :  $DATE$ */
