/*   Table type: sca_filter_const.idl
*   written by L. D. Carr -- lcarr@u.washington.edu
*/

   /*******************  Row struct *******************/
   struct sca_filter_const {
	float	pointsPerTrack;
	float	minPT;		/* transverse momentum         */
	float	maxPT;
	float	minY;		/* rapidity                    */
	float	maxY;
	float	InversSlope;    /* inverse slope of mt spectra */
	float	nGoodTraks;     /* total no. of good tracks    */
   };
/*  Last mod. for sca_filter_const.idl :  $DATE$ */
