/*   Table type: sca_const.idl
*   written by L. D. Carr -- lcarr@u.washington.edu
*/

   /*******************  Row struct *******************/
   struct sca_const {
	long	num_dim;
	float	minbinsize_x;
	float	maxbinsize_x;
	float	minbinsize_y;
	float	maxbinsize_y;
	float	step_binsize_x;
	float	step_binsize_y;
	float	auto_size;
	float	xmin;
	float	xmax;
	float	ymin;
	float	ymax;
	float	zmin;
	float	zmax;
	long	num_ranks;
	float	rank[10];
	long	dithmin;
	float	dithscale;
	float	perfectdither;
   };
/*  Last mod. for sca_const.idl :  $DATE$ */
