//:Copyright 1995, Lawrence Berkeley Laboratory
//:>--------------------------------------------------------------------
//:FILE:	spxI.idl
//:DESCRIPTION:	Interface definitions for SPX.
//:AUTHOR:	cet - Craig E. Tull, cetull@lbl.gov
//:BUGS:	-- STILL IN DEVELOPMENT --
//:HISTORY:	02feb97-v001b-cet- rename file
//:HISTORY:	20nov95-v001a-cet- include dependency on SOC
//:HISTORY:	25oct95-v000a-cet- creation
//:<--------------------------------------------------------------------

//:----------------------------------------------- INCLUDES           --
#include "socI.idl"

//:----------------------------------------------- TYPEDEFS           --

//:=============================================== INTERFACE          ==
interface spxDummyI : socObjectI {

//:----------------------------------------------- ATTRIBUTES         --
readonly attribute long nCalls;
		/* The number of calls to method and/or attribute
		functions of the object. */

//:----------------------------------------------- FUNCTIONS          --
STAFCV_T null();
		/* Do nothing. */
STAFCV_T getTime(out string time);
		/* Return a time string (local time). */

};

//:=============================================== INTERFACE          ==
interface spxGridI : socObjectI {

//:----------------------------------------------- ATTRIBUTES         --
readonly attribute short height;
		/* Height (# of rows) of the grid object. */
readonly attribute short width;
		/* Width (# of columns) of the grid object. */

//:----------------------------------------------- FUNCTIONS          --
STAFCV_T get(in short n, in short m, out long value);
		/* Get the cell value from cell (n,m). */
STAFCV_T set(in short n, in short m, in long value);
		/* Set the cell value in cell (n,m). */

};

//:=============================================== INTERFACE          ==
interface spxFactoryI : socFactoryI {

//:----------------------------------------------- ATTRIBUTES         --

//:----------------------------------------------- FUNCTIONS          --
STAFCV_T deleteDummy(in string name);
		/* Delete an spxDummy object. */
spxDummyI findDummy(in string name);
		/* Locate an spxDummy object by name. */
spxDummyI getDummy(in IDREF_T id);
		/* Locate an spxDummy object by idRef#. */
spxDummyI newDummy(in string name);
		/* Create a new spxDummy object. */

STAFCV_T deleteGrid(in string name);
		/* Delete an spxGrid object. */
spxGridI findGrid(in string name);
		/* Locate an spxGrid object by name. */
spxGridI getGrid(in IDREF_T id);
		/* Locate an spxGrid object by idRef#. */
spxGridI newGrid(in string name, in short height, in short width);
		/* Create a new spxGrid object. */

};

