*
* $Id: kcsigm.inc,v 1.1 1998/09/18 00:29:07 fisyak Exp $
*
* $Log: kcsigm.inc,v $
* Revision 1.1  1998/09/18 00:29:07  fisyak
* Add break off for Linux
*
* Revision 1.1.1.1  1996/03/08 15:32:59  mclareni
* Kuip
*
*
#ifndef CERNLIB_KUIP_KCSIGM_INC
#define CERNLIB_KUIP_KCSIGM_INC
*
*
* kcsigm.inc
*
      COMMON /KCSIGM/ ISIADD,NVSIGM

      COMMON /SIKUIP/ CHSIGM
      CHARACTER*80 CHSIGM


#endif
