*
* $Id: kcvect.inc,v 1.1 1998/09/18 00:29:07 fisyak Exp $
*
* $Log: kcvect.inc,v $
* Revision 1.1  1998/09/18 00:29:07  fisyak
* Add break off for Linux
*
* Revision 1.1.1.1  1996/03/08 15:32:59  mclareni
* Kuip
*
*
#ifndef CERNLIB_KUIP_KCVECT_INC
#define CERNLIB_KUIP_KCVECT_INC
*
*
* kcvect.inc
*
      COMMON /KCVECT/ NUMVEC,TOTPAV,GETPAV,TVECFL
      INTEGER TOTPAV,GETPAV
      LOGICAL TVECFL


#endif
