/*********************************** 
** Fri May 24 22:07:21 1996
** Automatically generated by /afs/rhic/star/arch/irix/dev/sys/bin/stafGen 
** DO NOT EDIT THIS FILE 
***********************************/ 
 
/*------------------ INCLUDES ----*/ 
#include <stream.h> 
#include <stdlib.h> 
#include <string.h> 
#include "kuip.h" 
 
/*------------------ ASPS --------*/ 
#include "asuLib.h" 
#include "emlLib.h" 
#include "socLib.h" 
#include "spxLib.h" 
#include "tdmLib.h" 
#include "duiLib.h" 
#include "dioLib.h" 
#include "amiLib.h" 
 
/*------------------ PAMS --------*/ 
#include "pam_load.h" 
 
/*------------------ PROTOTYPES --*/ 
extern CC_P int ami_load(amiBroker *broker); 
void unknown(); 
void usage(char* prog); 
 
/*================== MAIN ========*/ 
int main(int argc, char** argv) 
{ 
   if( argc != 1 )usage(argv[0]); 
 
/*------------------ START -------*/ 
#ifdef ASU 
   asu_init(); asu_start(); 
#endif /* ASU */ 
 
#ifdef EML 
   eml_init(); eml_start(); 
#endif /* EML */ 
 
#ifdef SOC 
   soc_init(); soc_start(); 
#endif /* SOC */ 
 
#ifdef SPX 
   spx_init(); spx_start(); 
#endif /* SPX */ 
 
#ifdef TDM 
   tdm_init(); tdm_start(); 
#endif /* TDM */ 
 
#ifdef DUI 
   dui_init(); dui_start(); 
#endif /* DUI */ 
 
#ifdef DIO 
   dio_init(); dio_start(); 
#endif /* DIO */ 
 
#ifdef AMI 
   ami_init(); ami_start(); 
#endif /* AMI */ 
 
 
/*------------------ INPUT -------*/ 
   printf("STAF - ready for user input.\n"); 
   ku_what(unknown); 
   printf("STAF - done with user input.\n"); 
 
/*------------------ STOP --------*/ 
#ifdef AMI 
   ami_stop(); 
#endif /* AMI */ 
 
#ifdef DIO 
   dio_stop(); 
#endif /* DIO */ 
 
#ifdef DUI 
   dui_stop(); 
#endif /* DUI */ 
 
#ifdef TDM 
   tdm_stop(); 
#endif /* TDM */ 
 
#ifdef SPX 
   spx_stop(); 
#endif /* SPX */ 
 
#ifdef SOC 
   soc_stop(); 
#endif /* SOC */ 
 
#ifdef EML 
   eml_stop(); 
#endif /* EML */ 
 
#ifdef ASU 
   asu_stop(); 
#endif /* ASU */ 
 
 
   return 1; 
} 
 
/*================== UNKNOWN =====*/ 
void unknown(){} 
 
/*================== USAGE =======*/ 
void usage(char* prog) 
{ 
   printf("Usage: %s \n",prog); 
   exit(0); 
} 
 
/*================== AMI_LOAD ====*/ 
int ami_load(amiBroker *broker) 
{ 
#include "pam_load.cc" 
 
   return TRUE; 
} 
 
