/*   gl3Para 
   Controls sl3Tpc
*/
struct gl3Para {
   short      infoLevel    ;     /* level of print info about progress */
   float      BField       ;     /* Magnetic field in Teslas */
   short      MergePrimaries ;   /* Flag to turn on(1)/off merging of primary tracks */
   long       NumberOfPsiSlices ;/* Number of psi slices for merger */
   long       NumberOfTanLSlices;/* Number of TanL slices for merger */
   float      MinSlicePsi  ;     /* Minimum psi value for merger */
   float      MaxSlicePsi  ;     /* Maximum psi value for merger */
   float      MinSliceTanL ;     /* Minimum Tanl value for merger */
   float      MaxSliceTanL ;     /* Maximum Tanl value for merger */
   float      SDPsiMaxMerge ;    /* Maximum psi  distance to merge primaries */
   float      SDTanlMaxMerge ;   /* Maximum tanl distance to merge primaries */
};

