/*   l3clPad
 * Table containing pad id's and pointers to adc values in l3cl_pixel table
*/
   struct l3clPad{
       short      row;        /* row number */
       short      pad;        /* pad number within a row */
       long	  first;      /* first time bin in sequence */
       long       last;       /* last time bin in sequence */
       long       jpix;       /* offset into the l3cl_pixel table */
   };
/*  Last mod. for l3clPad: $Date: 1998/11/10 16:21:20 $ */
