//   l3clPara    
// Controls L3 cluster finder
//
struct l3clPara {
   short      StartRow  ;     // First Padrow to be processed
   short      EndRow    ;     // Last  Padrow to be processed
   short      sector    ;
};
