/* 
Level 3 Geometry
 */
struct l3Geom {
	long nPadsInRow[45];
	float padrowOffset[45];
	float padSpacing[45];
	float sinPhi[24];
	float cosPhi[24];
	float driftLength;
	float timeScale; 
	float offset; 
};
/*  Last mod. for l3Geom: $Date: 1999/03/03 21:15:17 $ */

