/*   sl3Monitor  
   Monitors tracking performance 
*/
struct sl3Monitor  {
   short      sector       ;     /* sector processed */
   long       nPoints      ;     /* # of space points in sector */
   long       nTracks      ;     /* # of reconstructed tracks  */
   float      sTime        ;     /* Time required for processing */
};

