/*   sl3Track 
 * Table containing buffer with hit/track information
*/
struct sl3Track{
    char       data ;      /* 1 byte variable */
};
/*  Last mod. for sl3Track: $Date: 1999/07/07 19:02:59 $ */
