/* $Id: g2t_gem.idl,v 1.1 2006/06/26 18:06:42 potekhin Exp $
   $Log: g2t_gem.idl,v $
   Revision 1.1  2006/06/26 18:06:42  potekhin
   Requisite stub for the GEM detector interface


*/
#include "PAM.idl"
#include "g2t_track.idl"
#include "g2t_gem_hit.idl"

interface g2t_gem : amiModule{ STAFCV_T call (inout g2t_track g2t_track,
                                              out g2t_gem_hit g2t_gem_hit ); };
                      
