/*  g2t_comb.idl
*
*   Module: g2t_comb
*         description: This routine intelligently combines two g2t events
*                      Currently, it only worries about the TPC
*/

#include "PAM.idl"
#include "g2t_tpc_hit.idl"
#include "g2t_track.idl"
#include "g2t_vertex.idl"

interface g2t_comb : amiModule {
        STAFCV_T call
                ( inout g2t_tpc_hit g2t_hit_1
                , inout g2t_track g2t_track_1
                , inout g2t_vertex g2t_vertex_1
                , inout g2t_tpc_hit g2t_hit_2
                , inout g2t_track g2t_track_2
                , inout g2t_vertex g2t_vertex_2
                , inout g2t_tpc_hit g2t_hit_out
                , inout g2t_track g2t_track_out
                , inout g2t_vertex g2t_vertex_out
                );
};
/* Last mod. for g2t_comb: $Date: 1998/08/05 20:30:27 $ */
