/*          file:   g2t_pmd.idl
*           Module: g2tmain
*/
#include "PAM.idl"
#include "g2t_track.idl"
#include "g2t_pmd_hit.idl"

interface g2t_pmd : amiModule{ STAFCV_T call (inout g2t_track g2t_track,
                                              out g2t_pmd_hit g2t_pmd_hit ); };

