/*          g2t_get_kine.idl
*           Module: g2t_get_kine
*           Description: 
*/
#include "PAM.idl"
#include "g2t_vertex.idl"
#include "g2t_track.idl"
interface g2t_get_kine : amiModule{
          STAFCV_T call ( out    g2t_vertex         p_vert
			, out    g2t_track          p_track);
};
/* Last mod. for g2t: $Date: 1998/01/03 23:46:35 $ */




