/* Last mod. for g2t: $Date: 2004/08/05 16:39:12 $ */

/*          g2t_get_event.idl
*           Module: g2t_get_event
*/
#include "PAM.idl"
#include "g2t_pythia.idl"
interface g2t_get_pythia: amiModule {STAFCV_T call(out g2t_pythia pythia); };




