/* $Id: g2t_igt.idl,v 1.2 2006/06/26 18:05:18 potekhin Exp $
   $Log: g2t_igt.idl,v $
   Revision 1.2  2006/06/26 18:05:18  potekhin
   Add CVS tag


          file:   g2tmain.idl
          Module: g2tmain
*/
#include "PAM.idl"
#include "g2t_track.idl"
#include "g2t_igt_hit.idl"

interface g2t_igt : amiModule{ STAFCV_T call (inout g2t_track g2t_track,
                                              out g2t_igt_hit g2t_igt_hit ); };
                      
