/*          g2t_get_kine.idl
*           Module: g2t_get_kine
*           Description: general hit filling 
*
*/
#include "PAM.idl"
#include "g2t_vertex.idl"
#include "g2t_track.idl"
#include "g2t_hits.idl"
interface g2t_get_hits : amiModule{
          STAFCV_T call ( inout    g2t_vertex         p_vert
			, inout    g2t_track          p_track
			, inout    g2t_hits           p_hits
                        );
};
/* Last mod. for g2t: $Date: 1998/05/16 19:29:52 $ */




