/*          file:   g2tmain.idl
*           Module: g2tmain
*/
#include "PAM.idl"
#include "g2t_run.idl"    
#include "g2t_event.idl"  
#include "g2t_gepart.idl"   
#include "particle.idl"

#include "g2t_vertex.idl"
#include "g2t_track.idl"
#include "g2t_hits.idl"

#include "g2t_svt_hit.idl"  
#include "g2t_tpc_hit.idl"
#include "g2t_mwc_hit.idl"  
#include "g2t_ctf_hit.idl"
#include "g2t_emc_hit.idl"  
#include "g2t_smd_hit.idl"  
#include "g2t_eem_hit.idl"  
#include "g2t_esm_hit.idl"  
#include "g2t_ftp_hit.idl"  
#include "g2t_vpd_hit.idl"

#include "btof_btog.idl"
#include "btof_ctbb.idl"
#include "btof_toff.idl"
#include "btof_tray.idl"
#include "calb_calg.idl"
#include "cave_cave.idl"
#include "ecal_eetr.idl"
#include "ecal_emcg.idl"
#include "ecal_emxg.idl"
#include "ecal_esec.idl"
#include "ecal_exse.idl"
#include "ftpc_ffcc.idl"
#include "ftpc_frbd.idl"
#include "ftpc_fssd.idl"
#include "ftpc_ftpg.idl"
#include "magp_magg.idl"
#include "magp_mbar.idl"
#include "magp_mend.idl"
#include "mfld_mflg.idl"
#include "pipe_pipg.idl"
#include "svtt_selc.idl"
#include "svtt_serg.idl"
#include "svtt_sfpa.idl"
#include "svtt_ssup.idl"
#include "svtt_svtg.idl"
#include "svtt_svtl.idl"
#include "svtt_swam.idl"
#include "svtt_swca.idl"
#include "tpce_tecw.idl"
#include "tpce_tpcg.idl"
#include "tpce_tprs.idl"
#include "vpdd_vpdg.idl"


interface g2tmain : amiModule{ STAFCV_T call ( ); };
