/*          file:   g2tmain.idl
*           Module: g2tmain
*/
#include "PAM.idl"
#include "g2t_run.idl"    
#include "g2t_event.idl"  
#include "g2t_gepart.idl"   
#include "particle.idl"

#include "g2t_vertex.idl"
#include "g2t_track.idl"
#include "g2t_hits.idl"

#include "g2t_svt_hit.idl"  
#include "g2t_tpc_hit.idl"
#include "g2t_mwc_hit.idl"  
#include "g2t_ctf_hit.idl"
#include "g2t_emc_hit.idl"  
#include "g2t_smd_hit.idl"  
#include "g2t_eem_hit.idl"  
#include "g2t_esm_hit.idl"  
#include "g2t_ftp_hit.idl"  
#include "g2t_vpd_hit.idl"

interface g2tmain : amiModule{ STAFCV_T call ( ); };
