Common block PARAM.CMM : atomic parameters, 17.5.1994
	parameter (pi = 3.1415926536, elmm = 0.51099906, Ry = 13.6056981)
C electron mass (MEV), Rydberg(eV)
	parameter (hbc = 1.97327052e-5, fanco = 1.09762e-16 )
C h bar c (eV cm), Fano-Cooper constant (eV cm**2)
	parameter (bohr = 0.529177249e-8, fnstr = 137.0359895 )
C Bohr radius (cm), 1/alpha = fine structure constant
	parameter (rzer = 2.81794092e-13)
Classical electron radius (cm)
	parameter (prm = 938.2723, pion= 139.567, pmuo=105.65932 )
C proton-, pion-, muon-mass (MeV)
	parameter (amu = 931.4943, avog= 6.0221367e23, hce=12398.42 )
C atomic mass unit (MeV), Avogadro's number, hc/e (eV nm)
