//
// File generated by rootcint at Fri May 19 13:19:28 2000.
// Do NOT change. Changes will be lost next time file is generated
//
#include "FtfBaseHitDict.h"

#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

//______________________________________________________________________________
TBuffer &operator>>(TBuffer &buf, FtfBaseHit *&obj)
{
   // Read a pointer to an object of class FtfBaseHit.

   ::Error("FtfBaseHit::operator>>", "objects not inheriting from TObject need a specialized operator>> function"); if (obj) { }
   return buf;
}

//______________________________________________________________________________
void FtfBaseHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class FtfBaseHit.

   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(); if (R__v) { }
      R__b >> id;
      R__b >> row;
      //R__b.ReadArray(track);
      //R__b.ReadArray(nextTrackHit);
      //R__b.ReadArray(nextMcTrackHit);
      R__b >> xyChi2;
      R__b >> szChi2;
      R__b >> x;
      R__b >> y;
      R__b >> z;
      R__b >> dx;
      R__b >> dy;
      R__b >> dz;
      R__b >> q;
      R__b >> wxy;
      R__b >> wz;
      R__b >> s;
   } else {
      R__b.WriteVersion(FtfBaseHit::IsA());
      R__b << id;
      R__b << row;
      //R__b.WriteArray(track, __COUNTER__);
      //R__b.WriteArray(nextTrackHit, __COUNTER__);
      //R__b.WriteArray(nextMcTrackHit, __COUNTER__);
      R__b << xyChi2;
      R__b << szChi2;
      R__b << x;
      R__b << y;
      R__b << z;
      R__b << dx;
      R__b << dy;
      R__b << dz;
      R__b << q;
      R__b << wxy;
      R__b << wz;
      R__b << s;
   }
}

//______________________________________________________________________________
void FtfBaseHit::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
   // Inspect the data members of an object of class FtfBaseHit.

   TClass *R__cl  = FtfBaseHit::IsA();
   Int_t   R__ncp = strlen(R__parent);
   if (R__ncp || R__cl || R__insp.IsA()) { }
   R__insp.Inspect(R__cl, R__parent, "id", &id);
   R__insp.Inspect(R__cl, R__parent, "row", &row);
   R__insp.Inspect(R__cl, R__parent, "*track", &track);
   R__insp.Inspect(R__cl, R__parent, "*nextTrackHit", &nextTrackHit);
   R__insp.Inspect(R__cl, R__parent, "*nextMcTrackHit", &nextMcTrackHit);
   R__insp.Inspect(R__cl, R__parent, "xyChi2", &xyChi2);
   R__insp.Inspect(R__cl, R__parent, "szChi2", &szChi2);
   R__insp.Inspect(R__cl, R__parent, "x", &x);
   R__insp.Inspect(R__cl, R__parent, "y", &y);
   R__insp.Inspect(R__cl, R__parent, "z", &z);
   R__insp.Inspect(R__cl, R__parent, "dx", &dx);
   R__insp.Inspect(R__cl, R__parent, "dy", &dy);
   R__insp.Inspect(R__cl, R__parent, "dz", &dz);
   R__insp.Inspect(R__cl, R__parent, "q", &q);
   R__insp.Inspect(R__cl, R__parent, "wxy", &wxy);
   R__insp.Inspect(R__cl, R__parent, "wz", &wz);
   R__insp.Inspect(R__cl, R__parent, "s", &s);
}

/********************************************************
* FtfBaseHitDict.cxx
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#endif

extern "C" void G__cpp_reset_tagtableFtfBaseHitDict();

extern "C" void G__set_cpp_environmentFtfBaseHitDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../inc/FtfBaseHit.h");
  G__cpp_reset_tagtableFtfBaseHitDict();
}
extern "C" int G__cpp_dllrevFtfBaseHitDict() { return(51111); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* FtfBaseHit */
static int G__FtfBaseHit_print_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((FtfBaseHit*)(G__getstructoffset()))->print();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_print_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((FtfBaseHit*)(G__getstructoffset()))->print((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_DeclFileName_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((FtfBaseHit*)(G__getstructoffset()))->DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_DeclFileLine_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((FtfBaseHit*)(G__getstructoffset()))->DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_ImplFileName_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((FtfBaseHit*)(G__getstructoffset()))->ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_ImplFileLine_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((FtfBaseHit*)(G__getstructoffset()))->ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_Class_Version_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)((FtfBaseHit*)(G__getstructoffset()))->Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_Class_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((FtfBaseHit*)(G__getstructoffset()))->Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_IsA_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const FtfBaseHit*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_ShowMembers_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((FtfBaseHit*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_Streamer_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((FtfBaseHit*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FtfBaseHit_Dictionary_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((FtfBaseHit*)(G__getstructoffset()))->Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic default constructor
static int G__FtfBaseHit_FtfBaseHit_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   FtfBaseHit *p;
   if(0!=libp->paran) ;
   if(G__getaryconstruct()) p=new FtfBaseHit[G__getaryconstruct()];
   else                    p=new FtfBaseHit;
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__FtfBaseHitDictLN_FtfBaseHit);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__FtfBaseHit_FtfBaseHit_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   FtfBaseHit *p;
   p=new FtfBaseHit(*(FtfBaseHit*)G__int(libp->para[0]));
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__FtfBaseHitDictLN_FtfBaseHit);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
static int G__FtfBaseHit_wAFtfBaseHit_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (FtfBaseHit *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (FtfBaseHit *)((G__getstructoffset())+sizeof(FtfBaseHit)*i);
   else  delete (FtfBaseHit *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* FtfBaseHit */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncFtfBaseHitDict {
 public:
  G__Sizep2memfuncFtfBaseHitDict() {p=&G__Sizep2memfuncFtfBaseHitDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncFtfBaseHitDict::*p)();
};

size_t G__get_sizep2memfuncFtfBaseHitDict()
{
  G__Sizep2memfuncFtfBaseHitDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceFtfBaseHitDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableFtfBaseHitDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,
-1);
   G__setnewtype(-1,"Signed Character 1 byte",0);
   G__search_typename2("UChar_t",98,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Character 1 byte",0);
   G__search_typename2("Short_t",115,-1,0,
-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes",0);
   G__search_typename2("UShort_t",114,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes",0);
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes",0);
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes",0);
   G__search_typename2("Seek_t",105,-1,0,
-1);
   G__setnewtype(-1,"File pointer",0);
   G__search_typename2("Long_t",108,-1,0,
-1);
   G__setnewtype(-1,"Signed long integer 8 bytes",0);
   G__search_typename2("ULong_t",107,-1,0,
-1);
   G__setnewtype(-1,"Unsigned long integer 8 bytes",0);
   G__search_typename2("Float_t",102,-1,0,
-1);
   G__setnewtype(-1,"Float 4 bytes",0);
   G__search_typename2("Double_t",100,-1,0,
-1);
   G__setnewtype(-1,"Float 8 bytes",0);
   G__search_typename2("Text_t",99,-1,0,
-1);
   G__setnewtype(-1,"General string",0);
   G__search_typename2("Bool_t",98,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true)",0);
   G__search_typename2("Byte_t",98,-1,0,
-1);
   G__setnewtype(-1,"Byte (8 bits)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier",0);
   G__search_typename2("Option_t",99,-1,0,
-1);
   G__setnewtype(-1,"Option string",0);
   G__search_typename2("Ssiz_t",105,-1,0,
-1);
   G__setnewtype(-1,"String size",0);
   G__search_typename2("Real_t",102,-1,0,
-1);
   G__setnewtype(-1,"TVector and TMatrix element type",0);
   G__search_typename2("VoidFuncPtr_t",89,-1,0,
-1);
   G__setnewtype(-1,"pointer to void function",0);
   G__search_typename2("FreeHookFun_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocCFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Axis_t",102,-1,0,
-1);
   G__setnewtype(-1,"Axis values type",0);
   G__search_typename2("Stat_t",100,-1,0,
-1);
   G__setnewtype(-1,"Statistics type",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* FtfBaseHit */
static void G__setup_memvarFtfBaseHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__FtfBaseHitDictLN_FtfBaseHit));
   { FtfBaseHit *p; p=(FtfBaseHit*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->id)-(long)(p)),105,0,0,-1,-1,-1,1,"id=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->row)-(long)(p)),115,0,0,-1,-1,-1,1,"row=",0,"Row #     ");
   G__memvar_setup((void*)((long)(&p->track)-(long)(p)),89,0,0,-1,-1,-1,1,"track=",0,"track to which the pnt was assigned");
   G__memvar_setup((void*)((long)(&p->nextTrackHit)-(long)(p)),89,0,0,-1,-1,-1,1,"nextTrackHit=",0,"Next track hit             ");
   G__memvar_setup((void*)((long)(&p->nextMcTrackHit)-(long)(p)),89,0,0,-1,-1,-1,1,"nextMcTrackHit=",0,"Next MC track hit");
   G__memvar_setup((void*)((long)(&p->xyChi2)-(long)(p)),102,0,0,-1,-1,-1,1,"xyChi2=",0,"Chi2 in xy                 ");
   G__memvar_setup((void*)((long)(&p->szChi2)-(long)(p)),102,0,0,-1,-1,-1,1,"szChi2=",0,"Chi2 in sz                 ");
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),102,0,0,-1,-1,-1,1,"x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),102,0,0,-1,-1,-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->z)-(long)(p)),102,0,0,-1,-1,-1,1,"z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dx)-(long)(p)),102,0,0,-1,-1,-1,1,"dx=",0,"error on the x coordinate  ");
   G__memvar_setup((void*)((long)(&p->dy)-(long)(p)),102,0,0,-1,-1,-1,1,"dy=",0,"error on the y coordinate  ");
   G__memvar_setup((void*)((long)(&p->dz)-(long)(p)),102,0,0,-1,-1,-1,1,"dz=",0,"error on the z coordinate  ");
   G__memvar_setup((void*)((long)(&p->q)-(long)(p)),102,0,0,-1,-1,-1,1,"q=",0,"total charge assigned to this point ");
   G__memvar_setup((void*)((long)(&p->wxy)-(long)(p)),102,0,0,-1,-1,-1,1,"wxy=",0,"x-y weight x-y");
   G__memvar_setup((void*)((long)(&p->wz)-(long)(p)),102,0,0,-1,-1,-1,1,"wz=",0,"z weight on z");
   G__memvar_setup((void*)((long)(&p->s)-(long)(p)),102,0,0,-1,-1,-1,1,"s=",0,"Track trajectory");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__FtfBaseHitDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarFtfBaseHitDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncFtfBaseHit(void) {
   /* FtfBaseHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__FtfBaseHitDictLN_FtfBaseHit));
   G__memfunc_setup("print",557,G__FtfBaseHit_print_0_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("print",557,G__FtfBaseHit_print_1_0,121,-1,-1,0,1,1,1,0,"i - - 0 - level",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__FtfBaseHit_DeclFileName_2_0,67,-1,-1,0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__FtfBaseHit_DeclFileLine_3_0,105,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__FtfBaseHit_ImplFileName_4_0,67,-1,-1,0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__FtfBaseHit_ImplFileLine_5_0,105,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__FtfBaseHit_Class_Version_6_0,115,-1,G__defined_typename("Version_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__FtfBaseHit_Class_7_0,85,G__get_linked_tagnum(&G__FtfBaseHitDictLN_TClass),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__FtfBaseHit_IsA_8_0,85,G__get_linked_tagnum(&G__FtfBaseHitDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__FtfBaseHit_ShowMembers_9_0,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__FtfBaseHit_Streamer_0_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Dictionary",1046,G__FtfBaseHit_Dictionary_1_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic default constructor
   G__memfunc_setup("FtfBaseHit",960,G__FtfBaseHit_FtfBaseHit_2_1,(int)('i'),G__get_linked_tagnum(&G__FtfBaseHitDictLN_FtfBaseHit),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("FtfBaseHit",960,G__FtfBaseHit_FtfBaseHit_3_1,(int)('i'),G__get_linked_tagnum(&G__FtfBaseHitDictLN_FtfBaseHit),-1,0,1,1,1,0,"u 'FtfBaseHit' - 1 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~FtfBaseHit",1086,G__FtfBaseHit_wAFtfBaseHit_4_1,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncFtfBaseHitDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_globalFtfBaseHitDict() {

   /* Setting up global variables */
   G__resetplocal();


   G__resetglobalenv();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_funcFtfBaseHitDict() {
   G__lastifuncposition();


   G__resetifuncposition();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__FtfBaseHitDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__FtfBaseHitDictLN_FtfBaseHit = { "FtfBaseHit" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableFtfBaseHitDict() {
  G__FtfBaseHitDictLN_TClass.tagnum = -1 ;
  G__FtfBaseHitDictLN_FtfBaseHit.tagnum = -1 ;
}

extern "C" void G__cpp_setup_tagtableFtfBaseHitDict() {

   /* Setting up class,struct,union tag entry */
   G__tagtable_setup(G__get_linked_tagnum(&G__FtfBaseHitDictLN_FtfBaseHit),sizeof(FtfBaseHit),-1,0,(char*)NULL,G__setup_memvarFtfBaseHit,G__setup_memfuncFtfBaseHit);
}
extern "C" void G__cpp_setupFtfBaseHitDict() {
  G__check_setup_version(51111,"G__cpp_setupFtfBaseHitDict()");
  G__set_cpp_environmentFtfBaseHitDict();
  G__cpp_setup_tagtableFtfBaseHitDict();

  G__cpp_setup_inheritanceFtfBaseHitDict();

  G__cpp_setup_typetableFtfBaseHitDict();

  G__cpp_setup_memvarFtfBaseHitDict();

  G__cpp_setup_memfuncFtfBaseHitDict();
  G__cpp_setup_globalFtfBaseHitDict();
  G__cpp_setup_funcFtfBaseHitDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncFtfBaseHitDict();
  return;
}
class G__cpp_setup_initFtfBaseHitDict {
  public:
    G__cpp_setup_initFtfBaseHitDict() { G__add_setup_func("FtfBaseHitDict",&G__cpp_setupFtfBaseHitDict); }
   ~G__cpp_setup_initFtfBaseHitDict() { G__remove_setup_func("FtfBaseHitDict"); }
};
G__cpp_setup_initFtfBaseHitDict G__cpp_setup_initializerFtfBaseHitDict;

