#export SHELL := csh
ifndef INSTALL
BASE_DIR := $(shell pwd)
INSTALL := -ln -s
INSTALL := cp
endif
#
install_slm:
	$(INSTALL) $(BASE_DIR)/SLM_DIR/* $(SLM_DIR)
#
stafGen: $(SRCM_DIR)/stafGen.cc
	$(CXX) -o $@ $^
