#!/bin/csh

#
# Provide tail for zipped files
# J. Lauret 2010
#
set GREP=/bin/grep
set ZCAT=/bin/zcat
set TAIL=/usr/bin/tail

if ( $#argv == 0) then
    echo "Usage: $0 [options] file"
else
    set count=0
    set FILE=""
    set ARG=""

    while ( $count <= $#argv )
	set arg=$argv[$count]
	@ count++
	set T=`echo $arg | tr '[:alnum:]' ' '`
	#echo "[$T]"
	if ( "x$T" == "x-" ) then
	    set ARG  = "$ARG $arg"
	else
	    set FILE = "$FILE $arg"
	endif

	#echo "[$FILE] [$ARG]"
    end
    if ( "$FILE" != "") then
	$ZCAT $FILE  | $TAIL $ARG
    endif
endif
