// Revision 1.1  2001/06/21 Akio Ogawa + Jan Balewski

struct SpinTag  {
  long  nPrimary;       // number of primary tracks
  float maxPt;     // (GeV/c) the largest Pt of primary tracks
  float sumAbsPt;      // sum of modules of pT of primary tracks
  long  nBemcTower;    // number of BEMC towers above 0.5*MIP=0.15 MeV
  float bemcHighTower; // (GeV) the energy of the highest BEMC tower
};

// may be added:
/*
  long  nCtb;      // number of slats with ADC > 3
  float fpdEnergy; //  (ADC or GeV ?), sum of energy from FPD
  float bbTime;    // (ns or TDC ?) time difference from bbE vs. bbW 
  float bbEnergy;  //  (ADC or GeV ?), sum of energy from  bbE+bbW
*/
