* $Id: gene_do.inc,v 1.1.1.1 2004/01/12 23:49:37 potekhin Exp $
* $Log: gene_do.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:37  potekhin
*
* Revision 1.1  2001/02/27 10:14:15  nevski
*  first working release
*
C event bank offsets
      INTEGER NAGENE
      INTEGER JOGRUN,JOGEVT,JOGNAM,JOVRTX,JOVRTY,JOVRTZ,JOVRTT,
     +        JOWTFL,JOWEIG
      PARAMETER (NAGENE = 9)
      PARAMETER (JOGRUN = 4)
      PARAMETER (JOGEVT = 5)
      PARAMETER (JOGNAM = 6)
      PARAMETER (JOVRTX = 7)
      PARAMETER (JOVRTY = 8)
      PARAMETER (JOVRTZ = 9)
      PARAMETER (JOVRTT = 10)
      PARAMETER (JOWTFL = 11)
      PARAMETER (JOWEIG = 12)

