* $Id: genr_do.inc,v 1.1.1.1 2004/01/12 23:49:37 potekhin Exp $
* $Log: genr_do.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:37  potekhin
*
* Revision 1.1  2001/02/27 10:14:16  nevski
*  first working release
*
C Data offsets
      INTEGER NAGENR
      INTEGER JOGJID,JOGRRU,JOGTIM,JOGDAT,JOMACH,JOGRNA,JOGVER,
     +        JOGVDT,JOGZVR,JOZBVR
      PARAMETER (NAGENR = 10)
      PARAMETER (JOGJID = 4)
      PARAMETER (JOGRRU = 5)
      PARAMETER (JOGTIM = 6)
      PARAMETER (JOGDAT = 7)
      PARAMETER (JOMACH = 8)
      PARAMETER (JOGRNA = 9)
      PARAMETER (JOGVER = 10)
      PARAMETER (JOGVDT = 11)
      PARAMETER (JOGZVR = 12)
      PARAMETER (JOZBVR = 13)

