*
* $Id: gtmutr.inc,v 1.1.1.1 2004/07/17 20:02:49 perev Exp $
*
* $Log: gtmutr.inc,v $
* Revision 1.1.1.1  2004/07/17 20:02:49  perev
* STAR version of Geant321 TGeant3 etc
*
* Revision 1.1.1.1  2002/07/24 15:56:26  rdm
* initial import into CVS
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:34  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTMUTR_INC
#define CERNLIB_GEANT321_GTMUTR_INC
*
*
* gtmutr.inc
*
#if !defined(CERNLIB_INCLUDE)
*
      INTEGER NCVOLS,NSHIFT,KSHIFT,ICUBE,NAIN,JJJ,NIET,IVOOLD,
     +        IWPOIN,IHPOIN,IVECVO,IOLDSU,ICGP,IPORNT
      REAL    GXMIN,GXMAX,GYMIN,GYMAX,GZMIN,GZMAX,GXXXX,GYYYY,GZZZZ
      REAL    CLIPMI,CLIPMA,ABCD,BMIN,BMAX,CGB,CGB1,GBOOM
      REAL    PORGX,PORGY,PORGZ,POX,POY,POZ,PORMIR,PORMAR
#endif

#endif
