*
* $Id: gtparm.inc,v 1.1.1.1 2004/07/17 20:02:49 perev Exp $
*
* $Log: gtparm.inc,v $
* Revision 1.1.1.1  2004/07/17 20:02:49  perev
* STAR version of Geant321 TGeant3 etc
*
* Revision 1.1.1.1  2002/07/24 15:56:26  rdm
* initial import into CVS
*
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:32  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTPARM_INC
#define CERNLIB_GEANT321_GTPARM_INC
*
*
* gtparm.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER IPARAM,MPSTAK,NSPARA,NPGENE
      REAL    PCUTGA,PCUTEL,PCUTNE,PCUTHA,PCUTMU
#endif

#endif
