#!/bin/csh 
set nev=$1
set run=$2
set particle=$3
set e=$4
set pt=$5
set vz=$6
set outdir=$7
set nogeant=$8

echo  nev=$nev run=$run particle=$particle e=$e pt=$pt vz=$vz outdir=$outdir nogeant=$nogeant
 
stardev
set dir=$cwd
set sys=$STAR_HOST_SYS
set tmpdir=/tmp/$USER/fcs

if ( ! -e $tmpdir ) then
  mkdir -p $tmpdir
endif
cd $tmpdir

if ( ! -e .$sys ) then
  ln -s $dir/.$sys 
endif

if ( ! -e StRoot ) then
  ln -s $dir/StRoot
endif

if ( ! -e runSimFlat.C ) then
  ln -s $dir/runSimFlat.C
endif

if ( ! -e runSimBfc.C ) then
  ln -s $dir/runSimBfc.C
endif

if ( ! -e fcs_daq_map.txt ) then
  ln -s $dir/fcs_daq_map.txt
endif

if( ! -e fcs_ecal_et_gains.txt ) then
  ln -s $dir/fcs_ecal_et_gains.txt
endif

if( ! -e fcs_hcal_et_gains.txt ) then
  ln -s $dir/fcs_hcal_et_gains.txt
endif

if( ! -e mask ) then
  ln -s $dir/mask
endif

pwd
ls -ltra

set name={$particle}.pt$pt.vz$vz.run$run
echo nogeant=$nogeant name=$name  

if ( $nogeant == 0 ) then 
  echo root4star -b -q 'runSimFlat.C('$nev','$run',"'$particle'",'$e','$pt','$vz')' 
  root4star -b -q 'runSimFlat.C('$nev','$run',"'$particle'",'$e','$pt','$vz')'
else
  echo /bin/cp $dir/$outdir/$name.fzd $tmpdir/
  /bin/cp $dir/$outdir/$name.fzd $tmpdir/
endif

echo root4star -b -q 'runSimBfc.C('$nev','$run',"'$particle'",'$e','$pt','$vz')'
root4star -b -q 'runSimBfc.C('$nev','$run',"'$particle'",'$e','$pt','$vz',0,0)'

set name={$particle}.pt$pt.vz$vz.run$run
#set name={$particle}.e$e.run$run
echo moving $tmpdir/$name to $dir/$outdir/
ls -ltra  $name.*
/bin/mv $name.* $dir/$outdir/

#/bin/rm {$name}.*

