* $Id: csdim.inc,v 1.1.1.1 2004/01/12 23:49:40 potekhin Exp $
* $Log: csdim.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:40  potekhin
*
* Revision 1.1  2001/02/27 10:15:32  nevski
*  first working release
*
C --- DIMENSION STATEMENTS FOR CROSS SECTION DATA ---
      DIMENSION PLAB(41),CSEL(35,41),CSIN(35,41),CSPIEL(3,41),
     $          CSPIIN(3,41),CSPNEL(3,41),CSPNIN(3,41),
     $          ELAB(17),CNLWAT(15),CNLWEL(15,17),CNLWIN(15,17),
     $          CSCAP(100),EKFISS(21),CSFISS(4,21)
C
