* $Id: defcom.inc,v 1.1.1.1 2004/01/12 23:49:40 potekhin Exp $
* $Log: defcom.inc,v $
* Revision 1.1.1.1  2004/01/12 23:49:40  potekhin
*
* Revision 1.2  2001/03/02 21:17:21  nevski
* commons changed as in atlas version
*
* Revision 1.1  2001/02/27 10:15:33  nevski
*  first working release
*
#include "geant321/mxgkgh.inc"
#include "geant321/s_consts.inc"
#include "geant321/s_curpar.inc"
#include "geant321/s_result.inc"
#include "geant321/s_mat.inc"
#include "geant321/s_event.inc"
#include "geant321/s_prntfl.inc"
#include "geant321/s_errcom.inc"
#include "geant321/s_blank.inc"
C
