/**
 * <hr>
 * STAR VPD module. <br>
 * Outputs vertex calculated from VPD into STAF tables. <br>
 * Uses raw data output to calculate vertex position
 * into <a href=vps_vert.html>vpv_vert</a> table.
 * 
 * @author         Zoran Milosevich
 */

/* vpv.idl */
#include "PAM.idl"
#include "vps_par.idl"
#include "vps_raw.idl"
#include "vpv_vert.idl"

interface vpv : amiModule {
        STAFCV_T call
                ( inout vps_par          vpar
                , inout vps_raw          vraw
                , inout vpv_vert         vver
        );
};
/*  Last mod. for vpv: $Date: 1998/02/10 15:07:40 $ */

