/* scp_init_ped.idl */

#include "PAM.idl"
#include "scp_par.idl"
#include "scp_pedm.idl"

interface scp_init_ped : amiModule {
	STAFCV_T call (
		inout scp_par      par, 
		inout scp_pedm     pedm); 
};

