/* scp_calc_ped.idl */

#include "PAM.idl"
#include "scp_par.idl"
#include "scp_pedm.idl"
#include "scp_ped.idl"
#include "scp_bad_anodes.idl"

interface scp_calc_ped : amiModule {
	STAFCV_T call (
		inout scp_par        par,
		inout scp_pedm       pedm,
		inout scp_ped        ped,
                inout scp_bad_anodes bad_anodes);
};

