/* scp_proc_ped.idl */

#include "PAM.idl"
#include "scp_par.idl"
#include "scp_ped.idl"
#include "scp_pedm.idl"
#include "scp_raw.idl"
#include "scp_bad_anodes.idl"

interface scp_proc_ped : amiModule {
	STAFCV_T call (
		in    scp_par        par,
		in    scp_ped        ped,
		inout scp_pedm       pedm,
		in    scp_raw        raw,
                in    scp_bad_anodes bad_anodes);
};


