#ifndef COIN_PIXMAP_CAGRID_XPM
#define COIN_PIXMAP_CAGRID_XPM
/* XPM */
static const char *cAGrid[] = {
/* columns rows colors chars-per-pixel */
"120 119 6 1",
"  c black",
". c #83AFDB",
"X c #99CCFF",
"o c #A7DFFF",
"O c gray100",
"+ c None",
/* pixels */
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"+++++++++++++++++++++++++                                                                          +++++++++++++++++++++",
"+++++++++++++++++++++++++                                                                           ++++++++++++++++++++",
"++++++++++++++++++++++++                                                                            ++++++++++++++++++++",
"+++++++++++++++++++++++                                                                             ++++++++++++++++++++",
"++++++++++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo      ++++++++++++++++++++",
"+++++++++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo       ++++++++++++++++++++",
"++++++++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo        ++++++++++++++++++++",
"+++++++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    .    ++++++++++++++++++++",
"++++++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ..    ++++++++++++++++++++",
"+++++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ...    ++++++++++++++++++++",
"++++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ....    ++++++++++++++++++++",
"+++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    .....    ++++++++++++++++++++",
"++++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ......    ++++++++++++++++++++",
"+++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    .......    ++++++++++++++++++++",
"++++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ........    ++++++++++++++++++++",
"+++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    .........    ++++++++++++++++++++",
"++++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ..........    ++++++++++++++++++++",
"+++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ...........    ++++++++++++++++++++",
"++++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ............    ++++++++++++++++++++",
"+++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    .............    ++++++++++++++++++++",
"++++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ..............    ++++++++++++++++++++",
"+++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ...............    ++++++++++++++++++++",
"++++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ................    ++++++++++++++++++++",
"+++    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    .................    ++++++++++++++++++++",
"++                                                                            ..................    ++++++++++++++++++++",
"                                                                             ...................    ++++++++++++++++++++",
"                                                                            ....................    ++++++++++++++++++++",
"                                                                            ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................    ++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ...................    +++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ..................    ++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    .................    +++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ................    ++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ...............    +++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ..............    ++++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    .............    +++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ............    ++++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ...........    +++++++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ..........    ++++++++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    .........    +++++++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........    ++++++++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......    +++++++++++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ......    ++++++++++++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    .....    +++++++++++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....    ++++++++++++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ...    +++++++++++++++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX    ..    ++++++++++++++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXXXXXXXXXXXXXXX    .    +++++++++++++++++++++++++++++++++++++++",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ++++++++++++++++++++++++++++++++++++++++",
"    XXXXXXXXX    XXXXXXX    XXXXXXXXX    XXXXXXX    XXXXXXX    XXXXXXXXX       +++++++++++++++++++++++++++++++++++++++++",
"                                                                              ++++++++++++++++++++++++++++++++++++++++++",
"                                                                             +++++++++++++++++++++++++++++++++++++++++++",
"                                                                            ++++++++++++++++++++++++++++++++++++++++++++",
"+                                                                          +++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
};
#endif
