/*	l3 cluster finding
*
*	Module: l3cl      
*	description: Level 3 cluster finder 
*/
#include "PAM.idl"
#include "l3cl_para.idl"
#include "tss_tppad.idl"
#include "tss_tppixel.idl"
#include "tcl_tphit.idl"

interface l3cl : amiModule{
	STAFCV_T call
		( inout l3cl_para    para
                , in    tss_tppad    pad
                , in    tss_tppixel  pixel
                , out   tcl_tphit    hit
		);
};
/* Last mod. for l3cl: $Data$ */
