/*     
*
*       Module: l3Hit2TpcHit
*       description: Fills tpc hits with l3 hit buffer
*/

#include "PAM.idl"
#include "l3Geom.idl"
#include "sl3Buffer.idl"
#include "tcl_tphit.idl"

interface l3Hit2TpcHit: amiModule {
        STAFCV_T call
                ( in	l3Geom	    l3Geom
                , out	sl3Buffer   sl3hit   
                , in    tcl_tphit   tpHit
                );
};
/* Last mod. for l3cl: 07/07/99 ppy */


