/*        thm.idl
 *
 *        description: Outputs a matching of monte carlo and reconstructed hits
 */

#include "PAM.idl"
#include "thm_ctrl.idl"
#include "g2t_tpc_hit.idl"
#include "tcl_tphit.idl"
#include "tcl_tpc_index.idl"
#include "thm_evaluation.idl"


interface thm: amiModule {
        STAFCV_T call
                ( inout thm_ctrl      ctrl    
		, in 	g2t_tpc_hit   mhit
                , in    tcl_tphit     thit
                , out   tcl_tpc_index match
                , out   thm_evaluation eval  
                );
};
/* Last mod. for thm.idl: $Date: 1998/11/23 20:39:02 $ */

