/*     
*
*       Module: tpcHit2L3Hit
*       description: Fills l3 hit buffer with offline tpc hits
*/

#include "PAM.idl"
#include "l3Geom.idl"
#include "sl3Buffer.idl"
#include "tcl_tphit.idl"

interface tpcHit2L3Hit: amiModule {
        STAFCV_T call
                ( in	l3Geom	  l3Geom
                , in    tcl_tphit tpHit
                , out	sl3Buffer sl3Hit
                );
};
/* Last mod. for l3cl: 09/17/98 cs */


