*
* $Id: debugvf2.inc,v 1.1.1.1 2009/02/18 20:32:35 fisyak Exp $
*
* $Log: debugvf2.inc,v $
* Revision 1.1.1.1  2009/02/18 20:32:35  fisyak
*
*
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:57  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_DEBUGVF2_INC
#define CERNLIB_ZEBRA_DEBUGVF2_INC
*
*      VFORT (Put as first executable statement)
*
* debugvf2.inc
*
#if defined(CERNLIB_QMIBM)
 1001 CONTINUE
#endif

#endif
