*
* $Id: fzcocc.inc,v 1.2 2018/06/28 16:02:49 fisyak Exp $
*
* $Log: fzcocc.inc,v $
* Revision 1.2  2018/06/28 16:02:49  fisyak
* Merge with geant3
*
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:54  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_FZCOCC_INC
#define CERNLIB_ZEBRA_FZCOCC_INC
*
*
* fzcocc.inc
*
      COMMON /FZCOCC/NQOCC,IQOCDV(20),IQOCSP(20)
*  -------------   for ZEBRA JZ91 ------------------------------

#endif
