*
* $Id: rzbuff.inc,v 1.1.1.1 2009/02/18 20:32:36 fisyak Exp $
*
* $Log: rzbuff.inc,v $
* Revision 1.1.1.1  2009/02/18 20:32:36  fisyak
*
*
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:54  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_RZBUFF_INC
#define CERNLIB_ZEBRA_RZBUFF_INC
*
*
* rzbuff.inc
*
      COMMON /RZBUFF/ ITEST(8704)
C

#endif
