*
* $Id: tzuc.inc,v 1.1.1.1 2009/02/18 20:32:35 fisyak Exp $
*
* $Log: tzuc.inc,v $
* Revision 1.1.1.1  2009/02/18 20:32:35  fisyak
*
*
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:28  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:56  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_TZUC_INC
#define CERNLIB_ZEBRA_TZUC_INC
*
*
* tzuc.inc
*
      COMMON /TZUC/  JSTOR,IXTITL, NPARA,LNEW,NWOCC,NAME(20)

#endif
