/*          tte_track.idl
*           Module: tte_track
*           Description: monte carlo tracking 
*/
#include "PAM.idl"
#include "tpt_track.idl"
#include "tcl_tphit.idl"
#include "g2t_tpc_hit.idl"
#include "g2t_track.idl"
#include "tcl_tpc_index.idl"
#include "tcl_tpc_index_type.idl"

interface tte_track : amiModule{
          STAFCV_T call
                   (      out    tpt_track track
			, inout  tcl_tphit hit 
			, in     g2t_tpc_hit g2t_hit 
			, in     g2t_track g2t_track 
			, inout  tcl_tpc_index tindex 
			, in     tcl_tpc_index_type tindex_type);
};
/* Last mod. for tte_track: $Date: 1998/01/27 02:18:53 $ */
