/*  tte_hit_match.idl
*
*   Module: tte_hit_match
*         description: Matches geant and reconstructed hits based on proximity.
*/

#include "PAM.idl"
#include "g2t_tpc_hit.idl"
#include "tcl_tpc_index.idl"
#include "tcl_tpc_index_type.idl"
#include "tcl_tphit.idl"

interface tte_hit_match : amiModule{
        STAFCV_T call
                ( in    g2t_tpc_hit        g2t_hit
                , out   tcl_tpc_index      tpc_index
                , in    tcl_tpc_index_type tpc_index_type
                , in    tcl_tphit          tphit
                );
};
/* Last mod. for tte_hit_match: $Date: 1998/07/07 16:27:02 $ */
