# Makefile.control
# Customize these variables to control SLM (STAR Library Make).
#
# MANDATORY PARAMETERS -------------------------------------------------
#
# OPTIONAL PARAMETERS --------------------------------------------------
#
