/* evr_am.idl
* Module: evr_am
* Description: Event vertex reconstruction
*/

#include "PAM.idl"
#include "evr_evrpar.idl"
#include "tpt_track.idl"
#include "stk_track.idl"
#include "egr_globtrk.idl"
#include "svm_evt_match.idl"
#include "evr_privert.idl"

interface evr_am : amiModule {
        STAFCV_T call
                ( in    evr_evrpar      evrpar
                , in    tpt_track       tptrack
                , in    stk_track   svt_track 
                , in    egr_globtrk     globtrk 
                , in    svm_evt_match   evt_match
                , out   evr_privert     privert
        );
};
/* Last mod. for evr_am: $Date: 1997/12/31 14:33:26 $  */
