#!/bin/csh 

set run=$1
set type=$2
set skip=$3

set anadir=/ldaphome/akio/fgt
set dir=$run
@ dir /= 1000

echo makeplot $run $type  anadir=$anadir yearday=$dir

stardev
cd $anadir

if ( "$type" == "pedestal" ) then
  set ped=1
  echo This is pedestal run
else
  set ped=0
  echo This is physics run
endif

if ( ! -e $dir ) then 
    mkdir $dir
endif
if ( ! -e www/$dir ) then 
    mkdir www/$dir
endif
if ( ! -e $dir/ped ) then 
    mkdir $dir/ped
endif
if ( ! -e $dir/status ) then 
    mkdir $dir/status
endif
if ( ! -e $dir/log ) then 
    mkdir $dir/log
endif
if ( ! -e $dir/condor ) then 
    mkdir $dir/condor
endif
if ( -e $dir/log/$run.log ) then 
    \rm $dir/log/$run.log
endif

if ( "$skip" == "skip" ) then
  echo skipping runqa.C
else
  echo root4star -b -q runqa.C"($run,$ped)"
  root4star -b -q runqa.C"($run,$ped)" > $dir/log/$run.log
endif

if ( "$type" == "pedestal" ) then
  if ( -e $dir/ped/ped.$run.txt ) then	
#    if (-e ped.txt) then
#      \rm ped.txt
#    endif
#    ln -s $dir/ped/ped.$run.txt ped.txt
    ln -s $dir/ped/ped.$run.txt ped/ped.$run.txt
  endif
  if ( -e $dir/status/status.$run.txt ) then	
#    if (-e status.txt) then
#      \rm status.txt	
#    endif
#    ln -s $dir/status/status.$run.txt status.txt
    ln -s $dir/status/status.$run.txt status/status.$run.txt
  endif
  echo root -b -q makepedplot.C"($run)"
  root -b -q makepedplot.C"($run)"
else
  echo root -b -q makeqaplot.C"($run,0,1)"
  root -b -q makeqaplot.C"($run,0,1)"
  \mv $dir/*${run}*.pdf www/$dir/	

  if ( -e $dir/status/status.$run.txt ) then
    ln -s $dir/status/status.$run.txt status/status.$run.txt
  endif
  echo root -b -q makepedplot.C"($run,1)"
  root -b -q makepedplot.C"($run,1)"
  \mv $dir/*${run}.evtdump.txt www/$dir/ 
  \mv $dir/*${run}*.png www/$dir/ 
  ./maketiny.pl www/$dir

  echo root -b -q resid.C"($run,0,-1,2)"
  root -b -q resid.C"($run,0,-1,2)"
  \mv $dir/*${run}*.pdf www/$dir/	
endif

\mv $dir/*${run}*.png www/$dir/	
./maketiny.pl www/$dir
#makepage.pl $dir
