/* @(#)StRoot/StBFChain:$Name:  $:$Id: Bfc.idl,v 1.1 2000/08/06 19:10:14 fisyak Exp $ */
struct Bfc {
  char       Key[16];      /* nick name */
  char       Name[20];     /* maker name */
  char       Chain[20];    /* its chain */
  char       Opts[120];    /* required options */
  char       Maker[40];    /* required Makers */
  char       Libs[120];    /* libraries to be loaded */
  char       Comment[199];  
  char       Flag;         /* F/T to use it in chain */
};
