/*   raw_sec_m
 * This table defines the interpretation of subsequent tables.
 * One row per sector
*/
   struct raw_sec_m{
       unsigned short  tfirst;        /* First time bin */
       unsigned short  tlast;         /* last time bin */
       char            TimeRef;      /* Time-bin referencing */
       char            RowRefIn;    /* Pad-row ref., inner subsector */
       char            RowRefOut;   /* Pad-row ref., outer subsector */
       octet           SectorId;        /* Sector ID */
   };
/*  Last mod. for raw_sec_m: $Date: 1998/04/08 17:03:59 $ */


