/*   raw_pad
 * pad description, representing mapped data from one pad 
 * 
*/
   struct raw_pad{
       unsigned short  PadOffset;   /* index offset, pixel-data tables */
       unsigned short  SeqOffset;   /* index offset, sequence-level tables */  
       octet           nseq;        /* # of sequences on Pad */
       octet           SeqModBreak; /* # of seq before adding 2**8 to time */  
       octet           unused1;      /* Unused variable */
       octet           PadId;         /* Pad ID */
   };
/*  Last mod. for raw_pad: $Date: 1998/04/08 17:03:02 $ */