/* readout_map.idl
 *    (onetasth.ace)
 */
/*****************************************************************************
*   Table: readout_map
*   map of sector row pad corresponding     
*   to channel read in system test          
*/
   /*******************  Row struct *******************/
  struct readout_map {
       long      channel;    /* channel number as it comes off RDO board */
       long      pad;        /* pad number of channel */
       long      row;        /* row number of channel */
       long      sector;     /* sector number of channel */
  };
/*  Last mod. for tfc_readout_map: $Date: 1998/05/08 15:18:32 $ */

