/*   rm_secvariation_z.idl
*   Table: rm_secvariation_z
*        description: Parameters for the tde dedx module      
*                   be  used to correct sector to sector variation and
*		   remove   de/dx z (drift distance) dependence                      
*/
    struct rm_secvariation_z {           
       float   ref;  /* the reference dE/dx. */
    
       float   const_inner[24]; /* first parameter from linear fit */
       float   slope_inner[24]; /* second parameter from linear fit */

       float   const_outter[24]; /* same as above but for outter sectors */
       float   slope_outter[24]; /* same as above but for outter sectors */

   } ;

/*  Last mod. for rm_secvariation_z:   778542153 May 20 1999 */

