/*   Table type: tcc_morphology.idl
**********************************************************
*   Description: information used after cluster finder but 
*   before hit finder to optimize hit finding algorithms
*   and perhaps eventually to help with tracking
**********************************************************
*   author: L. D. Carr -- lcarr@u.washington.edu   8/12/98
**********************************************************
*   history:
*
**********************************************************
*/

   /*******************  Row struct *******************/
   struct tcc_morphology{
	long	clusterId;
	long 	rowNumber;
	long	sectorNumber;
	long	numberOfSequences;
	long	numberOfPixels;
	long	numberOfPads;
	long	numberOfHits;
	long	totalCharge;
	long	maxCharge;
	float	averageCharge;
	float	meanPadPosition;
	float	meanTimePosition;
	float 	padSigma1;
	float	timeSigma1;
	float	padTimeSigma1Sq;
	/* 2 = orthogonal direction to pad-time for quadrupole */	
	float 	padSigma2;
	float	timeSigma2;
	float	padTimeSigma2Sq;
	float	ecc1;        /* eccentricity */
	float	ecc2;
	float	linEcc1;     /* linearizedEccentricity */
	float	linEcc2;
	float	meanX;
	float	meanY;
	float	meanZ;
	/* used to mark clusters according to various cuts */
	long    clusterFlag;
   };
/*  Last mod. for tcc_morphology.idl :  $DATE$ */
