/*   Table type: tcc_cluster_index.idl
**********************************************************
*   Description: An index which is used to differentiate
*		 between the clusters in different sectors,
*		 in order to loop over Sector[j] raw adc
*                directories in run_tcc.kumac
**********************************************************
*   author: L. D. Carr -- lcarr@u.washington.edu   11/19/98
**********************************************************
*   history:
*
**********************************************************
*/

   /*******************  Row struct *******************/
   struct tcc_cluster_index{
	long    cluster_index;
	long    current_sector;
   };
/*  Last mod. for tcc_cluster_index.idl :  $DATE$ */
