/*   Table type: tcc_params.idl
**********************************************************
*   Description: parameters for tpc cluster characterization module
**********************************************************
*   author: L. D. Carr -- lcarr@u.washington.edu   11/19/98
**********************************************************
*   history:
*
**********************************************************
*/

   /*******************  Row struct *******************/
   struct tcc_params{
	float	numTimeBins;
	float	tpcLength;
	float   linearizationFactor;
	long    numTpcSlices;
	float   tpcSlice[5];
   };
/*  Last mod. for tcc_params.idl :  $DATE$ */
