/*    tcl_calib_rdo.idl
 *
 *    Table: tcl_calib_rdo
 *
 *    Description:  TPC Read-out board calibration data to be used in
 *                  calculating and determining gain and position corrections
 *                  for offline event reconstruction.
 *
 *    Units:
 *            Unless stated otherwise, the following units are assumed.
 *
 *               Temperature          in     Celsius
 *               Time Offsets         in     micro-seconds
 * 
 *
 *    This table will be instantiated for each TPC sector, for both inner
 *    and outer subsectors, for a total of 48 tables.  For inner sectors
 *    each table contains 2 tablerows, corresponding to the 2 readout boards
 *    per inner sector.  For outer sectors, this table will have 4 tablerows.
 *    For example, the table names within each sector could be:
 *            tcl_calib_rdo_in
 *            tcl_calib_rdo_out
 */

   struct tcl_calib_rdo    {
     long    rdo_id;            /* Unique readout board ID #                 */
     long    FEE_row_ref_first; /* Explicit tablerow reference for first FEE */
                                /* card belonging to this readout board. This*/
                                /* refers to the tcl_calib_fee table for this*/
                                /* inner/outer sector.                       */
     long    FEE_row_ref_last;  /* Explicit tablerow reference for last FEE  */
                                /* card as above                             */
     float   t0_nom;            /* Nominal time offset for entire RDO board  */
     float   RDO_Temp[2];       /* Runtime RDO board operating Temperature   */
  }  ;
/*  Last mod. for tcl_calib_rdo:                                             */



