/*    tcl_calib_global.idl
 *
 *    Table: tcl_calib_global
 *
 *
 *    Description:  Nominal and Run-time parameter values for the
 *                  TPC to be used in calculating and determining
 *                  gain and position corrections for offline event
 *                  reconstruction.
 *
 *    Organization of data in this table:
 *               (1) Electric field cage and anode wire region
 *               (2) Gas properties
 *               (3) Online signal/data processing information
 *               (4) Alignment corrections
 *               (5) Drift velocity
 *               (6) Gain and attenuation 
 *               (7) Position and distortion corrections & monitoring
 *
 *    Units:
 *            Unless stated otherwise, the following units are assumed.
 *
 *               Electric field       in     Volts/cm
 *               Magnetic field       in     Tesla
 *               Electric potential   in     Volts
 *               Gas pressure         in     Pascal
 *               Temperature          in     Celsius
 *               Length               in     cm
 *               Frequency            in     MHz
 *               Angles               in     degrees
 *               Drift Speed          in     cm/micro-sec
 *               Luminosity           in     1.0/(cm*cm*sec)
 * 
 *    This table will only contain 1 row.
 */

   struct tcl_calib_global  {

 /*  Electric field cage and anode wire region  */
     float   dE_dV_central;  /* Change in electric field with central    */
                             /*    membrane voltage                      */
     float   V_central_nom;  /* Nominal central membrane voltage         */
     float   V_central_tol;  /* Tolerance (+/-) in cent. mem. voltage    */
     float   V_central_run;  /* Actual, run-time central mem. voltage    */
     float   V181_EIFC;      /* Voltage on stripe 181, East end, IFC     */
     float   V181_EOFC;      /* Voltage on stripe 181, East end, OFC     */
     float   V181_WIFC;      /* Voltage on stripe 181, West end, IFC     */
     float   V181_WOFC;      /* Voltage on stripe 181, West end, OFC     */
     float   V182_EIFC;      /* Voltage on stripe 182, East end, IFC     */
     float   V182_EOFC;      /* Voltage on stripe 182, East end, OFC     */
     float   V182_WIFC;      /* Voltage on stripe 182, West end, IFC     */
     float   V182_WOFC;      /* Voltage on stripe 182, West end, OFC     */
     float   EB_angleE;      /* Overall angle between E and B field,East */
     float   EB_angleW;      /* Overall angle between E and B field,West */

 /*  Gas properties   */
     char    gastype;      /* 'P' for P10; 'H' for He-Ethane               */
     float   P_rel_nom;    /* Nominal, TPC gas pressure to ambient ratio   */
     float   P_abs_nom;    /* Nominal, absolute TPC gas pressure (Pa)      */
     float   P_abs_tol;    /* Tolerance (+/-) in TPC gas pressure (Pa)     */  
     float   P_rel_run[4]; /* Run-time TPC gas pressure to ambient ratio   */
                           /* [1] -> East half, Upper gas manifold         */
                           /* [2] -> East half, Lower gas manifold         */
                           /* [3] -> West half, Upper gas manifold         */
                           /* [4] -> West half, Lower gas manifold         */
     float   P_abs_run[4]; /* Run-time absolute TPC gas pressure (Pa)      */
                           /* East/West; Upper/Lower as preceding          */
     float   Temp_nom;     /* Nominal TPC gas temperature (C)              */
     float   Temp_tol;     /* Tolerance (+/-) in TPC gas temperature (C)   */
     float   Temp_run[4];  /* Run-time TPC gas temperature (C)             */
                           /* East/West; Upper/Lower as preceding          */
     float   Comp_nom[10]; /* Nominal gas fractions for P10 or He-Ethane   */ 
                           /*    [1] - inert gas (e.g. Ar)                 */
                           /*    [2] - hydrocarbon (e.g. methane)          */
                           /*    [3] - Oxygen contaminant                  */
                           /*    [4] - Water contaminant                   */
                           /*    [5-10] - Other contaminants               */
     float   Comp_tol[10]; /* Gas fraction tolerances (+/-), as preceding. */
     float   Comp_run[10]; /* Run-time gas fractions, as preceding         */
     float   dP_dheight;   /* Nominal pressure change with height          */
     float   dT_dheight;   /* Nominal temp. change with height             */
     float   P_mon_rel;    /* Run-time gas pressure to ambient ratio       */
                           /*     in the Monitor chamber                   */
     float   P_mon_abs;    /* Run-time absolute gas pressure (Pa)          */
                           /*     in the Monitor chamber                   */
     float   Temp_mon;     /* Run-time Monitor chamber gas temperature     */
     float   Comp_mon[10]; /* Run-time Monitor chamber gas fractions       */

 /*  Online signal/data processing information  */
     char    FEE_shaper_type;    /* Nominal FEE Shaper function type         */
                                 /* 'D' is default as in Eq.(5), S.N. #197   */
     char    DAQ_translation;    /* DAQ 10->8 bit translation function type  */
     char    DAQ_gain_function;  /* DAQ gain function type                   */
     float   FEE_shaper_par[3];  /* Nominal FEE Shaper function parameters   */
                                 /*    e.g. `tau' in Eq.(5), S.N. #197       */
     float   FEE_SCA_freq_nom;   /* Nominal FEE SCA sampling freq (MHz)      */
     float   FEE_SCA_freq_run;   /* Runtime FEE SCA sampling freq (MHz)      */
     float   FEE_SCA_feedback;   /* Runtime FEE SCA feedback control value   */
     float   DAQ_trans_par[10];  /* Online 10->8 bit trans. func. params     */
     float   dNoise_dFEE_temp;   /* Change in FEE noise with FEE op. temp    */
     float   FEE_cross_talk[4];  /* Universal FEE chip cross talk parameters:*/
                                 /* [1]-adjacent channel, prop to I          */
                                 /* [2]-adjacent channel, prop to dI/dt      */
                                 /* [3]-non-adjacent channels, prop to I     */
                                 /* [4]-non-adjacent channels, prop to dI/dt */
 unsigned short t_noise_in[512]; /* Generic noise ADCs per time bucket-inner */
 unsigned short t_noise_out[512];/* Generic noise ADCs per time bucket-outer */

 /*  Alignment corrections  */
     float   x_wheel_shiftE; /* X coord. shift in STAR c.s. - East Wheel  */
     float   y_wheel_shiftE; /* Y coord. shift in STAR c.s. - East Wheel  */
     float   z_wheel_shiftE; /* Z coord. shift in STAR c.s. - East Wheel  */
     float   x_wheel_shiftW; /* X coord. shift in STAR c.s. - West Wheel  */
     float   y_wheel_shiftW; /* Y coord. shift in STAR c.s. - West Wheel  */
     float   z_wheel_shiftW; /* Z coord. shift in STAR c.s. - West Wheel  */
     float   wheel_pitchE;   /* Pitch angle w.r.t. X-axis;  - East Wheel  */
     float   wheel_yawE;     /* Yaw angle   w.r.t. Y-axis;  - East Wheel  */
     float   wheel_rollE;    /* Roll angle  w.r.t. Z-axis;  - East Wheel  */
     float   wheel_pitchW;   /* Pitch angle w.r.t. X-axis;  - West Wheel  */
     float   wheel_yawW;     /* Yaw angle   w.r.t. Y-axis;  - West Wheel  */
     float   wheel_rollW;    /* Roll angle  w.r.t. Z-axis;  - West Wheel  */
     float   covE[21];       /* Covariance matrix, East wheel alignment   */
     float   covW[21];       /* Covariance matrix, West wheel alignment   */

 /*  Drift velocity   */
     float   dVd_dPressure;  /* Change in drift speed with gas pressure     */
     float   dVd_dTemp;      /* Change in drift speed with gas temp.        */
     float   dVd_dComp[10];  /* Change in drift speed with gas composition  */
     float   dVd_dV_central; /* Change in drift speed with central mem.     */
                             /*   voltage, at nominal V_central             */
     float   V_drift_HiVE;   /* Runtime drift speed from HiV control-East   */
     float   V_drift_cathE;  /* Drift speed from cathode emission data-East */
     float   V_drift_laserE; /* Drift speed from laser data-East            */
     float   V_drift_HiVW;   /* Runtime drift speed from HiV control-West   */
     float   V_drift_cathW;  /* Drift speed from cathode emission data-West */
     float   V_drift_laserW; /* Drift speed from laser data-West            */
     float   V_drift_mon;    /* Monitor chamber drift speed                 */

 /*  Gain and Attenuation    */
     char    OFL_gain_function;   /* Nominal offline gain function type      */
     char    Puls_gain_function;  /* Pulser analy. offline gain function type*/
     char    Atten_function;      /* Nominal z-dep attenuation function type */
     float   dgasG_dLum_in;       /* Change in gas gain with luminosity,inner*/
     float   dgasG_dLum_out;      /* Change in gas gain with luminosity,outer*/
     float   dgasG_dV_anode_in;   /* Change in gas gain with anode volt-inner*/
     float   dgasG_dV_anode_out;  /* Change in gas gain with anode volt-outer*/
     float   dgasG_dPressure_in;  /* Change in gas gain with gas press-inner */
     float   dgasG_dPressure_out; /* Change in gas gain with gas press-outer */
     float   dgasG_dTemp_in;      /* Change in gas gain with gas temp-inner  */
     float   dgasG_dTemp_out;     /* Change in gas gain with gas temp-outer  */
     float   dgasG_dComp_in[10];  /* Change in gas gain with gas comp-inner  */
     float   dgasG_dComp_out[10]; /* Change in gas gain with gas comp-outer  */
     float   Atten_paramsE;       /* Nominal attenuation params - East end   */
     float   Atten_paramsW;       /* Nominal attenuation params - West end   */
     float   dAttPar_dPressureE;  /* Chng in atten param with gas press-East */
     float   dAttPar_dPressureW;  /* Chng in atten param with gas press-West */
     float   dAttPar_dTempE;      /* Chng in atten param with gas temp-East  */
     float   dAttPar_dTempW;      /* Chng in atten param with gas temp-West  */
     float   dAttPar_dCompE[10];  /* Chng in atten param with gas comp-East  */
     float   dAttPar_dCompW[10];  /* Chng in atten param with gas comp-West  */

 /*  Position and distortion corrections & monitoring  */
     float   zoffset_nom_in;     /* Nominal z-offset (cm) due to ground plane*/ 
                                 /* to anode wire drift speed - inner sector */
     float   zoffset_nom_out;    /* Nominal z-offset (cm) due to ground plane*/ 
                                 /* to anode wire drift speed - outer sector */
     float   dzoff_dV_anode_in;  /* Change in preceding z-offset due to      */
                                 /* change in V_anode - inner sector         */
     float   dzoff_dV_anode_out; /* Change in preceding z-offset due to      */
                                 /* change in V_anode - outer sector         */
     long    pos_dist_mon_cath;  /* Position/distortion monitor flag from    */
                                 /* analysis of cathode emission patterns    */
     long    pos_dist_mon_laser; /* Position/distortion monitor flag from    */
                                 /* analysis of laser tracks                 */

  }  ;
/*  Last mod. for tcl_calib_global:                                          */




