/*    tcl_calib_padrow.idl
 *
 *    Table: tcl_calib_padrow
 *
 *    Description:  TPC padrow information that is used in calibrations.
 * 
 *    This table will be instantiated for each TPC sector, for both inner
 *    and outer subsectors, for a total of 48 tables.  For inner sectors
 *    each table contains 13 tablerows, corresponding to the 13 padrows 
 *    per inner sector.  For outer sectors, this table will have 32 tablerows.
 *    For example, the table names within each sector could be:
 *            tcl_calib_padrow_in
 *            tcl_calib_padrow_out
 */

   struct tcl_calib_padrow    {
     long    padrow_id;      /* Pad row id #, from 1 - 45                    */
     long    firstpad;       /* Explicit tablerow reference to tcl_calib_pad */
                             /* for the first pad on this padrow             */
     long    lastpad;        /* Explicit tablerow reference to tcl_calib_pad */
                             /* for the last pad on this padrow              */
  }  ;
/*  Last mod. for tcl_calib_padrow:                                          */



