/*    tcl_calib_pad.idl
 *
 *    Table: tcl_calib_pad
 *
 *    Description:  TPC pad specific calibration data to be used in
 *                  calculating and determining gain and position corrections
 *                  for offline event reconstruction.
 *
 *    Units:
 *            Unless stated otherwise, the following units are assumed.
 *
 *               Length               in     cm
 *               Time                 in     micro-seconds
 *
 *    This table will be instantiated for each TPC sector, for both inner
 *    and outer subsectors, for a total of 48 tables.  For inner sectors
 *    each table contains 1750 tablerows, corresponding to the 1750 pads
 *    per inner sector.  For outer sectors, this table will have 3942 tablerows.
 *    For example, the table names within each sector could be:
 *            tcl_calib_pad_in
 *            tcl_calib_pad_out
 */

   struct tcl_calib_pad    {
 unsigned short   pad_id;      /* coded value = 1000*padrow# + pad#          */
    octet    FEE_row_ref;      /* Explicit row reference to tcl_calib_fee_*  */
                               /* which this channel inputs to; >0 for Chip1 */
                               /* and <0 for Chip2.                          */
    octet    noise;            /* Noise ADC value for this channel           */
    octet    status;           /* Channel status information including that  */
                               /* from offline pulser analysis (bits 1-3),   */
                               /* from online-DAQ (bits 4-5), and nominal    */
                               /* default status (bits 6-8).                 */ 
    long     gain_constant[2]; /* Gain factor - constant offset; data from   */
                               /* online-DAQ, offline pulser analysis and    */
                               /* nominal-default values are packed          */
    long     gain_linear[2];   /* Gain factor - linear term; DAQ-Plsr-Nom    */
    long     gain_nonlinear[2];/* Gain factor - nonlinear term; DAQ-Plsr-Nom */
    long     width;            /* Shaper width parameter; from pulser analy. */
                               /* and nominal value, packed                  */
    long     t0;               /* t0 offset from pulser analy. and nom,packed*/
    long     errors[2];        /* Packed errors for: overall gain, shaper    */
                               /* width parameter, and t0 offset             */
 } ;
/*  Last mod. for tcl_calib_pad:                                             */

