/*    tcl_calib_badpixels.idl
 *
 *    Table: tcl_calib_badpixels
 *
 *    Description:  List of bad time bins on otherwise good channels. 
 *
 *    This table will be instantiated for each TPC sector, for both inner
 *    and outer subsectors, for a total of 48 tables.  The length varies
 *    depending on the number of problematic time buckets.
 *    For example, the table names within each sector could be:
 *            tcl_calib_badpixels_in
 *            tcl_calib_badpixels_out
 */

   struct tcl_calib_badpixels    {
 unsigned short   pad_id;      /* coded value = 1000*padrow# + pad#   */
 unsigned short   timebin;     /* bad time bin number = 1-512         */
 } ;
/*  Last mod. for tcl_calib__badpixels:                               */


