/*   tcl_tclpar
 * Table of parameters controlling how tcl works...
*/
   struct tcl_tclpar {
       long      decon;      /* deconvolution method (0=no decon) */
       long      mc;         /* look at and fill (or not) MC data (1/0) */
       long      mf_cpad;    /* closest sep. in pad for Mountain Finder */
       long      mf_ctim;    /* closest sep. in tdc in Mountain Finder */
       long      mf_min;     /* minimum peak height in Mountain Finder */
       long      min_nseq;   /* min # sequences for a cluster to be hit */
       long      tfit;       /* method used to fit time (0=mean) */
       long      triage;     /* use cluster cuts to see if >1 peak poss. */
       float     dxy_fact;   /* fudge factor for uncertainty in x and y */
       float     dz_fact;    /* fudge factor for uncertainty in z */
       float     mf_pv;      /* peak:valley cut for Mountain Finder */
       float     triage_rmscut;/* cut on rms_pad + rms_tdc */
   };
/*  Last mod. for tclpar:  $Date: 1998/01/06 23:57:32 $ */


