/*    tcl_calib_fee.idl
 *
 *    Table: tcl_calib_fee
 *
 *    Description:  TPC FEE board calibration data to be used in
 *                  calculating and determining gain and position corrections
 *                  for offline event reconstruction.
 *
 *    Units:
 *            Unless stated otherwise, the following units are assumed.
 *
 *               Temperature          in     Celsius
 *               Time Offsets         in     micro-seconds
 * 
 *
 *    This table will be instantiated for each TPC sector, for both inner
 *    and outer subsectors, for a total of 48 tables.  For inner sectors
 *    each table contains 55 tablerows, corresponding to the 55 FEE boards
 *    per inner sector.  For outer sectors, this table will have 126 tablerows.
 *    For example, the table names within each sector could be:
 *            tcl_calib_fee_in
 *            tcl_calib_fee_out
 */

   struct tcl_calib_fee    {
     long    fee_id;            /* Unique FEE board ID #                     */
     long    RDO_row_ref;       /* Explicit tablerow reference to the RDO    */
                                /* board this FEE card inputs to, in table   */
                                /* tcl_calib_rdo for this inner/outer sector.*/
     long    Pad_row_ref_1[16]; /* Explicit tablerow refs. for 16 pads for   */
                                /* chip#1 that input to this FEE card. Refers*/
                                /* to table tcl_calib_pad for this in/out sec*/
     long    Pad_row_ref_2[16]; /* Explicit tablerow refs. for 16 pads for   */
                                /* chip#2 that input to this FEE card. Refers*/
                                /* to table tcl_calib_pad for this in/out sec*/
     long    Pedestal_mon[2];   /* Pedestal stability monitor flag, Chips 1,2*/
     long    Pulser_mon[2];     /* Pulser offline analy. gain and width      */
                                /* stability monitor flag for Chips 1,2      */
     float   t0_nom[2];         /* Nominal time offset for Chips 1,2         */
     float   t0_pulser[2];      /* Pulser offline analy. time offset,Chips1,2*/
     float   t0_pulser_err[2];  /* Pulser time offset error for Chips 1,2    */
     float   FEE_Temp_nom[2];   /* Nominal FEE operating temperature         */
     float   FEE_Temp_tol[2];   /* FEE op. temp. tolerance (+/-)             */
     float   FEE_Temp_run[2];   /* Runtime FEE operating temperature         */
     float   Shaper_resp[2];    /* Shaper response width parameter (e.g.`tau'*/
                                /* in Eq.(5), S.N. #197) from offline analys */
                                /* of pulser data, for Chips 1,2             */
     float   Shaper_resp_err[2];/* Shaper response width error, Chips 1,2    */
  }  ;
/*  Last mod. for tcl_calib_fee:                                             */

