/*   tcl_tphit_st.h
* Table of hits (space points) in tpc
*/
   struct tcl_tphit {
       long      cluster;    /* id of a cluster used to reconstruct pnt. */
       long      flag;       /* hit quality (see TFS documentation) */
       long      id;         /* a unique point id */
       long      id_globtrk; /* id of reconstructed/sim global track */
       long      track;      /* track_id*1000+position on on a track (starts from 1) */
       long      truncTag;   /* a tag for ensemble truncation */
       float     alpha;      /* reconstructed crossing angle in xy */
       float     dalpha;     /* error on the crossing angle */
       float     lambda;     /* dip angle (degree) */
       float     dlambda;    /* error on the dip angle (degree) */
       float     q;          /* total charge assigned to this point */
       float     dq;         /* error on the charge */
       float     x;          /* reconstructed x coordinate */
       float     dx;         /* error on the x coordinate */
       float     y;          /* reconstructed y coordinate */
       float     dy;         /* error on the y coordinate */
       float     z;          /* reconstructed z coordinate */
       float     dz;         /* error on the z coordinate */
       float     phi;        /* orientation of the hit w.r.t padplane */
       float     prf;        /* value of the pad response (cm) */
       float     zrf;        /* value of the drift response (cm) */
       float     dedx;       /* de/dx for this hit */
       float     cl_x;       /* local x (pads) */
       float     cl_t;       /* local z (time) */
       short     row;        /* 100*isector + TPC row number */
       short     nseq;       /* number of sequences contributing to hit */
       short     npads;      /* number of pad fired in this hit */
       short     minpad;     /* lowest pad id in this hit */
       short     maxpad;     /* highest pad id in this hit */
       short     ntmbk;      /* number of time bucket fired in this hit */
       short     mintmbk;    /* lowest time bucket in hit */
       short     maxtmbk;    /* highest time bucket in hit */
       short     id_simtrk;  /* id of simulated track */
       short     id_quality; /* percentage of charge associated with above id */
   };
/*  Last mod. for tphit: $Date: 2007/10/03 21:32:14 $ */


