/*   tcl_tpseq
* Table of sequences in time in tpc
*/
   struct tcl_tpseq {
       long      jpix;       /* offset into tppixel table */
       long      next;       /* self-link pointer to next sequence */
       long      secpad;     /* sector-wide pad number */
       long      tpc_row;    /* encoded sector-row = 100*sector + row */
   };
/*  Last mod. for tpseq: $Date: 1998/01/06 23:57:35 $ */


