/*  
*  Auxiliary table of hits (space points) in tpc
*/
   struct tcl_tphit_aux {
       long      id;         /* a unique point id */
       long      flag;       /* evaluation of the hit quality */
       long      cluster;    /* id of a cluster used to reconstruct pnt. */
       long      nseq;       /* number of sequences contributing to hit */
       long      row;        /* TPC row number */
       long      npads;      /* no. of pads in this clutser */
       float     x;          /* reconstructed x coordinate */
       float     y;          /* reconstructed y coordinate */
       float     z;          /* reconstructed z coordinate */
       float     dx;         /* error on the x coordinate */
       float     dy;         /* error on the y coordinate */
       float     dz;         /* error on the z coordinate */
       float     prf;        /* value of the pad response (cm) */
       float     zrf;        /* value of the drift response (cm) */
       float     q;          /* total charge assigned to this point */
       float     xave;       /* centroid  in pads      */
       float     sigma;      /* sigma     in pads      */
       float     skew;       /* skewness               */ 
       float     kurto;      /* kurtosis               */
   };
/*  Last mod. for tphit: $Date: 1998/01/06 23:57:35 $ */


