/*   tcl_tphit_st.h
* Table of hits (space points) in tpc
*/
   struct tcl_tphit {
       long      cluster;    /* id of a cluster used to reconstruct pnt. */
       long      flag;       /* evaluation of the hit quality */
       long      id;         /* a unique point id */
       long      id_globtrk; /* id of reconstructed/sim global track */
       long      nseq;       /* number of sequences contributing to hit */
       long      row;        /* TPC row number */
       long      track;      /* track_id*1000+position on on a track (starts from 1) */
       float     alpha;      /* reconstructed crossing angle in xy */
       float     dalpha;     /* error on the crossing angle */
       float     dlambda;    /* error on the dip angle (degree) */
       float     dq;         /* error on the charge */
       float     dx;         /* error on the x coordinate */
       float     dy;         /* error on the y coordinate */
       float     dz;         /* error on the z coordinate */
       float     lambda;     /* dip angle (degree) */
       float     phi;        /* orientation of the hit w.r.t padplane */
       float     prf;        /* value of the pad response (cm) */
       float     q;          /* total charge assigned to this point */
       float     x;          /* reconstructed x coordinate */
       float     y;          /* reconstructed y coordinate */
       float     z;          /* reconstructed z coordinate */
       float     zrf;        /* value of the drift response (cm) */
   };
/*  Last mod. for tphit: $Date: 1999/11/07 02:57:16 $ */


