/*    tcl_calib_general.idl
 *
 *    Table: tcl_calib_general
 *
 *
 *    Description:  General, non-TPC specific data that are needed for
 *                  calculating and determining gain and position corrections
 *                  for offline event reconstruction.  These data are
 *                  collected here for the convenience of the TPC user.
 *
 *    Units:
 *            Unless stated otherwise, the following units are assumed.
 *
 *               Electric field       in     Volts/cm
 *               Magnetic field       in     Tesla
 *               Electric potential   in     Volts
 *               Gas pressure         in     Pascal
 *               Temperature          in     Celsius
 *               Length               in     cm
 *               Frequency            in     MHz
 *               Angles               in     degrees
 *               Drift Speed          in     cm/micro-sec
 *               Luminosity           in     1.0/(cm*cm*sec)
 *               Electric current     in     Amperes
 * 
 *    This table will only contain 1 row.
 */

   struct tcl_calib_general  {
     float   Luminosity;       /* Bunch crossing averaged, but overall time */
                               /* dependent luminosity for estimating space */
                               /* charge accumulation effects               */
     float   NMR_nom[10];      /* Nominal NMR probe values for Mag. field   */
     float   NMR_tol[10];      /* NMR probe tolerances (+/-)                */
     float   NMR_run[10];      /* Runtime NMR probe values for Mag. field   */
     float   Hall_nom[10];     /* Nominal Hall probe values for Mag. field  */
     float   Hall_tol[10];     /* Hall probe tolerances (+/-)               */
     float   Hall_run[10];     /* Runtime Hall probe values for Mag. field  */
     float   Mag_curr_nom[5];  /* Nominal magnet currents:                  */
                               /*      [1] - Main Coils                     */
                               /*      [2] - East Trim coil                 */
                               /*      [3] - West Trim coil                 */
                               /*      [4] - East Pole tip coil             */
                               /*      [5] - West Pole tip coil             */
     float   Mag_curr_tol[5];  /* Magnet current tolerances (+/-)           */
     float   Mag_curr_run[5];  /* Runtime magnet currents                   */
     float   Pressure_amb[10]; /* Ambient air pressure in WAH               */
     float   Temp_amb[10];     /* Ambient air temperature in WAH            */
     float   RHIC_clock_offset;/* RHIC bunch crossing-STAR trigger absolute */
                               /* time offset correction                    */  
  }  ;
/*  Last mod. for tcl_calib_general:                                        */

