/*    tcl_calib_sec.idl
 *
 *    Table: tcl_calib_sec
 *
 *    Description:  TPC sector specific calibration data to be used in
 *                  calculating and determining gain and position corrections
 *                  for offline event reconstruction.
 *
 *    Units:
 *            Unless stated otherwise, the following units are assumed.
 *
 *               Electric potential   in     Volts
 *               Length               in     cm
 *               Angles               in     degrees
 *               Drift Speed          in     cm/micro-sec
 * 
 *    This table will contain 24 table-rows, each tablerow contains data
 *    for one TPC sector.  This table may be instantiated twice, one
 *    for the inner subsectors and the other for the outer subsectors, e.g.:
 *            tcl_calib_sec_in
 *            tcl_calib_sec_out
 */

   struct tcl_calib_sec   {
     long    sector_id;         /* Sector ID number as in STAR Note #229     */
     long    pos_dist_mon_laser;/* Position/distortion monitor flag from     */
                                /* analysis of laser tracks                  */
     float   V_anode_nom[4];    /* Nominal anode wire voltages               */
     float   V_anode_tol[4];    /* Anode wire volt tolerances (+/-)          */
     float   V_anode_run[4];    /* Runtime anode wire voltages               */
     float   x_shift;           /* Sector alignment shift w.r.t. wheel along */
                                /* padrow direction; positive is with        */
                                /* increasing pad number as in STAR Note #229*/
     float   y_shift;           /* Sector alignment shift w.r.t. wheel       */
                                /* perpendicular to padrows; positive is     */
                                /* towards the outer field cage              */
     float   angle_shift;       /* Sector alignment rotation w.r.t. wheel;   */
                                /* positive angles are ccw as viewed from    */
                                /* inside the TPC, looking at the pad plane. */
     float   cov_sector[6];     /* Sector alignment covariance matrix        */
     float   V_drift_laser;     /* Drift speed from laser track analysis     */
     float   V_drift_cath;      /* Drift speed from cathode emission analy.  */
     float   Vgg_nom;           /* Nominal gated grid voltage when open      */
     float   Vgh_nom;           /* Nominal voltage added to alt.wires-closed */
     float   Vgl_nom;           /* Nominal voltage subtr from alt.wires-clos */
     float   Vgg_run;           /* Runtime gated grid voltage when open      */
     float   Vgh_run;           /* Runtime voltage added to alt.wires-closed */
     float   Vgl_run;           /* Runtime voltage subtr from alt.wires-clos */
  }  ;
/*  Last mod. for tcl_calib_sec:                                             */

     
