/*   tcl_hitclus_st.h
* Table of hits (space) in pad-row and timebuck-pad plane
*/
   struct tcl_hitclus {
    long               id;            /* hit id */
    short     sector;           /* TPC sector number */    
    short     row;           /* TPC row number from 1 to 45 in each sector*/
    short     cluster;       /* id of a cluster used to reconstruct pnt. */
    short     nhits;         /* total number of hits in this cluster*/
    short     nth_hit;       /* this is the nth hit among them  */  
    short     npads_clus;     /* number of pad fired in this cluster*/
    short     minpad_clus;     /* lowest pad id in this cluster */
    short     maxpad_clus;     /* highest pad id in this cluster */
    short     ntmbk_clus;     /* number of time bucket fired in this cluster */
    short     mintmbk_clus;   /* lowest time bucket in hitclus */
    short     maxtmbk_clus;   /* highest time bucket in hitclus */
    short     npads_hit;     /* number of pad fired in this hit */
    short     minpad_hit;     /* lowest pad id in this hit */
    short     maxpad_hit;     /* highest pad id in this hit */
    short     ntmbk_hit;     /* number of time bucket fired in this hit */
    short     mintmbk_hit;   /* lowest time bucket in hit */
    short     maxtmbk_hit;   /* highest time bucket in hit */
   };
/*  Last mod. for tphit: $Date: 1999/08/25 21:30:12 $ */


