/*   tdeparm.idl
*   Table: tdeparm
*        description: Parameters for the tde dedx module      
*                     latest version from Jeff Mitchell
*		      supercedes tdepar.idl                     
*/
    struct tdeparm {           
       long       debug[10];  /* tde debugging parameters */
       long       minrow;     /* Minimum row to include in dE/dx calc. */
       long      truncopt;   /* Select dedx calc option */
       long       use_glob;   /* use global tracks parameter */
       long      usemerge;   /* if =1, then use merged hits in the calc. */
       float     truncfact;  /* fraction of dedx values to truncate */
   } ;

/*  Last mod. for tdeparm:   778542153 Fri Nov 29 1996 */

