/* tdi_rdi_pars.idl
 *
 * Table: tdi_rdi_pars
 * 
 * Description: Radial Distortion Integral parameters
 */

struct tdi_rdi_pars {
  long   mode;        /* 0=none, 1=uniform, 2=short, 3/4=piston pad/HV */
  long   sector;      /* Armed sector number */
  float  rdi_max;     /* (1) (sign and) amplitude of distortion at OFC */
  float  rho_min;     /* (1) minimum radius of distortion */
  float  z_short;     /* (2) z-position of shorted field-cage stripe */
  float  dV;          /* (3,4) voltage mismatch */
};
