/* tdi_fit_pars.idl
 *
 * Table: tdi_fit_pars
 * 
 * Description: Straight line FIT selection parameters
 */

struct tdi_fit_pars {
  long sector;         /* sector of choice */
  long first_row;      /* first row to use in fit */
  long last_row;       /* last row to use in fit */
  long min_fit;        /* minimum number of hits for fit */
  long ntuple;         /* ntuple flag 1=open, 0=close */
};
