/* tdi_strack.idl
 *
 * Table: tdi_strack
 * 
 * Description: straight strack table
 */

struct tdi_strack {
  long id;         /* primary key */
  long nhit;       /* number of hits */
  long nfit;       /* number of hits used in fit */
  long hitid;      /* id of first hit */
  float slope_xy;  /* gradient in xy plane */
  float x0;        /* x intercept */
  float chisq_xy;  /* chisquare of xy fit */
  float slope_yz;  /* gradient in yz plane */
  float z0;        /* r intercept */
  float chisq_yz;  /* chisquare of yz fit */
  long last_row;   /* row of outer hit */
  float z_last;    /* z coordinate of outer hit */
  float res_xy;    /* xy residual of outer hit */
  float res_yz;    /* yz residual of outer hit */
  float alpha;     /* pad crossing angle */
  float lambda;    /* track dip angle */
  float sres_xy;   /* sum of xy residuals (unfitted points) */
  float sres_yz;   /* sum of yz residuals (unfitted points) */
};
