/**********************************************************************/
/*   Table: tfc_native_pedestal					      */
/*   native-mapped pedestals for system test			      */
/**********************************************************************/
  struct tfc_native_pedestal {
	long	sector;		/* sector number (1-24) */
	long	RDO;		/* RDO board number (1-6) */
	long	row;		/* row number (1-45) */
	long	pad;		/* pad number in this row (1-181) */
	long	bucket;		/* time bucket number (1-512) */
	float	ave;		/* average (over events) pedestal */
	float	rms;		/* rms (over events) of pedestal */
  };
