/**********************************************************************/
/*	Native data mapping table				      */
/**********************************************************************/
   struct tfc_native_map {
	long group;	/* group number (1-72) */
	long channel;	/* channel number (1-16) */
	long row;	/* row number (1-45) */
	long pad;	/* pad number (1-184) */
	long RDO;	/* Read-Out Board location (1-6) */
	long sector;	/* sector number (1-24) */
   };
/* last modified: $Date: 1997/12/31 14:34:12 $ */
