/***********************************************************************
*	Reformat switch settings
***********************************************************************/
  struct tfc_fmtpar {
	long	nped_samples[6];  /* # pedestal events in mean ped */
	long	npuls_samples[6]; /* # pulser events in mean pulser */
	long	event_type;	/* event type flag: 
				   0=data, 1=ped, 2=puls, 3=gain */
	long	ped_subtract;	/* 1 if ped should be subtracted from data */
	long	thresh;		/* pedestal-subtracted adc threshold */
	float	times_rms;	/* quant subtracted=ave+(times_rms)*rms */
	float	ave_gain;	/* gives absolute scale for gain */
	long	first_bucket;	/* first bucket used in gain calculation */
	long	last_bucket;	/* last bucket used  "   "     "         */
	long	only_type;	/* only index type to be processed (-1=all) */
	long	data_size;	/* size of data tables to be used (bytes) */
	long	printf;		/* output flag */
  };
