/*****************************************************************************
*   Table: tfc_pedstab
*   average pedestals from stability run
*/
   /*******************  Row struct *******************/
  struct tfc_pedstab {
	long	shift;		/* shift number */
	long	chip[30];	/* chip number */
	float	ped[30];	/* average pedestal value */
	float	ped_drift[30];	/* drift in pedestal over shifts */
	float	ped_dev[30];	/* deviation in pedestal over shifts */
	float	rms[30];	/* rms for average ped value */
	float	rms_drift[30];	/* drift in rms over shifts */
	float	rms_dev[30];	/* deviation in rms over shifts */
	float	gain[30];	/* average gain for each chip */
	float	gain_drift[30];	/* drift in gain over shifts */
	float	gain_dev[30];	/* deviation in gain over shifts */
	float	gain_rms[30];	/* rms in average gain */
  };
/*  Last mod. for tfc_pedstab: $Date: 1997/12/31 14:34:12 $*/
