/* bad_channels.idl
 *    (onetasth.ace)
 */
/*****************************************************************************
*   Table: bad_channels
*   for system test - which of the          
*   1152 channels should be ignored         
*/
   /*******************  Row struct *******************/
  struct bad_channels {
       long      channel;    /* channel number of bad channel */
  };
/*  Last mod. for tfc_bad_channels: $Date: 1997/12/31 14:34:11 $ */

