/*   tfs_fsctrl.idl
*
*   Table: tfs_fsctrl
*   
*        description: TFS control switches                    
*/

     struct tfs_fsctrl { 
       long       bipass;     /* bipasses event processing (0 = off ) */
       long       evmerg;     /* number of events to merge */
       long       fold;       /* event folding factor (2, 4, or 8) */
       long       init;       /* flag to initialize TFS (0 = initialize) */
       long       nevent;     /* number of output events required */
       long       ppflag;     /* pp event merging mode */
       long       print;      /* controls diagnostic prints (0 = off) */
       long       rndm;       /* Seed initialisatio( 1=on, 0=off) */
   };
/*  Last mod. for fsctrl:   $Date: 1997/12/31 14:34:12 $ */

