/*   tfs_fspar.idl
*
*   Table: tfs_fspar
*   
*        description: TFS parameter table                     
*/

   struct tfs_fspar {
       long      irmax;        /* number of inner sector rows */
       long      nrow;         /* total number of TPC rows */
       long      nsect;        /* total number of TPC sectors */
       float     padlen[2];    /* pad length (cm) */
       float     padsep[2];    /* pad pitch (cm) */
       float     padwid[2];    /* pad width (cm) */
       float     sldiff;       /* longitudinal diffusion */
       float     tshape;       /* shaping time (ns) */
       float     zbmax;        /* total time bins */
   };
/*  Last mod. for fspar:  $Date: 1999/10/11 16:47:52 $ */

