/*   tfs_fsctrl.idl
*
*   Table: tfs_fsctrl
*   
*        description: TFS control switches                    
*/

     struct tfs_fsctrl { 
       long       init;       /* flag to initialize TFS (0 = initialize) */
       long       print;      /* controls diagnostic prints (0 = off) */
       long       rndm;       /* Seed initialisatio( 1=on, 0=off) */
       long      sys_test;     /* sys_test=1 for system tests o/w = 0 */
       float     alpha_hi;     /* max angle for scaling (deg) */
       float     alpha_lo;     /* min angle for scaling (deg) */
       float     drmin;        /* merging criterion radial (pads) */
       float     dzmin;        /* merging criterion drift (time bins) */
       float     merge_r;      /* max merged size radial (pads) */
       float     merge_z;      /* max merged size drift (bins) */
       float     reslim;       /* maximum cluster size (cm) */
       float     sigma0[4];    /* resolution intrinsic term */
       float     ang_wireF[4]; /* resolution angular wire term */
       float     ang_padF[4];  /* resolution angular pad term */
       float     sprf_0[2];    /* prf intrinsic term */
       float     sprf_dr0[4];  /* zero B-field prf drift term */
       float     sprf_ta[2];   /* prf tan-alpha term */
   };
/*  Last mod. for fsctrl:   $Date: 1999/10/11 16:47:48 $ */

