/* tpc_pedestal.idl
 *    (onetasth.ace)
 */
/*****************************************************************************
*   Table: tpc_pedestal
*   pedestals for system test               
*                                           
*/
   /*******************  Row struct *******************/
  struct tpc_pedestal {
       long      bucket;     /* time bucket number */
       long      channel;    /* channel number from RDO board */
       float     ave;        /* average pedestal over sample events */
       float     rms;        /* rms (over samples) of pedestals */
  };
/*  Last mod. for tfc_tpc_pedestal: $Date: 1998/05/08 15:18:34 $ */

