/*   tpg_cathode.idl
*
*   Table: tpg_cathode
*          
*        description: Geometry for the cathode plane          
*/

   struct tpg_cathode { 
       long      cath_mat;   /* cathode material */
       float     cath_in_rad;/* inner radius of cathode plane */
       float     cath_out_rad;/* outer radius of cathode plane */
       float     cath_thick; /* thickness of cathode plane */
   };
/*  Last mod. for tpg_cathode:   $Date: 1998/01/06 23:57:36 $  */

