/*   tpg_transform.idl
*
*   Table: tpg_transform
*       
*        description: Local to and from global coordinates    
*             more..: transformation data.                    
*/

   /*******************  Row struct *******************/
   struct tpg_transform {  
       float     global_origin[3];/* Sector's origin, in global coordinates */
       float     local_origin[3];/* Translation to local, after rotation. */
       float     phi_limhi;  /* Phi coord, sector high limit, radians. */
       float     phi_limlo;  /* Phi coord, sector low limit, radians */
       float     sector_angle;/* Sector angle, in radians. */
       float     sector_cos; /* Sector angle cosine */
       float     sector_sin; /* Sector angle sine. */
       float     y_local_limhi;/* Y local coord, sector high limit */
       float     y_local_limlo;/* Y local coord, sector low limit. */
       float     z_global_limhi;/* Z-limit-high of sector, global coords. */
       float     z_global_limlo;/* Z-limit-low of sector, global coords. */
       float     z_local_limhi;/* Z-limit-high, local coords. (ie, drift). */
   };
/*  Last mod. for tpg_transform:   $Date: 1998/01/06 23:57:38 $  */

