/*   tpg_detector.idl
*
*   Table: tpg_detector
*         
*        description: TPC detector-wide geometry parameters   
*             more..: (valid for all TPC sectors)             
*	Additions by Mlisa - It is not really the best place
* 	  for it perhaps, but here we add VDRIFT = drift velocity
*	 	      and BUCKET_LENGTH = time duration of a time bucket
*/

   /*******************  Row struct *******************/
   struct tpg_detector {  
       long       nsectors;   /* Number of sectors;  inner/outer separate */
       float     drift_length;/* Drift length, along the beam */
       float     radius_in;  /* Inner radius, to center of row. */
       float     radius_out; /* Outer radius, to outside of last-row end */
       float     sector_angle;/* Angle between sectors, radians */
       float	 vdrift;	/* drift velocity (cm/us) */
       float	 bucket_length;	/* time duration of time bucket (us) */
   } ;
/*  Last mod. for tpg_detector:   $Date: 1997/10/27 22:07:13 $ */

