/*   tpg_pad.idl
*
*   Table: tpg_pad
*          
*        description: Describes characteristics unique to a given
*		      pad (electronics channel) of the TPC
*		      One entry per pad.
*	 Mike Lisa 4feb97
*
*	Note: We may also want to add to this table a field telling whether
*		this is a "bad" pad or not.
*/

   struct tpg_pad {
	float	t0;		/* t0 offset for electronics channel (us) */
	float	gain;		/* RELATIVE gain for channel (i.e. average is 1) */
	float	tau;		/* shaping time for electronics channel (us) */
	float	pedestal[512];	/* pedestal value for each time bucket (units=ADC counts) */
	short	sector;		/* sector number 1-24 */
	short	padrow;		/* padrow number 1-45 */
	short	pad;		/* pad number within padrow 1-184 (for row 13) */
   };
/*  Created 4feb97	*/


