/*   tpg_sector.idl
*
*   Table: tpg_sector
*        description: individual sector geometry parameters.  
*             more..: Inner and outer sectors are separate.   
*/

   /*******************  Row struct *******************/
   struct tpg_sector {  
       long       nrowpads[45];/* Number of pads in each row. */
       long       nrows;      /* Number of rows in each sector */
       float     pad_x_size; /* Pad size along the row -- uniform in sec */
       float     pad_x_space;/* Spacing between pads in a row -- uniform */
       float     row_y_size; /* active width of the rows in this sector */
       float     xrow[45];   /* Local X-coordinate of Pad 1, each row. */
       float     yrow[45];   /* Local Y coord. of each row. */
   };
/*  Last mod. for tpg_sector:   $Date: 1998/01/06 23:57:37 $ */

