/*   tpg_wire_plane.idl
*
*   Table: tpg_wire_plane
*       
*        description: TPC wire planes (gate,ground,field,anode
*/

   /*******************  Row struct *******************/
   struct tpg_wire_plane {
       char      dnum[80];   /* ID of drawings used to extract info */
       long       mat_aw;     /* Material for the anode wires */
       long       mat_fw;     /* Material for the field wires */
       long       mat_gaw;    /* Material for the gating grid */
       long       mat_grw;    /* Material for the ground wires */
       float     dim_aw;     /* Radius for the anode wire */
       float     dim_aw_s;   /* Dimension for the special anode wire */
       float     dim_fw;     /* Radius for the field wire */
       float     dim_gaw;    /* Radius for the gating grid wire */
       float     dim_grw;    /* Radius for the ground plane wire */
       float     dz_aw_in;   /* Dist to the pad plane for aw, inner sect */
       float     dz_aw_out;  /* Dist to the pad plane for aw, outer sect */
       float     dz_fw_in;   /* Dist to the pad plane for fw, inner sect */
       float     dz_fw_out;  /* Dist to the pad plane for fw, outer sect */
       float     dz_gaw_in;  /* Dist to the pad plane for gaw, inner sec */
       float     dz_gaw_out; /* Dist to the pad plane for gaw, outer sec */
       float     dz_grw_in;  /* Dist to the pad plane for grw, inner sec */
       float     dz_grw_out; /* Dist to the pad plane for grw, outer sec */
       float     num_aw_in;  /* Number of the anode wires, inner sector */
       float     num_aw_out; /* Number of the aw in the outer sector */
       float     num_fw_in;  /* Number of the field wires, inner sector */
       float     num_fw_out; /* Number of the fw in the outer sector */
       float     num_gaw_in; /* Number of the gating grid, inner sector */
       float     num_gaw_out;/* Number of the gaw in the outer sector */
       float     num_grw_in; /* Number of the ground wires, inner sector */
       float     num_grw_out;/* Number of the grw in the outer sector */
       float     rad_aw_in;  /* Rad dist to the first aw, inner sector */
       float     rad_aw_out; /* Rad dist to the first aw, outer sector */
       float     rad_fw_in;  /* Rad dist to the first fw in the inn. sec */
       float     rad_fw_out; /* Rad dist to the first fw, outer sector */
       float     rad_gaw_in; /* Rad dist to the first gaw, inner sector */
       float     rad_gaw_out;/* Rad dist to the first gaw, outer sector */
       float     rad_grw_in; /* Rad dist to the first grw, inner sector */
       float     rad_grw_out;/* Rad dist to the first grw, outer sector */
       float     sep_aw;     /* Wire pitch for the anode wires */
       float     sep_fw;     /* Wire pitch for the field wires */
       float     sep_gaw;    /* Wire pitch for the gate plane */
       float     sep_grw;    /* Wire pitch for the ground plane */
   };
/*  Last mod. for tpg_wire_plane:   $Date: 1998/01/06 23:57:38 $  */

