/*   tpt_track_pointers.idl
*
*   Table: tpt_track_pointers
*   
*        description: Temperory Reconstructed TPC tracks                
*
*/

   /*******************  Row struct *******************/
   struct tpt_track_pointers {
	  long    nhit;               /* number of his per track */
	  long    ipnt[100];          /* pointers to hits belonging to trk */
          long    pos[100];           /* position on a track */
	  float   p[9];               /* track parameters */
          float   dpar[9];            /* errors on track parameters */
          long    nfit;               /* # of points used in fit */
          long    flag;               /* flags from the fitting  */     
};
