/*   tpt_pars.idl
*
*   Table: tpt_pars
*   
*        description: Parameters for the track finding        
*/

   /*******************  Row struct *******************/
   struct tpt_pars {          /* Tptpar_row_st */ 
       long       debug[10];  /* Flags for debug prlong */
       long       display;    /* Enables longeractive tracking display */
       long       extend;     /* Switch for extending segments. */
       long       form_uv;    /* Switch for segment formation & mapping. */
       long       form_xy;    /* Switch for xy segment formation */
       long       g1;         /* allowed gap between 1 and 2 point */
       long       g2;         /* allowable gap between 2 and 3 point */
       long       irow_root_beg;/* row to start root formation */
       long       irow_root_end;/* row to end root formation */
       long       irow_seg_end;/* row to end segment formation (no begin) */
       long       mctest;     /* switch for the MC testing */
       long       merge;      /* Switch for segment merging */
       long       minfit;     /* minimum number of polongs on a track */
       long       mxtry;      /* max # of attempts to fit */
       long       nhol;       /* allowed gap size */
       long       nzslic;     /* # of slices( even) along the z axis. */
       long       pass_on;    /* Pass on or off */
       float     delrlm;     /* limit on the extrapolation in bend plane */
       float     delzlm;     /* limit on the extrapolation */
       float     drlm1;      /* tolerance on the 1 step in the bend plan */
       float     drmax;      /* max road width in x,y */
       float     drplim;     /* Limit on the linear extrap. in bend plan */
       float     drstr;      /* road width in st dev  in the bend plane */
       float     dzlm1;      /* tolerance on the first step */
       float     dzmax;      /* maximum road width in z */
       float     dzplim;     /* Limit for linear extrapolation in z */
       float     dzstr;      /* road width in st dev in z */
       float     mxweig;     /* max # of hits/channel for the starter */
       float     prob[2];    /* probability cut */
       float     zslim;      /* limit on the msc */
   };

/*  Last mod. for tpt_pars:   793401970 Tue Feb 21 16:26:10 1995 */

