/* tpt_strack.idl
*
*	Table: tpt_strack
*
*	description: Straight track parametrization - (B = 0)
*/

	struct tpt_strack    /*straight track parametrisation*/
  {
		long	trk;     /* track number */
		long	npnt;    /* number of points */
		float	ax;      /* track parametrised as ax*x+ay*y=1 */
                float   dax;     /* error on ax */
		float   ay;
                float   day;     /* error on ay */
                float   az;      /* tangent of the track dip angle */
                float   daz;     /* error on az */   
		float	azx;     /* z=azx*x+bzx */
		float   bzx;
		float	azy;     /* z=azy*y+bzy */
		float   bzy;  
                float   dazx;    /* error on azx */
                float   dazy;    /* error on azy */
                float   dbzx;    /* error on bzx */
                float   dbzy;    /* error on bzy */
                float   chisqxy; /* chisq for the fit in the x-y plane */
                float   chisqz;  /* chisq in the drift direction */
  };

/* Last mod. for tpt_strack: $Date: 1997/12/31 14:34:12 $ */