/* tpt_res.idl
*
*	Table: tpt_res
*
*	description: Track residua
*/

	struct tpt_res{
		long	trk;	/* track id */
		long	hit;    /* hit id*/
		float	resy;   /* residuum along the padrow */
		float	resz;   /* residuum in the drift direction */
};

/* Last mod. for tpt_res: $Date: 1998/12/11 19:19:56 $ */
