/* tstpar.idl
 *    (onetasth.ace)
 */
/*****************************************************************************
*   Table: tstpar
*   switch table for tst module             
*   which reads files from system test      
*/
   /*******************  Row struct *******************/
  struct tstpar {
	char	filin[160];	/* file containing pixel adc values */
	long	format;		/* what format is the data */
	long	nped_samples;	/* # pedestal events contributing to peds */
	long	ngain_samples;	/* # pulser events contributing to gains */
	long	ped_event;	/* 1 if this event is ped 0 otherwise */
	long	ped_subtract;	/* 1 if ped should be subtracted from data */
	long	thresh;		/* pedestal-subtracted adc threshold */
	float	times_rms;	/* quant subtracted=ave+(times_rms)*rms */
	float	ave_gain;	/* gives absolute scale for gain */
	long	first_bucket;	/* first bucket used in gain calculation */
	long	last_bucket;	/* last bucket used  "   "     "         */
  };
/*  Last mod. for tfc_tstpar: $Date: 1998/05/08 15:18:35 $ */

