/*   tte_mctrk.idl
*
*   Table: tte_mctrk
*   description: Table for the MC tracks that entered TPC
*/

   /*******************  Row struct *******************/
   struct tte_mctrk {          /* Tp_mctrk_row_st */ 
       long       mcid;       /* MC track id */
       long       nfst;       /* # of hits left after response simulation */
       long       nfstm;      /* Number of merged points on track. */
       long       ngnt;       /* # of Geant hits generated on this track */
       long       nrec1;      /* # of points on the longest segment. */
       long       nrec2;      /* # of points on the second longest segmen */
       long       nseg;       /* # of segments rec from this track */
       long       pid;        /* Particle ID */
       long       recid;      /* ID of the reconstructed track. */
       long       vid;        /* vertex id */
       long       evnum;      /* event number */
       float     ptg;        /* Generated pt */
       float     ptr;        /* Reconstructed pt */
       float     ptvg;       /* Transverse momentum generated at the ver */
       float     ptvr;       /* Rec'd pt at the vertex */
       float     pzg;        /* Generated pz */
       float     pzr;        /* Reconstructed pz. */
       float     pzvg;       /* Z component generated at the vertex. */
       float     pzvr;       /* Rec'd pz at the vertex */
       float     qfact;      /* Quality factor (fraction of good hits). */
       float     dedxg;      /* Generated dedx    */
       float     dedxr;      /* Reconstructed dedx   */
   };
/*  Last mod. for tte_mctrk: $DATE */

