/**********************************************************************/
/*	Data Table (10-bit)					      */
/**********************************************************************/
   struct type_shortdata {
	unsigned short data;	/* datum */
   };
/* last modified: $Date: 1997/12/31 14:34:12 $ */
