/**********************************************************************/
/*	Data Table (float)					      */
/**********************************************************************/
   struct type_floatdata {
	float data;	/* datum */
   };
/* last modified: $Date: 1998/11/09 21:20:42 $ */
