struct type_config {
        long  run_type; 
	long  trigger_mode; 
	long  n_trigs; 
	long  sc_interval; 
	long  map_pads; 
	long  sub_peds; 
	long  zero_suppress; 
	long  bad_suppress; 
	long  zp_thresh; 
	long  min_zp_seq; 
	long  max_zp_seq; 
	long  max_zp_seq_mode; 
	long  zp_presamples; 
	long  zp_postsamples; 
	long  trunc_ped; 
	long  min_ped; 
	long  max_ped; 
	long  max_ped_noise; 
	long  max_noisy_peds; 
	long  ped_algorithm; 
	long  gain_pulse_thresh; 
	long  min_gain_bucket; 
	long  max_gain_bucket; 
	long  gain_presamples; 
	long  gain_postsamples; 
	long  gain_calib; 
	long  min_frac_gain; 
	long  max_frac_gain; 
	long  gain_algorithm; 
	long  incl_geom; 
	long  incl_header; 
	long  dump_8bit; 
	long  dump_10bit; 
	long  dump_ped_means; 
	long  dump_ped_shifts; 
	long  dump_ped_widths; 
	long  dump_ped_status; 
	long  dump_gains; 
	long  dump_adc_map; 
	long  dump_gain_shifts; 
	long  dump_bad; 
	long  update_peds; 
	long  update_gains; 
	long  update_bad; 
	long  clear_bad; 
	long  rosies_enabled;
};
