/**********************************************************************/
/*	Index Table						      */
/**********************************************************************/
   struct type_index {
        unsigned long struct_row;	/* row # in structure table */
	unsigned long data_row;		/* row # in data table */
	octet data_type;		/* type of data in struct/data tbls */
	octet sector;			/* sector # (1-24) */
	octet rdo_loc;			/* RDO location (1-6, 0=unknown) */
	octet rgm;			/* Variable definition: see SN0282*/
					/* row # for "normal" data */
   };
/* last modified: $Date: 1997/12/31 14:34:11 $ */
