#!/bin/csh

unset DISPLAY
source /home/evpops/.login


if ($#argv != 1) then
  echo "Usage: $0 rootfile"
  echo "Runs the endOfRunAction on rootfile"
  exit 0
endif

set file=$1

cd /home/evpops/pplots/

rm endOfRunAction.C
echo "--- Creating the ROOT macro"
cat >endOfRunAction.C<<ROOTMACRO
{
  gROOT->Macro("Load.C");
  gSystem->Load("RTS");
  if (gROOT->IsBatch()) {
     gSystem->Load("libQtCore.so");
     gSystem->Load("libQtGui.so");
     gSystem->Load("libGui.so");
     gSystem->Load("libGQt.so");
     gSystem->Load("libQt3Support.so");
  }
  gSystem->Load("StDaqLib");
  gSystem->Load("OnlinePlots");
  gSystem->Load("StDbLib");
  gSystem->Load("StEEmcUtil");
  gSystem->Load("StEmcUtil");
  gSystem->Load("StStrangeMuDstMaker");
  gSystem->Load("StMuDSTMaker");
  gSystem->Load("St_db_Maker");
  gSystem->Load("StTriggerUtilities");
  gSystem->Load("StEEmcPoolmuEztPanitkin");
  gSystem->Load("StBEMCPlots");
  const char *homedir = gSystem->Getenv("ONLINEPLOTSDIR");
  if (!homedir) printf(" Attention: The environment variable \"ONLINEPLOTSDIR\" has not been set yet !!!\n");
  char* args[2];
   args[0] = "endOfRunAction";
   args[1] = "${file}";
   endOfRunActionMain::main(2, args);
}
ROOTMACRO

echo "--- Starting end of run action"
root4star -q endOfRunAction.C
