#!/bin/csh

unset DISPLAY

if ($#argv != 1) then
  echo "Usage: $0 rootfile"
  echo "Runs the endOfRunAction on rootfile"
  exit 0
endif

set file=$1

cd /home/operator/pplots/

rm endOfRunAction.C
echo "--- Creating the ROOT macro"
cat >endOfRunAction.C<<ROOTMACRO
{
  gSystem->Load("$QTDIR/lib/libqt-mt.so");
  gSystem->Load("libGui.so");
  gSystem->Load("libGQt.so");
  gROOT->Macro("Load.C");
  gSystem->Load("RTS");
  gSystem->Load("StDaqLib");
  gSystem->Load("OnlinePlots");
  gSystem->Load("StDbLib");
  gSystem->Load("StEEmcUtil");
  gSystem->Load("StEmcUtil");
  gSystem->Load("StStrangeMuDstMaker");
  gSystem->Load("StMuDSTMaker");
  gSystem->Load("StEEmcPoolmuEztPanitkin");
  gSystem->Load("StBEMCPlots");
  const char *homedir = gSystem->Getenv("ONLINEPLOTSDIR");
  if (!homedir) printf(" Attention: The environment variable \"ONLINEPLOTSDIR\" has not been set yet !!!\n");
  char* args[2];
   args[0] = "endOfRunAction";
   args[1] = "${file}";
   endOfRunActionMain::main(2, args);
}
ROOTMACRO

echo "--- Starting end of run action"
root4star -q endOfRunAction.C
