#!/bin/tcsh

unset DISPLAY

cd /home/evpops/pplots/

rm liveServer.C
echo "--- Creating the ROOT macro"
cat >liveServer.C<<ROOTMACRO
{
  gROOT->Macro("Load.C");
  gSystem->Load("RTS");
  if (gROOT->IsBatch()) {
     gSystem->Load("libQtCore.so");
     gSystem->Load("libQtGui.so");
     gSystem->Load("libGui.so");
     gSystem->Load("libGQt.so");
     gSystem->Load("libQt3Support.so");
  }
  gSystem->Load("StDaqLib");
  gSystem->Load("OnlinePlots");
  gSystem->Load("StDbLib");
  gSystem->Load("StEEmcUtil");
  gSystem->Load("StEmcUtil");
  gSystem->Load("StStrangeMuDstMaker");
  gSystem->Load("StMuDSTMaker");
  gSystem->Load("St_db_Maker");
  gSystem->Load("StTriggerUtilities");
  gSystem->Load("StEEmcPoolmuEztPanitkin");
  gSystem->Load("StBEMCPlots");
  const char *homedir = gSystem->Getenv("ONLINEPLOTSDIR");
  if (!homedir) printf(" Attention: The environment variable \"ONLINEPLOTSDIR\" has not been set yet !!!\n");
  char* args[5];
   args[0] = "pplotServer";
   args[1] = "-live";
   args[2] = "-start";
   args[3] = "-end";
   args[4] = "-nogui";
   evpServerMain::main(5, args);
}
ROOTMACRO

echo "--- Starting Server Loop"
while 1
        touch server.out
        nohup root4starN -q -b liveServer.C >>& server.out
        /RTS/bin/LINUX/i686/rtsLog -p 8005 -d WARNING -c server.csh Restarting evpServer in 30 sec... Press 'live' in presenter gui
        sleep 30;
end

