/*****************************************************************************
*   Table: emcJetTrigger
*        description: Table which contains Jet Patch Trigger
*        auther:      SUAIDE, Alexandre
*        compile with stic -f <name.idl>
******************************************************************************/
   struct emcJetTrigger 
   { 
       long   JetPatchNumber;     /* Patch Number*/
                     
       float  JetEt6bits;         /* Jet Patch Et */
       long   JetBits[32];        /* Jet bits (for this jet patch only) */
   };
