/*****************************************************************************
*   Table: emcPatchTrigger
*        description: Table which contains Patch and High Tower Trigger
*        auther:      SUAIDE, Alexandre
*        compile with stic -f <name.idl>
******************************************************************************/
   struct emcPatchTrigger 
   { 
       long   PatchNumber;         /* Patch Number*/
       float  Eta;                 /* mean eta of this patch */
       float  Phi;                 /* mean phi of this patch */
              
       long   TowerId[16];         /* towers (Soft Id) that make this patch */
                     
       float  PatchEt6bits;        /* Reconstricted Patch Et */
       float  HighTowerEt6bits;    /* Recontructed High Tower Et */
       long   HighTowerId;         /* High Tower Id */
       float  Ratio;               /* HT/Patch */

       long   PatchAdcSum6bits;   /* raw data adc sum */
       long   HighTowerAdc6bits;  /* raw data high tower adc */
       
       long   PatchBits[32];       /* Patch bits (for this patch only) */
       long   HighTowerBits[32];   /* High Tower bits (for this patch only)  */
       long   RatioBits[32];       /* Ratio bits (for this patch only) */ 
       
   };
