/*****************************************************************************
*   Table: emcTrigger
*        description: Table which contains EMC L0 Trigger
*        auther:      SUAIDE, Alexandre
*        compile with stic -f <name.idl>
******************************************************************************/
   struct emcTrigger 
   { 
       float  Et;                       /* total Et */
       long   NEtThresholds;            /* number of thresholds for et */
       float  EtThresholds[32];         /* et thresholds */
       long   EtBits[32];               /* et bits */
       
       long   NPatchThresholds;         /* number of patch thresholds */
       float  PatchThresholds[32];      /* patch thresholds */
       long   PatchBits[32];            /* patch bits */
       
       long   NHighTowerThresholds;     /* number of High Tower thresholds */
       float  HighTowerThresholds[32];  /* High Tower thresholds */
       long   HighTowerBits[32];        /* High Tower bits */

       long   NRatioThresholds;         /* number of High Tower thresholds */
       float  RatioThresholds[32];      /* High Tower thresholds */
       long   RatioBits[32];            /* High Tower bits */
              
       long   NJetThresholds;           /* number of Jet thresholds */
       float  JetThresholds[32];        /* Jet thresholds */
       long   JetBits[32];              /* Jet bits */
       
   };
