//
// File generated by /afs/rhic.bnl.gov/star/ROOT/5.34.09/.sl53_gcc432/rootdeb/bin/rootcint at Wed Aug 28 18:35:39 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME HelloCintDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "HelloCintDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TMyQButton_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void TMyQButton_Dictionary();
   static void *new_TMyQButton(void *p = 0);
   static void *newArray_TMyQButton(Long_t size, void *p);
   static void delete_TMyQButton(void *p);
   static void deleteArray_TMyQButton(void *p);
   static void destruct_TMyQButton(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TMyQButton*)
   {
      ::TMyQButton *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::TMyQButton),0);
      static ::ROOT::TGenericClassInfo 
         instance("TMyQButton", "./TMyQButton.h", 8,
                  typeid(::TMyQButton), DefineBehavior(ptr, ptr),
                  0, &TMyQButton_Dictionary, isa_proxy, 0,
                  sizeof(::TMyQButton) );
      instance.SetNew(&new_TMyQButton);
      instance.SetNewArray(&newArray_TMyQButton);
      instance.SetDelete(&delete_TMyQButton);
      instance.SetDeleteArray(&deleteArray_TMyQButton);
      instance.SetDestructor(&destruct_TMyQButton);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TMyQButton*)
   {
      return GenerateInitInstanceLocal((::TMyQButton*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TMyQButton*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void TMyQButton_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::TMyQButton*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_TMyQButton(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TMyQButton : new ::TMyQButton;
   }
   static void *newArray_TMyQButton(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TMyQButton[nElements] : new ::TMyQButton[nElements];
   }
   // Wrapper around operator delete
   static void delete_TMyQButton(void *p) {
      delete ((::TMyQButton*)p);
   }
   static void deleteArray_TMyQButton(void *p) {
      delete [] ((::TMyQButton*)p);
   }
   static void destruct_TMyQButton(void *p) {
      typedef ::TMyQButton current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TMyQButton

/********************************************************
* HelloCintDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableHelloCintDict();

extern "C" void G__set_cpp_environmentHelloCintDict() {
  G__cpp_reset_tagtableHelloCintDict();
}
#include <new>
extern "C" int G__cpp_dllrevHelloCintDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TMyQButton */
static int G__HelloCintDict_170_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMyQButton* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMyQButton((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) TMyQButton((const char*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new TMyQButton[n];
       } else {
         p = new((void*) gvp) TMyQButton[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new TMyQButton;
       } else {
         p = new((void*) gvp) TMyQButton;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__HelloCintDictLN_TMyQButton));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HelloCintDict_170_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMyQButton*) G__getstructoffset())->SetSize((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HelloCintDict_170_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TMyQButton*) G__getstructoffset())->Show((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TMyQButton*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HelloCintDict_170_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMyQButton*) G__getstructoffset())->SetText((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HelloCintDict_170_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TMyQButton*) G__getstructoffset())->SetOn((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TMyQButton*) G__getstructoffset())->SetOn();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HelloCintDict_170_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMyQButton*) G__getstructoffset())->SetStyle((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HelloCintDict_170_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TMyQButton*) G__getstructoffset())->CatchPad((TVirtualPad*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TMyQButton*) G__getstructoffset())->CatchPad();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__HelloCintDict_170_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TMyQButton* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TMyQButton(*(TMyQButton*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__HelloCintDictLN_TMyQButton));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMyQButton G__TTMyQButton;
static int G__HelloCintDict_170_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TMyQButton*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TMyQButton*) (soff+(sizeof(TMyQButton)*i)))->~G__TTMyQButton();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TMyQButton*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TMyQButton*) (soff))->~G__TTMyQButton();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__HelloCintDict_170_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMyQButton* dest = (TMyQButton*) G__getstructoffset();
   *dest = *(TMyQButton*) libp->para[0].ref;
   const TMyQButton& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TMyQButton */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncHelloCintDict {
 public:
  G__Sizep2memfuncHelloCintDict(): p(&G__Sizep2memfuncHelloCintDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncHelloCintDict::*p)();
};

size_t G__get_sizep2memfuncHelloCintDict()
{
  G__Sizep2memfuncHelloCintDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceHelloCintDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableHelloCintDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__HelloCintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HelloCintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HelloCintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HelloCintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HelloCintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__HelloCintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HelloCintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HelloCintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HelloCintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HelloCintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TMyQButton */
static void G__setup_memvarTMyQButton(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__HelloCintDictLN_TMyQButton));
   { TMyQButton *p; p=(TMyQButton*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HelloCintDictLN_QPushButton),-1,-1,4,"fMyButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarHelloCintDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTMyQButton(void) {
   /* TMyQButton */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__HelloCintDictLN_TMyQButton));
   G__memfunc_setup("TMyQButton",999,G__HelloCintDict_170_0_1, 105, G__get_linked_tagnum(&G__HelloCintDictLN_TMyQButton), -1, 0, 1, 1, 1, 0, "C - - 10 '\"\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSize",711,G__HelloCintDict_170_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - 'UInt_t' 0 - w h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Show",417,G__HelloCintDict_170_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 'kTRUE' show", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetText",721,G__HelloCintDict_170_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - text", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOn",489,G__HelloCintDict_170_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 'kTRUE' on", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetStyle",829,G__HelloCintDict_170_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - style", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CatchPad",760,G__HelloCintDict_170_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TVirtualPad' - 0 '0' pad", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("TMyQButton", 999, G__HelloCintDict_170_0_8, (int) ('i'), G__get_linked_tagnum(&G__HelloCintDictLN_TMyQButton), -1, 0, 1, 1, 1, 0, "u 'TMyQButton' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TMyQButton", 1125, G__HelloCintDict_170_0_9, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__HelloCintDict_170_0_10, (int) ('u'), G__get_linked_tagnum(&G__HelloCintDictLN_TMyQButton), -1, 1, 1, 1, 1, 0, "u 'TMyQButton' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncHelloCintDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalHelloCintDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcHelloCintDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__HelloCintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__HelloCintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HelloCintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__HelloCintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HelloCintDictLN_QPushButton = { "QPushButton" , 99 , -1 };
G__linked_taginfo G__HelloCintDictLN_TVirtualPad = { "TVirtualPad" , 99 , -1 };
G__linked_taginfo G__HelloCintDictLN_TMyQButton = { "TMyQButton" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableHelloCintDict() {
  G__HelloCintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__HelloCintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HelloCintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__HelloCintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HelloCintDictLN_QPushButton.tagnum = -1 ;
  G__HelloCintDictLN_TVirtualPad.tagnum = -1 ;
  G__HelloCintDictLN_TMyQButton.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableHelloCintDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__HelloCintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__HelloCintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HelloCintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__HelloCintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HelloCintDictLN_QPushButton);
   G__get_linked_tagnum_fwd(&G__HelloCintDictLN_TVirtualPad);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__HelloCintDictLN_TMyQButton),sizeof(TMyQButton),-1,1280,(char*)NULL,G__setup_memvarTMyQButton,G__setup_memfuncTMyQButton);
}
extern "C" void G__cpp_setupHelloCintDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupHelloCintDict()");
  G__set_cpp_environmentHelloCintDict();
  G__cpp_setup_tagtableHelloCintDict();

  G__cpp_setup_inheritanceHelloCintDict();

  G__cpp_setup_typetableHelloCintDict();

  G__cpp_setup_memvarHelloCintDict();

  G__cpp_setup_memfuncHelloCintDict();
  G__cpp_setup_globalHelloCintDict();
  G__cpp_setup_funcHelloCintDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncHelloCintDict();
  return;
}
class G__cpp_setup_initHelloCintDict {
  public:
    G__cpp_setup_initHelloCintDict() { G__add_setup_func("HelloCintDict",(G__incsetup)(&G__cpp_setupHelloCintDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initHelloCintDict() { G__remove_setup_func("HelloCintDict"); }
};
G__cpp_setup_initHelloCintDict G__cpp_setup_initializerHelloCintDict;

