/********************************************************************
* HelloCintDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HelloCintDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHelloCintDict();
extern void G__cpp_setup_inheritanceHelloCintDict();
extern void G__cpp_setup_typetableHelloCintDict();
extern void G__cpp_setup_memvarHelloCintDict();
extern void G__cpp_setup_globalHelloCintDict();
extern void G__cpp_setup_memfuncHelloCintDict();
extern void G__cpp_setup_funcHelloCintDict();
extern void G__set_cpp_environmentHelloCintDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMyQButton.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HelloCintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HelloCintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HelloCintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HelloCintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HelloCintDictLN_QPushButton;
extern G__linked_taginfo G__HelloCintDictLN_TVirtualPad;
extern G__linked_taginfo G__HelloCintDictLN_TMyQButton;

/* STUB derived class for protected member access */
