/*    additionalTriggerID.idl
*
*  Table: additionalTriggerID 
*
*       description:
*/ 


struct additionalTriggerID  { 

   unsigned long  runNumber;   /*   run number  */
   unsigned long  eventNumber;   /*   event number  */
   unsigned long  idxTrg;   /*   */
   unsigned long  daqTrgId;   /*   */
   unsigned long  offlineTrgId;   /*   bit in L3_Summary(0);  */
   unsigned long  trgNameVersion;   /*   identifier bit to offline  */
   unsigned long  trgVersion;   /*   */
   unsigned long  threashVersion;   /*   */
   unsigned long  psVersion;   /*   */

 };  
