/*    beamInfo.idl
*
*  Table: beamInfo
*
*       description:  //   beam state for run at start and end
*/ 


struct beamInfo { 

   unsigned long  runNumber;   /*   */
   long  entryTag;   /*     0=startrun, 1=endrun, 2=runave, 3=std  */
   char  blueSpecies[32];   /*     species  */
   unsigned long  blueMassNumber;   /*   */
   float  blueEnergy;   /*     energy  */
   float  blueIntensity;   /*     Ions  */
   float  blueLifeTime;   /*     Ions per minute  */
   float  blueBunchIntensity;   /*     bunch intensity  */
   char  yellowSpecies[32];   /*     species  */
   unsigned long  yellowMassNumber;   /*   */
   float  yellowEnergy;   /*     energy  */
   float  yellowIntensity;   /*     Ions  */
   float  yellowLifeTime;   /*     Ions per minute  */
   float  yellowBunchIntensity;   /*     bunch intensity  */
   float  blueFillNumber;   /*   */
   float  yellowFillNumber;   /*   */

 };  
