/* beamOrbitInfo.idl
*
* Table: beamOrbitInfo
*
* description: beam Orbit information
*
*/
struct beamOrbitInfo {
  unsigned long runNumber;
  long blue_beamPos5_horizontal;
  long blue_beamPos5_vertical;
  long yellow_beamPos5_horizontal;
  long yellow_beamPos5_vertical;
  long blue_beamPos6_horizontal;
  long blue_beamPos6_vertical;
  long yellow_beamPos6_horizontal;
  long yellow_beamPos6_vertical;
  long blue_filledBuckets;
  long yellow_filledBuckets;
};

