/*    bemcDimensions.idl
*
*  Table: bemcDimensions
*
*       description: //  BEmc geometry DB Overall table
*/ 


struct bemcDimensions { 

   long  nPatches;   /*   No of Patches installed  */
   long  nModules;   /*   Total Number of Modules installed  */
   long  nTowers;   /*   Total Number of Towers installed  */
   long  nActiveTowers;   /*   Total Number of Towers Active  */
   float  InnerCylinderRadius;   /*   Inner Radius of EMC Cyliner  */
   float  OuterCylinderRadius;   /*   Outer Radius of EMC Cyliner  */
   float  SMDEtaCylinderRadius;   /*   Outer Radius of EMC Cyliner  */
   float  SMDPhiCylinderRadius;   /*   Outer Radius of EMC Cyliner  */
   float  etaGapCenterEast;   /*   Gap in eta at eta=0 for East  */
   float  etaGapCenterWest;   /*   Gap in eta at eta=0 for Wast  */
   float  etaGapEndEast;   /*   Gap in eta at eta=1 for East  */
   float  etaGapEndWest;   /*   Gap in eta at eta=-1 for Wast  */
   float  phiGap;   /*   Gap in phi in between modules  */
   float  VariationOfScnThk;   /*   Variation of Scin thickness  */
   float  VariationOfPbThk;   /*   Variation of Pb thickness  */

 };  
