
/* 
 * table definition for L2 BEMC hardware pedestals on L0 
 */

struct bemcHwpedestal {
  unsigned long daqId;    /* ?? */
  unsigned long towerId;  /* ?? */
  float hwpedestal;       /* ?? */
};


