/*    bemcTowers.idl
*
*  Table: bemcTowers
*
*       description: //  bemcTowsers, BEmc Tower param table
*/ 


struct bemcTowers { 

   long  TowerNo;   /*   Id of Tower  */
   long  ModuleNo;   /*   Id of module corresponding to tower  */
   long  EtaBin;   /*   Id of Etabin corresponding to tower  */
   long  PhiBin;   /*   Id of Phibin corresponding to tower  */
   long  PMTBoxNo;   /*   Id of PMTBoxNo corresponding to tower  */
   long  CrateNo;   /*   Id of CrateNo corresponding to tower  */
   long  TowerDigitizerNo;   /*   Id of TowerDig corresponding to tower  */
   long  TowerDataCollector;   /*  Id of TowerDig corresponding to tower  */
   long  FiberGuideNo;   /*  Id of FiberGuide corresponding to tower  */
   long  FirstFiberConnector;   /*  Id of Fiberconnector(first)  */
   long  SecondFiberConnector;   /*  Id of Fiberconnector(2nd)  */
   long  OnePinFiberConnector;   /*  Id of One Pin Fiberconnector  */
   char  Status[8];   /*  Status Flag of the tower  */

 };  
