/*    bemcModules.idl
*
*  Table: bemcModules
*
*       description: //  bemcModules  Module-wise parameters to be stored for BEMC (120)
*/ 


struct bemcModules { 

   long  ModuleNo;   /*   Id No of module  */
   long  NActiveTower;   /*   No of Active Towers  */
   long  PMTBoxNo[2];   /*   PMT box no  */
   long  CrateNo[2];   /*   Crate No  */
   long  BackLegNo;   /*   Crate No  */
   long  TpcSectorNo;   /*   Crate No  */
   char  Status[8];   /*   Overall status of the module  */

 };  
