/*     bemcMap.idl
*
*  Table: bemcMap 
*
*        description: // BEMC mapping table
*/

struct bemcMap {
  octet m;                    /* module 1-120 */
  octet e;                    /* eta index 1-20 */
  octet s;                    /* sub index 1-2 */
  unsigned short daqID;        /* ordering of elements in DAQ file 0-4799 */
  octet crate;                /* electronics crates 1-30 */
  octet crateChannel;          /* index within a crate 0-159 */
  octet TDC;                  /* index in crate 80, 0-29 */
  unsigned short triggerPatch; /* tower belongs to this TP 0-299 */
  octet jetPatch;              /* tower belongs to this JP 0-11 */
  unsigned short DSM;          /* just integer div TP/10 0-29 */
  float eta;                  /* physical pseudorapidity of tower center */
  float phi;                  /* physical azimuth of tower center */
  char comment[255];
};

