/*     bprsMapping.idl
*
*  Table: bprsMapping
*
*         description: // BPRS mapping table
*/

struct bprsMapping {
  octet m;                    /* module 1-120 */
  octet e;                    /* eta index 1-20 */
  octet s;                    /* sub index 1-2 */
  octet PMTbox;                /* PMT box 1-30 (West), 31-60 (East) */
  octet MAPMT;                /* MAPMT # for this element in PMTbox 1-5 */
  octet pixel;                /* index inside MAPMT 1-16 */
  octet rdo;                  /* readout crate 0-3 */
  unsigned short rdoChannel;  /* index in readout crate 0-4799 */
  octet wire;                  /* wire number 1-40 */
  octet feeA;                  /* A value for FEE 1-2 */
  octet SCA;                  /* switched capacitor array 1-2 */
  octet SCAChannel;            /* index inside SCA 0-15 */
  octet powerSupply;          /* 1-2 */
  octet powerSupplyModule;    /* 1-15 */
  octet powerSupplyChannel;    /* 0-14 */
  float eta;                  /* physical pseudorapidity of tower center */
  float phi;                  /* physical azimuth of tower center */
  char comment[255];
};

