/*     bsmdeMap.idl
*
*  Table: bsmdeMap
*  
*         description: // BSMDE mapping table
*/
struct bsmdeMap {
  octet m;                    /* module 1-120 */
  octet e;                    /* eta index 1-150 (eta), 1-10 (phi) */
  octet s;                    /* sub index 1 (eta), 1-15 (phi) */
  octet rdo;                  /* readout crate 0-7 */
  unsigned short rdoChannel;  /* index in crate 0-4799 */
  octet wire;                  /* wire number 2-80 */
  octet feeA;                  /* A value for FEE 1-4 */
  float eta;                  /* physical pseudorapidity of strip center */
  float phi;                  /* physical azimuth of strip center */
  char comment[255];
};