/*  ctbDbMaskGain.idl 
*  
*  Table: ctbDbMaskGain.idl 
*
*  description:  //length of a comment total # of CTB slats
*/



/*
 * Mask & gain for 240 CTB slats, see SN299A for details
 */

struct ctbDbMaskGain {
  octet tray[240]; /* values: 0,1  */
  octet slat[240]; /* values: 0,119  */
  octet mask[240]; /* values: 0-good, 1-broken */
  float gain[240]; /* units: (ADC/MIP) */
  char comment[160]; /* commemnts */
};
