/*    daqEventTag.idl
*
*  Table: daqEventTag
*
*       description: Daq input to TagDb
*/ 


struct daqEventTag { 

  unsigned long  run;              /* run number  */
  unsigned long  fileSequence;     /* index portion of filename */
  unsigned short fileStream;      /* new in version 10.0  stream portion of filename */
  unsigned short isCopy;            /* new in version 10.0  is this a event a copy? */
  unsigned long  eventNumber;      /* monotonically increases in every file */
  unsigned short token;            /* the token */
  unsigned short physWord;        /* new in version 10.0  physics word */
  unsigned long  size;             /* in bytes */
  unsigned long  time;             /* Time built by EVB */
  unsigned short  trgWord;        /* trigger word */
  unsigned short  trg_cmd;        /* From trgActionWord  */
  unsigned short  daq_cmd;        /* From trgActionWord  */
  unsigned short  detector_bits;  /* From trgActionWord  */
  unsigned long  bx_hi;            /* RHIC bunch crossing (hi word)  */
  unsigned long  bx_lo;            /* RHIC bunch crossing (lo word)  */
  unsigned long l3_nTracks;	   /* unused */
  unsigned long trg_add_bits;      /* was any pileup detected  */
  unsigned long lastDSM;	   /*output from last dsm */
  unsigned long l1_trg_bits;       /* new in version 10.0  triggers satisfied after L1 */
  unsigned long l2_trg_bits;       /* new in version 10.0  triggers satisfied after L2 */
  unsigned long l3_trg_bits;       /* new in version 10.0  triggers satisfied after L3 */
};  
