/*    daqFileTag.idl
*
*  Table: daqFileTag
*
*       description: //  Daq input to FileList
*/ 


struct daqFileTag { 

  unsigned long  run;             /* unique run number  */
  unsigned long  beginEvent;      /* 1st event number in file  */
  unsigned long  endEvent;        /* last event number in file  */
  unsigned long  numberOfEvents;  /* total number of events  */
  unsigned long  fileSequence;    /* sequence part of filename  */
  octet  file[256];               /* unique file name without (hpss) path  */
  unsigned long  hpss;            /* is the data at hpss? */  
  unsigned long  fileStream;      /* new for version 10.0, stream part of filename */
};  
