/*    daqRunTag.idl
*
*  Table: daqRunTag
*
*       description: //  Daq input to Run-TagDb
*/ 


struct daqRunTag { 

   unsigned long  run;   
   unsigned long  whichtag;              /*   0 start, 1 stop  */
   unsigned long  startTime;             /*   NULL if stoprun  */
   unsigned long  stopTime;               /*   NULL if startrun  */
   unsigned long  runType;            /* Magic Number defining Run Type */ 
   unsigned long  totalNumberOfEvents;  /* sum of events  */
   unsigned long  whichEvb;              /* one of four  */
 };  
