/*    dsmPrescales.idl
*
*  Table: dsmPrescales
*
*       description:
*/ 


struct dsmPrescales { 

   long  runNumber;   /*   run number  */
   long  trgId;   /*   offline triggerbit  */
   long  dsmPrescale;   /*   dsm value  */

 };  
