/*    eemcDbPMTped.idl
*
*  Table: eemcDbPMTped
*
*       description:  *    PMT+MAPMT ADC pedestals for one sector
*/ 


struct eemcDbPMTped { 

   char  name[16000];   /*    sector/subsector/tower of strip/pre/post/tower  */
   float  ped[1000];   /*   pedestal in ADC chan  */
   float  sig[1000];   /*   width of pedestal in ADC chan  */
   char  comment[160];   /*   */

 };  
