/*    eemcDbPMTcal.idl
*
*  Table: eemcDbPMTcal
*
*       description:  *    EEMC Tower Box  calibration for one sector
*/ 


struct eemcDbPMTcal { 

   char  name[960];   /*      PMT ID  sector/box/tower  */
   float  gain[60];   /*   pmt effective gain of the tower  */
   float  egain[60];   /*   error of the gain  */
   float  hv[60];   /*   pmt actual HV (V), dac=HV/HVmax*1023  */
   char  comment[160];   /*   */

 };  
