/*    eemcDbBoxconf.idl
*
*  Table: eemcDbBoxconf
*
*       description:  *    EEMC Tower Box configuration for one sector
*/ 


struct eemcDbBoxconf { 

   char  name[80];   /*      PMT ID  sector/box/tower  */
   long  barcode[5];   /*      box barcode  */
   long  hvBranch[5];   /*      branch+ID  of HVsys controller  */
   char  comment[160];   /*      PMT ID  sector/box/tower  */

 };  
