/*    eemcDbPMTstat.idl
*
*  Table: eemcDbPMTstat
*
*       description:  *    EEMC status of Tower/Strip/Shower
*/ 


struct eemcDbPMTstat { 

   char  name[16000];   /*   sector/subsector/tower of strip/pre/post/tower  */
   unsigned short  stat[1000];   /*   status  code, see eemcConstDB.hh for definitions  */
   unsigned short  fail[1000];   /*   failure code, see eemcConstDB.hh for definitions  */
   char  comment[160];   /*   */

 };  
