/*    eemcDbADCconf.idl
*
*  Table: eemcDbADCconf
*
*       description:  *    PMT+MAPMT ADC channel/slot configuration for one sector
*/ 


struct eemcDbADCconf { 

   char  name[16000];   /*    sector/subsector/tower or strip or preTower ...  */
   long  crate[1000];   /*   slot  */
   long  channel[1000];   /*   channel  */
   char  comment[160];   /*   comment  */

 };  
