/*    eemcDbPMTconf.idl
*
*  Table: eemcDbPMTconf
*
*       description:  *     EEMC Tower PMT configuration for one sector
*/ 


struct eemcDbPMTconf { 

   char  name[960];   /*      PMT ID  sector/box/tower  */
   long  barcode[60];   /*      PMT  shield barcode  */
   long  sn[60];   /*      pmt serial number  */
   long  baseBarcode[60];   /*      cw base barcode  */
   long  baseSN[60];   /*      cw base serial number  */
   long  baseAddress[60];   /*      cw base programmable id  */
   char  comment[160];   /*   */

 };  
