/*    eemcDbPMTname.idl
*
*  Table: eemcDbPMTname
*
*       description:  *    EEMC Tower and PMT names
*/ 


struct eemcDbPMTname { 

   char  name[960];   /*    tower name  */
   char  tubeName[960];   /*    PMT  name  */
   char  comment[160];   /*   */

 };  
