/*    eemcDbPIXname.idl
*
*  Table: eemcDbPIXname
*
*       description:  *    EEMC PMT and MAPMT pixel names,
*/ 


struct eemcDbPIXname { 

   char  name[16000];   /*  logical name of  pixel  */
   char  tubeName[16000];   /*   hardware name of pixel  */
   char  comment[160];   /*   */

 };  
