/*    eemcDbPIXcal.idl
*
*  Table: eemcDbPIXcal
*
*       description:  *    EEMC calibration for every pixel ( PMT and MAPMT)
*/ 


struct eemcDbPIXcal { 

   char  name[16000];   /*    pixel name  */
   float  gain[1000];   /*   gain of the pixel  */
   float  egain[1000];   /*   error of the gain  */
   char  comment[160];   /*   */

 };  
