/*    eemcDbPMTchar.idl
*
*  Table: eemcDbPMTchar
*
*       description:  *    PMT characterization (from Sasha)
*/ 


struct eemcDbPMTchar { 

   long  sn;   /*      pmt base serial number  */
   float  speRes;   /*      single p. e.  resolution  (ch?)  */
   float  nomHV;   /*    HV (V) at gain 2x10^5  */
   float  darkC;   /*    dark current, (pA)  */
   char  comment[160];   /*   */

 };  
