/*    emcBarrelAdc.idl
*
*  Table: emcBarrelAdc
*
*       description:  //  emc Barrel Tower/Preshower ADC channel
*/ 


struct emcBarrelAdc { 

   float  ch[20];   /*   Channel : channel number  */

 };  
