/*    emcBTowEle.idl
*
*  Table: emcBTowEle
*
*       description: //  emc barrel tower electonics informations
*/ 


struct emcBTowEle { 

   long  moduleNumber;   /*   number: Module number  */
   long  fiberGuideNumber[20][2];   /*   number : FiberGuide number  */
   long  firstFiberConnector[20][2];   /*   number : first Fiber connector number  */
   long  secondFiberConnector[20][2];   /*   number : second Fiber connector number  */
   long  onepinFiberConnector[20][2];   /*   number : onepin Fiber connector number  */
   long  PMTBoxNumber[20][2];   /*   number : PMT Box number  */
   long  FEENumber[20][2];   /*   number : FEE cards number  */
   long  RDONumber[20][2];   /*   number : RDO cards number  */
   long  VMECrateNumber[20][2];   /*   number : VME crate number  */
   long  signalLineNumber[20][2];   /*   number : signal line number  */
   long  signalPortNumber[20][2];   /*   number : signal port number  */

 };  
