/*    emcBModuleEle.idl
*
*  Table: emcBModuleEle
*
*       description: //  emc barrel ModuleEle informations
*/ 


struct emcBModuleEle { 

   long  moduleNumber;   /*   number: Module number  */
   long  FEENumber;   /*   number : FEE cards number  */
   long  RDONumber;   /*   number : RDO cards number  */
   long  crateNumber;   /*   number : crate number  */

 };  
