/*    emcBModuleDim.idl
*
*  Table: emcBModuleDim
*
*       description: //  emc barrel electronics informations
*/ 


struct emcBModuleDim { 

   long  moudleNumber;   /*   number : modules number  */
   float  etaShiftAtCenter;   /*   eta   : eta shift at eta near 0  */
   float  errEtaShiftAtCenter;   /*   eta   : error on eta shift at eta near 0  */
   float  etaShiftAtEdge;   /*   eta   : eta shift at eta near +/-1  */
   float  errEtaShiftAtEdge;   /*   eta   : error on eta shift at eta near +/-1  */
   float  phiShiftAtCenter;   /*   radian : phi shifts  */
   float  errPhiShiftAtCenter;   /*   radian : error on phi shifts  */
   long  backLeg;   /*   number : bug leg number  */
   long  tpcSector;   /*   number : TPC sector number  */
   long  quadrant;   /*   number : Quadrant Number  */

 };  
