/*    emcCalSummary.idl
*
*  Table: emcCalSummary
*
*       description: *         //:  Table which contains the emc calibration summary
*/ 


struct emcCalSummary { 

   long  DetNumber;   /*     detector number  */
   long  FirstRun;   /*     first run used for calibration  */
   long  LastRun;   /*     last run used for calibration  */
   long  NEvents;   /*     number of events used for calibration  */
   long  CalibMode;   /*   calmode (1=Equalization, 10=MIP,100=Pi0,1000=Electron)  */
   char  Operator[64];   /*     Operator Name  */
   char  Comments[256];   /*     comments  */

 };  
