/*    emcCalSummary.idl
*
*  Table: emcCalSummary
*
*       description: //:  Table which contains the bemc calibration summary
*/ 


struct emcCalSummary { 

   long  DetNumber;   /*   detector number  */
   long  FirstRun;   /*   first run used for calibration  */
   long  LastRun;   /*   last run used for calibration  */
   long  NEvents;   /*   number of events used for calibration  */
   char  Operator[80];   /*   Operator Name  */
   char  Comments[200];   /*   comments  */

 };  
