/*    emcCalibration.idl
*
*  Table: emcCalibration
*
*       description: //:  Table which contains all calibration information
*/ 


struct emcCalibration { 

   long  Status;   /*   status of the tower/wire (0=problem, 1=ok)  */
   long  CalibStatus;   /*   calibration status (0=failed, 1=ok)  */
   long  CalibMode;   /*   calibration mode (1=MIP only,10=Pi0,100=Electron)  */
   float  AdcToE[5];   /*   ADC to Energy  */
   float  AdcToEErr[5];   /*   ADC to Energy error  */
   float  AdcToECov[5][5];   /*   ADC to Energy covariance matrix  */
   float  AdcToEChiSqr;   /*   ADC to Energy chi square  */
   float  AdcPedestal;   /*   ADC pedestal  */
   float  AdcPedestalRms;   /*   ADC pedestal RMS  */

 };  
