/*    emcCalib.idl
*
*  Table: emcCalib
*
*       description: //:  Table which contains all calibration information
*/ 


struct emcCalib { 

   octet  Status[4800];   /*   status of the tower/wire (0=problem, 1=ok)  */
   float  AdcToE[4800][5];   /*   ADC to Energy  */

 };  
