/*    emcDimensions.idl
*
*  Table: emcDimensions
*
*       description: //  emc dimensions informations
*/ 


struct emcDimensions { 

   float  etaBinBTow[2][21];   /*   eta   : nominal eta bin edges for west/east  */
   float  etaBinBSmd[2][11];   /*   eta   : nominal eta bin edges for west/east  */
   float  etaBinETow[2][13];   /*   eta   : nominal eta bin edges for west/east  */
   float  phiGap;   /*   radian   : nominal interrow phi gap  */
   float  etaGap;   /*   rapidity : nominal interrow eta gap  */
   float  variationOfPressure;   /*   ?       : variation of pressure  */
   float  variationOfScintThick;   /*   mm      : variation of scintillator thinkness  */
   float  variationOfPbThick;   /*   mm      : variation of Pb thinkness  */
   long  nModule[8];   /*   number : number of modules  */
   long  nEta[8];   /*   number : number of eta bin  */
   long  nSub[8];   /*   number : number of sub bin  */

 };  
