/*    emcElectronics.idl
*
*  Table: emcElectronics
*
*       description: //  emc electronics informations
*/ 


struct emcElectronics { 

   long  detectorId;   /*   number : detector id  */
   long  adcBits;   /*   bits   : number of ADC bits  */
   long  numberOfFEE;   /*   number : number of FEE cards  */
   long  numberOfRDO;   /*   number : number of RDO cards  */
   float  frequancyFEE;   /*   Hz     : FEE frequency  */
   long  typeOfShaperFEE;   /*   number : FEE shaper function type  */

 };  
