/*    emcEqualization.idl
*
*  Table: emcEqualization
*
*       description: //:  Table which contains equalization information
*/ 


struct emcEqualization { 

   long  EqStatus;   /*   equalization status (0=failed, 1=ok)  */
   long  EqRef;   /*   tower or wire used as reference for equalization  */
   float  EqSlope;   /*   equalization slope  */
   float  EqSlopeError;   /*   equalization slope error  */
   float  EqShift;   /*   equalization shift  */
   float  EqShiftError;   /*   equalization shift error  */
   float  EqCovariance;   /*   eq. covariance between slope and shift  */
   float  EqChiSqr;   /*   equalization fit chi square  */

 };  
