/*    emcETowAdc.idl
*
*  Table: emcETowAdc
*
*       description: //  emc Endcap Tower/Preshower ADC channel
*/ 


struct emcETowAdc { 

   float  ch[12][5];   /*   Channel : channel number  */

 };  
