/*    emcGain.idl
*
*  Table: emcGain
*
*       description: //:  Table which contains gain correction information
*/ 


struct emcGain { 

   octet  Status[4800];   /*   status of the tower/wire (0=problem, 1=ok)  */
   float  Gain[4800];   /*   Gain Variation  */

 };  
