/*    emcMipCalib.idl
*
*  Table: emcMipCalib
*
*       description: //:  Table which contains MIP information
*/ 


struct emcMipCalib { 

   long  Status;   /*  status of the etabin (0=problem, 1=ok)  */
   long  FirstModule;   /*   first module of this bin  */
   long  LastModule;   /*   last module of this bin  */
   long  FirstEta;   /*   first eta of this bin  */
   long  LastEta;   /*   last eta of this bin  */
   long  FirstSub;   /*   first sub division  */
   long  LastSub;   /*   last sub division  */
   long  MipFitAdcMin;   /*   first ADC to fit  */
   long  MipFitAdcMax;   /*   last ADC to fit  */
   float  MipFitParam[10];   /*   MIP fit parameters  */
   float  MipFitParamError[10];   /*   MIP fit parameters error  */
   float  MipFitCovMatrix[10][10];   /*   MIP fit covariance matrix  */
   float  MipFitChiSqr;   /*   MIP fit chi square  */
   float  MipPeakPosition;   /*   MIP peak position  */
   float  MipPeakPositionError;   /*   MIP peak position error  */
   float  MipPeakWidth;   /*   MIP peak width  */
   float  MipPeakWidthError;   /*   MIP peak width error  */

 };  
