/*    emcPed.idl
*
*  Table: emcPed
*
*       description: *    //:  Table which contains pedestal information for emctower ADCs
*/ 


struct emcPed { 

   octet  Status[4800];   /*    status of the emc tower(0=problem, 1=ok)  */
   short  AdcPedestal[4800];   /*    ADC pedestal of emc tower x 100  */
   short  AdcPedestalRMS[4800];   /*    ADC pedestal RMS of emc tower x 100  */
   float  ChiSquare[4800]; /* chi square of Pedestal fit */
 };  
