/*    emcPedestal.idl
*
*  Table: emcPedestal
*
*       description: *    //:  Table which contains pedestal information for emctower ADCs
*/ 


struct emcPedestal { 

   long  Status;   /*    status of the emc tower(0=problem, 1=ok)  */
   float  AdcPedestal;   /*    ADC pedestal of emc tower  */
   float  AdcPedestalRMS;   /*    ADC pedestal RMS of emc tower  */

 };  
