/*    emcSampFracP2.idl
*
*  Table: emcSampFracP2
*
*       description: //  Emc Sampling Fraction polynomial of degree 2 parametrization
*/ 


struct emcSampFracP2 { 

   float  p0;   /*   None  : parameters  */
   float  p1;   /*   None  : parameters  */
   float  p2;   /*   None  : parameters  */

 };  
