/*    emcSampFracMSU.idl
*
*  Table: emcSampFracMSU
*
*       description: //  Emc Sampling Fraction parametrization by MSU
*/ 


struct emcSampFracMSU { 

   float  constant;   /*   None  : parameters  */
   float  a;   /*   None  : parameters  */
   float  b;   /*   None  : parameters  */
   float  last_tower;   /*   None  : parameters  */

 };  
