/*    emcTriggerLUT.idl
*
*  Table: emcTriggerLUT
*
*       description: //   BEMC trigger LUT
*/ 


struct emcTriggerLUT { 

   unsigned long  FormulaTag[30][10];   /* Specifies which formula to use for calculating LUT  */
   unsigned long  FormulaParameter0[30][10];   /* parameter for that formula   */
   unsigned long  FormulaParameter1[30][10];   /* parameter for that formula   */
   unsigned long  FormulaParameter2[30][10];   /* parameter for that formula   */
   unsigned long  FormulaParameter3[30][10];   /* parameter for that formula   */
   unsigned long  FormulaParameter4[30][10];   /* parameter for that formula   */
   unsigned long  FormulaParameter5[30][10];   /* parameter for that formula   */

 };  

