/*    emcTriggerPed.idl
*
*  Table: emcTriggerPed
*
*       description: //   BEMC trigger Pedestal
*/ 


struct emcTriggerPed { 

   unsigned long  PedShift;   /*   */
   unsigned long  BitConversionMode[30][10];   /*   */
   unsigned long  Ped[30][160];   /*   */

 };  

