/*    epdQTMap.idl
*
*  Table: epdQTMap
*
*       description: //  EPD QT map
*/ 

struct epdQTMap { 
  unsigned short ew[744]; /* ew=0 East EPD, ew=1 West EPD */
  unsigned short pp[744]; /*pp=1-12, SuperSector number */
  unsigned short tile[744]; /* tile=1-31, tile number in a super sector*/
  short qt_board_adc[744]; /* ADC channle adddress, -1 for non existing channels*/
  short qt_channel_adc[744]; /* qt_channel_adc=1-32, -1 for non existing channels*/
  short qt_board_tac[744]; /* TAC channle adddress, -1 for non existing channels*/
  short qt_channel_tac[744]; /* qt_channel_tac=1-32, -1 for non existing channels*/
};
