/* etofSimEfficiency.idl
*
* table: etofSimEfficiency
*
* description: efficiency for hit creation in etof counters
*
*
* author: Florian Seck ( TU Darmstadt )
*
*/

struct etofSimEfficiency {
	float  efficiency[108];  /* hit creation efficiency in each counter */
};
