/* etofDigiTimeCorr.idl
*
* table: etofDigiTimeCorr
*
* description: correction parameter to be applied to each channel
*              on the digi level
*
* author: Florian Seck ( TU Darmstadt )
*
*/

struct etofDigiTimeCorr {
	float  timeCorr[6912];  /* time offset correction for etof digis */
};
