/* etofGeomAlign.idl
*
* table: etofGeomAlign
*
* description: geometry alignment parameters ( offset in localX, localY, localZ,
*              rotations in XY, XZ, YZ planes) of each etof module
*
* author: Florian Seck ( TU Darmstadt )
*
*/

struct etofGeomAlign {
	float  offsetX[36];  /* offset in local X (cm) */
	float  offsetY[36];  /* offset in local Y (cm) */
	float  offsetZ[36];  /* offset in local Z (cm) */
	float  angleXY[36];  /* rotation in local XY plane */
	float  angleXZ[36];  /* rotation in local XZ plane */
	float  angleYZ[36];  /* rotation in local YZ plane */
};
