/* etofMatchParam.idl
*
* table: etofMatchParam
*
* description: parameters used in the etof matchmaker
*
*
* author: Florian Seck ( TU Darmstadt )
*
*/

struct etofMatchParam {
	float  matchRadius;         /* maximum distance etof hit to track intersection */
	octet  trackCutNHitsFit;    /* track cut nHitsFit in TPC */
	float  trackCutNHitsRatio;  /* track cut nHitsFit to nHitsPoss ratio in TPC */
	float  trackCutLowPt;       /* track cut low pt */
};
