/* etofPulserTotPeak.idl
*
* table: etofPulserTotPeak
*
* description: parameters for ToT used to find the pulsers in the events
*
* author: Florian Seck ( TU Darmstadt )
*
*/

struct etofPulserTotPeak {
	octet pulserTot[216]; /*ToT peak position (bin: 0-255) of pulsers per side*/
};

