/* etofSignalVelocity.idl
*
* table: etofSignalVelocity
*
* description: calibration parameters of signal velocity
*              of etof counters
*
* author: Florian Seck ( TU Darmstadt )
*
*/

struct etofSignalVelocity {
	float  signalVelocity[108];  /* signal velocity of each counter  */
};
