/* etofPulserTimeDiffGbtx.idl
*
* table: etofPulserTimeDiffGbtx
*
* description: time difference of pulsers within one Gbtx
*                    (used to correct for missing pulsers)
*
* author: Florian Seck ( TU Darmstadt )
*
*/

struct etofPulserTimeDiffGbtx{
	float  pulserTimeDiffGbtx[144];  /* time difference between counters within one Gbtx */
};

