/*    fcsDetectorPosition.idl
 *
 *  Table: fcsDetectorPosition
 *
 *       description: // FCS Detector Position each [det=0~3]
 *                       det: 0=EcalN, 1=EcalS, 2=HcalN, 3=HcalS
 */ 

struct fcsDetectorPosition {   
    float xoff[4];   /* x offset [cm] from beam to front of near beam corner */
    float yoff[4];   /* y offset [cm] from beam to detector center */
    float zoff[4];   /* z offset [cm] from IR to front of near beam corner */
};  
