/*    fcsEcalGain.idl
 *
 *  Table: fcsEcalGain
 *
 *       description: // FCS ECal gain
 *                       energy[GeV] = adc[ch] * gain[GeV/ch] * gaincorr[]
 */ 

struct fcsEcalGain {   
  float gain[1486];     /* gain 2*748 */
};  
