/*    fcsEcalGainCorr.idl
 *
 *  Table: fcsEcalGainCorr
 *
 *       description: // FCS ECal gain correction
 *                       energy[GeV] = adc[ch] * gain[GeV/ch] * gainCorr[]
 */ 

struct fcsEcalGainCorr {   
  float gaincorr[1486];     /* gaincorr 2*748 */
};  
