/*    fcsHcalGain.idl
 *
 *  Table: fcsHcalGain
 *
 *       description: // FCS HCal gain
 *                       energy[GeV] = adc[ch] * gain[GeV/ch] * gaincorr[]
 */ 

struct fcsHcalGain {   
  float gain[520];     /* gain 2*260 */
};  
