/*    fcsHcalGainCorr.idl
 *
 *  Table: fcsHcalGainCorr
 *
 *       description: // FCS HCal gain correction
 *                       energy[GeV] = adc[ch] * gain[GeV/ch] * gaincorr[]
 */ 

struct fcsHcalGainCorr {   
  float gaincorr[520];     /* gaincorr 2*260 */
};  
