/*    fcsPresGain.idl
 *
 *  Table: fcsPresGain
 *
 *       description: // FCS Pres gain for single MIP peak
 *                       MIP[] = adc[ch] * gain[MIP/ch]
 */ 

struct fcsPresGain {   
  float gain[384];     /* gain 2*192 */
};  
