/*    fcsPresValley.idl
 *
 *  Table: fcsPresValley
 *
 *  description: // FCS Pres Valley in [MIP], should be around ~0.5 and cut here for hit/no hit
 */ 

struct fcsPresValley {   
  float valley[384];     /* valley position 2*192 */
};  
