/* fgtAlignment.idl
* Table: fgtAlignment
*
* description:
*    Allows for fixed rotation of each quadrant WRT STAR xyz
*    Index for phi, theta, phi = 4*n_disks + n_quads
*    Index for xoff, yoff, zoff = 4*n_disks + n_quads
*    n_disks runs from 0 - 5
*    n_quads runs form 0 - 3
*
*/

struct fgtAlignment
{
	double phi[24];
	double theta[24];
	double psi[24];
	double xoff[24];
	double yoff[24];
	double zoff[24];
};