/*    fgtElosCutoff.idl
*
*  Table:  fgtElosCutoff
*
*       description: //:  cutoff channel of FGT active volume energy loss  used to reject very high and unrealistic loss value
*/ 


struct fgtElosCutoff { 

   double  cutoff[10000];   /* cutoff channel of FGT active volume energy loss */
   char    comment[192];    /* comment */

 };
