/*    fgtGain.idl
*
*  Table: fgtGain
*
*       description: //:  Table which contains gain correction information
*/ 


struct fgtGain { 

   double  Gain[51200];   /*   Gain Variation  */
   octet  Status[51200];   /*   status of the channel (0=problem, 1=ok)  */

 };  
