/*    fgtPedestal.idl
*
*  Table: fgtPedestal
*
*       description: *    //:  Table which contains pedestal information for FGT
*/ 


struct fgtPedestal { 

   double  AdcPedestal[51200];   /*    ADC pedestal  */
   double  AdcPedestalRMS[51200];   /*    ADC pedestal RMS */
   octet  Status[51200];   /*    Status (0=problem, 1=ok)  */

 };  
