/*    fgtStatus.idl
*
*  Table: fgtStatus
*
*       description: //   fgt channel status
*/ 


struct fgtStatus { 

   octet  Status[51200];   /* channel status: 0 = OK, 1 = OFF, 2 = Not Installed, 3 = noisy..  */

 };  
