/*    fgtSimuParams.idl
*
*  Table: fgtSimuParams
*
*       description:  
*/

struct fgtSimuParams {
	double  param[100];    /* assorted params controlling fgt-slow simulator */
	char    comment[192];  /* description of the parameters */
};

