/*    fmsGeometry.idl
*
*  Table: fmsGeometry
*
*       description: //  FPD & FMS & FHC detector geometry
*/ 

/* Detector Name   detectorId  ew  ns  type   nX   nY  */
/* FPD-North            0       0   0   0      7    7  */
/* FPD-South            1       0   1   0      7    7  */
/* FPD-North-Pres       2       0   0   1      7    1  */
/* FPD-South-Pres       3       0   1   1      7    1  */
/* FPD-North-SMDV       4       0   0   2     48    1  */
/* FPD-South-SMDV       5       0   1   2     48    1  */
/* FPD-North-SMDH       6       0   0   3      1   48  */
/* FPD-South-SMDH       7       0   1   3      1   48  */
/* FMS-North-Large      8       1   0   4     17   34  */
/* FMS-South-Large      9       1   1   4     17   34  */
/* FMS-North-Small     10       1   0   4     12   24  */
/* FMS-South-Small     11       1   1   4     12   24  */
/* FHC-North           12       1   0   5      9   12  */
/* FHC-South           13       1   1   5      9   12  */

struct fmsChannelGeometry { 
  octet detectorId;   /* detector Id */
  octet type;         /* 0=SmallCell,1=Preshower,2=SMD-V,3=SMD-H,4=LargeCell,5=HadronCal */
  octet ew;           /* 0=east, 1=west */
  octet ns;           /* 0=north, 1=south */
  octet nX;           /* # of columns, max_channel is nX*nY */
  octet nY;           /* # of rows,    max_channel is nX*nY */
};  


