/*    fmsPosition.idl
*
*  Table: fmsPosition
*
*       description: //  FPD & FMS & FHC detector width and positions
*/ 

struct fmsDetectorPosition { 
  octet detectorId;   /* detector Id */
  float xwidth;       /* x width */
  float ywidth;       /* y width */
  float xoffset;      /* xoffset from beam line to inner edge of detector */
  float yoffset;      /* yoffset from beam line to center of detector */
  float zoffset;      /* z position where we measure x,y */
};  
