/*    fmsGainCorrection.idl
*
*  Table: fmsGainCorrection
*
*       description: // FMS & FPD detector gain correction
*                       energy(GeV) = adc(ch) * gain(GeV/ch) * gaincorrection
*/ 

struct fmsGainCorrection {   
  octet detectorId;     /* DetectorId */
  unsigned short ch;    /* Ch 1-578*/
  float corr;           /* gain correction factor */
};  
