struct fmsLedRef { 
  float  adc_ln[578]; /* LED ADC value Large North */
  float  err_ln[578]; /* LED uncertainty Large North */
  float  adc_ls[578]; // Large South
  float  err_ls[578];
  float  adc_sn[288]; // Small North
  float  err_sn[288];
  float  adc_ss[288]; // Small South
  float  err_ss[288];
 };  
