/*    fmsPatchPanelMap.idl
*
*  Table: fmsPatchPanelMap
*
*       description: //  FMS detector to patch panel map
*/ 

/* module 1=North Large, 2=South Large, 3=North Small ,4=South Small => moduleIDs */

struct fmsPatchPanelMap { 
  
  /* channel# 1-548 for L and 1-288 for S*/
  octet  ppPanel[548];    /* panel# 1-2 */
  octet  ppRow[548];      /* row# 1-20 */
  octet  ppColumn[548];   /* column# 1-16 */

};  
