struct fmsPi0Mass {
  float  mass_ln[578]; /* Reconstructed pi0 mass Large North */
  float  err_ln[578];  /* Mass uncertainty Large North */
  float  mass_ls[578]; // Large South
  float  err_ls[578];
  float  mass_sn[288]; // Small North
  float  err_sn[288];
  float  mass_ss[288]; // Small South
  float  err_ss[288];
};
