/*    fmsQTMap.idl
*
*  Table: fmsQTMap
*
*       description: //  FMS patch panel to QT map
*/ 

/* north=1/south=2 => sideIDs */

struct fmsQTMap { 
  /* panel# 1-2 */
  /* row# 1-20 */
  /* column# 1-16 */
  octet  qtCrate[2][20][16];    /* QT crate# 1-4 */
  octet  qtSlot[2][20][16];     /* QT slot# 1-16 */
  octet  qtChannel[2][20][16];  /* QT channel# 0-31 */
};  
