/*    fmsRec.idl
*
*  Table: fmsRec
*
*       description: // FMS reconstruction parameters
*
*/

struct fmsRec {

    //the following numbers are used by StFmsPointMaker::isValidChannel()
    //to define detector boundaries
    //row/column lower limit
    unsigned short ROW_LOW_LIMIT;
    unsigned short COL_LOW_LIMIT;
    //central hole in large cells
    float CEN_ROW_LRG;
    unsigned short CEN_ROW_WIDTH_LRG;
    unsigned short CEN_UPPER_COL_LRG;
    //central hole in small cells
    float CEN_ROW_SML;
    unsigned short CEN_ROW_WIDTH_SML;
    unsigned short CEN_UPPER_COL_SML;
    //cuts off 7x7 triangle from the corners
    float CORNER_ROW;
    float CORNER_LOW_COL;

    //the following are used for cluster/point id encodings
    //in case the parent cluster of a point cannot be accessed
    //by TRef
    unsigned short CLUSTER_BASE;
    unsigned short CLUSTER_ID_FACTOR_DET;

    //the following are used by StFmsEventClusterer
    unsigned short TOTAL_TOWERS;
    float PEAK_TOWER_FACTOR;
    float TOWER_E_THRESHOLD;
    float BAD_2PH_CHI2;
    float BAD_MIN_E_LRG;
    float BAD_MAX_TOW_LRG;
    float BAD_MIN_E_SML;
    float BAD_MAX_TOW_SML;
    float VALID_FT;
    float VALID_2ND_FT;
    float VALID_E_OWN;

    //these are parameters of the shower shape
    float SS_C;
    float SS_A1;
    float SS_A2;
    float SS_A3;
    float SS_B1;
    float SS_B2;
    float SS_B3;

    //empirical cuts used by StFmsClusterFinder::categorise()
    unsigned short CAT_NTOWERS_PH1;
    float CAT_EP1_PH2;
    float CAT_EP0_PH2;
    float CAT_SIGMAMAX_MIN_PH2;
    float CAT_EP1_PH1;
    float CAT_EP0_PH1;
    float CAT_SIGMAMAX_MAX_PH1;

    //the following numbers are used by StFmsEventClusterer::OnePhotonFitParameters
    float PH1_START_NPH;
    float PH1_DELTA_N;
    float PH1_DELTA_X;
    float PH1_DELTA_Y;
    float PH1_DELTA_E;

    //these are used by StFmsEventClusterer::TwoPhotonFitParameters
    unsigned short PH2_START_NPH;
    float PH2_START_FSIGMAMAX;
    float PH2_RAN_LOW;
    float PH2_RAN_HIGH;
    float PH2_STEP_0;
    float PH2_STEP_1;
    float PH2_STEP_2;
    float PH2_STEP_3;
    float PH2_STEP_4;
    float PH2_STEP_5;
    float PH2_STEP_6;
    float PH2_MAXTHETA_F;
    float PH2_LOWER_NPH;
    float PH2_LOWER_XF;
    float PH2_LOWER_YF;
    float PH2_LOWER_XMAX_F;
    float PH2_LOWER_XMAX_POW;
    float PH2_LOWER_XMAX_LIMIT;
    float PH2_LOWER_5_F;
    float PH2_LOWER_6_F;
    float PH2_UPPER_NPH;
    float PH2_UPPER_XF;
    float PH2_UPPER_YF;
    float PH2_UPPER_XMIN_F;
    float PH2_UPPER_XMIN_P0;
    float PH2_UPPER_XMIN_LIMIT;
    float PH2_UPPER_5_F;
    float PH2_UPPER_6_F;
    float PH2_3_LIMIT_LOWER;
    float PH2_3_LIMIT_UPPER;

    //StFmsEventClusterer::GlobalPhotonFitParameters
    float GL_LOWER_1;
    float GL_UPPER_DELTA_MAXN;
    float GL_0_DLOWER;
    float GL_0_DUPPER;
    float GL_1_DLOWER;
    float GL_1_DUPPER;
    float GL_2_DLOWER;
    float GL_2_DUPPER;
};
