/*    fpostGain.idl
*
*  Table: fpostGain
*
*       description: //  FPOST MIP position in ch
*/ 

struct fpostGain { 
  unsigned short slatid; /* 0-240: slat Id */
  float MIP; /* Single MIP ADC ch */ 
};  
