/*    fpostPed.idl
*
*  Table: fpostPed
*
*       description: //  FPOST pedestal
*/ 

struct fpostPed {
	unsigned short slatid; /* 0-240: slat Id */
	float Mean; /* Mean of Gaussian Fit for ADC [ch] */
	float Sigma; /* Sigma of Guassian Fit for ADC [ch] */
};

