/*    fpostPosition.idl
*
*  Table: fpostPosition
*
*       description: //  FPOST detector width and position
*/ 

struct fpostPosition {
  unsigned short slatid; /* 0-240: slat Id */
  float length; /* length ( Depends on S1,S2,etc. cm) */
  float width; /* width (5 cm) */
  float thickness; /* thickness (1 cm) */
  float angle_xy; /* angle in the xy measured with resp. to the pos x-axis (45 South, 135 North)*/
  float xoffset; /* xoffset from beam line to center of detector (cm) */
  float yoffset; /* yoffset from beam line to center of detector (cm) */
  float zoffset; /* z position from IR (cm) */ 
};
