/*    fpostMap.idl
*
*  Table: fpostMap
*
*       description: //  FPOST QT map
*/ 

struct fpostMap { 
  unsigned short slatid; /* 0-240: slat Id */
  short QTaddr; /* 0-7 : QT Address */
  short QTch; /* 0-31 : QT channel */ 
};  
