/*    fpostSlatId.idl
*
*  Table: fpostSlatId
*
*       description: //  FPOST slat Id
*/ 

struct fpostSlatId { 
  unsigned short slatid; /* 0-240: slat Id */
  unsigned short quad; /* 1-2, 0 for none-exsistant slat */
  unsigned short layer; /* 1-6, 0 for none-exsistant slat */
  unsigned short slat; /* 1-43, 0 for none-exsistant slat */ 
};  

