/*    fpsConstant.idl
*
*  Table: fpsConstant
*
*       description: //  FPS constants
*/ 

struct fpsConstant { 
  unsigned short nQuad;        /*  4 */
  unsigned short nLayer;       /*  3 */
  unsigned short maxSlat;      /* 21 */
  unsigned short maxQTaddr;    /*  8 */
  unsigned short maxQTch;      /* 32 */
};  
