/*    fpsChannelGeometry.idl
*
*  Table: fpsChannelGeometry
*
*       description: //  FPS number of slats for each quad & layer
*/ 

struct fpsChannelGeometry { 
  unsigned short quad;         /* 1=Q1(South Top), 2=Q2(South Bottom),3=Q3(North Top), 4=Q4(North Bottom) */
  unsigned short layer;        /* 1=layer1, 2=layer2, 3=layer3 */
  unsigned short nslat;        /* # of slat (19,20 or 21) */
};  
