/*    fpsMap.idl
*
*  Table: fpsMap
*
*       description: //  FPS QT map
*/ 

struct fpsMap { 
  octet slatid;       /* 0-251: slat Id = (quad-1)*nLayer*maxSlat + (layer-1)*maxSlat + (slat-1)*/
  octet QTaddr;       /* 0-7 : QT Address */
  octet QTch;         /* 0-31 : QT channel  */
};  
