/*    fpsPosition.idl
*
*  Table: fpsPosition
*
*       description: //  FPS detector width and position
*/ 

struct fpsPosition {
  unsigned short slatid; /* 0-251: slat Id = (quad-1)*nLayer*maxSlat + (layer-1)*maxSlat + (slat-1)*/
  float xwidth;       /* x width (cm) */
  float ywidth;       /* y width (cm) */
  float zwidth;       /* z width/thickness (cm) */
  float xoffset;      /* xoffset from beam line to cetner of detector (cm) */
  float yoffset;      /* yoffset from beam line to center of detector (cm) */
  float zoffset;      /* z position from IR (cm) */
};
