/*    fpsPed.idl
*
*  Table: fpsPed
*
*       description: //  FPS pedestal
*/ 

struct fpsPed {
	unsigned short slatid; /* 0-251: slat Id = (quad-1)*nLayer*maxSlat + (layer-1)*maxSlat + (slat-1) */
	float Mean; /* Mean of Gaussian Fit for ADC [ch] */
	float Sigma; /* Sigma of Guassian Fit for ADC [ch] */
};

