/*    ftpcDriftField.idl
*
*  Table: ftpcDriftField
*
*       description: //    FTPC drift field
*/ 


struct ftpcDriftField { 

   long   numberOfEFieldBinsUsed;    /* number of electric field bins used    */
   long   maximumNumberOfEFieldBins; /* maximum number of electric field bins */

   float  driftCathodeVoltage;      /* in kV                                  */
   float  minimumDriftField;        /* smallest drift field in drift map      */
   float  stepSizeDriftField;       /* step size for drift field              */
   float  radiusTimesField;         /* v(r)/ln(r(a)/r(i)), 7365.1 V           */

 };  
