/*    ftpcVoltage.idl
*
*  Table: ftpcVoltage
*
*       description:
*/ 


struct ftpcVoltage { 

   unsigned long  runNumber;   /*   */
   double  cathodeVEast;   /*   */
   double  cathodeVWest;   /*   */
   double  anodeV1East;   /*   */
   double  anodeV2East;   /*   */
   double  anodeV3East;   /*   */
   double  anodeV4East;   /*   */
   double  anodeV5East;   /*   */
   double  anodeV6East;   /*   */
   double  anodeV1West;   /*   */
   double  anodeV2West;   /*   */
   double  anodeV3West;   /*   */
   double  anodeV4West;   /*   */
   double  anodeV5West;   /*   */
   double  anodeV6West;   /*   */

 };  
