/*    ftpcFastSimGas.idl
*
*  Table: ftpcFastSimGas
*
*       description: //    FTPC Fast Simulator gas parameters
*
*/
   struct ftpcFastSimGas {
      long orderOfFastEstimates;         /* number of P3-fit parameters */ 
      float driftVelocityEstimates[4];  /* parameters of a P3-fit of drift-velocity */
      float driftTimeEstimates[4];      /* parameters of a P3-fit of drift-time */
      float sigmaRadialEstimates[4];    /* parameters of a P3-fit of sigma(rad) */
      float sigmaAzimuthalEstimates[4]; /* parameters of a P3-fit of sigma(azi) */
      float errorRadialEstimates[4];    /* parameters of a P3-fit of radial error */
      float errorAzimuthalEstimates[4]; /* parameters of a P3-fit of azimuthal error */
   };
