/*    ftpcElectronics.idl
*
*  Table: ftpcElectronics
*
*       description:
*/ 


struct ftpcElectronics { 

   double  tZero;   /*   us (microseconds)  */
   double  uSecondsPerTimebin;   /*   us (microseconds)  */
   double  laserTZero;   /*   us (microseconds)  */

 };  
