/*    ftpcClusterGeom
*
*  Table: ftpcClusterGeom
*
*       description: //    FTPC Cluster Geometry values
*
*/
   struct ftpcClusterGeom {

     long minTimebin;                // min timebin for cluster search inner
     long minTimebinMed;             // min timebin for cluster search medium
     long minTimebinOut;             // min timebin for cluster search out
     long maxTimelength;             // max timelength of cluster inner
     long maxTimelengthMed;          // max timelength of cluster medium 
     long maxTimelengthOut;          // max timelength of cluster out
     long maxPadlength;              // max padlength of cluster inner
     long maxPadlengthMed;           // max padlength of cluster medium
     long maxPadlengthOut;           // max padlength of cluster out
     long deltaTime;                 // width of unfolding window in time
     long deltaPad;                  // width of unfolding window in pad 
     float minChargeWindow;          // minimum charge to make hit in search window
   };
