/*    ftpcElectronics.idl
*
*  Table: ftpcElectronics
*
*       description:
*/ 


struct ftpcElectronics { 

   double  tZero;   /*   us (microseconds)  */
   double  uSecondsPerTimebin;   /*   us (microseconds)  */
   double  laserTZero;   /*   us (microseconds)  */
   short   swapRDO6RDO7East; /* = 1 if RDO6 and RDO7 in Ftpc East should be swapped */
                             /* during Run 10 it was discovered that the RDO6,RDO7  */
                             /* cables in Ftpc East were exchanged. Run 11070033    */
                             /* (2010-03-11) is the last run with swapped cables    */

 };  
