/*    ftpcDriftMap.idl
*
*  Table: ftpcDriftMap
*
*       description: //    FTPC Drift Map calculated by StDriftMapMaker
*/ 


struct ftpcDriftMap { 

   float  e;   /*   electric field for this bin  */
   float  v[10];   /*   vdrift for this padrow, e-field  */
   float  psi[10];   /*   deflection angle for this padrow, e-field  */
   float  dv_dp[10];   /*   dvdrift/dpressure(normalized)  */
   float  dpsi_dp[10];   /*   dphi/dpressure(normalized)  */

 };  
