/*    ftpcAmpOffset.idl
*
*  Table: ftpcAmpOffset
*
*       description: //   FTPC detector calibration amplitude offset table
*/ 


struct ftpcAmpOffset { 

   float  offset[960];   /*   amplitude offset for this pad  */

 };  
