/*    ftpcTrackingPars.idl
*
*  Table: ftpcTrackingPars
*
*       description: //    FTPC Tracking parameters
*                          See StRoot/StFtpcTrackMaker/,
*                          (especially StFtpcConfMapper.cc) 
*                          for detailed instructions.
* 
*/
   struct ftpcTrackingPars {

     /* Vertex position 
      */
     float maxVertexPosZWarning;
     float maxVertexPosZError;

     /* Vertex reconstruction 
      */
      long histoBins;
     float histoMin;
     float histoMax;
     float maxDcaVertex; 
      long minNumTracks;
     
     /* Tracker 
      */
     long rowSegments;
     long phiSegments;
     long etaSegments;
     
     /* Tracking 
      * the 4 indizes represent: 0: main vertex tracking                        
      *	                         1: non vertex tracking
      *                          2: no field tracking
      *                          3: laser tracking       
      */
      long laser[4];             /* to switch on laser tracking (was of type bool before)    */
      long vertexConstraint[4];  /* to switch on vertex constraint (was of type bool before) */
      long maxTrackletLength[4];
      long minTrackLength[4];
      long rowScopeTracklet[4];
      long rowScopeTrack[4];
      long phiScope[4];
      long etaScope[4];
     float maxDca[4];
     
     /* Tracklets 
      */
     float maxAngleTracklet[4];
     
     /* Tracks 
      */
     float maxAngleTrack[4];
     float maxCircleDist[4];
     float maxLengthDist[4];
     
     /* Split tracks 
      */
     float maxDist;
     float minPointRatio;
     float maxPointRatio;     
   };
