/*    ftpcGas.idl
*
*  Table: ftpcGas
*
*       description: //    FTPC gas measurements
*/ 


struct ftpcGas { 

   float  percentAr;                /*   */
   float  percentCO2;               /*   */
   float  percentNe;                /*   */
   float  percentHe;                /*   */
   float  gasGain;                  /*   */
   float  gasAttenuation;           /* [1/cm] */
   float  gasIonizationPotential;   /* [eV] */
   float  baseTemperature;          /* degree Centigrade */
   float  basePressure;             /* Torr  */
   float  pressureOffset;           /* Torr  */
   float  temperatureDifference;    /* gas temperature difference FTPC West-Eastin degree Centigrade */

 };  
