/*    ftpcFastSimPars.idl
*
*  Table: ftpcFastSimPars
*
*       description: //    FTPC Fast Simulator code parameters
*/
   struct ftpcFastSimPars {
       long  ftpcWestGeantVolumeId        ; /* GEANT volume id for FTPC west  */
       long  ftpcEastGeantVolumeId        ; /* GEANT volume id for FTPC east  */
       long  unfoldedClusterFlag          ; /* unfolded cluster bit number */
       long  badShapeClusterFlag          ; /* bad shape cluster bit number */
       long  mergedClusterFlag            ; /* merged cluster bit number */
       long  numberOfPadsDedxSmearing     ; /* number of pads used for de/dx smearing  */
       long  numberOfBinsDedxSmearing     ; /* number of bins used for de/dx smearing  */
       float radiusTolerance              ; /* tolerance used for radius check  */
       float sigmaSpacingFactor           ; /* sigma spacing factor  */
       float adcConversionFactor          ; /* convert GEANT energy loss to adc counts */
       float clusterChargeConversionFactor; /* convert adc counts to charge  */
   };
