/*    ftpcAmpSlope.idl
*
*  Table: ftpcAmpSlope
*
*       description: //   FTPC detector calibration amplitude slope table
*/ 


struct ftpcAmpSlope { 

   float  slope[960];   /*   amplitude slope for this pad  */

 };  
