/*    ftpcDimensions.idl
*
*  Table: ftpcDimensions
*
*       description: //    FTPC dimensions
*/ 


struct ftpcDimensions { 

   long  totalNumberOfPadrows;         /*   total number of padrows                               */
   long  numberOfPadrowsPerSide;       /*   number of padrows in one FTPC                         */
   long  firstPadrowToSearch;          /*   first active padrow                                   */
   long  lastPadrowToSearch;           /*   last active pad row                                   */
   long  numberOfSectorsPerPadrow;     /*   total number of sectors                               */
   long  firstSectorToSearch;          /*   first active sector                                   */
   long  lastSectorToSearch;           /*   last active sector                                    */
   long  phiOrigin;                    /*   phi angle of first sector                             */
   long  phiPerSector;                 /*   phi angle per sector                                  */
   long  numberOfPadsPerSector;        /*   number of pads per sector                             */
  float  padLength;                    /*   pad length in cm                                      */
  float  padPitch;                     /*   pad pitch in cm                                       */
  float  radiansPerPad;                /*   phi angle for each pad                                */
  float  radiansPerGap;                /*   phi angle of each sector gap                          */
   long  numberOfTimebinsPerSector;    /*   number of timebins per sector                         */
  float  sizeOfTimebin;                /*   size of timebin                                       */
  float  innerRadiusSensitiveVolume;   /*   inner radius of sensitive volume                      */
  float  outerRadiusSensitiveVolume;   /*   outer radius of sensitive volume                      */
  float  installationPointX[2];        /*   x-coord of installation point, [0] = east, [1] = west */ 
  float  installationPointY[2];        /*   y-coord of installation point, [0] = east, [1] = west */ 
  float  installationPointZ[2];        /*   z-coord of installation point, [0] = east, [1] = west */ 
};  
