/*    ftpcClusterPars
*
*  Table: ftpcClusterPars
*
*       description: //    FTPC Cluster Finder run and code parameters
*
*/
   struct ftpcClusterPars {
     // code parameters
     long gaussFittingFlags;        /* 0=no gaussfit, 1=pad gaussfit, */
                                    /* 2=time gaussfit, 3=all gaussfit */
     long minimumClusterMaxADC;     /* cluster minimum peakheight */
     long numberOfDriftSteps;       /* # of steps in drift map integration */
     long orderOfDiffusionErrors;   /* order of diffusion errors */
     float padDiffusionErrors[3];   /* point error[cm] in pad direction as */
                                    /* function of driftlength up to 2nd order*/
     float timeDiffusionErrors[3];  /* point error[cm] in time direction as */
                                    /* function of driftlength up to 2nd order*/
     float lorentzAngleFactor;      /* lorentz angle correction factor */
     float padBadFitError;          /* additional error for bad-fit clusters*/
     float timeBadFitError;         /* additional error for bad-fit clusters*/
     float padUnfoldError;          /* additional error for unfolded clusters*/
     float timeUnfoldError;         /* additional error for unfolded clusters*/
     float padFailedFitError;       /* additional error for failed-fit clusters*/
     float timeFailedFitError;      /* additional error for failed-fit clusters*/
     float padCutoffClusterError;   /* additional error for cut-off clusters*/
     float timeCutoffClusterError;  /* additional error for cut-off clusters*/
     float padSaturatedClusterError;       /* additional error for saturated clusters*/
     float timeSaturatedClusterError;      /* additional error for saturated clusters*/
     float twoPadWeightedError;     /* additional error 2-pad-cluster, weighted mean */
     float twoPadGaussError;        /* additional error 2-pad-cluster, gaussfit */
     float threePadWeightedError;   /* additional error 3-pad-cluster, weighted mean */
     float threePadGaussError;      /* additional error 3-pad-cluster, gaussfit */
     float zDirectionError;         /* parameter for error in z-direction */

     long maxNumSequences;           /* max number of used sequences (not used yet) */
     long maxNumSeqPeaks;            /* max number of peaks per sequence */
     long maxNumPeaks;               /* max number of unfolded peaks per cluster */
     long maxNumCUC;                 /* max number of cluster under construction (not used yet) */
     long maxLoops;                  /* max loopnumber in unfolding */
     long maxFastLoops;              /* max loopnumber in fast unfolding */ 
     float unfoldLimit;              /* accuracy of unfolding */
     float unfoldFailedLimit;        /* limit for failed unfolding */

     // run parameters
     float normalizedNowPressure;   /* normalized air pressure (in hPa) */
     float adjustedAirPressureWest;  /* temperature adjusted air pressure for FTPC West */
     float adjustedAirPressureEast;  /* temperature adjusted air pressure for FTPC East */
     float gasTemperatureWest;      /* temperature of gas in FTPC West */
     float gasTemperatureEast;      /* temperature of gas in FTPC East */
   };
