/*    ftpcGasSystem.idl
*
*  Table: ftpcGasSystem
*
*       description:
*/ 


struct ftpcGasSystem { 

   unsigned long  runNumber;   /*       run number  */
   unsigned long  timeOffset;   /*       eventtime  */
   double  westO2ppm;   /*   */
   double  westO2mv;   /*   */
   double  eastO2ppm;   /*   */
   double  eastO2mv;   /*   */
   double  extO2ppm;   /*   */
   double  extO2mv;   /*   */
   double  westH2Odp;   /*   */
   double  eastH2Odp;   /*   */
   double  flowAr;   /*   */
   double  flowCO2;   /*   */

 };  
