
/*    ftpcVoltageStatus.idl
*
*  Table: ftpcVoltageStatus
*
*       description:
*/ 


struct ftpcVoltageStatus { 

   unsigned long  runNumber;   /*   */
   unsigned long  startStatusTime;   /*   */
   unsigned long  endStatusTime;   /*   */
   unsigned long  statusWest;   /*   */
   unsigned long  statusEast;   /*   */

 };  
