/*    ftpcdVDriftdP.idl
*
*  Table: ftpcdVDriftdP
*
*       description: //    FTPC dVdrift/dPressure
*/ 


struct ftpcdVDriftdP { 

   float  dv_dp[11010];   /*   dvdrift/dpress per padrow, e-field bin */
                          /*   press norm at 20 degC,1013.25hPa       */

 };  
