/*      ftpcTemps.idl
*
*  Table:  ftpcTemps
*
*
*  Description: // Additional("extra") FTPC Body Temperatures
*      (laptop ->SlowContol)
*
*/

struct ftpcTemps {
			float extra1East; /*ftpc_t_ex_2_1.VAL*/
			float extra2East; /*ftpc_t_ex_2_2.VAL*/
			float extra3East; /*ftpc_t_ex_2_3.VAL*/
			float extra4East; /*ftpc_t_ex_2_4.VAL*/
			float extra5East; /*ftpc_t_ex_2_5.VAL*/
			float extra6East; /*ftpc_t_ex_2_6.VAL*/
			float extra7East; /*ftpc_t_ex_2_7.VAL*/
			float extra1West; /*ftpc_t_ex_1_1.VAL*/
			float extra2West; /*ftpc_t_ex_1_2.VAL*/
			float extra3West; /*ftpc_t_ex_1_3.VAL*/
			float extra4West; /*ftpc_t_ex_1_4.VAL*/
			float extra5West; /*ftpc_t_ex_1_5.VAL*/
			float extra6West; /*ftpc_t_ex_1_6.VAL*/
			float extra7West; /*ftpc_t_ex_1_7.VAL=0.0(not active*/
            };
