/*    ftpcSlowSimGas.idl
*
*  Table: ftpcSlowSimGas
*
*       description: //    FTPC Slow Simulator gas parameters
*
*/
   struct ftpcSlowSimGas {
      float electricField        ;  /* electric field strength */
      float driftVelocity        ;  /* drift velocity */
      float diffusionZ           ;  /* diffusion constant */
      float diffusionX           ;  /* diffusion constant */
      float diffusionY           ;  /* diffusion constant */
      float lorentzAngle         ;  /* lorentz angle of drift electrons */
   };
