/*    ftpcGasOut.idl
*
*  Table: ftpcGasOut
*
*       description:
*/ 


struct ftpcGasOut { 

   unsigned long  runNumber;   /*   run number  */
   double  gasOutEast;   /*   ftpcHDLCTemps.gasOut elementID = 1  */
   double  gasOutWest;   /*   ftpcHDLCTemps.gasOut elementID = 2  */
   double  body1East;   /*   ftpcHDLCTemps.body1  elementID = 1  */
   double  body1West;   /*   ftpcHDLCTemps.body1  elementID = 2  */
   double  body2East;   /*   ftpcHDLCTemps.body2  elementID = 1  */
   double  body2West;   /*   ftpcHDLCTemps.body2  elementID = 2  */
   double  body3East;   /*   ftpcHDLCTemps.body3  elementID = 1  */
   double  body3West;   /*   ftpcHDLCTemps.body3  elementID = 2  */
   double  body4East;   /*   ftpcHDLCTemps.body4  elementID = 1  */
   double  body4West;   /*   ftpcHDLCTemps.body4  elementID = 2  */

 };  
