/*    ftpcEField.idl
*
*  Table: ftpcEField
*
*       description: //    FTPC electric field
*/ 


struct ftpcEField { 

   long   numberOfEFieldBins;   /* number of electric field bins */

   float  e[761];               /*   electric field for each bin  */

 };  
