/*    ftpcDeflection.idl
*
*  Table: ftpcDeflection
*
*       description: //    FTPC deflection angle
*/ 


struct ftpcDeflection { 

   float  psi[11010];   /*   deflection angle for each padrow, e-field. both at 20 degC, 1013.25hPa  */

 };  
