/*    ftpcdDeflectiondP.idl
*
*  Table: ftpcdDeflectiondP
*
*       description: //    FTPC dpsi/dpressure
*/ 


struct ftpcdDeflectiondP { 

   float  dpsi_dp[11010];   /*   dpsi/dpress per padrow, e-field bin */
                            /*   press norm to 20 degC,1013.25hPa    */

 };  
