/*    ftpcGas.idl
*
*  Table: ftpcGas
*
*       description: //    FTPC gas measurements
*/ 


struct ftpcGas { 

   float  percentAr;                /*   */
   float  percentCO2;               /*   */
   float  percentNe;                /*   */
   float  percentHe;                /*   */
   float  gasGain;                  /*   */
   float  gasAttenuation;           /* [1/cm] */
   float  gasIonizationPotential;   /* [eV] */
   float  baseTemperature;          /* degree Centigrade */
   float  basePressure;             /* Torr  */
   float  pressureOffset;           /* Torr  */
   float  temperatureDifference;    /* gas temp diff between SVT high voltage off/on in degree C */
   float  defaultTemperatureWest;   /* default gas temperature for FTPC West */
   float  defaultTemperatureEast;   /* default gas temperature for FTPC East */
   float  minPressure;              /* minimum barometric pressure (in hPa) */
   float  maxPressure;              /* maximum barometric pressure (in hPa) */
   float minGasTemperature;         /* minimum gas temperature (in degree C) */
   float maxGasTemperature;         /* maximum gas temperature (in degree C) */
   float adjustAverageWest;         /* adjustment to FTPC West gas temperature calculated from laser analysis */
   float adjustAverageEast;         /* adjustment to FTPC East gas temperature calculated from laser analysis */
 };  
