/*    ftpcAsicMap.idl
*
*     Table: ftpcAsicMap
*
*     description:  FTPC ASIC mapping information
*
*/

struct ftpcAsicMap {
   short  EastIsInverted;            /* = 1 if the pads within a row are counted counter clockwise */
                                     /* looking in direction of the positive z-axis (west) */
                                     /* of the STAR coordinate system for FTPC East*/ 
   short  Asic2EastNotInverted;      /* = 1 if the second asic in FTPC east is not inverted */
                                     /* this error was discovered after the Y2001-2002 data taking */
                                     /* the error was correct before the Y2003 data taking started */
};
