/*    ftpcTimeOffset.idl
*
*  Table: ftpcTimeOffset
*
*       description: //    FTPC detector calibration time offset table
*/ 


struct ftpcTimeOffset { 

   float  offset[960];   /*   time offset for this pad  */

 };  
