/*    ftpcGasOut.idl
*
*  Table: ftpcGasOut
*
*       description:
*/ 


struct ftpcGasOut { 

   unsigned long  runNumber;   /*   run number  */
   double  gasOutEast;   /*   ftpcHDLCTemps.gasOut elementID = 1  */
   double  gasOutWest;   /*   ftpcHDLCTemps.gasOut elementID = 2  */

 };  
