/*    ftpcSlowSimPars.idl
*
*  Table: ftpcSlowSimPars
*
*       description: //    FTPC Slow Simulator code parameters
*/
   struct ftpcSlowSimPars {
       long randomNumberGenerator    ;  /* select random number generator */
       long zeroSuppressThreshold    ;  /* minimum ADC value  */
       long numSlowSimGridPoints     ;  /* number of drift grid points used */
       long maxAdc                   ;  /* maximum ADC value */
       long numGaussIntSteps         ;  /* number of gauss intergration steps */
       long diffusionCoarseness      ;  /* diffusion coarseness */
       
       float adcConversion           ;  /* 1000.0 electrons/adc value */
       float chamberCathodeVoltage   ;  /* drift cathode voltage */
       float sigmaPadResponseFuntion ;  /* pad-response-function sigma in um */
       float shaperTime              ;  /* shaper time in ns */ 
       float slowSimPressure         ;  /* atmospheric pressure in hPa */
   };
