/*    HitError.idl
*
* Table: HitError
* Description: Collection of parameters used to calculate hit errors.
* There should be one such parameter set for each detector. Some detectors, such
* as the TPC may have more.
*
* coeff[6] : a list of 6 coefficients which meaning changes for each detector.
*
* There are two instances of this struct for the TPC i.e. one for the inner and outer sectors.
*/ 
	

struct HitError 
{ 
  double coeff[6];/***/
};  
