/*    HitError.idl
*
* Table: HitError
* Description: Collection of parameters used to calculate hit errors.
* There should be one such parameter set for each detector. Some detectors, such
* as the TPC may have more.
*
  coeff[6] : a list of 6 coefficients which meaning changes for each detector
  For TPC coeff is in  cm^2 and 
  there are two instances of this struct i.e. one for the inner and outer sectors.
  coeff[0] =>  Intrinsic resolution, padrow direction
  coeff[1] =>  Drift dependent resolution, padrow direction
  coeff[2] =>  angular wire dependent resolution, padrow direction
  coeff[3] =>  Intrinsic resolution, z direction
  coeff[4] =>  Drift dependent resolution, z direction
  coeff[5] =>  angular wire dependent resolution, z direction
*/ 

struct HitError 
{ 
  double coeff[6];/***/
};  
