/* istControl.idl
*
*  Table: istControl
*
*  description: Control parameters for the IST
* 
*/

struct istControl {
  float kIstChanMaxRmsNoiseLevel;	// maximum rms noise level marked as regular channel
  float kIstChanMinRmsNoiseLevel;       // minimum rms noise level marked as regular channel
  float kIstApvMaxCmNoiseLevel;		// maximum common mode noise level marked as regular chip
  float kIstPedCutDefault;		// pedestal cut for pedestal calculation: default value 3.0
  float kIstHitCutDefault;		// hit S/N cut: default value 5.0
  float kIstCMNCutDefault;		// common mode noise cut for CMN calculation: default value 3.0
  unsigned short kIstMinNumOfRawHits;	// min number of raw hits per event over a ladder area
  unsigned short kIstMaxNumOfRawHits;	// max number of raw hits per event over a ladder area
  octet kIstAlldata;			// all data
  octet kIstADCdata;			// non-ZS data
  octet kIstZSdata;			// ZS data
  octet kIstDefaultTimeBin;		// default maximum ADC time bin index
};
