/* istChipConfig.idl
*
* Table: istChipConfig
*
* description: IST chip configuration status for 864 APV chips
*
*/

struct istChipConfig {
    long run;             
    octet s[864];   /* 0 good status; 1 permanently dead; 2 mis-configured; 3-255 reserved. */
};
