/* istPedNoise.idl
*
* Table: istPedNoise
*
* description: IST detector channel pedestal, rms noise and common mode noise
*
*/
struct istPedNoise {
    unsigned short cmNoise[864];         /* 100 * cm noise in ADC counts per chip      */
    unsigned short pedestal[110592];     /* pedestal in ADC counts per channel   */
    unsigned short rmsNoise[110592];     /* 100 * rms noise in ADC counts per channel  */
};
