//:Description: Survey data
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  iTPCSurvey.time.C:
//:iTPC survey measurements J.Thomas, 04/20/2018
struct iTPCSurvey {
  long   Id;
  float  Angle; 
  float  dx;
  float  dy;
  float  ScaleX;
  float  ScaleY;
  char   comment[32];
};
