/*    itpcPadPlanes.idl
*
*  Table: itpcPadPlanes
*
*       description:
*/ 


struct itpcPadPlanes { 

   long  padRows;   /*   */
   long  innerPadRows;   /*   */
   long  innerPadRows48;   /*   */
   long  innerPadRows52;   /*   */
   long  outerPadRows;   /*   */
   long  superInnerPadRows;   /*   */
   long  superOuterPadRows;   /*   */
   double  innerSectorPadWidth;   /*   */
   double  innerSectorPadLength;   /*   */
   double  innerSectorPadPitch;   /*   */
   double  innerSectorRowPitch1;   /*   */
   double  innerSectorRowPitch2;   /*   */
   double  firstPadRow;   /*   */
   double  firstOuterSectorPadRow;   /*   */
   double  lastOuterSectorPadRow;   /*   */
   double  firstRowWidth;   /*   */
   double  lastRowWidth;   /*   */
   double  outerSectorPadWidth;   /*   */
   double  outerSectorPadLength;   /*   */
   double  outerSectorPadPitch;   /*   */
   double  outerSectorRowPitch;   /*   */
   double  outerSectorLength;   /*   */
   double  ioSectorSeparation;   /*   */
   double  innerSectorEdge;   /*   */
   double  outerSectorEdge;   /*   */
   double  innerSectorPadPlaneZ;   /*   */
   double  outerSectorPadPlaneZ;   /*   */
   long  innerPadsPerRow[40];   /*   */
   long  outerPadsPerRow[32];   /*   */
   double  innerRowRadii[40];   /*   */
   double  outerRowRadii[32];   /*   */

 };  
