/*    itpcPadGainT0.idl
*
*  Table: itpcPadGainT0
*
*       description:
*/ 


struct itpcPadGainT0 { 
  long run;                   /* pulser run number used */
  float  Gain[24][40][120];   /* Gains per pad*/
  float  T0[24][40][120];     /* T0 per pad*/
 };  
