/*    KalmanTrackFinderParameters.idl
*
*  Table: KalmanTrackFinderParameters
*
*  Description: set of control parameter used by the ITTF tracker.
*
*/ 
	

struct KalmanTrackFinderParameters { 
  long   useMcAsRec; 		/**/
  long   useTrackFilter; 	/*Whether a track filter should be used internally*/
  long   elossCalculated; 	/*Whether the Energy loss should be calculated while propagating tracks*/
  long   mcsCalculated; 	/*Whether multiple coulomb scattering should be include in erro matrices*/ 
  long    maxNullCount; 	/*Maximum number of null hits on active detector layers*/
  long    maxContigNullCount; 	/*Maximum number of contiguous null hits*/ 
  long    minCountForReset; 	/*Number of adjacent layers with hits before nullContiguous is reset to zero */
  long    mHitRegions;		/*2050 means 0<svtHit<20, 20<ssdHit<50*/
  long    mHitWeights;	        /*Coeffs of nhits. sum must be >=20*/
  double  maxChi2Vertex; 	/*max vertex incremental chi2 value acceptable*/ 
  double  massHypothesis; 	/*mass used in the tracking for mcs and eloss calculation purposes*/
  double  maxDca2dZeroXY; 	/*max 2d dca to X=Y=0  for primary track*/ 
  double  maxDca3dVertex; 	/*max 3d dca to vertex for primary track*/ 
};  
