/*    KalmanTrackFitterParameters.idl
*
*  Table: KalmanTrackFitterParameters
*
*       description:
*/ 
	

struct KalmanTrackFitterParameters { 
	double maxChi2; 	/* Maximum Chi2 */
	double maxChi2Vtx; 	/* Maximum Chi2 for vertex*/
 };  
