/*    kretDbBlobS.idl
*
*  Table: kretDbBlobS
*
*       description:       online-DB, any large string of characters, ver2
*/ 


struct kretDbBlobS { 

   char  dataS[500000];   /*   string with  data  */
   char  comment[160];   /*   */

 };  
