/*    L0TriggerInfo.idl
*
*  Table: L0TriggerInfo
*
*       description:
*/ 


struct L0TriggerInfo { 

   long  runNumber;   /*   idx_rn  */
   long  daqTriggerId;   /*   id_trigger  */
   long  offlineTriggerId;   /*   offlineBit  */
   long  psL0;   /*   desiredL0PS  */
   char  name[64];   /*   name  */
   unsigned long  detectorLiveOnBits;   /*   */
   unsigned long  detectorLiveOffBits;   /*   */
   unsigned long  detectorRequest;   /*   */

 };  
