/*    l3AlgorithmCount.idl
*
*  Table: l3AlgorithmCount
*
*       description: //    algorithm counter per fileSequenc
*/ 


struct l3AlgorithmCount { 

   long  runNumber;   /*   */
   long  fileNumber;   /*   daq file sequence number  */
   long  algId;   /*   */
   long  nProcessed;   /*   */
   long  nAccept;   /*   */
   long  nBuild;   /*   */

 };  
