/*    l3AlgorithmSum.idl
*
*  Table: l3AlgorithmSum
*
*       description: //    Algorithm summary
*/ 


struct l3AlgorithmSum { 

   long  runNumber;   /*   */
   long  algId;   /*   */
   long  nProcessed;   /*   */
   long  nAccept;   /*   */
   long  nBuild;   /*   */

 };  
