/*    l3AlgorithmInfo.idl
*
*  Table: l3AlgorithmInfo
*
*       description: //    algorithm identifier and parameters
*/ 


struct l3AlgorithmInfo { 

   long  runNumber;   /*   run number  */
   long  idxAlg;   /*   algorithm sequence number  */
   long  algId;   /*   unique algorithm id  */
   long  preScale;   /*   */
   long  postScale;   /*   */
   long  GI1;   /*   Algorithm parameters  */
   long  GI2;   /*   */
   long  GI3;   /*   */
   long  GI4;   /*   */
   long  GI5;   /*   */
   float  GF1;   /*   */
   float  GF2;   /*   */
   float  GF3;   /*   */
   float  GF4;   /*   */
   float  GF5;   /*   */

 };  
