/*    l3GlobalCounter.idl
*
*  Table: l3GlobalCounter
*
*       description: //    global counter
*/ 


struct l3GlobalCounter { 

   long  runNumber;   /*   */
   long  fileNumber;   /*   */
   long  nProcessed;   /*   */
   long  nReconstructed;   /*   */

 };  
