/*    l3RunSummary.idl
*
*  Table: l3RunSummary
*
*       description: //    run counter
*/ 


struct l3RunSummary { 

   long  runNumber;   /*   */
   long  nGl3Nodes;   /*   */
   long  totalNProcessed;   /*   */
   long  totalNReconstructed;   /*   */

 };  
