/*:Description: 
  :Synonyms::::
  :Source:
  :Update:
  :Update frequncy:
  :Reminder:
  :Recall frequency:
  :Size of Data:
  :Pointer to data:  
*/
struct LocalTrackSeedFinder {

  /*  type varnam;      Units : Comments */

  double deltaY;            /* search window in the next layer when connecting two points           */
  double deltaZ;            /* search window in the next layer when connecting two points           */
  double mExtrapDeltaY;     /* search window in the next layer when extending a conection of points */
  double mExtrapDeltaZ;     /* search window in the next layer when extending a conection of points */
  long   seedLength;        /* minimum number of points to connect                                  */
  long   maxSkipped;        /* max number of layers one can skip                                    */
  long   extrapMaxLength;   /* define the Max number of points to extrapolate                       */
  long   extrapMinLength;   /* define the Min number of points to extrapolate                       */
  long   useOrigin;         /* Use the origin to calculate helix                                    */


};

/*  Last mod. for :LocalTrackSeedFinder  $Log $  */

