//:Description: TMultiDimFit
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  MDFCorrection.time:
struct MDFCorrection {
  octet   idx; // row index
  octet   nrows; // total no. of real rows in the table; For Db interface (where nrows = 50)
  octet   PolyType;  // type = 0 kMonomials, type = 1 kChebyshev, type = 2 kLegendre
  octet   NVariables;// == 2 for now.
  octet   NCoefficients;
  octet   Power[100];    //  p_ij = Power[i * NVariables + j];
  double  DMean; // 
  double  XMin[2];
  double  XMax[2];
  double  Coefficients[50]; 
  double  CoefficientsRMS[50]; 
};
