/* mtdEventFilterCuts.idl
*
* Table: mtdEventFilterCuts
*
* description: // hold the cuts used for event filtering of MTD data
*
*/
 
struct mtdEventFilterCuts 
{
  float minTrkPtAll;   /* minimum pt cut on all tracks */
  float minTrkPtLead;  /* minimum pt cut on leading track */
  float minNHitsFit;   /* minimum number of fit hits */
  float minNHitsDedx;  /* minimum number of hits used for dE/dx */ 
  float minFitHitsFrac;/* minimum fraction of fit hits over possible hits */
  float maxDca;        /* maximum 3D dca */
  float minNsigmaPi;   /* minimum NsigmaPi cut */
  float maxNsigmaPi;   /*  maximum NsigmaPi cut */
  float maxDeltaZ;     /* maximum DeltaZ cut on track-hit pair */
  float minNMuons;     /* minimum number of muon candidates */
};
