/* mtdModuleToQTmap.idl
*
* Table: mtdModuleToQTmap
*
* description: // mapping between MTD backleg/module to the triggering QT board
*
*/
struct mtdModuleToQTmap 
{
  short qtBoardId[150];  /* qt board id for each module*/
  short qtChannelId[150]; /* qt channel id for each module */
};
