/* mtdPositionCorr.idl
*
* Table: mtdPositionCorr
*
* description: // correction for MTD hit positions
*
*/
struct mtdPositionCorr 
{
  float yCorr[150]; /* y offset for each module */
  float zCorr[1800]; /* z offset for each cell */
};
