/* mtdQTSlewingCorr.idl
*
* Table: mtdQTSlewingCorr
*
* description: // Online slewing correction for QT board
*
*/
struct mtdQTSlewingCorr {
  float slewingBinEdge[512];  /* bin edges for slewing correction */
  float slewingCorr[512]; /* slewing per bin for each module */
};
