/* mtdSlewingCorr.idl
*
* Table: mtdSlewingCorr
*
* description: // Slewing correction for MTD calibration
*
*/
struct mtdSlewingCorr 
{
  float slewingBinEdge[3000];  /* bin edges for slewing correction */
  float slewingCorr[3000]; /* slewing per bin for each module */
};
