/* mtdTDIGOnBackleg.idl
 *
 * Tables: mtdTDIGOnBackleg
 *
 * description: // positioning of TDIG boards on backlegs 
*/

struct mtdTDIGOnBackleg {
  short backlegId;   /* backleg Id */   
  short tdigId[8];   /* serial numbers of TDIG boards on this backleg */
};
