/* mtdTriggerTimeCut.idl
*
* Table: mtdTriggerTimeCut
*
* description: // cut on the timing difference between MTD hits and trigger time to select hits from the triggered collision
*
*/
struct mtdTriggerTimeCut 
{
  float minTriggerTime[150]; /* Lower bound for each module */
  float maxTriggerTime[150]; /* Upper bound for each module */
};
