
struct OnlBeamDescriptor {
  char  name[60];
  char  description[255];
  short   z;          
  short   a;
  short   q;
  float   p;
  float   intensity;  
  short   direction;  /* 0=CCW, 1=CW */
};



