/*    pmdBrdMipCalib.idl
*
*  Table: pmdBrdMipCalib
*
*       description: //:Table which contains MIP information for each Board
*                    total 144 x 9 boards
*/ 

struct pmdBrdMipCalib { 

   long  Status;   /*  status of the etabin (0=problem, 1=ok)  */
   long  SMNumber; /* Supermodule number of the board */
   long  UnitmoduleNumber; /* Unitmodule number in Supermodule of board*/
   long  FEEBoardNumber; /* FEE Board number */
   long  MipFitAdcMin;   /*   first ADC to fit  */
   long  MipFitAdcMax;   /*   last ADC to fit  */
   float  MipPeakPosition[64];   /*   MIP peak position  */
   float  MipPeakPositionError[64]; /*   MIP peak position error  */
   float  MipPeakWidth[64];   /*   MIP peak width  */
   float  MipPeakWidthError[64];   /*   MIP peak width error  */
   float  MipFitParam[3];   /*   MIP fit parameters  */
   float  MipFitChiSqr;   /*   MIP fit chi square  */

 };  
