/*    pmdSMCalib.idl
*
*  Table: pmdSMCalib
*
*       description: *    //:  Calibration table for each SM in PMD, 24 SMs.
*/ 


struct pmdSMCalib { 

   short  SM_Number;   /*   SM Number */
   short  SM_Avg_Mip_MPV;   /*    Overall average MIP MPV ADC for the whole SM */
   float  CellGain[120][120];   /*   Cellwise Gain Number[row][col] */
   float  CellMpvError[120][120];   /*    Error in MIP MPV(not on gain) */
   float  CellMipWidth[120][120];   /*    Width of MIP peak (fitted) */
   float  CellMipWidthError[120][120];   /*    Mean Pedestal ADC */
   float  CellMipMean[120][120];   /*    Mean Pedestal ADC */
   float  CellMipChiSq[120][120];   /*    Isolated cell hist fit chiSq/NDF  */
   short  CellMipEntry[120][120];   /*    Isolated cell hist entry  */
   short  Status[120][120];   /*    Cell Status (0=Bad, 1=Good) */
 };  
