/*    pmdCalSummary.idl
*
*  Table: pmdCalSummary
*
*  description: *         //:  Table which contains the pmd calibration summary
*/ 


struct pmdCalSummary { 

   char  Operator[64];   /*     Operator Name  */
   char  Comments[256];   /*     comments  */
   long  DetNumber;   /*     detector number  */
   long  SMNumber; /* supermodule number */
   long  FirstRun;   /*     first run used for calibration  */
   long  LastRun;   /*     last run used for calibration  */
   long DataType;   /* ped data or physics data ? */
   float ZVertexCut; /* Zvertexcut used for the events */
   long MIPMaxNoOfEntries;  /* Max no of entries for MIP selection */
   long  NEvents;   /*     number of events used for calibration  */
   long  CalibMode;   /*   calmode (eg. 1=MIP, 2 = fast equalization )  */
   float SMEqualization[12]; /* SM to SM equalization numbers */

 };  
