/*    pmdCalibSummary.idl
*
*  Table: pmdCalibSummary
*
*  description: *         //:  Table which contains the pmd calibration summary
*/ 


struct pmdCalibSummary { 

   octet  Operator[64];   /*     Operator Name  */
   octet  Comments[256];   /*     comments  */
   long  DetNumber;   /*     detector number  */
   long  SMNumber; /* supermodule number */
   long  FirstRun;   /*     first run used for calibration  */
   long  LastRun;   /*     last run used for calibration  */
   long  PedDataType;   /* ped Beam On or Ped beam OFF? */
   float ZVertexCut; /* Zvertexcut used for the events */
   long  MIPMinimumNoOfEntries;  /* Max no of entries for MIP selection */
   long  NEvents;   /*     number of events used for calibration  */
   long  CalibMode;   /*   calmode (eg. 1=MIP, 2 = fast equalization )  */
   long  FitUpperRange;   /*  fit upper range,lower is 0  */
   long  AdcCut;   /*   AdcCut for colecting isolated cell hist  */
   float SMEqualization[12]; /* SM to SM equalization numbers */

 };  
