/*    pmdDimensions.idl
*
*  Table: pmdDimensions
*
*       description: //  pmd geometry DB Overall table for the whole detector
*/ 

struct pmdDimensions { 

  long  SubDetector;    /* no of Subdetectors(CPV/PMD) installed */
  long  Supermodules[2];  /* No of supermodules installed */
  long  ActiveModules[2];  /* No of Modules Active */
  float  InitialPointForSM[2][12];  /* initial x,y position of Supermodules  */
  long  UnitModNumberInSM[2][12];  /* No of UnitModules in each Supmodules */
  float  XYZpos[3]; /* Z-distnce from vertex */ 
 };  

