/*    pmdHotCells.idl
*
*  Table: pmdHotCells
*
*       description: *    provide bitmask of hot cells in pmd & cpv
*                         arranged as 48 chains of 1728 (=32*54) channels
*/ 


struct pmdHotCells { 

   unsigned long m00; /* 32 bits for first 32 channels in chain */
   unsigned long m01;
   unsigned long m02;
   unsigned long m03;
   unsigned long m04;
   unsigned long m05;
   unsigned long m06;
   unsigned long m07;
   unsigned long m08;
   unsigned long m09;
   unsigned long m10;
   unsigned long m11;
   unsigned long m12;
   unsigned long m13;
   unsigned long m14;
   unsigned long m15;
   unsigned long m16;
   unsigned long m17;
   unsigned long m18;
   unsigned long m19;
   unsigned long m20;
   unsigned long m21;
   unsigned long m22;
   unsigned long m23;
   unsigned long m24;
   unsigned long m25;
   unsigned long m26;
   unsigned long m27;
   unsigned long m28;
   unsigned long m29;
   unsigned long m30;
   unsigned long m31;
   unsigned long m32;
   unsigned long m33;
   unsigned long m34;
   unsigned long m35;
   unsigned long m36;
   unsigned long m37;
   unsigned long m38;
   unsigned long m39;
   unsigned long m40;
   unsigned long m41;
   unsigned long m42;
   unsigned long m43;
   unsigned long m44;
   unsigned long m45;
   unsigned long m46;
   unsigned long m47;
   unsigned long m48;
   unsigned long m49;
   unsigned long m50;
   unsigned long m51;
   unsigned long m52;
   unsigned long m53; /* 32 bits for last 32 channels in chain */

 };  
