/*    pmdPed.idl
*
*  Table: pmdPed
*
*       description: *    //:  Table which contains pedestal information for PMD(one row for each chain, PMD has 48 chains,each having 1728 channels)
*/ 


struct pmdPed { 

   short  MeanPedestal[1728];   /*    Mean Pedestal ADC */
   short  RmsPedestal[1728];   /*    Rms Pedestal ADC  */
   short  PedThreshold[1728]; /* Threshold applied on each channel */
 };  
