/*    pmdReadBoard.idl
*
*  Table: pmdReadBoard
*
* description: //  pmd electronics information for each readout board 
  64 channels per board, total 144 x 9 boards */


struct pmdReadBoard { 
   long  SMNumber; /* Unit module number */
   long  UnitmoduleNumber; /* Unit module number */
   long  CrateNumber;  /*Crate Number */
   long  ChainNumber;  /*Chain Number */
   long  CramNumber;  /*Cram Number (could be same as chain number) */
   long  FEEBoardNumber;   /*  Serial number of the board in that chain  */
   long  StartChannelNumber;  /* Start of Channel Number in that chain */ 
   long  EndChannelNumber;  /* End of Channel Number in that chain */ 
   long  FEEDeadChannelNumber[64];  /*Dead Channel Number  in that board */
   long  SMRow[64];  /* SM row numbers for that board */
   long  SMCol[64];  /* SM Column numbers for that board */
 };  
