/*    pmdSMChain_GNF.idl
*
*  Table: pmdSMChain_GNF
*
*       description: *    gain normalization factor parameters for each
*                         SM-chain combination
*/ 


struct pmdSMChain_GNF { 

   long sm;              /* super module */
   long chain;           /* chain */
   float mean_factor;    /* mean */
   float errmean_factor; /* error on mean */
   float mpv_factor;     /* most probable value */
   float errmpv_factor;  /* error on mpv */

 };  
