/*    pmdSMDimensions.idl
*
*  Table: pmdSMDimensions
*
*   description: //PMD supermodule DB Overall table for each SM (total 24 SMs)
*/ 


struct pmdSMDimensions { 
  char SMName[8];   /* Name of SM eg SM-M-1-4 etc*/
  long  SubDetector;   /* Detector number   */
  long  SMNumber;      /* Supermodule number */
  long  ActiveModules; /* Active Unitmodule number */
  long  UMPerSupermodule;    /* No of Unitmodules per supermodule */
  long  ipad;   /* column number of supermodule */
  long  jpad;  /* row number of the supermodule */
  long  FEEChainNumber[4];  /* Readout chain number in the super module (Max 4 chains per SM) */ 
  long  StartBoardNo[4];  /* Starting Board number in the super module*/ 
  long  EndBoardNo[4];  /* End Board number in the super module*/ 
  long  DeadChannelinUM[9];  /* Dead Channel in UM*/ 
 };  

