/*    pmdUMDimensions.idl
*
*  Table: pmdUnitModuleDimensions
*
*       description: // PMD Unitmodule information
*      Total 144 UMs
*/ 


struct pmdUMDimensions { 

  long  DetectorID;  /* Detector ID */
  long  SuperModuleID;    /* Supermodule ID */
  long  FEEChainNumber;   /* Chain number of the unit module */ 
  long  StartBoardNumber; /* Initial Board Number*/
  long  EndBoardNumber; /* Final Board Number */
  char  BoardStatus[16];  /* Overall status of the boards in the unit module */
};  

