/* pp2ppPedestal.idl
*
* Table: pp2ppPedestal for each of the 20480 channels
*
* description: Pedestals for each of the 20480 channels
* Chains 0 and 2 ha4 only 4 SVX's whereas chains 1 and 3 have 6 SVX's 
* => For each sequencer ( which has 4 chains ), there are a total of (2*4 + 2*6) = 20 SVX's
* => The total no. of channels = 8*20*128 = 20480
*
*/

struct pp2ppPedestal {

  octet   sequencer ; /* Sequencer no. (1-8)   */
  octet   chain ;     /* Chain no.     (0-3)   */
  octet   SVX       ; /* SVX no.       (0-5)   */
  octet   channel ;   /* Channel no.   (0-127) */
  double  mean ;      /* Pedestal mean         */
  double  rms ;       /* Standard Deviation    */

} ;
