/* pp2ppPMTSkewConstants.idl
*
* Table: pp2ppPMTSkewConstants
*
* description: these constants are used to get the right timing from the TAC of the PMT's
*
*/

struct pp2ppPMTSkewConstants {

	double skew_param[64] ; /* skew parameters, 1-64 */

};
