/* pp2ppZ.idl
*
* Table: pp2ppZ
*
* description: the z coordinates for 4 planes (A, B, C & D) of the 8 roman pots
*              -- All nos. are in the unit of m .
*
* The order in the table is as follows :

  double  EHI_A ;       /* RP EHI Plane/Chain A */
  double  EHI_B ;       /* RP EHI Plane/Chain B */
  double  EHI_C ;       /* RP EHI Plane/Chain C */
  double  EHI_D ;       /* RP EHI Plane/Chain D */

  double  EHO_A ;       /* RP EHO Plane/Chain A */
  double  EHO_B ;       /* RP EHO Plane/Chain B */
  double  EHO_C ;       /* RP EHO Plane/Chain C */
  double  EHO_D ;       /* RP EHO Plane/Chain D */

  double  EVU_A ;       /* RP EVU Plane/Chain A */
  double  EVU_B ;       /* RP EVU Plane/Chain B */
  double  EVU_C ;       /* RP EVU Plane/Chain C */
  double  EVU_D ;       /* RP EVU Plane/Chain D */

  double  EVD_A ;       /* RP EVD Plane/Chain A */
  double  EVD_B ;       /* RP EVD Plane/Chain B */
  double  EVD_C ;       /* RP EVD Plane/Chain C */
  double  EVD_D ;       /* RP EVD Plane/Chain D */

  double  WHI_A ;       /* RP WHI Plane/Chain A */
  double  WHI_B ;       /* RP WHI Plane/Chain B */
  double  WHI_C ;       /* RP WHI Plane/Chain C */
  double  WHI_D ;       /* RP WHI Plane/Chain D */

  double  WHO_A ;       /* RP WHO Plane/Chain A */
  double  WHO_B ;       /* RP WHO Plane/Chain B */
  double  WHO_C ;       /* RP WHO Plane/Chain C */
  double  WHO_D ;       /* RP WHO Plane/Chain D */

  double  WVD_A ;       /* RP WVD Plane/Chain A */
  double  WVD_B ;       /* RP WVD Plane/Chain B */
  double  WVD_C ;       /* RP WVD Plane/Chain C */
  double  WVD_D ;       /* RP WVD Plane/Chain D */

  double  WVU_A ;       /* RP WVU Plane/Chain A */
  double  WVU_B ;       /* RP WVU Plane/Chain B */
  double  WVU_C ;       /* RP WVU Plane/Chain C */
  double  WVU_D ;       /* RP WVU Plane/Chain D */

*/

struct pp2ppZ {

  double rp_z_plane[32]; /* the z coordinates for 4 planes (A, B, C & D) of the 8 roman pots */

};

