/* pp2ppPedestal160.idl
*
* Table: pp2ppPedestal160 for 160 channels
*
* description: Pedestals for 160 channels
*
*/

struct pp2ppPedestal160 {

  double  mean[160];      /* Pedestal mean         */
  double  rms[160];       /* Standard Deviation    */

};
