/* pp2ppRPpositions.idl
*
* Table: pp2ppRPpositions - roman pot positions
*
* description: positions of roman pots
*
*/

struct pp2ppRPpositions {

 double b_left_W1D;
 double b_right_W1U;
 double b_bot_W2D;
 double b_top_W2U;
 double y_left_E1D;
 double y_right_E1U;
 double y_bot_E2D;
 double y_top_E2U;

};
