/*    ppDbLog.idl
*
*  Table: ppDbLog
*
*       description:
*/ 


struct ppDbLog { 

   char  dataType[128];   /*   unique type of entry, hardcoded  */
   char  author[128];   /*   name of user  */
   char  comment[1024];   /*   comment entered by user  */

 };  
