/*    ppDbSpinConf.idl
*
*  Table: ppDbSpinConf
*
*       description:
*/ 


struct ppDbSpinConf { 

   char  name[128];   /*   name of scheme  */
   long  nBunch;   /*     number of bunches in ring  */
   long  IDspin[120];   /*   spin-ID.gt.0 for each bunch, 0=ignore this bunch  */
   long  IDyell[120];   /*   yellow bunch ID.ge.1  */
   long  IDblue[120];   /*     blue bunch ID.ge.1  */

 };  
