/*    ppDbSpinAvr.idl
*
*  Table: ppDbSpinAvr
*
*       description:
*/ 


struct ppDbSpinAvr { 

   long  nSpinID;   /*   number of spin configurations  */
   char  author[128];   /*   name of user  */
   char  comment[1024];   /*   comment entered by user  */
   float  lum[20];   /*   integrated luminosity (a.u.) per spinID  */
   long  nBunch[20];   /*   no. of bunches per spinID  */
   float  yellPx[20];   /*   yellow beam average X-polarization per spinID  */
   float  yellPxEr[20];   /*   its error  */
   float  bluePx[20];   /*   blue beam average X-polarization  per spinID  */
   float  bluePxEr[20];   /*   its error  */
   float  yellPy[20];   /*   yellow beam average Y-polarization per spinID  */
   float  yellPyEr[20];   /*   its error  */
   float  bluePy[20];   /*   blue beam average Y-polarization  per spinID  */
   float  bluePyEr[20];   /*   its error  */

 };  
