/*  pvpdStrobeDef.idl
 *
 *  Table: pvpdStrobeDef
 *
 *  description: // strobe event ranges for pVPD TDCs
 */

struct pvpdStrobeDef{
  long id;           /* pvpd tube Id */
  long strobeTdcMin; /* lower range for pVPD strobe event */
  long strobeTdcMax; /* upper range for pVPD strobe event */
};
