/*pvpdCalib.idl
*
*Table: pvpdCalib
*
*	description: // pvpd tot calibration parameters
*		channelid: west 1-19, east 20-38
*/

struct pvpdCalib{
	float tot[61];		/*tot*/
	float totcorr[61];	/*tot correction*/
};