/* pvpdConfig.idl
 *
 * Table: pvpdConfig
 *
 * description: // coincidence configuration for pVPDs
 */

struct pvpdConfig{
  long nEastTubes; /* total number of east tubes */
  long nWestTubes; /* total number of west tubes */
  long eastwestCoincidence;  /* east-west coincidence: AND(1) or OR(0) */
  long minEastTubes; /* minimum tubes east coincidence */
  long minWestTubes; /* minimum tubes west coincidence */
};

