/* pxlBadRowColumns.idl
 *
 * Table: pxlBadRowColumns
 *
 * description: bad (empty or hot) rows and columns
 *
 */
struct pxlBadRowColumns {
  unsigned long badRowColumns[10000];  /* 100*(1000000*isCol+1000*(40*(sec-1)+10*(lad-1)+sen)+rowOrCol)+stat */
};
