/*    pxlDigmapsSim
*
*  Table: pxlDigmapsSim
*
* description: DigmapsSim parameters for the PXL 
* 
*/ 

struct pxlDigmapsSim {
  float adcThreshold; /* adc threshold parameter */
  float planeEpitaxialThickness; /* DIGMAPS plane parameters */
  float planeNoiseElectrons;
  float planeTemprature;
  float planeIonizationEnergy;
  float planeSegmentSize;
  float planeMaxSegmentSize;
  float planeMaxChargePerSegment;
  float planeDiffusionMaxX;
  float planeDiffusionMaxY;
  float planeReflexCoefficient;
  float planeMod_SigTenMicrons;
  float transportRangeLimit; /* in pitch unit */
  float transport_Norm_g_1st;
  float transport_x0_g_1st;
  float transport_sigma_g_1st;
  float transport_Gamma_lor_1st;
  float transport_x0_lor_1st;
  float transport_norm_lor_1st;
  float transport_Norm_g_2nd;
  float transport_x0_g_2nd;
  float transport_sigma_g_2nd;
  float transport_Gamma_lor_2nd;
  float transport_x0_lor_2nd;
  float transport_norm_lor_2nd;
  float energyLandauMean; /* Landau mean/sigma for MIP particle */
  float energyLandauSigma;
  float par[10]; /* parameters to scale for beta*gamma dependence */
  float resAddX; /* resolution in local X direction */
  float resAddZ; /* resolution in local Z direction */
  short transportChargeModel; /* DIGMAPS charge transport parameters in model 5: l1dimgauslor */
};
