/* pxlHotPixels.idl
 *
 * Table: pxlHotPixels
 *
 * description: single hot pixels mask
 *
 */
struct pxlHotPixels {
  unsigned long hotPixel[10000]; /* 1000000*(40*(sector-1)+10*(ladder-1)+sensor) + 1000*row + column */
};
