/*  pxlRowColumnStatus.idl
* 
*  Table: pxlRowColumnStatus
*
*     description: PXL sensor row/column status for 400 sensors, 960 columns vs 928 rows per sensor (~1000)
*
*/

struct pxlRowColumnStatus {
	octet rows[400000]; /* row/column status: 0: not in place, 1: in place and good, 2-255: reserved */
	octet cols[400000];
};
