/*  pxlSensorStatus.idl
* 
*  Table: pxlSensorStatus
*
*     description: PXL sensor status for 400 sensors
*
*/

struct pxlSensorStatus {
	octet status[400]; /* pxl sensor status: 0: not in place, 1: in place and good, 2-255: reserved */
};
