/* pxlSensorTps.idl
 *
 * Table: pxlSensorTps
 *
 * description: // pxl sensor correction by Thin Plate Spline 
 *
 */
struct pxlSensorTps {
  long Id; /* 1000*sector + 100*ladder + sensor, sector[1-10], ladder[1-4], sensor[1-10] */
  unsigned short nMeasurements; /* n measurements for TPS fit */
  float A[3]; /* */
  float X[121]; /* */ 
  float Y[121]; /* */
  float W[121]; /* */
};