/*    rhicfGain.idl
*
*  Table: rhicfGain
*
*       description: // RHICf detector gains
*
*                         plate [tower#*16 + plate#]
*                         smallbar [40*layer# + 20*xy# + bar#]
*                         largebar [80*layer# + 40*xy# + bar#]
*
*                         energy[GeV] = (adc-ped)[ch] * gain[GeV/ch]
*/

struct rhicfGain{
	float plate[32];                 /* GSO plate of small and large tower  */
	float smallbar[160];    /* GSO bar of small tower  */
	float largebar[320];    /* GSO bar of large tower  */
};  
