/*    rhicfPlateRange.idl
*
*  Table: rhicfPlateRange
*
*       description: // adcL (higher C/ch) will be converted to adcH (lower C/ch) if adcL is overflow.
*                       adcH = plate[tower][plate][0] + plate[tower][plate][1]*adcL
*                       
*/ 

struct rhicfPlateRange{
    float plate[64];    /* [32*tower# + 2*plate# + parameter#]; GSO plate of small and large tower  */
};  
