/*    rhicfBarMap.idl
*
*  Table: rhicfBarMap
*
*       description: // Adress to convert raw 512 channels to small and large bar[layer][xy][bar]
*                    // Geometry_rhicf
*/ 

struct rhicfBarMap{
    unsigned short smallbar[160];    /* GSO bar of small tower  */
    unsigned short largebar[320];    /* GSO bar of large tower  */
};  
