
/*    smdCalib.idl
*
*  Table: smdCalib
*
*       description: //:  Table which contains all calibration information
*/ 


struct smdCalib { 

   octet  Status[18000];   /*   status of the tower/wire (0=problem, 1=ok)  */
   float  AdcToE[18000][5];   /*   ADC to Energy  */
 };  
