
/*    smdGain.idl
*
*  Table: smdGain
*
*       description: //:  Table which contains gain information
*/ 


struct smdGain { 

   octet  Status[18000];   /*   status of the tower/wire (0=problem, 1=ok)  */
   float  Gain[18000];   /*   Gain Variation  */
 };  
