/*    smdPedestal.idl
*
*  Table: smdPedestal
*
*       description: *    //:  Table which contains pedestal information for shower max ADCs
*/ 


struct smdPedestal { 

   long  Status;   /*    status of the smd stripe(0=problem,1=ok)  */
   float  AdcPedestal[128];   /*    ADC pedestals of smd stripe  */
   float  AdcPedestalRMS[128];   /*    ADC pedestals RMS of smd stripe  */

 };  
