/*    smdPed.idl
*
*  Table: smdPed
*
*       description: *    //:  Table which contains pedestal information for shower max ADCs
*/ 


struct smdPed { 

   octet  Status[18000];   /*    status of the smd stripe (0=problem,1=ok)  */
   short  AdcPedestal[18000][3];   /*    ADC pedestals of smd strip x 100  */
   short  AdcPedestalRMS[18000][3];   /*    ADC pedestals RMS of smd strip x 100  */

 };  
