/*    spaceChargeCor.idl
*
*  Table: spaceChargeCor
*
*       description: Table for Space Charge Corrections
*/ 


struct spaceChargeCor { 

   double  fullFieldB;   /* Negative Full Field Correction  */
   double  halfFieldB;   /* Negative Half Field Correction  */
   double  zeroField;   /*  Zero Field " "  */
   double  halfFieldA;   /*  Postive Half " " */
   double  fullFieldA;   /*  Postive Full " " */
   double  satRate;   /* Saturation Rate Hz  */
   float   factor;    /*  Multiplicative Factor */
   float   detector;    /* 0=RICH, 1=BBCx, 2=ZDCx, 3=ZDCe+w, 4=BBCe+w */
   float   offset;      /* Offset at zero luminosity */
   float   ewratio;      /* Ratio of charge east/west */

 };  
