/*    spaceChargeCor.idl
*
*  Table: spaceChargeCor
*
*       description: Table for Space Charge Corrections
*/ 


struct spaceChargeCor { 

   double  fullFieldB;   /* Negative Full Field Correction  */
   double  halfFieldB;   /* Negative Half Field Correction  */
   double  zeroField;   /*  Zero Field " "  */
   double  halfFieldA;   /*  Postive Half " " */
   double  fullFieldA;   /*  Postive Full " " */
   double  satRate;   /* Saturation Rate Hz  */
   float   factor;    /*  Multiplicative Factor */

 };  
