/*    spinDbStar.idl
*
*  Table: spinDbStar
*
*       description:
*/ 


struct spinDbStar { 

   long  bXoff7;   /*   offsets for 7 bXing, range=(0,119)  */
   long  bXoff48;   /*   offsets for 48-bit bXing, range=(0,119)  */
   char  comment[160];   /*   */

 };  
