/*    spinDbV124.idl
*
*  Table: spinDbV124
*
*       description:
*/ 


struct spinDbV124 { 

   long  bucketOffset[2];   /*   time bucket offset for bXing=0 at STAR, range=(0,359)  */
   long  rotatorState[2];   /*   enum: trans, long, ...  */
   octet  v124bits[360];   /*   (unpol,down,up,fill) x (blue, yellow) x (360)timeBuckets , packed  */
   char  comment[160];   /*   */

 };  
