/*    spinDbBXmask.idl
*
*  Table: spinDbBXmask
*
*       description:
*/ 


struct spinDbBXmask { 

   octet  bXmask[120];   /*   0=use=default, non-0=drop bXing, range=(0,119) at STAR IP  */
   char  comment[160];   /*   */

 };  
