/*    ssdBarrelPosition.idl
*
*  Table: ssdBarrelPosition
*
* description: SSD Barrel position
* absolute orientations and positions in Star
*/ 


struct ssdBarrelPosition { 

  double  driftDirection[3];       /* drift direction  */
  double  normalDirection[3];      /* coordinates of unit vector normal to barrel  */
  double  transverseDirection[3];  /* t=nxd, transverse to drift and normal direction  */
  double  centerPosition[3];       /* coordinates of the barrel center in the Star syst.  */

 };  
