/*    ssdConfiguration.idl
*
*  Table: ssdConfiguration
*
*  description:  SSD configuration
*/ 


struct ssdConfiguration { 

  long nMaxSectors;         /* 4 */
  long nMaxLadders;         /* 20*/
  long nMaxWafers;          /* 320*/
  long ladderIsPresent[20]; /* (1,1,2,0,0,0,0,0,2,3,3,3,4,0,0,0,0,0,4,1) === Year2004 */

};  
