/*    ssdDimensions.idl
*
*  Table: ssdDimensions
*
*       description: //  SSD dimensions
*/ 


struct ssdDimensions {
  long    wafersPerLadder;    /* 16         */
  long    a128PerSide;        /* 6          */
  long    stripPerSide;       /* 768        */
  double stripPitch;         /* 0.0095 cm  */
  double stereoAngle;        /* 0.0175 rad */
  double waferHalfLength;    /* 3.75 cm    */  
  double waferHalfWidth;     /* 2.1  cm    */
  double waferHalfThickness; /* 0.015 cm   */
  double waferHalfActLength; /* 3.65 cm    */
  double waferHalfActWidth;  /* 2. cm       */
 };  
