/*    ssdGainCalib.idl
*
*  Table: ssdGainCalibWafer
*
*  description:  SSD gain Calib per wafer
*/ 

struct ssdGainCalibWafer { 
  long   nLadder ;
  long   nWafer;  // 1 to 320 
  double nGain ;  // 320 values N over P charge


};  
