/*    ssdLaddersPosition.idl
*
*  Table: ssdLaddersPosition
*
*  description: SSD Ladders position
*  absolute orientations (must become relative to 
*  parent sector)
*/ 


struct ssdLaddersPosition { 

   long    id;                      /* Identifier : sector(from 1 to 4)*100+ladder (from 1 to 20) */
   double  driftDirection[3];       /* drift direction  */
   double  normalDirection[3];      /* coordinates of unit vector normal */
   double  transverseDirection[3];  /* t=nxd, transverse to drift and normal direction   */
   double  centerPosition[3];       /* coordinates of the ladder center in the Star syst  */

 };  
