/*    ssdNoise.idl
*
*  Table: ssdNoise
*
*  description:  SSD noise (new table)
*/ 
struct ssdNoise { 
  long id;
  octet rmsp[768]; /*array of noise for strips in a wafer p-side*/
  octet rmsn[768]; /*array of noise for strips in a wafer n-side*/

};  
