/*   ssdPedStrip_st.idl
 *   Module:
 *   Specific output of the pedestal/noise data for reconstruction software 
 *   Table of strips with noise and pedestal signals (8*4 = 32 bytes)
 */
//the strip id is coded as fallow:
// id_strip=10000*(10*strip_number+id_side)+id_wafer
//strip number=1-768
//id_side=0 for p side, 1 for n side

   struct ssdPedStrip {
     long      id;       /* Strip Id in the table */
     long      id_strip;    /* Strip identifier  strip(              */
     long      pedestal;  /* pedestal in ADC count */
     long      noise;   /* noise in ADC count (16*real noise)  */
    };
