/*    ssdSectorsPosition.idl
*
*  Table: ssdSectorsPosition
*
*  description: SSD Sectors position
*  absolute orientations (must become relative to 
*  parent barrel)
*/ 


struct ssdSectorsPosition { 

   long     id;                     /* Identifier : sector(from 1 to 4) */
   double  driftDirection[3];       /* drift direction  */
   double  normalDirection[3];      /* coordinates of unit vector normal to sectors */
   double  transverseDirection[3];  /* t=nxd, transverse to drift and normal direction   */
   double  centerPosition[3];       /* coordinates of the sector center in the Star syst  */

 };  
