/*  ssdStripCalib.idl
*
*  Table: ssdStripCalib
*
* description: ssdStripCalib
* tables containing the pedestal, rms and state of each ssd strip.
* id_strip goes from 1 to 768
* id_side goes from 0 (p-side) to 1 (n-side)
* id_wafer goes from 7101 to 8620
*/ 


struct ssdStripCalib {
  long id;         /* 10000*(10*id_strip+id_side)+id_wafer */
  octet pedestals;  /* 0-255*/
  octet rms;        /* 0-255*/
};
