/*    ssdWafersPosition.idl
*
*  Table: ssdWafersPosition
*  
*  description: SSD Wafers position
*  absolute orientations (must become relative to 
*  parent ladder)
*/ 


struct ssdWafersPosition { 

  long    id;                      /* Identifier: 7000+wafer(from 1 to 16)*100+ladder (from 1 to 20)*/
  long    id_shape;                /* Wafer shape id index   */
  long    ladder;                  /* Ladder number wafer is on  */
  long    layer;                   /* Layer number wafer is on.   */
  long    num_chip;                /* Chip number within ladder  */
  double  driftDirection[3];       /* Drift direction  */
  double  normalDirection[3];      /* Coordinates of unit vector normal to wafer */
  double  transverseDirection[3];  /* t=nxd, transverse to drift and normal direction    */
  double  centerPosition[3];       /* coordinates of the wafer center in the Star syst  */

 };  
