/*    ssdWaferConfiguration.idl
*
*  Table: ssdWaferConfiguration
*
*  description:  SSD wafer status : 1 = wafer active, 0 = wafer inactive 
*/ 

struct ssdWaferConfiguration { 
  long   nLadder ;   // 0 to 19
  long   nWafer  ;   // 0 to 15 
  long   nStatus ;   // 320 values 


};  
