/*  sstConfiguration.idl
 *
 *  Table: sstConfiguration
 *
 *  description:  SST configuration
 */ 

struct sstConfiguration { 
  long nMaxSectors;         /* 4 */
  long nMaxLadders;         /* 20*/
  long nMaxWafers;          /* 320*/
  long ladderIsPresent[20]; /* 1 means present, 0 means no present*/
};  
