/*sstChipCorrect.idl 
* 
* Table: sstChipCorrect 
* 
* Description: sst chip correction factor.once per run 
chip coding is : side[0-1]*1920 + ladder[0-19]*96 + wafer[0-15]*6 + chip[0-5] 
*/  
struct sstChipCorrect { 
	unsigned short nCutPos[3840];  // 0 to 1024 
	unsigned short nCorrect[3840]; // 0 to 1024 
};
