/*  sstClusterControl.idl
*	
*   Table: sstClusterControl
*		
*   description: control parameters 
*   of cluster finder and matcher
*   replace scf_ctrl and scm_ctrl tables
*/ 

struct sstClusterControl { 

  long   clusterTreat;  /* 13 */
  double highCut;       /* 5.0 in sn unit*/
  double testTolerance; /* set to 20% */
  double adcTolerance;  /* set to 20% */
  double matchMean;     /* 0. */
  double matchSigma;    /* 8. */

};
