/* sstMaskChip.idl
 *
 * Table: sstMaskChip
 *
 * description:  chip masking table ; id of chip is stored
 *
 */
struct sstMaskChip{
  unsigned short chip[3840]; /* side*2000 + ladder[0-19]*96 wafer[0-15]*6 + chip[1-6]*/
};