/*    sstSlsCtrl.idl
*
*  Table: sstSlsCtrl
*
* description: Control parameters for the SST 
* Slow Simulator (sls) and Pedestal Annihilator(spa)   
*/ 


struct sstSlsCtrl { 
  long nElectronInAMip;	         /*      22500 in electron unit */
  long adcDynamic;	         /*         20 in mip unit */
  long a128Dynamic;	         /*         12 in mip unit */
  long nbitEncoding;	         /*         10 number of adc bit for encoding */
  long nstripInACluster;         /*          4 */
  long daqCutValue;	         /*          3 */
  long rmsToNoise;                /*         16 */
  double pairCreationEnergy;	 /*    3.6e-09 energy to create a e+e-pair(GeV) */
  double parDiffP;	         /*    0.00123 */
  double parDiffN;	         /*    0.00094 */
  double parIndRightP;           /*      0.021 */
  double parIndRightN;	         /*      0.026 */
  double parIndLeftP;	         /*      0.013 */
  double parIndLeftN;	         /*       0.01 */
};
