/*  sstStripCalib.idl
*
*  Table: sstStripCalib
*
* description: sstStripCalib
* tables containing the pedestal, rms of each ssd strip.
*
*/ 
struct sstStripCalib {
  short pedestals[491520];  /* 0-1024*/
  octet rms[491520];        /* 0-255*/
};
