/*
 *  sstWafersPosition.idl
 *
 *  Table: sstWafersPosition
 *  description: SST Wafers position
 *  absolute orientations (must become relative to parent ladder)
 *  explanation : each array contains the 3-coordinates for all wafers (320)
 *
 *  For example, coding is :
 *    driftDirection[0] = d[0] for wafer 0
 *    driftDirection[1] = d[1] for wafer 0
 *    driftDirection[2] = d[2] for wafer 0
 *
 *    driftDirection[3] = d[0] for wafer 1
 *    driftDirection[4] = d[1] for wafer 1
 *    driftDirection[5] = d[2] for wafer 1
 *
 *  wafer coding is ladder[0-19]*16 + wafer[0-15]  
 */ 

struct sstWafersPosition { 
  double  driftDirection[960];       /* Drift direction  */
  double  normalDirection[960];      /* Coordinates of unit vector normal to wafer */
  double  transverseDirection[960];  /* t=nxd, transverse to drift and normal direction    */
  double  centerPosition[960];       /* coordinates of the wafer center in the Star syst  */ 
  
};    
