/*    starMagOnl.idl
*
*  Table: starMagOnl
*
*       description:
*/ 


struct starMagOnl { 

   unsigned long  runNumber;   /*   run number  */
   unsigned long  time;   /*   unix time of entry  */
   double  current;   /*   magnet current (- means B polarity)  */

 };  
