/*    HitError.idl
*
* Table: StvHitErrs
* Description: Collection of parameters used to calculate hit errors.
* There should be one such parameter set for each detector. Some detectors, such
* as the TPC may have more.
*
  yErr =>      Intrinsic resolution, padrow or Y direction
  zErr =>      Intrinsic resolution, z direction
  widTrk   =>  Track_width sigma**2
  thkDet   =>  (Thickness of detector plane)**2/12
  yDiff    =>  Y Drift dependent diffusion resolution, z direction
  zDiff    =>  Z Drift dependent diffusion resolution, z direction
*/ 

struct StvHitErrs 
{ 
double yErr  ; /* Intrinsic resolution, padrow or Y direction		*/
double zErr  ; /* Intrinsic resolution, z direction			*/
double widTrk; /* Track_width sigma**2					*/
double thkDet; /* (Thickness of detector plane)**2/12			*/
double yDiff ; /* Y Drift dependent diffusion resolution, z direction	*/
double zDiff ; /* Z Drift dependent diffusion resolution, z direction	*/
};  
