/*    HitError.idl
*
* Table: StvHitErrs
* Description: Simplest parameters used to calculate hit errors
* Typical case some pixel detector. X axis supposed to be orthogonal
* to hit plane. Errors provided only for Y,Z coordinates in a local frame
*
  yErr =>      	Y resolution **2 in local frame
  zErr =>      	Z resolution **2 in local frame
*/ 

struct StvHitErrs 
{ 
double yErr  ; /* Y resolution **2 in local frame		*/
double zErr  ; /* Z resolution **2 in local frame		*/
};  
