/*	Stv constants */

struct StvKonst {
      float 	mXi2Hit;		/*Xi2 to accept new hit*/
      float    	mXi2Vtx;		/*Xi2 to accept vertex	*/
      float 	mXi2Joi;		/*Xi2 in Refit join left & right subtrack*/
      float 	mXi2Trk;		/*Xi2 for track */
      float 	mXi2Hlx;		/*Xi2 in Helix	*/
      float     mDca2dZeroXY;		/*max 2d dca to X=Y=0  for primary track*/
      float     mDca3dVertex;  		/*max 3d dca to vertex for primary track*/
      float     mMaxCurv;		/*Maximal allowed curvature*/
      float     mMinP2;		        /*Minimal allowed momentum**2 for Geant3*/
      float     mMaxPti;		/*Maximal allowed 1/pt */
      float     mMaxRes;		/*Maximal allowed residual */
      float     mCoeWindow;		/*Error coeficient for searching window*/
      float     mMaxWindow;		/*Maximal window to search hits*/

      long      mMinSeedHits;		/*Min number of seed hits allowed MidEta*/
      long      mMaxSeedHits;		/*Max number of seed hits allowed MidEta*/

      long      mMinHits;		/*Min number of hits allowed MidEta*/
      long      mNorHits;		/*Normal number of hits allowed MidEta*/
      long      mGoodHits;		/*Min umber of Good hits in track MidEta*/

      long	mMinTotHits;		/*Min number hits per track*/
      long 	mMinGoodHits;		/*Min number good hits for track*/
      long 	mMinContHits;		/*Min length of good hit sequence*/
      long 	mMaxContNits;		/*Max length of acceptable non hit sequence*/
      long 	mMaxTotNits;		/*Max number of acceptable non hits*/
      float	mRxyMax;		/*Max radius for tracking*/
      float	mZMax;			/*Max Z      for tracking*/


      long      mMinSeedHitsFw;		/*Min number of seed hits allowed MidEta*/
      long      mMaxSeedHitsFw;		/*Max number of seed hits allowed MidEta*/

      long      mMinHitsFw;		/*Min number of hits allowed forwEta*/
      long      mNorHitsFw;		/*Normal number of hits allowed forwEta*/
      long      mGoodHitsFw;		/*Min umber of Good hits in track forwEta*/

      long	mMinTotHitsFw;		/*Min number hits per track forwEta*/
      long 	mMinGoodHitsFw;		/*Min number good hits for track forwEta*/
      long 	mMinContHitsFw;		/*Min length of good hit sequence forwEta*/
      long 	mMaxContNitsFw;		/*Max length of acceptable non hit sequence forwEta*/
      long 	mMaxTotNitsFw;		/*Max number of acceptable non hits*/
      float	mRxyMaxFw;		/*Max radius for tracking*/
      float	mZMaxFw;		/*Max Z      for tracking*/


};


