/*    StvTpcHitErrs.idl
*
* Table: StvTpcHitErrs
* Description: Collection of parameters used to calculate hit errors.
* There should be one such parameter set for each detector. Some detectors, such
* as the TPC may have more.
*
  yErr =>      	Intrinsic resolution, padrow or Y direction
  zErr =>      	Intrinsic resolution, Z direction
  thkDet=>	Effective detector thickness**2 , not fitted 
  yyDiff=>	Diffusion in XY direction *yFactor
  zzDiff=>	Diffusion in Z direction  *zFactor
  yzDiff=>	Diffusion in Y direction  *zFactor
  yFact=>	Error factor in Y-direction (supposed to be <1 but life is hard)
  zFact=>	Error factor in Z-direction (supposed to be <1 but life is hard)
  zAB2   =>	Constant member in Z direction (a*b)**2

<dX*dX>  = thkDet/12
<dY*dY>  = tP2*thkDet/12*yFact +yyDiff/cP2
<dZ*dZ> =  tL2/cP2*(thkDet/12*zFact + yzDiff) +zAB2/180/cP2+ zzDiff

<dY*dX>	 = tP   * thkDet/12 *sqrt(yFact)
<dZ*dX>  = tL/cP*(thkDet/12)*sqrt(zFact)
<dZ*dY> =  (tP*tL)/cP*((thkDet/12 + yyDiff/yFact))*sqrt(yFact*zFact)



*/ 

struct StvTpcHitErrs 
{ 
double yErr  ; 	/* Intrinsic resolution, padrow or Y direction		*/
double zErr  ; 	/* Intrinsic resolution, z direction			*/
double thkDet;	/* detector thickness**2 , not fitted			*/
double yyDiff;  /* Diffusion in XY direction *yFactor			*/
double zzDiff;  /* Diffusion in Z direction  *ZFactor			*/
double yzDiff;  /* Diffusion in Y direction  *ZFactor			*/
double yFact ; 	/*	Error factor in Y-direction 			*/
double zFact ; 	/*	Error factor in Z-direction 			*/
double zAB2  ;	/* Constant member in Z direction (a*b)**2		*/
};  
