/*  svtAnodeDriftCorr.idl
*
* Table:  svtAnodeDriftCorr 
*
*   Description: // SVT drift velocity correction per anode
*
*/
 
struct svtAnodeDriftCorr {

  long ID; /* identifier */

  float driftVelocCorr[240];   /* drift velocity correction*/
};

