/*    svtConfiguration.idl
*
*  Table: svtConfiguration
*
*       description: //  SVT configuration
*/ 


struct svtConfiguration { 

   long  numberOfBarrels;   /*   */
   long  numberOfLadders;   /*   */
   long  numberOfWafers;   /*   */
   long  numberOfHybrids;   /*   */
   long  numberOfLaddersPerBarrel[3];   /*   */
   long  numberOfWafersPerLadder[3];   /*   */
   long  numberOfHybridsPerWafer;   /*   */
   long  numberOfAnodes;   /*   */
   long  numberOfTimeBins;   /*   */

 };  
