//:Description: Polynomial correction for Svt; Used for Drift Distance depended correction for each alive hybrid
struct svtCorrection {
  long   type;  // type = 0 polymonical fit,
                // type = 1 TChebyshev poly in range [min,max] => [-1,1]
                // type = 2 shifted  TChebyshev poly in range [min,max] => [ 0,1]
  long   idx;   // row index
  long   nrows; // total no. of real rows in the table; For Db interface (where nrows = no. of hybrids)
  long   barrel; 
  long   layer;
  long   ladder;
  long   wafer;
  long   hybrid;
  long   Npar; // digree of polynomial
  double param[12];  // a[npar]
  double dparam[12];  // a[npar]
  char   Comment[20];
};
