/*    svtDriftVelocity.idl
*
*  Table: svtDriftVelocity
*
*       description:
*/ 


struct svtDriftVelocity { 

   double  injectionDriftVelocity[240];   /*   cm/us : from charge injection in drift region (per anode)  */
   double  injectionDriftVelocityFocus[240];   /*   cm/us : from charge injection in Focusing region (per anode)  */
   double  averageDriftVelocity[240];   /*   cm/us : from maximum distance (per anode)  */

 };  
