/*    svtDriftCurve.idl
*
*  Table: svtDriftCurve
*
*       description: //  Drift time versus drift distance bench measurements
*/ 


struct svtDriftCurve { 

   long  ID;   /*   */
   double  driftCurve[3][10];   /* 9deg poly fit/analog from bench measurements  */

 };  
