/*    svtDimensions.idl
*
*  Table: svtDimensions
*
*       description: //  SVT dimensions
*/ 


struct svtDimensions { 

   double  barrelRadius[6];   /*  cm :  */
   double  supportBeThickness;   /*   */
   double  supportBeWidth;   /*   */
   double  frameAlLength;   /*   */
   double  frameAlThickness;   /*   */
   double  frameAlWidth;   /*   */
   double  frameCsLength;   /*   */
   double  frameCsThickness;   /*   */
   double  frameCsWidth;   /*   */
   double  frameSiLength;   /*   */
   double  frameSiThickness;   /*   */
   double  frameSiWidth;   /*   */
   double  frameTotalLength;   /*   */
   double  frameTotalThickness;   /*   */
   double  frameTotalWidth;   /*   */
   double  waferLength;   /*  cm  */
   double  waferThickness;   /*   */
   double  waferWidth;   /*   */
   double  focusRegionLength;   /*  cm : focusing region length  */
   double  distanceInjector[4];   /*  cm : Distance from anodes to injection lines.  */
   double  laserPosition[5];   /*  cm : focusing region length  */

 };  
