/*    svtElectronics.idl
*
*  Table: svtElectronics
*
*       description: //  electronic signal characteristics
*/ 


struct svtElectronics { 

   long  numberOfInjectionLines;   /*   */
   double  distanceInjector[4];   /*   Distance (mm) correspondent to injection lines.  */
   double  errorDistanceInjector;   /* distance=distanceInjector(i)+/-errorDistanceInjector  */
   double  nominalGain;   /*   mV/fC  */
   double  samplingFrequency;   /*   MHz  */
   double  tZero[24];   /*   us (microseconds)  */
   double  adcCharge;   /*   fC/adc count  */
   double  adcConversion;   /*   mV/adc count  */
   double  a;   /*   drift velocity parameter a: v2 = a*v1 - b  */
   double  b;   /*   drift velocity parameter b: v2 = a*v1 - b  */

 };  
