/*    svtPedestals.idl
*
*  Table: svtPedestals
*
*       description: *         //  SVT pedestals
*/ 


struct svtPedestals { 

   long  ID;   /*   */
   float  pedestal[240][128];   /*   */
   float  rms;   /*   */

 };  
