/*    svtRDOs.idl
 *
 *  Table: svtRDOs
 *
 *       description: // David Lynn  06/14/06
 *  The structure contains useful information hvVolt, hvCurr.
 * A half ladder's data should be useful if hvVolt is approximately 1500 
 * (or -1500, I don't know if they include the sign). If however, lvFault is 
 * true, then the data is not useful as the hybrids are not working even though 
 * high voltage is there.
 *
 * If hvCurr is far from 4500 uA (or -4500), then one or more detectors from 
 * that half ladder is drawing above average current. The external resistor 
 * chain draws about 4500 uA. If however, lvFault is true, then the data is not 
 * useful
 *
 * northTemp,southThemp, and hvBoardTemp are the three temperature sensors at 
 * the end of each half-ladder. Both northTemp and southTemp sit on the carbon 
 * fiber water channels and should track the water temp quite well. hvBoardTemp 
 * sits on the board adjacent to the edge detector and is not water cooled. I 
 * don't know what it is most likely to track with.
*/ 

struct svtRDOs { 
  long           barNum     ;      /*                   */
  long           ladNum     ;      /*                   */
  char           rdo[16]    ;      /*                   */
  long           portNum    ;      /*                   */
  float          v1         ;      /*P?_V1                 */
  float          v2         ;      /*P?_V2                 */
  float          v3         ;      /*P?_V3                 */
  float          p6         ;      /*P?_P6                 */
  float          mv         ;      /*P?_MV                 */
  float          m6         ;      /*P?_M6                 */
  float          v1Curr     ;      /*P?_V1_Curr            */
  float          v2Curr     ;      /*P?_V2_Curr            */
  float          v3Curr     ;      /*P?_V3_Curr            */
  float          p6Curr     ;      /*P?_P6_Curr            */
  float          mvCurr     ;      /*P?_MV_Curr            */
  float          northTemp  ;      /*P?_T1 sensors at the end of each half-ladder*/ 
  float          southTemp  ;      /*P?_T2 and should track the water temp*/
  float          hvBoardTemp;      /*P?_T3 adjacent to the edge detector */
  float          optTemp    ;      /*P?_T4                 */
  float          lgRingCurr ;      /*P?_G1                 */
  float          rgRingCurr ;      /*P?_G2                 */
  float          lgAnodeCurr;      /*P?_G3                 */
  float          rgAnodeCurr;      /*P?_G4                 */
  float          hvVolt     ;      /*HV_RD_MV_P? hvVolt is approximately 1500 (or -1500) */
  float          hvCurr     ;      /*HV_RD_MC_P? If hvCurr is far from 4500 uA (or -4500) */
  char           hvTrip[16] ;      /*HV_HVTripped_P?                  */
  long           lvFault    ;      /*HV_LVFault_P? if lvFault=true the hybrids are not working*/
};  
