/*    svtRDOstripped.idl
 *
 *  Table: svtRDOstripped
 *
 *       description: // David Lynn  06/14/06
 *  The structure contains useful information hvVolt, hvCurr.
 * A half ladder's data should be useful if hvVolt is approximately 1500 
 * (or -1500, I don't know if they include the sign). If however, lvFault is 
 * true, then the data is not useful as the hybrids are not working even though 
 * high voltage is there.
 *
 * If hvCurr is far from 4500 uA (or -4500), then one or more detectors from 
 * that half ladder is drawing above average current. The external resistor 
 * chain draws about 4500 uA. If however, lvFault is true, then the data is not 
 * useful
 *
 * northTemp,southThemp, and hvBoardTemp are the three temperature sensors at 
 * the end of each half-ladder. Both northTemp and southTemp sit on the carbon 
 * fiber water channels and should track the water temp quite well. hvBoardTemp 
 * sits on the board adjacent to the edge detector and is not water cooled. I 
 * don't know what it is most likely to track with.
*/ 

struct svtRDOstripped { 
  long           barNum     ;      /*                   */
  long           ladNum     ;      /*                   */
  char           rdo[16]    ;      /*                   */
  float          northTemp  ;      /*sensors at the end of each half-ladder*/ 
  float          southTemp  ;      /*and should track the water temp*/
  float          hvBoardTemp;      /*adjacent to the edge detector */
  float          hvVolt     ;      /* hvVolt is approximately 1500 (or -1500) */
  float          hvCurr     ;      /*If hvCurr is far from 4500 uA (or -4500) */
  long           lvFault    ;      /*if lvFault=true the hybrids are not working*/
  long           date       ;      /*date [yyyymmdd] & time [hhmmss] where */
  long           time       ;      /*hvVolt reached  value -1500 +/- 5 V  */
  long           dateOff    ;      /*date [yyyymmdd] & time [hhmmss] where */
  long           timeOff    ;      /*hvVolt becomes not  -1500 +/- 5 V  */
  /*and has sayed there for 1 hours, date == 0 means inValid               */
};  
