/*    svtWafersPosition.idl
*
*  Table: svtWafersPosition
*
*       description: //  SVT Wafers position
*/ 


struct svtWafersPosition { 

   long  ID;   /*   */
   double  driftDirection[3];   /*   */
   double  normalDirection[3];   /*   */
   double  transverseDirection[3];   /*   */
   double  centerPosition[3];   /*   */

 };  
