 /*    tkkinkpar.idl
  *
  *  Table: tkkinkpar
  *
  *       description: Reconstructions level cuts for Kinks
  */

struct tkkinkpar {
    
    long    numOfPadRows;   /*Number of padrows. Used only for Year 1   data. */
    float   dcaParentDaughterMax;   /*Parent-Daughter DCA max */
    float   parentPtMin;   /*Lower limit cut on Pt parent  */
    float   vertexRMax2D;   /*Upper limit fiducial volume */
    float   vertexRMin2D;   /*Lower limit fiducial volume  */
    float   thetaMin;   /*Kink min decay angle*/
    float   parentDipAngleMax;    /*Parent dip angle */
    float   impactCut;    /*DCA parent to primary vertex */
    float   parentLastDaughterStart2D;  /*radial distance last point parent track - first point daughter track */
    float   parentLastDaughterStartZ;  /* z distance lastpoint parent track- first point daugther track */
    float   projectPointZDiff;    /*2D DCA parent-daugther */
    float   distanceKinkParent2D;    /*Radial distance parent-primary vertex */
    float   distanceKinkDaughter2D; /*Raidal distance daugther-prymary vertex */    
    float   distanceKinkParentZ;   /*z distance parent-primary vertex*/
    float   distanceKinkDaughterZ;   /*z distance daugther-primary vertex */

};

