/* tofAdcRange.idl
 *
 * Tables: tofAdcRange
 *
 * description: // Adc range cut for TOF daq ADCs
 */

struct tofAdcRange {
  long entries; /* an index of entries */
  short daqChannel[200];/* the daq Channel */
  short adcChan[200]; /* CAMAC ADC channel Id */
  short adcMin[200]; /* ADC min cut of tof channels */
  short adcMax[200]; /* ADC max cut of tof channels */
};
