/* tofCamacDaqMap.idl
 *
 * Tables: tofCamacDaqMap
 *
 * description: // CAMAC daq map of tof detectors
 */

struct tofCamacDaqMap {
  long entries;
  short detectorId[26000]; /* 0-pVPD, 1-TOFp, 2-TOFr */
  short trayId[26000]; /* pVPD east=-2, west=-1, for Tofr/p trayId */
  short daqChannel[26000]; /* pVPD:0-5(11), TOFp:0-41, TOFr:0-71(119)...,
                              TOT:0-10... */
  short adcChan[26000];    /* CAMAC ADC# 0-131(179)... */
  short tdcChan[26000];    /* CAMAC TDC# 0-119(184)... */
};
