/* tofCorrection.idl
 *
 * tofCorrection
 *
 * description: // correction parameters for tof calibration
 */

struct tofCorrection {
  long  npar;  /* number parameters in polynomial fit */
  float min;   /* minimum of fit range */
  float max;   /* maximum of fit range */
  float a[10];  /* parameters of polynomial fit */
};
