/* tofConfig.idl
 *
 * tofConfig
 *
 * description: // structure configuration for MRPC-TOF
 */

struct tofConfig {
  long nTrays; /* total number of mrpc-tof trays */
  long nModules; /* total number of modules in one tray */
  long nCells; /* total number of cells in one module */
};
