/* tofCamacDaqMap.idl
 *
 * Tables: tofCamacDaqMap
 *
 * description: // CAMAC daq map of tof detectors
 */

struct tofCamacDaqMap {
  long entries;
  short detectorId[200]; /* 0-pVPD, 1-TOFp, 2-TOFr */
  short trayId[200]; /* pVPD east=-2, west=-1, for Tofr/p trayId */
  short daqChannel[200]; /* pVPD:0-5(11), TOFp:0-41, TOFr:0-71(119)...,
                              TOT:0-10... */
  short adcChan[200];    /* CAMAC ADC# 0-131(179)... */
  short tdcChan[200];    /* CAMAC TDC# 0-119(184)... */
};
