/* tofConfig.idl
 *
 * tofConfig
 *
 * description: // structure configuration for MRPC-TOF
 */

struct tofConfig {
  short nTrays; /* total number of mrpc-tof trays */
  short nModules; /* total number of modules in one tray */
  short nCells; /* total number of cells in one module */
};
