/* tofDaqMap.idl
 *
 * Tables: tofDaqMap
 *
 * description: // Map btw TDIG chan to MRPC/PMT channel */

struct tofDaqMap {
   short MRPC2TDIGChanMap[192]; /* global TDIG channel number for MRPC     */
   short PMT2TDIGLeChanMap[50]; /* global TDIG leading edge channel number for vpd PMTs */
   short PMT2TDIGTeChanMap[50]; /* global TDIG trailing edge channel number for vps PMTs */
};
