/* tofGeomAlign
 *
 * Tables: tofGeomAlign
 *
 * description: // tof alignment parameters for trays, trayId will be
 *              // indicated as the elementID (+1) in data base
 */

struct tofGeomAlign {
  float z0;     /* offset in z */
  float x0;     /* offset in radius */
  float phi0;   /* offset in phi (local y direction) */
  float angle0; /* tilt angle in xy plane relative to ideal case */
};
