/* tofINLCorr
 *
 * Tables: tofINLCorr
 *
 * description: // INL correction tables information for TOF TDIGs
 */

struct tofINLCorr {
  short tdigId;         /*  TDIG board serial number id  */
  short tdcChanId;      /*  tdcId(0:2)*8+chan(0:7)       */
  float INLCorr[1024];  /*  INL correction values        */
};
