/* tofINLSCorr
 *
 * Tables: tofINLSCorr
 *
 * description: // INL correction tables information for TOF TDIGs (in short)
 */

struct tofINLSCorr {
  short tdigId;         /*  TDIG board serial number id  */
  short tdcChanId;      /*  tdcId(0:2)*8+chan(0:7)       */
  short INLCorr[1024];  /*  INL correction values        */
};
