/* tofModuleConfig.idl
 *
 * Tables: tofModuleConfig
 *
 * description: // structure configuration for the Modules of MRPC-TOF
 */

struct tofModuleConfig {
  long entries;
  short iTray[4000]; /* number Id of the tray */
  short iModule[4000]; /* number Id(local in the tray) of the module */
  short iStatModule[4000]; /* status of this module */
  short iStatCells[4000]; /* status of 6 cells in bitwise: (hightest)6-->1(lowest) 
                             --- changed to long */
  short iChannel[6][4000]; /* daq channel Id of cell 1-6 (0-5) */
};
