/* tofPedestal.idl
 *
 * Tables: tofPedestal
 *
 * description: // pedestal information for TOF daq ADCs
 */

struct tofPedestal {
  long daqChannel; /* pVPD:0-5(11), TOFp:0-41, TOFr:0-71(119) */
  long adcChan; /* CAMAC ADC channel Id */
  short adcPedestal; /* ADC pedestal of tof channels */
};
