/* tofPedestal.idl
 *
 * Tables: tofPedestal
 *
 * description: // pedestal information for TOF daq ADCs
 */

struct tofPedestal {
  long entries;
  short daqChannel[200]; /* pVPD:0-5(11), TOFp:0-41, TOFr:0-71(119)..., 
                              TOT: 0-10... */
  short adcChan[200]; /* CAMAC ADC channel Id */
  short adcPedestal[200]; /* ADC pedestal of tof channels */
};
