/* tofrCaliPars.idl
 *
 * tofrCaliPars
 *
 * description: // tofr offline calibration parameters -- year3
 */

struct tofrCaliPars {
  float TDCLowLimit; /* TDC low limit */
  float TDCHighLimit; /* TDC high limit */
  float NonLinTDCCut; /* cut for different nonliear correction func */
  float ADCCut; /* ADC cut for different slewing func */
  float TDCWidth; /* TDC bin width */
  float NonLinPar[12][6][8]; /* TDC non-linearity correction par */
  float T0BeforeSlewingPar[12][6]; /* T0 correction before TA slewing */
  float TASlewingPar[12][6][6]; /* TA slewing correction par */
  float T0AfterSlewingPar[12][6]; /* T0 correction after TA slewing */
  float ZPar[8]; /* local z position correction par */
  float T0AfterZPar[12][6]; /* T0 after Z correction */
};
