/* tofResolution.idl
 *
 * Tables: tofResolution
 *
 * description: // resolution for each TOF daq channel
 */

struct tofResolution {
  long entries; /* an index of entries */
  short daqChannel[200]; /* pVPD:0-5(11), TOFp:0-41, TOFr:0-71(119)... */
  short tdcChan[200]; /* CAMAC TDC channel Id */
  float resolution[200]; /* timing resolution of tof channels */
};
