/* tofr5Maptable.idl
 *
 * Tables: tofr5Maptable
 *
 * description:  Map btw TOFr5 module chan to MRPC channel */

struct tofr5Maptable {
  short tdigchan[192];   /* global channel number for TDIG boards       */ 
  short  modulechan[192]; /* global module channel number for tofr5 MRPC */
};

