/* tofr5INLtable
 *
 * Tables: tofr5 INL tables
 * blocks of forty
 * description: // INL correction tables information for TOFr5 TDIG
 */

struct tofr5INLtable {
  char boardID[8]; /*  10 TDIG boards in tofr5  */
  short boardNumber; /* TDIG board number   */
  short TDCID;    /*  40 TDCs on 10 TDIG boards */
  float INLcorrection[1024];  /* 40*1024 INL table corrections, 
                                TDC4 on each TDIG boards have only 
                                256 values */ 
};
