/*    tofSlatGeom.idl
*
*  Table: tofSlatGeom
*
*       description: //   geometry table per tof slat
*/ 


struct tofSlatGeom { 

   long  ieta;   /*   */
   float  z;   /*   */
   float  z_min;   /*   */
   float  z_max;   /*   */
   float  cosang;   /*   */
   float  r;   /*   */
   float  eta_min;   /*   */
   float  eta_max;   /*   */
   float  eta;   /*   */
   long  iphi;   /*   */
   float  phi;   /*   */
   float  phi_min;   /*   */
   float  phi_max;   /*   */
   long  trayId;   /*   */

 };  
