/* tofSimPars.idl
 *
 * tofSimPars
 *
 * description:  // MRPC-TOF simulator code parameters
 *
 */

struct tofSimPars {
  float par_nClusters[4]; /* parameters of 3rd polynomial function of number of
			     clusters vs. 1/sqrt(gamma) */
  float er; /* relative permittivity of the glass (w.r.t. that of free space)*/
  float d_inner; /* thickness of inner glass (mm) */
  float d_outer; /* thickness of outer glass (mm) */
  float d_gap; /* thickness of gap (mm) */
  long nGaps; /* number of gaps */
  float alpha; /* effective Tompson coefficient */
  long nClustersMax; /* saturation value of number of clusters */
  float vDriftMean; /* mean drifting velocity (mm/ps) */
  float vDriftErr; /* window size of difting velocity with uniform sampling 
		      (relative ratio w.r.t. mean velocity */
  float nEperCluster; /* mean number of electrons per cluster */
  float nEMax; /* saturation number of electrons */
  float vLight; /* speed of light (mm/ps) */
  float qElectron; /* electron charge (A*ps) */
  float Adcthreshold; /* adc threshold */
  float timeRes; /* timing resolution of MRPC */

  long nTbins; /* number of divided bins in timing scale */
  float TbinWidth; /* timing bin width */
  float T0; /* T0 in timing scale */

  float amp; /* amplifying ratio of charge signal */
  float AdcBinWidth; /* ADC bin width */
  float TdcBinWidth; /* TDC bin width (ps) */
};
