/* tofTDIGOnTray.idl
 *
 * Tables: tofTDIGOnTray
 *
 * description: // positioning of TDIG boards on trays 
*/

struct tofTDIGOnTray {
  short trayId;      /* tray Id */   
  short tdigId[8];   /* serial numbers of TDIG boards on this tray */
};
