/* tofTOffset.idl
 *
 * Tables: tofTOffset
 *
 * description: T0 of each channel of TOF dectectors (valid since Run8)
 *
 */

struct tofTOffset {
  short trayId;
  float T0[192];      /* Time offset of each module channel */
};
