/* tofTrgWindow
 *
 * Tables: tofTrgWindow
 *
 * description: // tof trigger timestamp window cuts to select physical hits
 */

struct tofTrgWindow {
  unsigned short trgWindow_Min;    /*  trigger time window cuts */       
  unsigned short trgWindow_Max;    /*  trigger time window cuts */
};
