/*toft0Calib.idl
*
*Table: toft0Calib
*
*	description: // TOF t0 calibration parameters
*	array index = trayid(TOF tray ID 1-120) * moduleid(TOF module ID 1-32) * cellid(TOF cell ID 1-6)
*/

struct toft0Calib{
	float t0corr[23040];	/*TOF t0 correction */
};