/* tofTrayConfig.idl
 *
 * Tables: tofTrayConfig
 *
 * description: // structure configuration for the trays of MRPC-TOF
 */

struct tofTrayConfig {
  long entries;
  short iTray[120]; /* number Id of the trays of MRPC-TOF */
  short nModules[120]; /* total number of modules in this tray */
};
