/* tofTzero.idl
 *
 * Tables: tofTzero
 *
 * description: T0 of each daq channel of TOF dectectors
 *
 */

struct tofTzero {
  long entries;
  short daqChannel[200]; /* pVPD:0-5(11), TOFp:0-41, TOFr:0-71(119)... */
  short tdcChan[200]; /* CAMAC TDC# 0-119(184)... */
  float Tzero[200]; /* Time offset of each daq channel */
};
