/* tofTotbCorr
 *
 * Tables: tof Tot Calibration Correction tables, binary format
 * description: // Tdc-Tot Correction parameters
 */

struct tofTotbCorr {
  short trayId;   /* trayId (1:120), -1 for East (u)pVPD, -2 for West (u)pVPD */
  short moduleId; /* moduleId (1:32) - for cell-by-cell corr */
  short cellId;  /* cellId (1:6) - for cell-by-cell corr */
  short tdcId;   /* boardId(1:8)+tdcId(1:4) - for production */
  float tot[60]; /* edge of tot intervals for corr */
  float corr[60];   /* absolute corr value */
};
