/* tofTACorr.idl
 *
 * tofTACorr
 *
 * description: // TA slewing correction parameters for tof calibration
 */

struct tofTACorr {
  long  npar;  /* number parameters in polynomial fit */
  short daqChannel[200]; /* pVPD:0-5(11), TOFp:0-41, TOFr:0-71(119)... */
  short tdcChan[200]; /* CAMAC TDC# 0-119(184)... */
  float a[2000];  /* parameters of polynomial fit */
};
