/* tofZbCorr.idl
 *
 * Tables: tof Z Calibration Correction tables, binary format
 * description: // Tdc-Z Correction parameters
 */

struct tofZbCorr {
  short trayId;   /* trayId (1:120) */
  short moduleId; /* moduleId (1:32) - for cell-by-cell corr */
  short cellId;   /* cellId (1:6) - for cell-by-cell corr */
  float z[60]; /* edge of z intervals for corr */
  float corr[60];   /* absolute corr value */
  octet N; /* useable size of the array */
};
