/*
  :Description: 
  :Synonyms::::
  :Source:
  :Update:
  :Update frequncy:
  :Reminder:
  :Recall frequency:
  :Size of Data:
  :Pointer to data:  TPCPadplanes.time:
*/
struct tpc_padplanes {
  /*  type varnam;      Units : Comments */

    long   padRows;
    long   innerPadRows;
    long   innerPadRows48;
    long   innerPadRows52;
    long   outerPadRows;
    long   superInnerPadRows;
    long   superOuterPadRows;

    double innerSectorPadWidth;
    double innerSectorPadLength;
    double innerSectorPadPitch;
    double innerSectorRowPitch1;
    double innerSectorRowPitch2;
    double firstPadRow;
    double firstOuterSectorPadRow;
    double lastOuterSectorPadRow;
    double firstRowWidth;
    double lastRowWidth;
    double outerSectorPadWidth;
    double outerSectorPadLength;
    double outerSectorPadPitch;
    double outerSectorRowPitch;
    double outerSectorLength;
    double ioSectorSeparation;
    double innerSectorEdge;
    double outerSectorEdge;
 
    long   innerPadsPerRow[13];
    long   outerPadsPerRow[32];
    double innerRowRadii[13];
    double outerRowRadii[32];
};

/* $Log $ */
