/*    TpcAltroParameters.idl
*
*  Table: TpcAltroParameters
*
*       description:
*       N = no. of Altro parameters, 
*       N = 0  => filter is switched off
*       N = -1 => old TPC electronics
*       Altro::ConfigTailCancellationFilter(int K1, int K2, int K3, int L1, int L2, int L3)
*       altro_reg[6] is  
*	altro_reg[0] =  K1 coefficient of the TCF
*	altro_reg[1] =  K2 coefficient of the TCF
*	altro_reg[2] =  K3 coefficient of the TCF
*	altro_reg[3] =  L1 coefficient of the TCF
*	altro_reg[4] =  L2 coefficient of the TCF
*	altro_reg[5] =  L3 coefficient of the TCF
*/ 
struct TpcAltroParameters { 
  long N;               /*  = no. of Altro parameters */
  long altro_reg[6];    /* Altro parameters per sector*/
 };  
