/*    tpcAvCurrent.idl
*
*  Table: tpcAvCurrent
*
*       description: Accumulate charge for inner and outer sectors
*       from slow control  tpchv:SUM_CURR_1 and  tpchv:SUM_CURR_0, respectively
*       since 2006-01-01 00:00:00  
*/ 


struct tpcAvCurrent { 
  long            run;       /* run no. which was used for current averaging */
  float           currentI;  /* all Inner Sectors averaged current per run (uA) */
  float           currentO;  /* all Outer Sectors averaged current per run (uA) */
  float           chargeI;   /* all Inner Sectors (C) */
  float           chargeO;   /* all Outer Sectors (C) */

 };  
