struct TpcAvgPowerSupply { 
  long  run;               /* run no. used for averaging  */
  long  start_time;        /* begin unix time of averaging interval */
  long  stop_time;         /* end   unix time of averaging interval */
  float Current[192];      /* average current per sector(24) and channel(8) [muA]*/
  float Charge[192];       /* accumulated charge per sector(24) and channel(8) [C]*/
  float Voltage[192];      /* average Voltage per sector(24) and channel(8) [V]*/
};  
