/*    tpcAnodeHV.idl
*
*  Table: tpcAnodeHVavg
*
*       description: average voltages over stable periods of time, 
*/ 


struct tpcAnodeHVavg { 

   unsigned short  sector;   /*  sector 1-24 */
   unsigned short  socket;   /*  MWC socket/card (ISOR=17,OSIR=18,OSOR=19)  */
   float  voltage;           /*  average voltage  */
   float  rms;               /*  rms for averaged voltage */
   long    numentries;		 /*  number of entries used for average */
   long    numoutliers;       /*  number of encountered outliers */
 };  
