/*    tpcAltroParams.idl
 *
 *  Table: tpcAltroParams
 *
 *       description: Parameters of Altro cheap configuration
 *       N = no. of Altro parameters, 
 *       N = 0  => filter is switched off
 *       N = -1 => old TPC electronics
 *       Altro::ConfigZerosuppression(int Threshold, int MinSamplesaboveThreshold, int Presamples, int Postsamples)
 *       Altro::ConfigTailCancellationFilter(int K1, int K2, int K3, int L1, int L2, int L3)
 */ 
struct tpcAltroParams { 
  long N;               /*  = no. of Altro parameters */
  long Altro_thr; //  Threshold
  long Altro_seq; //  MinSamplesaboveThreshold
  long Altro_K1;  //  K1 coefficient of the TCF
  long Altro_K2;  //  K2 coefficient of the TCF
  long Altro_K3;  //  K3 coefficient of the TCF
  long Altro_L1;  //  L1 coefficient of the TCF
  long Altro_L2;  //  L2 coefficient of the TCF
  long Altro_L3;  //  L3 coefficient of the TCF
 };  
