/*    tpcAcCharge.idl
*
*  Table: tpcAcCharge
*
*       description: Accumulate charge for inner and outer sectors
*       from slow control  tpchv:SUM_CURR_1 and  tpchv:SUM_CURR_0, respectively
*       since 2006-01-01 00:00:00  
*/ 


struct tpcAcCharge { 
  float           chargeI;   /*  all Inner Sectors */
  float           chargeO;   /*  all Outer Sectors */

 };  
