/*    tpcAnodeHV.idl
*
*  Table: tpcAnodeHV
*
*       description:
*/ 


struct tpcAnodeHV { 

   unsigned short  sector;   /*  sector 1-24 */
   unsigned short  socket;   /*  MWC socket/card (ISOR=17,OSIR=18,OSOR=19)  */
   double  voltage;         /*   HV setting  */

 };  
