//:Description: Drift Distance depended correction
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  tpcCorrectionX.time:
struct tpcCorrectionX {
  long   type;  // type = 0 polymonical fit,                                        use only [min,max]
                // type = 1 TChebyshev poly in range [min,max] => [-1,1]           
                // type = 2 shifted  TChebyshev poly in range [min,max] => [ 0,1]  
                // type = 3 X => Log(1 - |x|)                                       use only [min,max]
                // type = 4 X => Log(1 - |x|)*sign(x)                                -"-
                // type = 5 X => Log(x), for x <= 1 => 0
                // type = 10 (== log(1. + OffSet/x) + poly(x,npar))                  -"-
                // type = 11 (== log(1. + OffSet/x) + poly(x,npar) for log(ADC) and |Z|
                // type = 200 cut on range [min,max]
                // type = 300 don't correct out of range [min,max]
  long   idx; // row index
  long   nrows; // total no. of real rows in the table; For Db interface (where nrows = 50)
  long   npar;  // npar < 0, X = exp(x) paramterization; abs(npar) >= 100 cut on range [min.max]
  double OffSet;// use for type = 10 (== log(1. + OffSet/x) + poly(x,npar)
  double min;   // fit range
  double max;   // 
  double a[10];  // a[npar]
};
