/*    tpcCalibResolutions.idl
*
*  Table: tpcCalibResolutions
*
*       description: Table for Resolutions of TPC Calibrations
*/

struct tpcCalibResolutions {

    float   SpaceCharge;     /* SpaceCharge correction */
    float   GridLeak;        /* GridLeak correction */
    char    comment[255];    /* comments */

};