/*    tpcChargeEvent.idl
*
*  Table: tpcChargeEvent
*
*       description: Table of events depositing significant charge into the TPC;
*                    bunchCrossing is stored as 32-bit pairs because no 64-bit integer
*                    works with the database, i.e. the first bunch crissing is actually
*                    (eventBunchCrossingsHigh[0] << 32) + eventBunchCrossingsLow[0]
*                    with appropriate 32-to-64 conversion before bit-shifting
*/ 


struct tpcChargeEvent { 

   long nChargeEvents; /* number of charge events in this record */
   unsigned long eventBunchCrossingsLow[4096]; /* number of bunches into the run when charge event occurred (32 low bits) */
   unsigned long eventBunchCrossingsHigh[4096]; /* number of bunches into the run when charge event occurred (32 high bits) */
   float  eventCharges[4096]; /* metric of magnitude of charge deposited in TPC */
   long badBunch; /* collider bunch where most of the charge events occurred */

 };  
