//:Description: Drift Distance depended correction
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  TpcdEdxCor.time:
struct TpcdEdxCor {
  long  npar; 	
  float min;   // fit range
  float max;   // 
  float a[10];  // a[npar]
};
