/*    tpcDriftVelocity.idl
*
*  Table: tpcDriftVelocity
*
*       description:
*/ 

struct tpcDriftVelocity { 
  float  laserDriftVelocityEast;   /*   cm/us : from laser beam analysis  */
  float  laserDriftVelocityWest;   /*   cm/us : from laser beam analysis  */
  float  cathodeDriftVelocityEast; /*   cm/us : from cathode emission  */
  float  cathodeDriftVelocityWest; /*   cm/us : from cathode emission  */
 };  
