/*    tpcDedxPidCalib.idl
*
*  Table: tpcDedxPidCalib
*
*       description: //  dedx calibration parameters done at dst production
*/ 


struct tpcDedxPidCalib { 

   float  gasCalib;   /*   calibration  for variations in gas gain  */
   float  electronBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  electronAmpPar[4];   /*   parameters for describing the amplitude  */
   float  electronResoPar[2];   /*   parameters for describing the resolution  */
   float  pionMinusBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  pionMinusAmpPar[4];   /*   parameters for describing the amplitude  */
   float  pionMinusResoPar[2];   /*   parameters for describing the resolution  */
   float  kaonMinusBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  kaonMinusAmpPar[4];   /*   parameters for describing the amplitude  */
   float  kaonMinusResoPar[2];   /*   parameters for describing the resolution  */
   float  antiProtonBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  antiProtonAmpPar[4];   /*   parameters for describing the amplitude  */
   float  antiProtonResoPar[2];   /*   parameters for describing the resolution  */
   float  positronBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  positronAmpPar[4];   /*   parameters for describing the amplitude  */
   float  positronResoPar[2];   /*   parameters for describing the resolution  */
   float  pionPlusBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  pionPlusAmpPar[4];   /*   parameters for describing the amplitude  */
   float  pionPlusResoPar[2];   /*   parameters for describing the resolution  */
   float  kaonPlusBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  kaonPlusAmpPar[4];   /*   parameters for describing the amplitude  */
   float  kaonPlusResoPar[2];   /*   parameters for describing the resolution  */
   float  protonBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  protonAmpPar[4];   /*   parameters for describing the amplitude  */
   float  protonResoPar[2];   /*   parameters for describing the resolution  */
   float  deuteronBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  deuteronAmpPar[4];   /*   parameters for describing the amplitude  */
   float  deuteronResoPar[2];   /*   parameters for describing the resolution  */
   float  chargedBandPar[7];   /*   parameters for Bethe_Block distribution  */
   float  chargedResoPar[2];   /*   parameters for describing the resolution  */

 };  
