//:Description: Drift Distance depended correction
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  TpcDriftDistCorr.time:
struct TpcDriftDistCorr {
  float a0;  // Qudratic interpolation for correction
  float a1;  // exp(-(a0+a1*z+a2*z*z); z is distance from membrane (z = -Z for Sector > 12)
  float a2;  // Separate correction for outer(<=24) and inner (>24)
};
