/*    tpcEffectiveGeomB.idl
*
*  Table: tpcEffectiveGeomB
*
*       description:
*/ 


struct tpcEffectiveGeomB { 

  double  drift_length_correction;   /*  cm: Diff between actual drift length and  */
  double  z_inner_offset;            /*  cm: Effective distance between  */
  double  z_outer_offset;            /*  cm: Effective distance between  */
  double  z_inner_offset_West;       /*  cm: Effective distance West with respect to East */
  double  z_outer_offset_West;       /*  cm: Effective distance West  -"-                 */
 };  
