/*    tpcExtraGainCorrection.idl
*
*  Table: tpcExtraGainCorrection
*
*       description: list of pad with bad pulser data
*/ 
struct tpcExtraGainCorrection { 
  octet   idx; // active line number >= 1
  octet   nrows;// total no. of active rows;
  long    runMin;
  long    runMax;
  octet   sector;
  octet   row;
  short   padMin;
  short   padMax;
  octet   RDO;
  octet   FEE; // if positive reactivate intire FEE else if negative use row and [padMin,padMax] range
  octet   status; // 0 => dead, 1 => Alive
 };  
