/*    tpcEffectiveGeom.idl
*
*  Table: tpcEffectiveGeom
*
*       description:
*/ 


struct tpcEffectiveGeom { 

   double  drift_length_correction;   /*  cm: Diff between actual drift length and  */
   double  z_inner_offset;   /*  cm: Effective distance between  */
   double  z_outer_offset;   /*  cm: Effective distance between  */

 };  
