/*    tpcFeeGainCor.idl
*
*  Table: tpcFeeGainCor
*  
*       description: Tpc gain correction for half Fee (even/odd)
*/ 


struct tpcFeeGainCor { 

   float  Gain[182][2];   /*  Gains per Fee and even/odd padrow */

 };  
