/*    tpcFieldCageShort.idl
*
*  Table: tpcFieldCageShort
*
*       description: *    provide info on shorted rings in the field cages
*/ 


struct tpcFieldCageShort { 

   float side;     /* 0 = east, 1 = west */
   float cage;     /* 0 = inner, 1 = outer */
   float ring;     /* ring location of the short (e.g. 169.5) */
   float resistor; /* MOhm value of added external resistor to resistor chain */
   float MissingResistance; /* missing resistance */

 };  
