/*:Description: 
  :Synonyms::::
  :Source:
  :Update:
  :Update frequncy:
  :Reminder:
  :Recall frequency:
  :Size of Data:
  :Pointer to data:  
*/
struct tpcFieldCage {

  /*  type varnam;      Units : Comments */

  float innerFieldCageShift;     /* cm : z shift of inner field cage w.r.t outer field cage */
  float eastClockError;     /* radians :  Phi rotation of East end of TPC in radians */
  float westClockError;     /* radians :  Phi rotation of West end of TPC in radians */

};

/*  Last mod. for tpcFieldCage:  $Log $  */

