/*    tpcGainMonitor.idl
*
*  Table: tpcGainMonitor
*
*       description: *         UCLA gain monitor chamber
*/ 


struct tpcGainMonitor { 

   float  center;   /*   */
   float  height;   /*   */
   float  width;   /*   */

 };  
