/*    tpcGridLeak.idl
*
*  Table: tpcGridLeak
*
*       description: Table for TPC GridLeaks
*/ 


struct tpcGridLeak { 

   double  InnerGLRadius;   /* Radius of GL around inner sectors           */
   double  MiddlGLRadius;   /* Radius of GL between inner/outer sectors    */
   double  OuterGLRadius;   /* Radius of GL around outer sectors           */

   double  InnerGLWidth;    /* Width of GL around inner sectors            */
   double  MiddlGLWidth;    /* Width of GL between inner/outer sectors     */
   double  OuterGLWidth;    /* Width of GL around outer sectors            */

   double  InnerGLStrength; /* Strength of GL around inner sectors         */
   double  MiddlGLStrength; /* Strength of GL between inner/outer sectors  */
   double  OuterGLStrength; /* Strength of GL around outer sectors         */

 };  
