/*:Description: 
  :Synonyms::::
  :Source:
  :Update:
  :Update frequncy:
  :Reminder:
  :Recall frequency:
  :Size of Data:
  :Pointer to data:  
*/
struct tpcGlobalPosition {

  /*  type varnam;      Units : Comments */

  float LocalxShift;     /* cm : x position of TPC center in magnet frame */
  float LocalyShift;     /* cm : y position of TPC center in magnet frame */
  float LocalzShift;     /* cm : z position of TPC center in magnet frame */

  //use direction cosines

  float PhiXY;         /* radians: rotation angle around z axis */
  float PhiXZ;         /* radians: rotation angle around y axis */
  float PhiYZ;         /* radians: rotation angle around x axis */
  float XX;            /* XX element of rotation matrix */
  float YY;            /* YY element of rotation matrix */
  float ZZ;            /* ZZ element of rotation matrix */ 

};

/*  Last mod. for tpcGlobalPosition:  $Log $  */

