//:Description: 
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  TPCGas.time:
struct tpcGas {

  //  type varnam;    //Units : Comments
  float barometricPressure;        // mbar : TPC-PT_B
  float inputTPCGasPressure;       // mbar : TPC-PT_8 @ 7 o'clock
  float nitrogenPressure;          // mbar : TPC-PI_15
  float gasPressureDiff;           // mbar : TPC-PT_7

  float inputGasTemperature;       // degrees K: TPC-T4
  float outputGasTemperature;      // degrees K: TPC-T5

  // Gas input values:
  float flowRateArgon1;            // liters/min : TPC-FM_5
  float flowRateArgon2;            // liters/min : TPC-FM_4
  float flowRateMethane;           // liters/min : TPC-FM_11
  float percentMethaneIn;          // percent    : TPC-CH4_M4
  float ppmOxygenIn;               // ppm        : TPC-O2_M1

  // Gas exhaust values:
  float flowRateExhaust;           // liters/min : TPC-PT11
  float percentMethaneOut;         // ppm        : TPC-CH4_M3
  float ppmWaterOut;               // ppm        : TPC-H2O_M2
  float ppmOxygenOut;              // scf/hr     : TPC-O2_M5
  float flowRateRecirculation;     // liters/min : TPC-FI_7

};
