/*    tpcHighVoltages.idl
*
*  Table: tpcHighVoltages
*
*       description: //  Cathode and gating grid voltage for ExB distortions
*/ 


struct tpcHighVoltages { 

   float  cathode;   /*   kVolts  */
   float  gatedGridRef;   /*   Volts - nominal TPC value but is set by 48 sub-sectors  */
   float  gridLeakWallTip[24];   /*   Volts - iTPC GridLeak wall tip voltage for 24 sectors  */
   float  gridLeakWallSide[24];   /*   Volts - iTPC GridLeak wall side voltage for 24 sectors  */
                                  /*   above +100 means no wall  */

 };  
