/*    tpcHVPlanes.idl
*
*  Table: tpcHVPlanes
*
*       description: orientation of TPC HV planes:
*                    central membrane
*                    east gated grid
*                    west gated grid
*/ 


struct tpcHVPlanes { 

   float CM_shift_z;   /* physical z shift of the CM plane                      */
   float CM_tilt_x;    /* x component of the CM plane's normal unit vector      */
   float CM_tilt_y;    /* y component of the CM plane's normal unit vector      */
   float GGE_shift_z;  /* physical z shift of the GG East plane                 */
   float GGE_tilt_x;   /* x component of the GG East plane's normal unit vector */
   float GGE_tilt_y;   /* y component of the GG East plane's normal unit vector */
   float GGW_shift_z;  /* physical z shift of the GG West plane                 */
   float GGW_tilt_x;   /* x component of the GG West plane's normal unit vector */
   float GGW_tilt_y;   /* y component of the GG West plane's normal unit vector */

 };
