/*:Description: 
  :Synonyms::::
  :Source:
  :Update:
  :Update frequncy:
  :Reminder:
  :Recall frequency:
  :Size of Data:
  :Pointer to data:  
*/
struct tpcHitErrors {

  /*  type varnam;      Units : Comments */

  float sig2_intrinsic_outer_x;     /* cm^2 : Intrinsic resolution, outer sector, padrow direction*/
  float sig2_drift_outer_x;     /* cm^2 : Drift dependent resolution, outer sector, padrow direction*/
  float sig2_tan_outer_x;     /* cm^2 : angular wire dependent resolution, outer sector, padrow direction*/
  float sig2_intrinsic_outer_z;     /* cm^2 : Intrinsic resolution, outer sector, z direction*/
  float sig2_drift_outer_z;     /* cm^2 : Drift dependent resolution, outer sector, z direction*/
  float sig2_tan_outer_z;     /* cm^2 : angular wire dependent resolution, outer sector, z direction*/

  float sig2_intrinsic_inner_x;     /* cm^2 : Intrinsic resolution, inner sector, padrow direction*/
  float sig2_drift_inner_x;     /* cm^2 : Drift dependent resolution, inner sector, padrow direction*/
  float sig2_tan_inner_x;     /* cm^2 : angular wire dependent resolution, inner sector, padrow direction*/
  float sig2_intrinsic_inner_z;     /* cm^2 : Intrinsic resolution, inner sector, z direction*/
  float sig2_drift_inner_z;     /* cm^2 : Drift dependent resolution, inner sector, z direction*/
  float sig2_tan_inner_z;     /* cm^2 : angular wire dependent resolution, inner sector, z direction*/

};

/*  Last mod. for tpcHitErrors:  $Log $  */

