/*    tpcHighVoltages.idl
*
*  Table: tpcHighVoltages
*
*       description: //  Cathode and gating grid voltage for ExB distortions
*/ 


struct tpcHighVoltages { 

   float  cathode;   /*   kVolts  */
   float  gatedGridRef;   /*   Volts - nominal TPC value but is set by 48 sub-sectors  */

 };  
