/*    tpcOmegaTau.idl
*
*  Table: tpcOmegaTau
*
*       description: Table for TPC OmegaTau
*/ 


struct tpcOmegaTau { 

   float  tensorV1;   /* tensor for OmegaTau           */
   float  tensorV2;   /* tensor for OmegaTau    */
   unsigned short  distortionCorrectionsMode;   /* modes for field distortion and non-uniformity corrections  */

 };  
