/*    tpcPadGainT0.idl
*
*  Table: tpcPadGainT0
*
*       description:
*/ 


struct tpcPadGainT0 { 
  long run;                   /* pulser run number used */
  float  Gain[24][45][182];   /* Gains per pad*/
  float  T0[24][45][182];     /* T9 per pad*/
 };  
