/*    tpcPadResponse.idl
*
*  Table: tpcPadResponse
*
*       description: //  trs parameters for pad response functions
*/ 


struct tpcPadResponse { 

   float  innerGasGainFluctuation;   /*   unitless  */
   float  outerGasGainFluctuation;   /*   unitless  */
   float  innerPadResponseSigma;   /*   cm  */
   float  outerPadResponseSigma;   /*   cm  */
   float  innerWirePadCoupling;   /*   cm  */
   float  outerWirePadCoupling;   /*   cm  */
   float  innerRowNormalization;   /*   unitless  */
   float  outerRowNormalization;   /*   unitless  */
   float  innerCouplingFunctionConstants[4];   /*   unitless  */
   float  outerCouplingFunctionConstants[4];   /*   unitless  */
   float  innerChargeFractionConstants[6];   /*   unitless  */
   float  outerChargeFractionConstants[6];   /*   unitless  */
   float  errorFunctionRange;   /*   unitless  */
   long  errorFunctionEntry;   /*   unitless  */
   float  longitudinalDiffusionConstant;   /*   cm/sqrt(cm)  */
   float  transverseDiffusionConstant;   /*   cm/sqrt(cm)  */
   float  InnerOuterFactor;   /*   dimensionless  */

 };  
