/*    tpcPedestal.idl
*
*  Table: tpcPedestal
*
*       description:
*/ 


struct tpcPedestal { 

   float  Pedestal[100][182];   /*  Pedestals per */
   float  Rms[100][182];        /*  Rms per */
 };  
