//:Description: 
//:Synonyms::::
//:Source:
//:Update:
//:Update frequency:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  tpcPowerSupply.time:
struct tpcPowerSupply {

  //     type varnam;    //Units : Comments
  float  Voltages[96];   // volts
  float  Currents[96];   // micro Amper
  long   Status[96];   
  long   Reason;

};
