/*    tpcPedestal.idl
*
*  Table: tpcPedestal
*
*       description:
*/ 


struct tpcPedestal { 

   float  Pedestal[45][182];   /*  Pedestals per */
   float  Rms[45][182];        /*  Rms per */
 };  
