//:Description: Correction to reconstructed cluster position in pads
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  TpcPadCorrection.time:
struct TpcPadCorrection {
  char  HistName[32]; // Original histogram name
  char  Type[8];      // Polynomial type 
  short npads;        // no. of pad in cluster; npads = 1 => all
  short InOut;        // = 1 inner,  = 2 outer sectors
  short N;            // order of polymial
  short R;            // type of polynomial, see StarRoot/TPolynomial
  double a0,a1,a2,a3,a4,a5,a6,a7,a8,a9; // coefficients
  double prob;        // fit probability

};
