/*    tpcPadGainT0B.idl
*
*  Table: tpcPadGainT0B
*
*       description:
*/ 


struct tpcPadGainT0B { 
  long run;                   /* pulser run number used */
  float  Gain[100][182];   /* Gains per pad*/
  float  T0[100][182];     /* T0 per pad*/
 };  
