/*    tpcRDOT0offset.idl
*
*  Table: tpcRDOT0offset
*
*       description:
*/ 


struct tpcRDOT0offset { 
  octet  isShifted[24];/* flag if there is any RDO off set to tsector */
  float  t0[24][10];   /* RDO t0 offset per sector: [0-23], rdo [0-5] Tpx, [6-9] iTpc  (time bins) */
 };  
