/*    TpcResponseSimulator.idl
*
*  Table: TpcResponseSimulator
*
*       description: //  Tpc Response Simulator parameters
*/ 


struct TpcResponseSimulator { 

  float  I0;                   /* = 13.1 eV, CH4 */		       
  float  Cluster;    	       /* = 3.2, average no. of electrons per primary  */			       
  float  W;          	       /* = 26.2 eV */								       
  float  OmegaTau;   	       /* = 3.02, fit of data */
  float  K3IP;       	       /* = 0.68,(pads) for a/s = 2.5e-3 and h/s = 0.5 */
  float  K3IR;       	       /* = 0.89,(row)  for a/s = 2.5e-3 and h/s = 0.5 */
  float  K3OP;       	       /* = 0.55,(pads) for a/s = 2.5e-3 and h/s = 1.0 */
  float  K3OR;       	       /* = 0.61,(row)  for a/s = 2.5e-3 and h/s = 1.0 */
  float  FanoFactor; 	       /* = 0.3 */                                                                       
  float  AveragePedestal;      /* = 50.0 */
  float  AveragePedestalRMS;   /* = 1.4, Old Tpc electronics */
  float  AveragePedestalRMSX;  /* = 0.7, New Tpx electronics */
  float  tauIntegration;       /* = 2.5*74.6e-9  secs */
  float  tauF;                 /* = 394.0e-9 secs Tpc */
  float  tauP;                 /* = 775.0e-9 secs Tpc */
  float  tauXI;                /* =  60.0e-9 secs Tpx Inner integration time */
  float  tauXO;                /* =  74.6e-9  secs Tpx Outer integration time */
  float  tauCI;                /* =   0  */
  float  tauCO;                /* =   0  */
  float  SigmaJitterTI;        /* = 0.2  for Tpx inner */
  float  SigmaJitterTO;        /* = 0.2  for Tpx outer */
  float  SigmaJitterXI;        /* = 0.0  for Tpx inner */
  float  SigmaJitterXO;        /* = 0.0  for Tpx outer */
  float  longitudinalDiffusion;/*   cm/sqrt(cm)  */
  float  transverseDiffusion;  /*   cm/sqrt(cm)  */
  float  NoElPerAdc;           /* = 335, No. of electrons per 1 ADC count, keep for back compartibility */
  float  NoElPerAdcI;          /* = 335, No. of electrons per 1 ADC count for inner TPX */
  float  NoElPerAdcO;          /* = 335, No. of electrons per 1 ADC count for outer TPX */
  float  NoElPerAdcX;          /* = 335, No. of electrons per 1 ADC count for iTPC      */
  float  OmegaTauScaleI;       /* = 2.145, effective reduction of OmegaTau near 
				  Inner sector anode wire */
  float  OmegaTauScaleO;       /* = 1.8, effective reduction of OmegaTau near 
				  Outer sector anode wire */
  float  SecRowCorIW[2];  /* parameterization of Inner West correction vs row */
  float  SecRowCorOW[2];  /* parameterization of Outer West correction vs row */
  float  SecRowCorIE[2];  /* parameterization of Inner East correction vs row */
  float  SecRowCorOE[2];  /* parameterization of Outer East correction vs row */

  float  SecRowSigIW[2];  /* parameterization of Inner West gain sigma vs row */
  float  SecRowSigOW[2];  /* parameterization of Outer West gain sigma vs row */
  float  SecRowSigIE[2];  /* parameterization of Inner East gain sigma vs row */
  float  SecRowSigOE[2];  /* parameterization of Outer East gain sigma vs row */
  float  PolyaInner;      /* = 1.38, Polya parameter for inner sectors */
  float  PolyaOuter;      /* = 1.38, Polya parameter for outer sectors */
  float  T0offset;        /* = 0.0   extra off set for Altro chip */
  float  T0offsetI;       /* = 0.0   extra off set for inner sector */
  float  T0offsetO;       /* = 0.0   extra off set for outer sector */
  float  FirstRowC;       /* = 0.0   extra correction for the first pad row */
 };  
