/*    tpcRDOMasks.idl
*
*  Table: tpcRDOMasks
*
*       description:
*/ 


struct tpcRDOMasks { 

   unsigned long  runNumber;   /*       run number  */
   unsigned long  sector;   /*   sector  */
   unsigned long  mask;   /*   enable mask  */

 };  
