/*    tpcRDOMap.idl
*
*  Table: tpcRDOMap
*
*       description: Map tpc row, pad range [padMin, padMax] to rdo number
*/ 


struct tpcRDOMap { 
  long  idx;   // row index
  long  nrows; // total no. of real rows in the table; For Db interface (where nrows = 50)
  octet row;
  octet padMin;
  octet padMax;
  octet rdo;
 };  
