
struct tpcSlewing {
  long   type;  // type = 0 polymonical fit,
                // type = 1 TChebyshev poly in range [min,max] => [-1,1]
                // type = 2 shifted  TChebyshev poly in range [min,max] => [ 0,1]
                // type = 10 (== log(1. + OffSet/x) + poly(x,npar)
                // type = 200 cut on range [min.max]
  long   npar;  // npar < 0, X = exp(x) paramterization; abs(npar) >= 100 cut on range [min.max]
  double OffSet;// use for type = 10 (== log(1. + OffSet/x) + poly(x,npar)
  double min;   // fit range
  double max;   // 
  double a[10];  // a[npar]
};
