/*    tpcSCGL.idl
*
*  Table: tpcSCGL
*
*       description: Table for SpaceCharge and GridLeak Correction parameters
*       SC parameters: 4 array elements for west, plus 4 for east = 8,
*          each of the 4 elements are additive terms in the SC formula
*       GL parameters: 24 array elements for TPC sectors,
*          plus radius and width of the charge sheet
*       scaler and mode definitions in StDetectorDbMaker/St_tpcSCGLC.h
*/ 


struct tpcSCGL { 

   float   SC[8];         /* Scale factor relating luminosity scaler to SpaceCharge */
   float   SCoffset[8];   /* Offset to define luminosity for SpaceCharge */
   float   SCexponent[8]; /* Luminosity exponential factor for SpaceCharge */
   float   SCscaler[8];   /* Luminosity detector scaler */

   float   GL[24];        /* Scale factor relating SpaceCharge to GridLeak */
   float   GLoffset[24];  /* Offset to define luminosity for GridLeak */
   float   GLradius;      /* Radius of GridLeak between inner/outer sectors */
   float   GLwidth;       /* Width of GridLeak between inner/outer sectors */

   long    mode;          /* Modes to simplify parameter controls */

   char    comment[256];

 };
