/*    tpcSectorT0offset.idl
*
*  Table: tpcSectorT0offset
*
*       description:
*/ 


struct tpcSectorT0offset { 

   float  t0[48];   /* Sector t0 offset per sector: [0-23] Tpx, [24-47] iTpc  (time bins)*/

 };  
