/*    tpcSectorPosition.idl
*
*  Table: tpcSectorPosition
*
*       description:
*      This table rotates the inner and outer sector points using the following
*      steps:
*      1) move x position (sector 12 coordinates) by outerSectorLocalxShift
*      2) Rotate outer points clockwise by outerSectorRotationAngle about
*         point (0,123cm).
*      3) Rotate inner points clockwise by innerSectorRotationAngle about
*         point (0,123cm)
*/ 


struct tpcSectorPosition { 

   float  innerSectorLocalxShift;   /*   cm : shift in local x coord.  */
   float  innerSectorLocalyShift;   /*   cm : shift in local y coord.  */
   float  innerSectorRotationAngle;   /*   degrees : clockwise rotation  */
   float  innerSectorCovMatrix;   /*   0  */
   float  outerSectorLocalxShift;   /*   cm : shift in local x coord.  */
   float  outerSectorLocalyShift;   /*   cm : shift in local y coord.  */
   float  outerSectorRotationAngle;   /*   degrees : clockwise rotation  */
   float  outerSectorCovMatrix;   /*   0  */

 };  
