/*    TpcSecRowCor.idl
*
*  Table: TpcSecRowCor
*  
*       description: Tpc gain correction for sector & row
*/ 


struct TpcSecRowCor { 
  float  GainScale[100];   /*  Gains for sector & row */
  float  GainRms[100];     /*  RMS  - " -  */
 };  
