/*    tpcSlowControlSim.idl
*
*  Table: tpcSlowControlSim
*
*       description:
*/ 


struct tpcSlowControlSim { 

   double  driftVelocity;   /*   */
   double  driftVoltage;   /*   */
   double  innerSectorAnodeVoltage;   /*   */
   double  innerSectorGatingGridV;   /*   */
   double  outerSectorAnodeVoltage;   /*   */
   double  outerSectorGatingGridV;   /*   */
   double  innerSectorGasGain;   /*   */
   double  innerSectorGasGainVzero;   /*   */
   double  innerSectorGasGainb;   /*   */
   double  outerSectorGasGain;   /*   */
   double  outerSectorGasGainVzero;   /*   */
   double  outerSectorGasGainb;   /*   */
   double  hallPressure;   /*   */
   double  hallTemperature;   /*   */

 };  
