/*    TpcSecRowCor.idl
*
*  Table: TpcSecRowCor
*  
*       description: Tpc gain correction for secot row
*/ 


struct TpcSecRowCor { 
  float  GainScale[45];   /*  Gains for sector & row */
  float  GainRms[45];     /*  RMS  - " -  */
 };  
