/*    tpcTimeNorms.idl
*
*  Table: tpcTimeNorms
*
*       description:
*/ 


struct tpcTimeNorms { 

   float  innerNorm[24];   /*   Sector-to-Sector corrections  */
   float  outerNorm[24];   /*   Sector-to-Sector corrections  */

 };  
