//:Description: Time depended Gain scale factor
//:Synonyms::::
//:Source:
//:Update:
//:Update frequncy:
//:Reminder:
//:Recall frequency:
//:Size of Data:
//:Pointer to data:  TpcTimeGain.time:
struct TpcTimeGain {
  float ScaleFactor;
  float ErrorScaleFactor;
};
