/*    tpcWirePlanes.idl
*
*  Table: tpcWirePlanes
*
*       description:
*/ 


struct tpcWirePlanes { 

   double  anodeWireRadius;   /*   */
   double  frischGridWireRadius;   /*   */
   double  gatingGridWireRadius;   /*   */
   double  anodeWirePitch;   /*   */
   double  frischGridWirePitch;   /*   */
   double  gatingGridWirePitch;   /*   */
   double  innerSectorAnodeWirePadSep;   /*   AnodeWire-to-PadPlane distance  */
   double  innerSectorFrischGridPadSep;   /*   FrischGrid-to-PadPlane distance  */
   double  innerSectorGatingGridPadSep;   /*   GatingGrid-to-PadPlane distance  */
   double  outerSectorAnodeWirePadSep;   /*   AnodeWire-to-PadPlane distance  */
   double  outerSectorFrischGridPadSep;   /*   FrischGrid-to-PadPlane distance  */
   double  outerSectorGatingGridPadSep;   /*   GatingGrid-to-PadPlane distance  */
   long  numInnerSectorAnodeWires;   /*   */
   long  numInnerSectorFrischGridWires;   /*   */
   long  numInnerSectorGatingGridWires;   /*   */
   double  firstInnerSectorAnodeWire;   /*   */
   double  firstInnerSectorFrischGridWire;   /*   */
   double  firstInnerSectorGatingGridWire;   /*   */
   double  lastInnerSectorAnodeWire;   /*   */
   long  numOuterSectorAnodeWires;   /*   */
   long  numOuterSectorFrischGridWires;   /*   */
   long  numOuterSectorGatingGridWires;   /*   */
   double  firstOuterSectorAnodeWire;   /*   */
   double  firstOuterSectorFrischGridWire;   /*   */
   double  firstOuterSectorGatingGridWire;   /*   */
   double  lastOuterSectorAnodeWire;   /*   */

 };  
