/*   tpg_pad_plane.idl
*
*   Table: tpg_pad_plane
*       
*        description: Constants that describe TPC pad plane   
*             more..: configuration                           
*/

   /*******************  Row struct *******************/
   struct tpg_pad_plane {
       char      dnum[80];   /* ID of drawings used to extract numbers */
       long       npads[45];  /* # of pads per row */
       long       nrow_in;    /* # of rows in the inner sector */
       long       nrow_out;   /* # of rows in the outer sector */
       long       nsect;      /* Number of the end-cap sectors */
       float     pad_len_in; /* Pad length for the inner sector */
       float     pad_len_out;/* Pad length for the outer sector */
       float     pad_sep_in; /* Pad pitch for the inner rows */
       float     pad_sep_out;/* Pad pich for the outer rows */
       float     pad_wid_in; /* Pad width for the inner sector */
       float     pad_wid_out;/* Pad width for the outer sector */
       float     rad[45];    /* Radial distance to the center of the row */
   };
/*  Last mod. for tpg_pad_plane:   $Date: 2010/01/26 20:55:50 $ */

