/*    TrackingParameters.idl
*
*  Table: TrackingParameters
*
*  Description: Detector specific tracking parameters
*  There is one such a strut for each tracking detector : TPC, SVT, SSD.
*/ 
	

struct TrackingParameters { 
	double minSearch; /*  Minimum Search Window */
	double maxSearch; /*  Maximum Search Window */
	double scaling;   /*  Search Window Scaling */
	double maxChi2;   /*  Max Chi2 */
 };  
