/*   
*  trgDsmReg.idl
*
*  Table: trgDsmReg
*
*  Description: set of dsm register values, associated with a run
*  Quesion marks: no range information provided by requestor.
*
*/

struct trgDsmReg {
	unsigned long runNumber; 	/* run number*/
	long 	dcRegister; 		/* register ID */
	long 	dcValue; 			/* ??? */
	long 	dcDefaultvalue; 	/* ??? */
	octet 	dcObject; 			/* Crate ID, 1-14 */
	octet 	dcIndex; 			/* ??? */
	char 	dcLabel[64];		/* ??? */
};