/*    trgOfflineFilter.idl
*
*  Table: trgOfflineFilter
*
*       description: *    offline trigger IDs for use in filtering events
*/ 


struct trgOfflineFilter { 

   unsigned long  trigid;    /*     trigger id of interest */

 };  
