/*    trgTimeOffset.idl
*
*  Table: trgTimeOffset
*
*       description: //  trigger offset common to all detector-level clock modules
*/ 


struct trgTimeOffset { 

   float  offset;       /*   standard trigger offset in micro-seconds  */
   float  laserOffset;  /*   laser trigger offset in micro-seconds  */
   float  laserOffsetW; /*   laser extra trigger offset for West laser */

 };  
