/*    trigL3Expanded.idl
*
*  Table: trigL3Expanded
*
*       description:
*/ 


struct trigL3Expanded { 

   long  runNumber;   /*   run number  */
   char  l2TriggerResultType[32]; /* StL2triggerResultType */
   octet  name[32];   /*   descriptive name  */
   long  l3TrgId;   /*   level three triggerId / daq offline bit  */
   long  l3ExpandedTrgId;   /*   calculated level three expanded triggerId */
   long  l2Algo;  /*  level two algorithm */
   float l2Ps;   /*   level two prescale  */

 };  
