/*    trigPrescales.idl
*
*  Table: trigPrescales
*
*       description:
*/ 


struct trigPrescales { 

   long  runNumber;   /*   run number  */
   long  idxTrigger;   /*   daq trigger id  */
   long  idxLevel;   /*   L1/L2/L3  */
   long  id;   /*   trigger algorithm id  */
   float  ps;   /*   prescale  */

 };  
