/*    triggerThreshold.idl                                                                                                                              
*                                                                                                                                                    
*  Table: triggerThreshold                                                                                                                              
*                                                                                                                                                    
*       description:  *    Trigger Simulator storage - trigger thresholds per run
*/ 

struct triggerThreshold {
 
  char comments[200];    /* comments */
  octet trigthr[131072];  /* serialized TObjArray of trigger thresholds */
  long  size; /* real size of serialized blob */

 };

