/*    triggerInfo.idl
*
*  Table: triggerInfo
*
*       description:
*/ 


struct triggerInfo { 

   long  runNumber;   /*   idx_rn  */
   long  idxTrg;   /*   idx_trigger  */
   long  daqTrgId;   /*   daq trigger id  */
   long  offlineTrgId;   /*   offlineBit  */
   long  trgNameVersion;   /*   identifier bit to offline  */
   long  trgVersion;   /*   */
   long  threashVersion;   /*   */
   long  psVersion;   /*   */
   long  psL0;   /*   desiredL0PS  */
   char  name[64];   /*   name  */
   unsigned long  detectorLiveOnBits;   /*   */
   unsigned long  detectorLiveOffBits;   /*   */
   unsigned long  detectorRequest;   /*   */
   long  idxLevel;   /*   L1/L2/L3  */
   long  algorithmId;   /*   trigger algorithm id  */
   float  ps;   /*   prescale  */

 };  
