/*    triggerDefinition.idl                                                                                                                              
*                                                                                                                                                    
*  Table: triggerDefinition                                                                                                                              
*                                                                                                                                                    
*       description:  *    Trigger Simulator storage - trigger definitions per run
*/ 

struct triggerDefinition {
 
  char comments[200];    /* comments */
  octet trigdef[131072];  /* serialized TObjArray of trigger definitions */
  long  size; /* true size of serialized blob */

 };

