/*   V0FinderParameters.idl
*
*    Table: V0FinderParameters
*
*        description: Parameter table for V0 reconstruction   
*/

struct V0FinderParameters {
       long      iflag;      /* Controls execution flow, i.e. evaluate done now or not. */
       long      n_point;    /* Min. number of points on track */ 
       float     dca;        /* cut on dca between the two tracks */
       float     dcav0;      /* cut on dca(impact param) of V0 from event vertex */
       float     dlen;       /* cut on dist. of decay from prim. vertex */
       float     alpha_max;  /* Max. abs. value of arm. alpha allowed, only first entry used */
       float     ptarm_max;  /* Max. value of arm. pt allowed, only first entry used*/
       float     dcapnmin;   /* Min. value of tracks at interaction */
       float     dcapn_pt;   /* Max. pt of V0 for which dcapnmin cut applies */
};
