/*    VertexCuts.idl
*
*  Table: VertexCuts
*
*  Description: Detector specific tracking parameters
*  There is one such a strut for each tracking detector : TPC, SVT, SSD.
*/ 
	

struct VertexCuts { 
    long    MinNumberOfFitPointsOnTrack;
    long    MinTrack;         // Min number of tracks
    float   DcaZMax;
    double  RImpactMax;       // Max distance between helix and nominal beamline (0,0,z)  
    float   MinFracOfPossFitPointsOnTrack; // Min nFit/nPoss of tracks                                                                                                 
    float   MinTrackPt;       // Min pt of tracks 
};  
