/*    vertexSeed.idl
*
*  Table: vertexSeed
*
*       description: *    provides a line in 3D to use as a seed for primary
*/ 


struct vertexSeed { 

   float  x0;   /*     cm   : x intercept of x vs z line  */
   float  dxdz;   /*          :    slope    of x vs z line  */
   float  y0;   /*     cm   : y intercept of y vs z line  */
   float  dydz;   /*          :    slope    of y vs z line  */
   float  err_x0;   /*     cm   : error on x0  */
   float  err_dxdz;   /*          : error on dxdz  */
   float  err_y0;   /*     cm   : error on y0  */
   float  err_dydz;   /*          : error on dydz  */
   float  chisq_dof;   /*   chi square / dof of fit  */
   float  weight;   /*   weight of seed to use in vertex-finding  */
   float  stats;   /*   number of events used in seed-finding  */

 };  
