/*    vertexSeedTriggers.idl
*
*  Table: vertexSeedTriggers
*
*       description: *    acceptable offline trigger IDs for use in vertexSeed finding
*/ 


struct vertexSeedTriggers { 

   unsigned long  trigid;    /*     acceptable trigger id */

 };  
