/* vpdDelay
 *
 * Tables: vpd delay parameters, binary format 
 * description: // VPD delay parameters used for initial hit selection in StBTofSortRawHit
 */


struct vpdDelay {

	float delay[38]; /* vpd delay for tubeId (1:38) => West (1:19), East (20:38) */

}; 

