/* vpdSimParams.idl
*
* Table: vpdSimParams
*
* description: db table for Vpd Simulation Parameters
*
*/
struct vpdSimParams{
	short tubeRes;     	/* Single Tube Resolutions for Vpd tubes in picoseconds*/
	octet tubeID;       /* Vpd Tube ID, 0-37 */
	octet tubeStatusFlag;   /* Flag for whether tube was active (True) or not (False) */
	octet tubeTriggerFlag;  /* Flag for whether tube was triggered on (True) or not (False) */
};
