/* vpdTriggerToTofMap.idl
*
* Table: vpdTriggerToTofMap
*
* description: 	The map for vpd PMTs from vpd trigger side to the tof side electronics
*				indexed : 38 entries, one per physical PMT tube, updated about once per run
*
*/
struct vpdTriggerToTofMap {

	short eastWest;						/* eastWest east = 0, 1 = west, like StBeamDirection*/
	short triggerIndex; 				/* triggerIndex, 1-19 (only 16 active as of 06/2014) */
	short tofIndex; 					/* tofIndex, 1-19 for valid channel, -1 if unset*/

};
