/* vpdTotCorr
 *
 * Tables: vpd Tot Calibration Correction tables, binary format
 * description: // Tdc-Tot Correction parameters
 */

struct vpdTotCorr {
  short tubeId;   /* tubeId (1:38), West (1:19), East (20:38) */
  float tot[128]; /* edge of tot intervals for corr */
  float corr[128];   /* absolute corr value */
  short corralgo;   /* 0 - default vpd-start calibration algorithm */
                  /* 1 - non-vpd-start calibration algorithm */
};
