/*    ZdcCalPars.idl
*
*  Table: ZdcCalPars
*
*       description: //   slewing corrections for zdc timing
*/ 


struct ZdcCalPars { 

   double  EAP0;   /*   east param 0  */
   double  EAP1;   /*   east param 1  */
   double  EAP2;   /*   east param 2  */
   double  EAP3;   /*   east param 3  */
   double  WAP0;   /*   west param 0  */
   double  WAP1;   /*   west param 1  */
   double  WAP2;   /*   west param 2  */
   double  WAP3;   /*   west param 3  */
   double  VPAR;   /*   */
   double  OFF;   /*   */

 };  
