/*	
 * zdcsmdBeamCenter.idl
 *
 *	Table: zdcsmdBeamCenter
 *
 *	description: 	Table which contains BeamCenter information for zdcsmd ADCs
 */

struct zdcsmdBeamCenter {

	long RunID;                    /*  runID */
	float ZdcsmdBeamCenter[4];     /* BeamCenter of zdcsmd */
 };

