#!/opt/star/bin/perl
Import qw ( env INCLUDE LIB BIN BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
$build =~ s/\\/\//g;

(my $obj_dir = DirPath '.') =~ s/\\/\//g;
(my $Dir = $obj_dir) =~ s/$build\///g;
my $ObjDir = "#" . $obj_dir; 
my $STAR_SYS = $env->{ENV}->{STAR_SYS};

my $libr = "libJprof." . $env->{SUFSOLIB};
my $pkg  = "jprof";
my $PKG  = $pkg . $env->{SUFEXE};
my $DIR  = Cwd::cwd(); 
my $Libraries;

my $CXXFLAGS = $env->{CXXFLAGS};
my $CPPFLAGS = $env->{CPPFLAGS};
my $LIBPATH  = $env->{LIBPATH};
my $SOFLAGS  = $env->{SOFLAGS};

$CXXFLAGS =~ s/-ansi//;
$CPPFLAGS =~ s/-ansi//;


# This is a Linux stack oriented on package
if($^O eq "solaris"){
    # Package made for Linux. Give up man !!
    print "---> $pkg package cannot be assembled on $^O\n";
    return;

} elsif ($STAR_SYS =~ /64_/ || $STAR_HOST_SYS =~ /alpha/ ) {
    print "---> $pkg package will be skipped for now ... \n";
    return;

} else {
    print "---> build $pkg with cons $Dir\n";
}


# Save a copy in the src directory
$CPPPATH = "#" . $Dir . 
    $main::PATH_SEPARATOR . $Dir . "/exe".
    $main::PATH_SEPARATOR . $ObjDir."/exe";


# Change some values to accomodate
#$CPPFLAGS = "";
$Libraries = " -lJprof -lbfd -liberty -ldl ";

# Correct a 'cons' annoying side-effect
$tmp = $LIBPATH;
$tmp =~ s/\#//;
if( -d $tmp){ $LIBPATH = $tmp;}


if ($param::debug) {
    # Display new or current values
    print "Jprof Conscript\n";
    print "\tLibraries = $Libraries\n";
    print "\tCPPPATH   = $CPPPATH\n";
    print "\tLIBPATH   = $LIBPATH\n";
    print "\tSOFLAGS   = $SOFLAGS\n";
    print "\tCXXFLAGS  = $CXXFLAGS\n";
    print "\tCPPFLAGS  = $CPPFLAGS\n";
}
# Find sources and determine what should go in t
# the library. /leaky/ is pretty much hardcoded.
foreach $file (script::find_sources($Dir)){
    if($file !~ /leaky/){
	push(@src,$file);
    } else {
	$main = $file;
    }
}

if ($param::debug) {
    print " *** Main found as ".$main."\n";
    print " *** Sources are   ".join(" ",@src)."\n";
}


# Two tasks / two clones
$env1 = $env->clone('Libraries' => $Libraries,
		    'LIBPATH'   => $LIBPATH,
		    'CXXFLAGS'  => $CXXFLAGS,
		    'CPPFLAGS'  => $CPPFLAGS,
		    'EXTRA_SOFLAGS' => undef,
		    'CPPPATH'   => $CPPPATH);



# Library
LinkedModule $env1 $libr, @src;
Install      $env1 $LIB, $libr;

# Exec. Make it depend on the .so library, otherwise,
# compilation precedence is rather unpredictable.
my $Plibr = $LIB."/".File::Basename::basename($libr);

script::Keep  $pkg;
Depends       $env1 $pkg, $Plibr;
Program       $env1 $pkg, $main;
Install $env1 $BIN, $pkg;
  
