#!/opt/star/bin/perl
#use Env;
Import qw ( env INCLUDE LIB BIN BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
$build =~ s/\\/\//g;# print "OBJ = $OBJ build = $build MAIN = $MAIN\n";
(my $ObjDir = DirPath '.') =~ s/\\/\//g;# print "ObjDir = $ObjDir\n";
(my $Dir = $ObjDir) =~ s/$build\///g; #print "Dir = $Dir\n";
$ObjDir = "#" . $ObjDir;# print "ObjDir = $ObjDir\n";
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $FC     = $env->{FC};
my $FCPATH = $env->{FCPATH};
my $FFLAGS = $env->{FFLAGS};
my $FPPFLAGS = $env->{FPPFLAGS};
my $FEXTEND = $env->{FEXTEND};
my $FDEBUG = $env->{FDEBUG};
my $CPPFLAGS = $env->{CPPFLAGS};
my $CPPPATH = $env->{CPPPATH};
my $pkg  = "starsim"; 
my $PKG = $pkg;     print "Run cons in $Dir for $PKG\n";
my $SO_PKG = $PKG . "." . $env->{SUFSOLIB};# print "SO_PKG = $SO_PKG\n";
my $LIBPKG = "lib" . $PKG . "." . $env->{SUFLIB};
$FCPATH  = "#asps/Simulation/starsim/include";
$FCPATH .= $main::PATH_SEPARATOR . "#asps/Simulation/gcalor/include";
$FCPATH .= $main::PATH_SEPARATOR . "#asps/Simulation/geant321/include";
$FCPATH .= $main::PATH_SEPARATOR . $env->{ENV}->{CERN_ROOT} . "/include";
$FPPFLAGS .= " -D__ROOT_ -DCERNLIB_TYPE -DCERNLIB_UNIX " .
  "-DCERNLIB_BSLASH -DCERNLIB_DZDOC -DCERNLIB_SHL " .
  "-DCERNLIB_NONEWL -DCERNLIB_HIGZ  -DCERNLIB_CG  " .
  "-DCERNLIB_HADRON -DCERNLIB_GCALOR";
$FPPFLAGS .= " -DCPP_TITLE_CH=\"'" . $pkg . "'\"";
$FPPFLAGS .= " -DCPP_VERS=\"'v*'\"";
$FPPFLAGS .= " -DCPP_DATE=\"`date +%%y%%m%%d`\"";
$FPPFLAGS .= " -DCPP_TIME=\"`date +%%H%%M`\"";
$CPPFLAGS .= " -Df2cFortran";
$CPPPATH  = "#asps/Simulation/starsim/include";
$CPPPATH .= $main::PATH_SEPARATOR . $env->{Packages}->{MYSQL}->{INCDIR}; 
$CPPPATH .= $main::PATH_SEPARATOR . $env->{ENV}->{CERN_ROOT} . "/include";
$CPPPATH .= $main::PATH_SEPARATOR . $env->{ENV}->{CERN_ROOT} . "/src/pawlib/paw/ntuple";
$CPPFLAGS  = "-DCERNLIB_DZDOC -DCERNLIB_NONEWL -DCERNLIB_SHL -DCERNLIB_HADRON -DCERNLIB_BSLASH -DCERNLIB_HIGZ -DCERNLIB_CG";
if ($STAR_SYS =~ /^rh/ or $STAR_SYS =~ /^i386/) {
  $FPPFLAGS .= " -DCERNLIB_LINUX";
  $CPPFLAGS .= " -DCERNLIB_LINUX";
}
if ($STAR_SYS =~ /^rh80/) {
  $FPPFLAGS .= " -DCERNLIB_MYSQL";
  $CPPFLAGS .= " -DCERNLIB_MYSQL";
  $CPPFLAGS  = " -Df2cFortran -DCERNLIB_QMGLIBC";
}
if ($FC =~ /pgf77/) { 
  $FC       = $env->{G77}; print "set FC => $FC ==============================\n" if $param::debug;
  $FFLAGS   = $env->{G77FLAGS}; 
  $FEXTEND  = $env->{G77EXTEND};
}
$env2 = $env->clone('FC'           => $FC,
		    'FPPFLAGS'     => $FPPFLAGS,
		    'FFLAGS'       => $FFLAGS,
		    'FCPATH'       => $FCPATH,
		    'FEXTEND'      => "",
		    'FDEBUG'       => $FDEBUG,
		    'CPPFLAGS'     => $CPPFLAGS,
		    'CPPPATH'      => $CPPPATH,
		    'AGETOFLAGS'   => "",
		    'LIBS'         => $LIBS,
		    'ObjDir'       => $obj_dir,
		    'Libraries'    => $Libraries
		   );
my @src  = find_sources($Dir);
my $pwd = Cwd::cwd();# print "pwd = $pwd  Dir => $Dir\n";
my @sources = ();
foreach my $s (@src) {
  my @list = glob "$Dir/$s"; #print "$s => list = @list\n";
  foreach my $ss (@list) {
    $ss =~ s/$Dir\///;# print "$ss\n";
    next if $ss =~ /atlroot/;
    next if $ss =~ /acmain\.cxx/;
    next if $ss =~ /deccc\/traceqc\.c/;
    next if $ss =~ /deccc\/mykuip\.c/;
    next if $ss =~ /atmain\/traceq\.age/;
    next if $ss =~ /atmain\/etime\.F/ and $FC !~ /g77/;
    next if $ss =~ /deccc\/idisp\.c/ and $FC !~ /g77/;
    next if $ss =~ /atmain\/agxinit\.cdf/;
    next if $ss =~ /atmain\/guinti\.cdf/;
    next if $ss =~ /atmain\/sterror\.age/;
    next if $ss =~ /deccc\/fputools\.c/ and $FC !~ /g77/;
    push @sources, $ss; 
  }
}
if ($#sources > -1) {
  if ($STAR_SYS !~ /alpha/) {
    Library      $env2 $LIBPKG, @sources;  
    Install $env2 $LIB, $LIBPKG;
  } else {
    my @objfiles = Objects $env2  @sources;# print "+++++++++++  $STAR_SYS ********* @objfiles \n";
    Command $env2 ("input_object.list"), @objfiles, qq([perl] open(F, ">%>"); print F "%<"; close(F); 1);
    Command $env2 ($LIBPKG), ("input_object.list"), qq(%ARCOM);
    Install $env2 $LIB, $LIBPKG;
  }
}  
my @starsim = qw(acmain.cxx deccc/traceqc.c atmain/traceq.age atmain/sterror.age deccc/mykuip.c);# deccc/idisp.c);
my $pgm = "starsim";
my $PGI = $env->{ENV}->{PGI};
my $PGILIBS = "";
script::Keep $pgm;
my $LD = $env->{LD};
if ($LD eq 'g++') {$LD = $env->{CC};}
my $LDFLAGS = $env->{LDFLAGS};
$LDFLAGS .= $env->{LDEXPORT};
my $LIBPATH    = $env->{LIBPATH};
if ($LIBPATH) {$LIBPATH .= $main::PATH_SEPARATOR;}

my $LIBS    = $env->{LIBS};
if ($PGILIBS) {$LIBS .= " " . $PGILIBS;}  
$LIBS .= $env->{LDALL};
$LIBS .= " -lstarsim";
if ($LD eq 'gcc' or $LD eq 'g++' or $LD eq 'icc' ) {
  if ($env->{LIBG2C}) {
    $LIBPATH .= $main::PATH_SEPARATOR . File::Basename::dirname($env->{LIBG2C});
    $LIBS .= " " . $env->{LIBG2C};
    if ( $LD eq 'gcc' or $LD eq 'g++' ) {$LIBS .= " " . $env->{LIBSTDC};}
  }
}
$LIBS .= $env->{LDNONE};
$LIBS .= " -lgeant321";
$LIBS .= " -lgcalor";
my $Libraries = $env->{Libraries};
$LIBPATH .= $main::PATH_SEPARATOR . $env->{Packages}->{MYSQL}->{LIBDIR};
$Libraries .= " " . $env->{CERNLIBS} . " " . $env->{Packages}->{MYSQL}->{LIBS} .
$Libraries .=  " " .   $env->{FLIBS} . " " . $env->{CLIBS} . " " . $env->{SYSLIBS};
$envP = $env2->clone('LDFLAGS'   => $LDFLAGS,
		     'LIBPATH'   => $LIBPATH,
		     'LIBS'      => $LIBS,
		     'LD'        => $LD,
		     'FEXTEND'      => "",
		     'Libraries' => $Libraries
		    );
Program      $envP $pgm, @starsim;
my $d = $Dir . "/";
my @list = glob $d . "atlsim.*";# print "Dir  = $Dir; list = @list\n";
foreach my $l (@list) {
  my $f = File::Basename::basename($l); 
  my $s = $f; $s =~ s/atlsim/starsim/; #  print "$l => $s\n";
  Command $envP $BIN ."/". $s, "#" . $d ."/". $f, qq(cp %< %>);
  InstallAs $envP $s, $f;
}		 
Command $envP $BIN . "/" . $pgm, $pgm, qq(cp %< %>);
