/*:Copyright 1995, Lawrence Berkeley National Laboratory
*:>---------------------------------------------------------------------
*:FILE:        asuLib.inc
*:<---------------------------------------------------------------------
*/
#ifndef ASULIB_INC
#define ASULIB_INC
#define ASU Analysis Service Utilities
#endif /*ASULIB_INC*/

/*------------------------------------------------ TEMPORARY        --*/
#include "asu_codes.h"


